### ISSUE TITLE
Bug report: 模拟位置模块 微信小程序不生效

### ISSUE THREAD

**Issue by sunzongzheng** [taichi-framework/TaiChi#1006]
**Describe the bug**
`模拟位置`模块，太极中启用，在微信小程序中无法获取定位。
我找了一个安卓5.1直接刷xposed，装同样版本的模块，微信小程序中定位正常

![image](https://user-images.githubusercontent.com/12635613/67924096-99a29980-fbea-11e9-956e-2657e341a25b.png)

**To Reproduce**
1. 启用`模拟位置`模块
2. 微信小程序中获取定位
3. 无法获取定位

**Expected behavior**
能正确获取到定位

**Smartphone (please complete the following information):**
Magisk version：
TaiChi-Magisk module version：5.1.3
TaiChi version：5.5.8-1008
Which Xposed modules are enabled ?：模拟位置
Xposed modules version：1.2.681.1701
Which Magisk modules are enabled ?：绿色守护、无障碍、youtube adaway、scanLogin、易开发、QX模块、suduhide、微信斗图神器、AD快消、zuper、unblockmusic pro、dingPass
Magisk modules version：
Device ：小米Mix2s
ROM：miui 11 9.9.26

**Additional context**
如果这个小程序可以在企业微信中打开，从企业微信打开时定位正常

**Comment by tiann** [comment]
可能是模块对高版本支持的问题。

**Comment by sunzongzheng** [comment]
但是如果在企业微信中打开小程序，定位是正常的
