### ISSUE TITLE
BUG：XprivacyLua 在Android 10下无法正常工作

### ISSUE THREAD

**Issue by cs-usst** [taichi-framework/TaiChi#1009]
## 什么问题

XprivacyLua + Taichi + Magisk 在Android 10下无法正常工作

## 详细情况

升级Android 10后，XprivacyLua + Taichi + Magisk组合下无法正常限制权限，具体表现为：使用XprivacyLua限制[IMEI](https://play.google.com/store/apps/details?id=com.bobgearstudio.imei&hl=en_US)软件全部权限后，IMEI能够读取机型信息；安装酷安后，并使用XprivacyLua限制其读取手机应用列表，但酷安仍能读取并出现软件更新提示。

Magisk 版本：20101
太极 Magisk 模块版本：5.1.4
太极APP版本：5.5.8
开启的 Xposed 模块：XprivacyLua
Xposed模块版本：太极提供的1.24
开启的其他 Magisk 模块：Busybox，YouTube Vanced
其他 Magisk 模块版本：1.31.1,14.21.54
手机型号：Nokia 7.1
ROM版本：Android 10

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by cs-usst** [comment]
modules.list
/data/app/eu.faircode.xlua-89zRfnrd01V8HWTdT4BJWg==/base.apk
/data/app/com.oasisfeng.greenify-rmRRQ4rlK-SloK4PkJkj2w==/base.apk

apps.list
com.fkzhang.wechatxposed
eu.faircode.xlua
com.oasisfeng.greenify

**Comment by tiann** [comment]
插件的问题

**Comment by cs-usst** [comment]
> 
> 
> 插件的问题

但是如果用EdXposed + Android 10 + XprivacyLua(1.25) 就没有这个问题
