### ISSUE TITLE
BUG：一加7P升级安卓10以后无法将网易云音乐加入至太极

### ISSUE THREAD

**Issue by JueLuo99** [taichi-framework/TaiChi#1010]
## 什么问题

一加7Pro，使用官方升级安卓10以后无法将网易云音乐加入至太极

## 详细情况

1. 在较旧的系统上可以正常使用太极阴搭配网易云及相关模块使用
2. 官方发布了 Android 10 稳定版，我的设备亦升级至该版本
3. 在 Android 10 上安装太极阴 5.5.8 版本
4. 安装网易云音乐 6.4.4 版本
5. 根据太极 APP 的提示进行卸载
6. 根据太极 APP 的提示进行安装时，安装包管理器安装过程中突然消失；太极 APP 内部提示该应用异常，需要安装；设备的应用列表内无法找到网易云音乐，推测安装并没有完成
7. 补充：低于当前最新版本（6.4.4）的网易云音乐官方安装包似乎都无法正常安装，安装包管理器会提示”应用未安装”

Magisk 版本：(无）
太极 Magisk 模块版本：(无）
太极APP版本：5.5.8
开启的 Xposed 模块：(无）
Xposed模块版本：(无）
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：OnePlus 7 Pro
ROM版本：官方的H2OS稳定版（Hydrogen OS 10.0.GM21）

## 配置文件

 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。
设备未解锁未获取 root 权限，使用太极阴，无法访问上述文件

请告诉我我还可以提供的信息，将会尽力提供

**Comment by tiann** [comment]
换个渠道卸载应该就可以了。
