### ISSUE TITLE
Bug report: 抖音只能加载一页数据

### ISSUE THREAD

**Issue by caopengfei** [taichi-framework/TaiChi#1012]
## 什么问题
抖音8.4.0版本只加载了一页数据，再往上滑的时候显示“没有更多了”。

## 详细情况
打开抖音，往上滑动，才几条数据之后就显示“没有更多了”。

Magisk 版本：
太极 Magisk 模块版本：
太极APP版本：东皇钟-5.5.8-1019
开启的 Xposed 模块：无
Xposed模块版本：太极 阴内核 127
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：华为荣耀 6A DLI-AL10 5.1.3
ROM版本：7.0

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
看起来不是框架的问题。
