### ISSUE TITLE
BUG：安卓10的ColorOS6.7刷入太极阳后无法开机

### ISSUE THREAD

**Issue by chan1108** [taichi-framework/TaiChi#1014]
## 什么问题

Reno 10x zoom在升级到安卓10后，不管是在recovery下还是在magisk manager下刷入太极阳都bootloop无法开机

## 详细情况

刷入太极阳后无法开机

Magisk 版本：20.1
太极 Magisk 模块版本：5.1.4
太极APP版本：5.5.8
开启的 Xposed 模块：无
Xposed模块版本：无
开启的其他 Magisk 模块：Magisk manager for recovery mode & iOS 12.1 Emoji
其他 Magisk 模块版本：2019.4.4 & version9
手机型号：Reno 10x zoom （PCCM00）
ROM版本：PCCMOO_11_C.04_23c59a3d

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。
https://pan.baidu.com/s/1ayNwC0WPGL-n_kmZED_NrQ

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
把其他模块都关掉再看看
