### ISSUE TITLE
BUG：太极magisk5.1.4无法通过safetyNet检查

### ISSUE THREAD

**Issue by wuweiluohua** [taichi-framework/TaiChi#1017]
## 什么问题

太极magisk5.1.4无法通过safetyNet检查
## 详细情况

安装magisk通过确认safetyNet检查后，再安装太极模块就ctaProfile和basiclnetegrity两项检测均无法通过

Magisk 版本：20.1
太极 Magisk 模块版本：5.1.4/5.1.3/4.7.0
太极APP版本：5.5.8
开启的 Xposed 模块：假装分享/音量增强器/AD快消/模拟位置/LocationReportEnabler/Q ++模块/云村清洁工/核心破解
Xposed模块版本：
开启的其他 Magisk 模块：Busybox for Android Ndk(1.31.1)/MagiskHide Props Config(V5.0.1-V65)/SafetyPatch(V3)
其他 Magisk 模块版本：（无）
手机型号：小米 MIX2
ROM版本：miui11 9.10.31

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
先确认下是不是太极模块导致的问题。
在我的 MIX 2S上，不论开不开太极模块，都可以通过检查；在 Pixel 开发版系统上，开不开太极都无法通过检查。

**Comment by wuweiluohua** [comment]
装好了magisk+Busybox for Android Ndk(1.31.1)/MagiskHide Props Config(V5.0.1-V65)/SafetyPatch(V3)这3个模块以后进行了safetyNet检查，两项都能正常通过；然后装taichi5.1.4模块重启，再safetyNet检查就两项都不能通过；再次卸载taichi5.1.4模块重启，进行safetyNet检查又能正常通过检查。另根据某大佬意见，我又装上PetNoires safetySpoofer模块测试，再安装taichi5.1.4模块进行safetyNet检查能通过，但是打开太极就发现只能启动太极阴，无法使用太极阳

**Comment by wuweiluohua** [comment]
> 先确认下是不是太极模块导致的问题。
> 在我的 MIX 2S上，不论开不开太极模块，都可以通过检查；在 Pixel 开发版系统上，开不开太极都无法通过检查。

装好了magisk+Busybox for Android Ndk(1.31.1)/MagiskHide Props Config(V5.0.1-V65)/SafetyPatch(V3)这3个模块以后进行了safetyNet检查，两项都能正常通过；然后装taichi5.1.4模块重启，再safetyNet检查就两项都不能通过；再次卸载taichi5.1.4模块重启，进行safetyNet检查又能正常通过检查。另根据某大佬意见，我又装上PetNoires safetySpoofer模块测试，再安装taichi5.1.4模块进行safetyNet检查能通过，但是打开太极就发现只能启动太极阴，无法使用太极阳

**Comment by tiann** [comment]
可能是其他几个模块跟太极有冲突吧

**Comment by FishMagic** [comment]
如果使用了太极的全局模式，请将需要safety net的应用加入排除列表中并重启手机，已经确定太极生效的应用会出现safety net不通过的情况
