### ISSUE TITLE
BUG：RedmiNote7Pro在Taichi-Magisk环境下微信会频繁出现阻止闪退

### ISSUE THREAD

**Issue by 8MiYile** [taichi-framework/TaiChi#1019]
## 什么问题

打开微信后有操作或者不操作都会提示 太极阻止微信闪退 造成语音消息无法发送,

## 详细情况

Magisk 版本：20.2
太极 Magisk 模块版本：5.1.3
太极APP版本：5.5.8
开启的 Xposed 模块：QX,WeX
Xposed模块版本：QX:2.1;WeX:2.3
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：Redmi Note 7 Pro
ROM版本：V11.0.4.0.PFHCNXM (MIUI11)

## 配置文件
 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。
客人不会提供以上两个文件(log文件都不会导出),所以只能按现有信息来反馈

**Comment by tiann** [comment]
用微X网盘提供的微信版本
