### ISSUE TITLE
Modules not supported, TV4PlayAdaway and DplayAdaway

### ISSUE THREAD

**Issue by ChanceGPM** [taichi-framework/TaiChi#1021]
I would like to suggest to add compatibility with the Xposed modules TV4PlayAdaway and DplayAdaway. They are currently not supported so I can't enable them. 

https://repo.xposed.info/module/no.markus.tv4playadaway
https://repo.xposed.info/module/no.markus.dplayadaway

Thanks.

**Comment by tiann** [comment]
should be fixed now.
