### ISSUE TITLE
Module not compatible: Fingerface

### ISSUE THREAD

**Issue by CiriousJoker** [taichi-framework/TaiChi#1022]
Fingerface is a new module for the Google Pixel 4 which isn't compatible with TaiChi.

Here's the link to the module:
https://github.com/topjohnwu/Fingerface

Module works with EdXposed.

**Comment by tiann** [comment]
Please try it again.

**Comment by CiriousJoker** [comment]
@tiann 
Now I can activate the module but it doesn't work, the fake fingerprint sensor isn't detected.

The module works with EdXposed though
