### ISSUE TITLE
关于 无极激活码 的问题

### ISSUE THREAD

**Issue by 1604589485** [taichi-framework/TaiChi#1023]
## 什么问题
我今天刷机之后无极变回了太极
我想用原来的激活码再次激活的时候，发现并不能在同一设备下再次激活

## 详细情况
不是说一个设备 可以用第一次激活的码 在激活吗？

Magisk 版本：19.3
太极 Magisk 模块版本：5.1.4
太极APP版本：
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：
ROM版本：

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by 1604589485** [comment]
手机的型号 mate20 Pro  版本号 emui9.1.0.135

**Comment by 1604589485** [comment]
我现在在怀疑是不是我升级了 系统版本的问题

**Comment by tiann** [comment]
开启无极的时候已经提示了，不保证刷机有效。

**Comment by 1604589485** [comment]
那能不能再给我一个激活码 非常感谢 我以后也会一直支持太极的

**Comment by tiann** [comment]
0ef27669-bbb2-4a97-ac0e-8e0e72b92263

**Comment by 1604589485** [comment]
我以后会积极的反馈bug 并希望太极功能越做越强大，争取早日开发出可以完美替代原版XP。

**Comment by 19770214** [comment]
（小声bb）太极可能用的AndroidID来识别的设备，重新刷机会导致AndroidID改变，可以试着用相关应用修改回之前的或者进行修复
