### ISSUE TITLE
Module not compatible: Edge Sense Plus

### ISSUE THREAD

**Issue by CiriousJoker** [taichi-framework/TaiChi#1024]
Title says it all, couldn't test with EdXposed.

**Comment by CiriousJoker** [comment]
btw. Edge Sense Plus does work without the Xposed module being active, so this doesn't have much priority

**Comment by tiann** [comment]
I enabled the module, and the module toast that "xposed enable (true)", but it seems not working, nothing happened when i squeeze the screen edge

**Comment by CiriousJoker** [comment]
It does work with the Magisk module for some reason. I also gave it all possible permissions (most importantly probably root)

**Comment by CiriousJoker** [comment]
Btw. this only works with Pixel devices. You probably already know that, but just in case
