### ISSUE TITLE
我已经刷好太极阳，但是没有模块管理

### ISSUE THREAD

**Issue by xianghongwu** [taichi-framework/TaiChi#1032]
## 什么问题

我已经刷好太极阳，但是没有模块管理

## 详细情况

Magisk 版本：
太极 Magisk 模块版本：
太极APP版本：
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：
ROM版本：

**Comment by tiann** [comment]
彻底卸载掉原来的  Xposed。
