### ISSUE TITLE
建議：希望太極能夠支持拆分app

### ISSUE THREAD

**Issue by mickychenchen** [taichi-framework/TaiChi#1033]
## 什么问题

希望太極能夠支持拆分app

## 详细情况

許多app都改用拆分apk
這類app在太極中無法創建

Magisk 版本：無
太极 Magisk 模块版本：無
太极APP版本：5.5.8
开启的 Xposed 模块：無
Xposed模块版本：無
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：Samsung note 8
ROM版本：原廠 Android 9.0

## 配置文件

無

**Comment by akhilkedia** [comment]
This stackoverflow answer and the corresponding Github repo for extracting/installing split apks might be helpful - 
https://stackoverflow.com/questions/55212788/is-it-possible-to-merge-install-split-apk-files-aka-app-bundle-on-android-d
https://github.com/nkalra0123/splitapkinstall

**Comment by tiann** [comment]
split apk is supported.
