### ISSUE TITLE
BUG：修改为你遇到的问题的详细描述

### ISSUE THREAD

**Issue by zhengnanGit** [taichi-framework/TaiChi#1034]
## 什么问题

太极分身中没有微信防撤回模块
小米的手机双开应用系统中没有对模块的双开

## 详细情况
安装太极
卸载原来的微信重新安装太极推荐微信
安装太极的防撤回模块
主微信可以防撤回
双开太极和微信
双开的太极检测不到微信防撤回模块
子微信无法加载微信防撤回

Magisk 版本：
太极 Magisk 模块版本：
太极APP版本：
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：
ROM版本：

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
双开步骤不对。
参考教程：https://mp.weixin.qq.com/s/1iQVJscDyO9K04UiSMhVVg

**Comment by tiann** [comment]
试一下这个：https://www.lanzous.com/i7lq7qh

**Comment by zhengnanGit** [comment]
> 试一下这个：https://www.lanzous.com/i7lq7qh
> 
> 步骤：
> 
> 1. 安装太极，把应用添加到太极。
> 2. 双开你需要的应用，完毕。
> 
> 注意：无需双开太极和模块。

QAQ 用了，是可以了。不过到晚上的时候号被封了
