### ISSUE TITLE
XInsta 2.1.1 rootless TaiChi don't work

### ISSUE THREAD

**Issue by SafiXS** [taichi-framework/TaiChi#1035]
XInsta 2.1.0 and 2.1.1 won't work on latest 5.5.8 TaiChi on rootless stock EMUI 10 (Android 10) with Huawei P30 Pro.
On EMUI 9 everything work as it should but after clean update nothing...

I contacted the Dev of XInsta. He was trying to contact you to find out where the problem is.

**Comment by miaachan** [comment]
I am currently using XInsta Version 2.1.1 which I had uploaded to TaiChi asking for support b4. And it is working fine till now.

Config:
TaiChi Magisk
Instagram Version Code: 176649504
Device Codename: GM1910
Android Version: 10
XInsta Version 2.1.1

**Comment by SafiXS** [comment]
> I am currently using XInsta Version 2.1.1 which I had uploaded to TaiChi asking for support b4. And it is working fine till now.
> 
> FYI, Here is my config:
> TaiChi Magisk
> Instagram Version Code: 176649504
> Device Codename: GM1910
> Android Version: 10
> XInsta Version 2.1.1

The problem seems only appear on unrooted devices

**Comment by miaachan** [comment]
> > I am currently using XInsta Version 2.1.1 which I had uploaded to TaiChi asking for support b4. And it is working fine till now.
> > FYI, Here is my config:
> > TaiChi Magisk
> > Instagram Version Code: 176649504
> > Device Codename: GM1910
> > Android Version: 10
> > XInsta Version 2.1.1
> 
> The problem seems only appear on unrooted devices


Check your error log to see whether it did try to hook. It doesn't work for me at first too. But I figure out from the error log and discover that it never attempts to rehook after updating hooks.

**Comment by tiann** [comment]
#925
