### ISSUE TITLE
EMUI9.1刷入太极magisk后太极app闪退

### ISSUE THREAD

**Issue by zixing131** [taichi-framework/TaiChi#1038]
## 什么问题

EMUI9.1刷入太极magisk后太极app闪退

## 详细情况

EMUI9.1刷入太极magisk后太极app闪退

Magisk 版本：20.1
太极 Magisk 模块版本：5.1.4
太极APP版本：5.6.4-1176
开启的 Xposed 模块：无
Xposed模块版本：无
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：华为荣耀10
ROM版本：9.1.0.336

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。
apps.list:
me.firesun.wechat.enhancement
com.eg.android.AlipayGphone
bin.xposed.screenshotdelayremover.mod
me.zjns.lovecloudmusic
com.android.packageinstaller
com.netease.mail
com.tencent.mobileqq
me.weishu.corepatch
com.virb3.trustmealready
pansong291.xposed.quickenergy
com.raincat.unblockmusicpro
bin.xposed.Unblock163MusicClient
com.netease.cloudmusic
modules.list:

/data/app/me.firesun.wechat.enhancement-t35GQA9d9tBzcUUMf2cvTA==/base.apk
/data/app/com.fkzhang.qqxposed-i4YB4yzbARpl6qmZfgZ6vQ==/base.apk
/data/app/com.virb3.trustmealready-90hlHWkRorBT16-oqW7QSA==/base.apk
/data/app/louis.baseapk-FpnWyddmb6z3KJF5VMDxxA==/base.apk
/data/app/com.specher.music163-SluOA6gr07oK8mz-4K1VjA==/base.apk
/data/app/me.weishu.corepatch-gOlHxgnfxE8zfoeCG63WKA==/base.apk
/data/app/bin.xposed.screenshotdelayremover.mod-7OD0f_ly7xRb5Z31mo3fxg==/base.apk
/data/app/pansong291.xposed.quickenergy-i41oBNAvs4qeoql_SH9LZg==/base.apk
/data/app/bin.xposed.Unblock163MusicClient-wTNlhodpfraAajWy6qW8hA==/base.apk
/data/app/com.raincat.unblockmusicpro-zrhgbasRvM82PgvOVlE2Uw==/base.apk
/data/app/me.zjns.lovecloudmusic-2bTWIG4UArW-6T0Py8JMIQ==/base.apk

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
EMUI 阉割了某个系统服务，导致太极不正常，就算修复了闪退也无法正常以 太极阳的模式工作。我可能需要一个手机测试才能搞定。

**Comment by tiann** [comment]
模块升级到 6.1.5，app升级到5.9.0
