### ISSUE TITLE
Bug report: sudohide 1.28 not working

### ISSUE THREAD

**Issue by tupac55** [taichi-framework/TaiChi#1040]
**Describe the bug**
can't make sudohide 1.28 work

I've added all apps in taichi app, checked sudohide 1.28 in module list, rebooted, go to sudohide app, hide app, reboot, and it's not working

With the same steps in edxposed it's working..

**Smartphone (please complete the following information):**
Magisk version：20.1
TaiChi-Magisk module version：5.1.5
TaiChi version：5.5.8

Device ：Xiaomi Mi 9T
ROM : xiaomi.eu rom
.

**Comment by tupac55** [comment]
![Screenshot_2019-12-06-10-27-26-876_org thunderdog challegram](https://user-images.githubusercontent.com/36693689/70328314-04be3c00-1839-11ea-92da-39f773090bb2.jpg)


Here's an other guy on the telegram channel that say sudohide not working..

**Comment by tiann** [comment]
every app or just Google Play?

**Comment by tupac55** [comment]
Just tried now and it's only from Google play store, to test i downloaded "my apps " from the play store and tried hiding an app and it worked but hiding from Google play store is not working ,

I've also tried with global mode "on"

And it's the same.. it's not hiding YouTube or Instagram (the two app I need hiding from Google play store)

**Comment by tiann** [comment]
Because Google Play is in the only hardcoded black list of Taichi :(

When i release Taichi in the early, a user claimed to be a Googler told me that it is bad to allow someone to modify Google Play, it may break the IAP and made developers suffer from cracked mods.

**Comment by Sy1er** [comment]
Is it possible for you to remove play store from black list or make an advance toggle to disable it. 
Thanks

**Comment by tupac55** [comment]
Yeah please at least give us the option to toggle it because as cracked YouTube and Instagram doesn't support latest version we have to hide from Google play to not have them auto updated (yeah Google auto update YouTube even with auto update off go check xda)

**Comment by tupac55** [comment]
More of that EdXposed is hooking Google play store and doesn't break IAP, I bought many IAP and also donated to some dev from IAP never had issue :) 

Maybe this "Googler" guy had a bad xposed module that break IAP for him ?

**Comment by tiann** [comment]
Please try this version: https://www.lanzous.com/i7w4xof

**Comment by tiann** [comment]
> More of that EdXposed is hooking Google play store and doesn't break IAP, I bought many IAP and also donated to some dev from IAP never had issue :)
> 
> Maybe this "Googler" guy had a bad xposed module that break IAP for him ?

Only using Xposed-styled framework doesn't break IAP, some bad guys may develop a malicious module to achieve this(Although i didn't see any module like this in public) .

Taichi restrict and audit the module now, so i think it may not be a problem now.

**Comment by Sy1er** [comment]
> Please try this version: https://www.lanzous.com/i7w4xof

Thanks for the update. It's working, I don't see update for Instagram and Vanced YouTube.

**Comment by tupac55** [comment]
> Please try this version: https://www.lanzous.com/i7w4xof

This one is working great ! Also tried IAP and worked great also ! Thanks you Tiann 👍  




> > More of that EdXposed is hooking Google play store and doesn't break IAP, I bought many IAP and also donated to some dev from IAP never had issue :)
> > Maybe this "Googler" guy had a bad xposed module that break IAP for him ?
> 
> Only using Xposed-styled framework doesn't break IAP, some bad guys may develop a malicious module to achieve this(Although i didn't see any module like this in public) .
> 
> Taichi restrict and audit the module now, so i think it may not be a problem now.


Yeah i understand, that's also why i prefer use Taichi, it's more modulable and more secure because everything is under good dev control, I only test with Edxposed to test if it's module issue or framework issue.
