### ISSUE TITLE
Bug report: support for Quote lock 

### ISSUE THREAD

**Issue by BHUSHAN7988** [taichi-framework/TaiChi#1041]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
Magisk version：
TaiChi-Magisk module version：
TaiChi version：
Which Xposed modules are enabled ?：
Xposed modules version：
Which Magisk modules are enabled ?：
Magisk modules version：
Device ：
ROM：

**Additional context**

**Comment by tiann** [comment]
#925
