### ISSUE TITLE
Bug report: YouTube去广告，锁屏播放\NoAdsBackgroundPlaybackYT Doesn't block ads

### ISSUE THREAD

**Issue by tupac55** [taichi-framework/TaiChi#1042]
**Describe the bug**
YouTube去广告，锁屏播放\NoAdsBackgroundPlaybackYT 2.0.9

This module doesn't block ads on Taichi, all other function of the module is working correctly, such as background playback.

I've tested with EdXposed 4478 YAHFA and it work as it should, it block the ads and play youtube in background. 

To go futher i've tested with Global mode On and Off, it's the same

To be sure to make it working you have to have the Youtube 14.43.55 ( https://www.apkmirror.com/apk/google-inc/youtube/youtube-14-43-55-release/ ) and not the latest from the playstore otherwise it won't work even on EdXposed (because the dev behind the module isn't always updating the hook to the latest version of youtube )

**Smartphone (please complete the following information):**
Magisk version：20.1
TaiChi-Magisk module version：5.1.5
TaiChi version：5.5.8-1180
Device ：Xiaomi Mi 9T
ROM：Xiaomi.eu rom

**Comment by tupac55** [comment]
Any news on this ? @tiann

**Comment by tupac55** [comment]
No news for this ?

**Comment by xkillerz** [comment]
Same problem

**Comment by OoHHHHHHH** [comment]
Same problem
