### ISSUE TITLE
BUG：太极阳 提示系统时间不正确

### ISSUE THREAD

**Issue by wxx9248** [taichi-framework/TaiChi#1044]
## 什么问题

太极模块管理界面提示系统时间不正确，但是系统时间是正确的并且已经网络同步。
当前时区：Eastern Standard Time (EST) (GMT-5)，调回国内时区(GMT+8)问题依旧存在。
重新安装无效。

## 详细情况
![Screenshot_20191207-200403](https://user-images.githubusercontent.com/24369565/70382810-bcce1080-192f-11ea-8cc6-42ed97b9209d.png)

现在导致太极无法启用新模块，但是已经启用的模块似乎不受影响。
但由于我重装了太极，现在所有模块均无法使用。

Magisk 版本：20.1 (20100)
太极 Magisk 模块版本：5.1.4
太极APP版本：5.6.4
开启的 Xposed 模块：无
Xposed模块版本：-
开启的其他 Magisk 模块：
1. ADB & Fastboot for Android NDK
2. Busybox for Android NDK
3. Curl for Android
4. GNU Utils for Android
5. GPay SQLite Fix
6. Greenify4Magisk
7. Magisk Manager for Recovery Mode (mm)
8. Nano for Android NDK
9. SQLite for ARM aarch64 devices
10. SSH for Magisk
11. Tai Chi
12. aria2c for android
 
其他 Magisk 模块版本：（无）
手机型号：Xiaomi MI 8 (dipper)
ROM版本：[PixelExperience_dipper-10.0-20191120-2201-OFFICIAL.zip](https://download.pixelexperience.org/dipper)

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

**apps.list**
com.fkzhang.qqxposed
com.fkzhang.wechatxposed
com.raincat.unblockneteasemusic
tv.danmaku.bili
com.tencent.mm
com.oasisfeng.greenify
com.tencent.mobileqq
com.netease.cloudmusic

**modules.list**
无此文件。

补充：有能力请务必提供日志文件以快速解决问题。

**Comment by 4ft35t** [comment]
这个问题如何修复的，我遇到了同样问题。Pixel 3a XL，Android 10，太极 6.12。卸载重装问题依旧

**Comment by wxx9248** [comment]
抱歉，我也不是很清楚

有一段时间我一直用不了太极，然后记得好像是一次系统更新解决了……

现在用6.1.2没有问题……




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"4ft35t"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 晚上10:12
收件人:&nbsp;"taichi-framework/TaiChi"<TaiChi@noreply.github.com&gt;;
抄送:&nbsp;"wxx9248"<wxx9248@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [taichi-framework/TaiChi] BUG：太极阳 提示系统时间不正确 (#1044)





 
这个问题如何修复的，我遇到了同样问题。Pixel 3a XL，Android 10，太极 6.12。卸载重装问题依旧

**Comment by 4ft35t** [comment]
临时切换到 EDXposed 了，等下个版本再来看看

**Comment by PikuZheng** [comment]
相同问题，太极803
所以楼上最后怎么解决的？
