### ISSUE TITLE
Module cannot be enabled (grayed out) in 'Manage Module'

### ISSUE THREAD

**Issue by bubbleguuum** [taichi-framework/TaiChi#1045]
I'm the author of an Xposed module and want to test it with Taichi.
However it does not appear in the 'Manage Modules' list by default.
It is listed with 'Show all modules', but cannot be enabled (check box grayed out).

What is necessary so it can be enabled ?

**Smartphone (please complete the following information):**
Magisk version：20.1
TaiChi-Magisk module version：5.1.7
TaiChi version：5.7.0-1203
Which Xposed modules are enabled ?：nonr
Xposed modules version：
Which Magisk modules are enabled ?：nonr
Magisk modules version：
Device Samsung Galaxy 9
ROM：Stock

**Comment by Sy1er** [comment]
Hi @bubbleguuum you need to submit your module [Here](http://admin.taichi.cool/) to use it with TaiChi

**Comment by bubbleguuum** [comment]
Thanks. Isn't there a way for a developer to test that it works without having to submit the module ?

**Comment by tiann** [comment]
https://taichi.cool/zh/doc/wuji.html
