### ISSUE TITLE
BUG：修改为你遇到的问题的详细描述

### ISSUE THREAD

**Issue by AceMONKEY519** [taichi-framework/TaiChi#1048]
## 什么问题
抖音更新后无法播放视频
（请简要说明你遇到的问题）

## 详细情况
更新9.1.0及以后版本均无法播放视频
（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：
太极 Magisk 模块版本：5.1.7
太极APP版本：5.7.0
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：一加7
ROM版本：氧OS beta6

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
请提供问题的详细情况
