### ISSUE TITLE
BUG：无法打开luckin coffee

### ISSUE THREAD

**Issue by cc9014** [taichi-framework/TaiChi#1049]
## 什么问题

将luckin coffee安装进太极后，无法打开。首页卡屏

## 详细情况

从3.0版本开始出现这个问题，因为微信装在太极中，如果不把luckin也装进去的话，无法分享优惠券等其他和微信有关的联动。

Magisk 版本：
太极 Magisk 模块版本：无
太极APP版本：5.7.0-1217 （太极·阴）
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：HUAWEI MATE 9
ROM版本：EMUI 9.1.0

## 配置文件

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
#456
