### ISSUE TITLE
Bug report: 

### ISSUE THREAD

**Issue by molafir** [taichi-framework/TaiChi#1051]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
Magisk version：
TaiChi-Magisk module version：
TaiChi version：
Which Xposed modules are enabled ?：
Xposed modules version：
Which Magisk modules are enabled ?：
Magisk modules version：
Device ：
ROM：

**Additional context**
https://github.com/bigsinger/AndroidIdChanger
Please add AndroidIdChanger
MODEL not working

**Comment by tiann** [comment]
https://github.com/taichi-framework/TaiChi/issues/925
