### ISSUE TITLE
BUG：红米note8pro卡机卡进度条，不识别sim，模块随机失效等

### ISSUE THREAD

**Issue by lryyddy** [taichi-framework/TaiChi#1052]
## 什么问题

红米note8pro卡机卡进度条，不识别sim，模块随机失效等

## 详细情况

随机出现开机卡进度条，并不是首屏，重启无效，得进入recovery然后再重启才正常，有时候得多进两次recovery才可以
启动后不识别sim，严重情况下也无法打开wifi，重启后大概率能解决
摄像头和手电筒随机出现打不开的情况
模块会随机出现失效

Magisk 版本：19.3
太极 Magisk 模块版本：5.6.8 5.7.0
太极APP版本：5.1.5
开启的 Xposed 模块：微x，qx，音量增强器
Xposed模块版本：2.5  2.1  0.35
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：红米note8pro
ROM版本：11.0.1 11.0.2

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
SELinux 的问题，已修复。

**Comment by lryyddy** [comment]
> SELinux 的问题，已修复。

刷入最新的6.0.0，仍然小概率的出现了开机没有信号，打不开手电筒的情况和大概率出现模块失效的情况，请问是哪方面的问题呢？会不会存在老版本taichi magisk没卸载干净的情况
