### ISSUE TITLE
Support xPrivacyLua Pro

### ISSUE THREAD

**Issue by flostingapplesauce** [taichi-framework/TaiChi#1054]
The stable version of xPrivacyLua seems to be fine, but the xPrivacyLua Pro apk doesn't recognize that xPrivacyLua is installed.

![Screenshot_20191218-152803_XPrivacyLua_Pro](https://user-images.githubusercontent.com/55167013/71120748-0aa60c80-21ab-11ea-806f-4b0ba91910bf.png)

![Screenshot_20191218-152756_XPrivacyLua](https://user-images.githubusercontent.com/55167013/71120731-037efe80-21ab-11ea-9b6b-8452a6eb4b39.png)

![Screenshot_20191218-153125_XPrivacyLua_Pro](https://user-images.githubusercontent.com/55167013/71120996-8607be00-21ab-11ea-8f4f-5dc2cc427a96.png)

**Comment by HinataKato** [comment]
https://github.com/taichi-framework/TaiChi/issues/925

**Comment by flostingapplesauce** [comment]
Thanks HinataKato

**Comment by mickychenchen** [comment]
I saw the xprivacylua's author said that he won't make it support in Taichi because Taichi is not open source. I hope it can support the pro too but looks like it won't happen. 😔
