### ISSUE TITLE
BUG：handleloadpackage not called taichi

### ISSUE THREAD

**Issue by iponkan** [taichi-framework/TaiChi#1055]
## 什么问题

handleloadpackage not called taichi

## 详细情况

[WifiSimulator](https://github.com/xuelongqy/WifiSimulator)源码运行，发现没有触发
handleloadpackage

Magisk 版本：20.1
太极 Magisk 模块版本：5.1.7
太极APP版本：东皇钟5.7.3-1243
开启的 Xposed 模块：WIFI模拟器
Xposed模块版本：1.0
开启的其他 Magisk 模块：模拟定位
其他 Magisk 模块版本：1.2.681.1701
手机型号：Google Pixel
ROM版本：Android 10.0

## 配置文件

modules.list
```
/data/app/com.rong.xposed.fakelocation-_anw8-Id19a2bAiuNeCcvQ==/base.apk
/data/app/com.knoyo.wifisimulator-ratDb5IZ0BxLmjN7H32mLQ==/base.apk

``` 
app.list
```
com.knoyo.wifisimulator
com.chenxiabin.xposed.ding
com.wuxiaosu.rimethelper
com.sky.xposed.rimet
__all__
com.sollyu.xposed.hook.model
com.rong.xposed.fakelocation
com.alibaba.android.rimet
com.iponkan.myapplication

```

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by iponkan** [comment]
#900

**Comment by tiann** [comment]
参见：https://github.com/taichi-framework/TaiChi/wiki/how-to-debug-and-develop
