### ISSUE TITLE
taichi-magisk与广发银行系app不兼容

### ISSUE THREAD

**Issue by Fo0o0oX** [taichi-framework/TaiChi#1057]
## 什么问题

taichi-magisk安装后会导致广发银行app、发现精彩app（广发银行信用卡应用）闪退。

## 详细情况

安装taichi-magisk 6.0.0，打开广发银行app 5.0、发现精彩app 4.0闪退。
在magisk中取消勾选taichi-magisk模块，重启后广发银行app、发现精彩app运行正常。
在太极app中并未添加广发银行app和发现精彩app，也无修改此2app的模块。
复现只需要在magisk下安装taichi-magisk，从应用市场下载广发银行app或发现精彩app，点开即可出现闪退。
手机是Redmi K20 Pro，安卓10，MIUI 11 19.12.19开发版

Magisk 版本：20.1
太极 Magisk 模块版本：6.0.0
太极APP版本：5.7.7
开启的 Xposed 模块：杜比大喇叭、大圣净化V-XP、上帝模式、微X模块、XQuickEnery
Xposed模块版本：1.5.3、1.9.1、2.7.10、2.5、1.2.7-temp.1
开启的其他 Magisk 模块：MM、Systemless Hosts、Taichi、iOS12.1 Emoji
其他 Magisk 模块版本：2019.4.4、1.0、6.0.0、version 9
手机型号：Redmi K20 pro
ROM版本：MIUI 11 19.12.29 | 开发版

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
不安装太极模块，只安装面具并且开启 Magisk Hide，也无法使用广发银行app。

**Comment by Fo0o0oX** [comment]
> 不安装太极模块，只安装面具并且开启 Magisk Hide，也无法使用广发银行app。

不会吧？在我手机上是正常的啊 安装面具和hide广发，广发app 5.0.5和发现精彩app 4.2.0都是可以正常运行的。
会不会是复现版本太旧？当然，我的状态是magisk安装了太极未勾选未启用

**Comment by tiann** [comment]
发现问题了，是因为我手机安装了包名含有“xposed”的应用。卸载之后，把广发银行加入太极，可以正常使用。

**Comment by Fo0o0oX** [comment]
> 发现问题了，是因为我手机安装了包名含有“xposed”的应用。卸载之后，把广发银行加入太极，可以正常使用。

好像我遇到的问题跟太极APP什么关系，Magisk肯定是hide的，然后如果不在magisk manager勾taichi，那么广发系app运行正常，勾了就会闪退，与广发系app是否加入太极app无关，只要开启magisk太极模块，广发系app加入了太极app也闪退…怪了…

**Comment by LoveHikari** [comment]
使用magisk taichi模块5.1.2版本时可以正常使用

**Comment by tiann** [comment]
我测了好几个手机，只要开启 Magisk Hide, 即使把广发银行加入太极，一样可以正常使用。所以我觉得这很可能不是太极自己的问题。

**Comment by Fo0o0oX** [comment]
> 我测了好几个手机，在只开启太极面具模块的情况下，只需开启 Magisk Hide, 即使把广发银行加入太极，一样可以正常使用。所以我觉得这很可能不是太极自己的问题。

大佬拿安卓10的MIUI11开发版测试了吗？我用安卓9的FLYME8测试也不闪退…

**Comment by LoveHikari** [comment]
同miui11，当使用5.1.2版本时是可以使用的，其他高版本皆闪退

**Comment by tiann** [comment]
也就是说，
用当前的广发系App + 5.1.2 版本的模块可以用
当前的广发系App + 5.1.3+ 版本的模块会闪退？

**Comment by cqxxbing** [comment]
我没有安装taichi 只是magisk +xposed 也一样闪退，也是K20P
