### ISSUE TITLE
界面改进：强烈建议增加深色模式支持！

### ISSUE THREAD

**Issue by ZerOri** [taichi-framework/TaiChi#1060]
非常喜欢太极的默认白名单模式，目前手机上的app就太极还不支持深色（黑暗）模式了，希望能加以适配，这个功能对OLED屏设备来说还是非常舒服的，万分感谢。

**Comment by gogomarine** [comment]
这种应该只算是Feature Request吧

**Comment by tiann** [comment]
更新到 6.1.0 即可
