### ISSUE TITLE
无法安装应用

### ISSUE THREAD

**Issue by asukayume** [taichi-framework/TaiChi#1061]
## 什么问题

创建应用后进行到“已就绪，按此安装”这一步时无限循环。点击安装，安装完成后提示“已就绪，按此安装”。

## 详细情况
https://imgur.com/a/CpnyGhJ
我试过一共4个app，Google play中下载的QQ可以成功安装,tiktok也是从Google play中下载的但是并不能安装,不是从Google play中安装的测试应用也不能安装。

Magisk 版本：
太极 Magisk 模块版本：无
太极APP版本：5.7.3-1298
开启的 Xposed 模块：无
Xposed模块版本：无
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：SM-G975N（Samsung S10）
ROM版本：one ui 2.0（Android10

## 配置文件
没root似乎没有这个目录
请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
#1033
