### ISSUE TITLE
Inspeckage模块无法正常使用

### ISSUE THREAD

**Issue by ddgweb** [taichi-framework/TaiChi#1064]
Inspeckage2.4，太极magisk最新，虽然能正常勾选Inspeckage，也能监听port，但是网页访问Inspeckage，无法使用大部分功能比如截图、实时刷新、设置代理。
经对比测试，VitraXP可以正常使用，Inspeckage。希望太极这边能优化一下

**Comment by tiann** [comment]
实测可以，姿势不对。
