### ISSUE TITLE
Bug report: 大圣净化V-XP对分身后的微信失效

### ISSUE THREAD

**Issue by jiahe224** [taichi-framework/TaiChi#1068]
先做好应用后再分身，结果分身后的应用并无大圣净化的效果。
设备：MIX 2S
系统：Android 8.0、MIUI 9.6.4
微信：7.0.3
太极阴：5.7.7
大圣净化V-XP：2.5.2

**Comment by tiann** [comment]
如果插件不支持多开，框架也没办法。

**Comment by jiahe224** [comment]
> 如果插件不支持多开，框架也没办法。

刚更新了最新版，发现太极·阴不支持大圣净化VXP版的悟空里的url规则
