### ISSUE TITLE
美团外卖应用不能创建应用

### ISSUE THREAD

**Issue by a736134190** [taichi-framework/TaiChi#1070]
想用将美团外卖中的红包分享到微信中，需要把美团外卖也创建下应用，但是美团外卖的应用不能被创建

**Comment by xesp** [comment]
好像真是这样。我创建美团之后闪退。打不开。

**Comment by KingGGG** [comment]
你可以先试试看 把美团卸载了 再优化美团外卖 （保证一下没有双开美团外卖） 我flyme也提示安装不了 甚至都安装不了正版的美团外卖 但是卸载了以后 就可以了！！！
