### ISSUE TITLE
如果在不开全局情况下让某些模块（如大圣去广告）等对所有app有效？

### ISSUE THREAD

**Issue by iaston** [taichi-framework/TaiChi#1072]
使用的是太极阳，最新版本。
如果不开启全局，就会只对太极内的app生效，如果开启全局，感觉为了个别模块而对系统影响太大。有什么办法吗？

**Comment by tiann** [comment]
常用的有广告的 app 就那么几个，都加进去就ok了。另外我并不觉得全局对系统有那么巨大的影响。
