### ISSUE TITLE
emui9如何双开任意app

### ISSUE THREAD

**Issue by iaston** [taichi-framework/TaiChi#1073]
> 现在，不论是太极阳还是太极阴，双开应用只需两步：
> 
> 
> 
> 把 App 添加（太极·阳）、或者创建到太极。
> 
> 直接在系统中双开对应的应用即可！

可是我把app添加到太极了，在emui的分身中还是只看见QQ和微信，其他的APP还是不能双开。

是哪里操作错了吗？

**Comment by tiann** [comment]
系统限制，只能双开特定app。你可以用 Island 之类的
