### ISSUE TITLE
现在版本还有必要开启阴阳之门吗？

### ISSUE THREAD

**Issue by iaston** [taichi-framework/TaiChi#1074]
> https://github.com/taichi-framework/TaiChi/wiki/How-to-activate-The-God's-door
> 阴阳之门的用途
> 可以大幅优化 太极 创建应用和升级应用的流程；不再需要手动确认，整个流程可以一气呵成。
> 额外提供类似冰箱的冻结功能；可以冻结和隐藏应用。

但现在我用的太极阳上完全没有阴阳的菜单了（之前的版本是有这个菜单的，点击后会提示你要开启，我一直用的是magisk版本），那是不是就说明现在太极上已经没必要用阴阳之门了？

**Comment by tiann** [comment]
单纯用模块的话没啥必要
