### ISSUE TITLE
BUG：太极magisk现在出现了6.0跟6.1是什么版本。。

### ISSUE THREAD

**Issue by kfqkfy** [taichi-framework/TaiChi#1079]
## 什么问题

之前从这边下载了5.x的，然后在
TaiChi-Magisk这个项目里出现了6.x，magisk跟微信公众号最新版都是6.x的，但是6.x的大小比5.x的大了10倍，还有测试了6.x版本支付宝指纹支付一直处于关闭状态，点开通提示指纹服务暂不可用，
TaiChi-Magisk那个项目里没法提issue，就提到这边了，太极换回5.1.3支付宝指纹就没问题了

## 详细情况

Magisk 版本：20.3
太极 Magisk 模块版本：6.1
太极APP版本：5.7.3
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：荣耀10
ROM版本：emui9.1

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
重新实现过后的版本，大小我觉得不是什么问题；如果有别的问题，用老版本也没啥问题。
