### ISSUE TITLE
下载模块页面无法连接到网络

### ISSUE THREAD

**Issue by PalmerChia** [taichi-framework/TaiChi#1082]
试了移动网络或wifi都不行，第一次用
![Screenshot_20200114-164747_TaiChi](https://user-images.githubusercontent.com/13855764/72328389-c9dbdd80-36ed-11ea-962a-825198022005.jpg)

**Comment by heisenme** [comment]
这个问题解决了吗，我现在也是这个问题，移动，wifi, 代理都不行。
