### ISSUE TITLE
Bug report: 掌上公交卡死

### ISSUE THREAD

**Issue by zhenhappy** [taichi-framework/TaiChi#1083]
## 什么问题
掌上公交卡死, 一运行不是很卡卡死, 就是过个三五秒左右就闪退, 好不容杀掉进程才缓过来, 经过测试,即使什么Xposed模块都不启用, 也是同样的情况, 会不会是这货有什么反Xposed机制

（请简要说明你遇到的问题）

## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

太极APP版本：5.8.2-1455
开启的 Xposed 模块：上帝模式, DisableFlagSecure, JustTrustMe, AD快消
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：小米9 Pro 5G
ROM版本：MIUI11 20.1.13

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
可以说下 “掌上公交” 具体是哪个app吗？
另外，是否可以关闭上帝模式和AD快消这两个模块再试试？

**Comment by zhenhappy** [comment]
> 可以说下 “掌上公交” 具体是哪个app吗？
> 另外，是否可以关闭上帝模式和AD快消这两个模块再试试？
是这款软件, 各大应用商店都很容易搜索到, 我后面有试过就是把所有的插件都卸载掉, 也还是不行, 同样问题, 不清楚是什么原因
![image](https://user-images.githubusercontent.com/9161946/72490812-31f80400-3853-11ea-9cc0-69edfd1b2643.png)

**Comment by tiann** [comment]
你用的是太极阴对吗？

**Comment by zhenhappy** [comment]
> 你用的是太极阴对吗？

对, 我手机没解锁也没root也没有刷Magisk模块, 所以应该也只能是太极阴了
