### ISSUE TITLE
BUG：Magisk-taichi v6 各版本均造成支付宝指纹不可用

### ISSUE THREAD

**Issue by Yun7Chen** [taichi-framework/TaiChi#1086]
## 什么问题

Magisk-taichi v6 各版本均造成支付宝指纹不可用（提示：验证失败，请尝试联系手机厂商）。

## 详细情况
Magisk 刷入 magisk-taichi v6 以上版本，均会造成上述问题，而降级为 v5.17 、v5.14，支付宝指纹可正常使用。

Magisk 版本：v7.51＋v20.3（与此无关）
太极 Magisk 模块版本：v6.16（其实是所有v6版本）
太极APP版本：v5.91（与此无关）
开启的 Xposed 模块：多，但无关
Xposed模块版本：多，但无关
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：华为 Mate10
ROM版本：EMUI 8.1

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

[apps.zip](https://github.com/taichi-framework/TaiChi/files/4080670/apps.zip)
[modules.zip](https://github.com/taichi-framework/TaiChi/files/4080671/modules.zip)

![Screenshot_20200118-153114](https://user-images.githubusercontent.com/48726306/72663794-5b6e8680-3a31-11ea-9ec4-5a62e816b869.jpg)

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
是怎么测出来是 v6导致的？把支付宝数据完全清除，然后开启magisk hide试的吗？
我自己也用的是 v6，可以正常使用指纹支付。

**Comment by Yun7Chen** [comment]
@tiann 原就是根据版本更替来测试是否正常，得出上述结论，刚按你说的流程，重装6.16，钛备份清缓存、数据，hide支付宝，还是不能用。

**Comment by fsy953643268** [comment]
我也一样，升级v6指纹会用不了

**Comment by fsy953643268** [comment]
我是emui9.1

**Comment by binext** [comment]
同样的情况，EMUI 9.1.0.337
太极 Magisk 模块版本：v6.18
太极APP版本：v5.93

尝试过magisk模块v6.18，v6.10，v5.13都无法启用太极阳，
v6.18模块下，支付宝的开启指纹支付直接报暂时不可用，
退回v5.13支付宝开启指纹支付正常开启。

之前的EMUI 9.1.0.321，magisk模块v5.13能正常启用太极阳，不知道华为升级又搞什么了，结果退不回去了。
