### ISSUE TITLE
BUG：界面无法正常显示，全局模式无法关闭

### ISSUE THREAD

**Issue by RSSYLY** [taichi-framework/TaiChi#1089]
## 什么问题
界面无法正常显示，全局模式开启后又无法关闭

## 详细情况
前提条件:在装好太极模块后重启生效后打开全局模式,再次重启，进入太极。
1. 如图，首页异常
![Screenshot_20200123-232626_TaiChi](https://user-images.githubusercontent.com/59304676/72999915-09679f80-3e3b-11ea-8fe9-0abaaffad934.jpg)

2.无法关闭全局模式，点击滑块后如图
![Screenshot_20200123-235022_TaiChi](https://user-images.githubusercontent.com/59304676/73000065-4c297780-3e3b-11ea-84b0-b80414d0da86.jpg)

3.应用白名单为空白
![Screenshot_20200123-235104_TaiChi](https://user-images.githubusercontent.com/59304676/73000036-3ddb5b80-3e3b-11ea-8479-4d9ac62d44a4.jpg)

Magisk 版本：20.3
太极 Magisk 模块版本：6.1.6
太极APP版本：5.8.2
开启的 Xposed 模块：绿色守护，应用变量，应用管理，对话框取消，Scene，阻止更新，音量控制器，文本自定义
Xposed模块版本：4.7.5,3.3.2,5.2.7,1.7.0,2.7.8,1.3,0.0.8,2.3.1
开启的其他 Magisk 模块：无
其他 Magisk 模块版本：无
手机型号：三星A9P sm-a9100
ROM版本：(无法找到，oreo8.0，a9100ZCU1BRK3)

## 配置文件

modules.list
/data/app/com.oasisfeng.greenify-gNn1j5SmPdaui3Hil2A5Qw==/base.apk
/data/app/com.sollyu.xposed.hook.model-_K638x_Uu9_68UOHJGYg2Q==/base.apk
/data/app/github.tornaco.xposedmoduletest-oOF8KTc2YXkUmRdgWKdhgw==/base.apk
/data/app/com.mhook.dialog-rnIZBV-1VFWmqU52a_YtSg==/base.apk
/data/app/com.omarea.vtools-YSOvtd0kX5o8ZTjMZQq-fQ==/base.apk
/data/app/me.weishu.preventupdate-bqSkZtiVtMEoQ72k7vo5xQ==/base.apk
/data/app/com.hentaibear.volumecontroller-HbCr7V8l4RPLoU_0rrrNSA==/base.apk
/data/app/liubaoyua.customtext-JxS9M7CPbjUS-YKsE3N2MA==/base.apk
/data/app/com.jozein.xedgepro-oN40TULm9y_jz0QI9QrG8w==/base.apk

apps.list
me.weishu.preventupdate
com.omarea.vtools
liubaoyua.customtext
__all__
com.jozein.xedgepro
com.hentaibear.volumecontroller
com.oasisfeng.greenify
com.sollyu.xposed.hook.model
github.tornaco.xposedmoduletest
com.mhook.dialog

**Comment by RSSYLY** [comment]
> ## 什么问题
> 界面无法正常显示，全局模式开启后又无法关闭
> 
> ## 详细情况
> 前提条件:在装好太极模块后重启生效后打开全局模式,再次重启，进入太极。
> 
> 1. 如图，首页异常
>    ![Screenshot_20200123-232626_TaiChi](https://user-images.githubusercontent.com/59304676/72999915-09679f80-3e3b-11ea-8fe9-0abaaffad934.jpg)
> 
> 2.无法关闭全局模式，点击滑块后如图
> ![Screenshot_20200123-235022_TaiChi](https://user-images.githubusercontent.com/59304676/73000065-4c297780-3e3b-11ea-84b0-b80414d0da86.jpg)
> 
> 3.应用白名单为空白
> ![Screenshot_20200123-235104_TaiChi](https://user-images.githubusercontent.com/59304676/73000036-3ddb5b80-3e3b-11ea-8479-4d9ac62d44a4.jpg)
>4.模块列表里，点击禁用某个模块会导致太极闪退
> 
> Magisk 版本：20.3
> 太极 Magisk 模块版本：6.1.6
> 太极APP版本：5.8.2
> 开启的 Xposed 模块：绿色守护，应用变量，应用管理，对话框取消，Scene，阻止更新，音量控制器，文本自定义
> Xposed模块版本：4.7.5,3.3.2,5.2.7,1.7.0,2.7.8,1.3,0.0.8,2.3.1
> 开启的其他 Magisk 模块：无
> 其他 Magisk 模块版本：无
> 手机型号：三星A9P sm-a9100
> ROM版本：(无法找到，oreo8.0，a9100ZCU1BRK3)
> 
> ## 配置文件
> modules.list
> /data/app/com.oasisfeng.greenify-gNn1j5SmPdaui3Hil2A5Qw==/base.apk
> /data/app/com.sollyu.xposed.hook.model-_K638x_Uu9_68UOHJGYg2Q==/base.apk
> /data/app/github.tornaco.xposedmoduletest-oOF8KTc2YXkUmRdgWKdhgw==/base.apk
> /data/app/com.mhook.dialog-rnIZBV-1VFWmqU52a_YtSg==/base.apk
> /data/app/com.omarea.vtools-YSOvtd0kX5o8ZTjMZQq-fQ==/base.apk
> /data/app/me.weishu.preventupdate-bqSkZtiVtMEoQ72k7vo5xQ==/base.apk
> /data/app/com.hentaibear.volumecontroller-HbCr7V8l4RPLoU_0rrrNSA==/base.apk
> /data/app/liubaoyua.customtext-JxS9M7CPbjUS-YKsE3N2MA==/base.apk
> /data/app/com.jozein.xedgepro-oN40TULm9y_jz0QI9QrG8w==/base.apk
> 
> apps.list
> me.weishu.preventupdate
> com.omarea.vtools
> liubaoyua.customtext
> **all**
> com.jozein.xedgepro
> com.hentaibear.volumecontroller
> com.oasisfeng.greenify
> com.sollyu.xposed.hook.model
> github.tornaco.xposedmoduletest
> com.mhook.dialog

**Comment by tiann** [comment]
能否把系统升级到 9.0 再看看？
