### ISSUE TITLE
BUG：登录腾讯视频提示签名不对

### ISSUE THREAD

**Issue by wwlwwlwwlwwl** [taichi-framework/TaiChi#1090]
## 什么问题
在太极中创建微信和腾讯视频之后 在腾讯视频中使用微信登录提示签名不对

## 详细情况
![Screenshot_20200124_112001_com tencent qqlive](https://user-images.githubusercontent.com/47500260/73042313-c1c53000-3e9b-11ea-8919-8c9d29c14326.jpg)
在太极中创建微信 正常登录腾讯视频提示无法找到微信 在太极中同时创建两个应用 在腾讯视频中登录提示应用签名不对 和截图中一样

太极APP版本：5.8.2-1503
开启的 Xposed 模块：微信:微X模块，MDWechat 腾讯视频:无
Xposed模块版本：微X模块:2.3，MDWechat:3.5.0
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：华为Mate10
ROM版本：EMUI10.0.0.143(C00E143R1P4)

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。
未root 无法读取这两个文件

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
强制停止微信之后再试试

**Comment by wwlwwlwwlwwl** [comment]
可以了 感谢
