### ISSUE TITLE
BUG：太极阳激活Thanox太极出现异常

### ISSUE THREAD

**Issue by shenxiang-c** [taichi-framework/TaiChi#1097]
激活Thanox重启后，从无极变为太极，太极首页版本字体消失且除thanox以外模块全部失效，在xposed下使用则无异常

Magisk 版本：20.3
太极 Magisk 模块版本：6.1.6
太极APP版本：5.9.1
开启的 Xposed 模块：QX模块，上帝模式，
开启的其他 Magisk 模块：riru及存储重定向,busybox。
其他 Magisk 模块版本：（无）
手机型号：LEX720
系统版本Android7.1.2
![Screenshot_2020-02-07-18-40-39-885_com android systemui](https://user-images.githubusercontent.com/60726227/74023202-0e4f5600-49da-11ea-937f-8a6fdf953c8f.png)

**Comment by tiann** [comment]
Android 9.0以下经提供有限的支持。
