### ISSUE TITLE
能否尽量解决无法调用太极外部应用的通用性问题

### ISSUE THREAD

**Issue by meetinnet** [taichi-framework/TaiChi#1101]
太极阴。
看过文档，也知道解决方法，就是把无法调用的应用在太极里面创建一遍即可。
问题是这种应用实在太多了，有的又特别庞大，比如王者荣耀，登录就提示未安装微信，创建一遍好几个大G空间十几分钟素材下载。包括一些新闻app，如头条，财经app，银行app，微视，都不能转发分享。
除了一个个的添加到太极阴里面，还有没有更好地方法解决一下通用问题呢。
谢谢。

**Comment by meetinnet** [comment]
是不是发错地方了，怎么label是Bug

**Comment by tiann** [comment]
只有这个办法
