### ISSUE TITLE
BUG：oppoa59m依次安装了magisk和太极，然后重启，手机就一直卡在开机界面。

### ISSUE THREAD

**Issue by tltanlintl** [taichi-framework/TaiChi#1107]
Magisk版本：20.3
太极Magisk模块版本：6.1.8
太极APP版本：5.8.2
打开的Xposed模块：
Xposed模块版本：
打开的其他Magisk模块：（无）
其他Magisk模块版本：（无）
手机型号：oppo a59m
ROM版本：正式版-161209

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by Mapaler** [comment]
Sony XZs(G8232)，Magisk版本：20.4，太极Magisk模块版本：6.1.8
Magisk版本藏20.3更新到20.4后，手机开机到SONY Logo界面就会重启，然后重复重启过程。
卸载Magisk后重装多次重试发现，一旦20.4安装太极模块，就会导致无限重启的情况，20.3不会。

**Comment by emperorxu** [comment]
Magisk版本：20.4
太极Magisk模块版本：6.1.8
太极APP版本：6.0.2
手机型号：SONY XZP
Magisk版本更新到20.4后，手机开机到SONY XPERIA Logo界面就会重复重启，卸载Magisk后恢复，不安装太极Magisk，20.4Magisk正常使用

**Comment by xiaofei290** [comment]
Magisk版本：20.4
太极Magisk模块版本：6.1.8
太极APP版本：6.1.1
手机型号：SONY XZ1C
Magisk版本更新到20.4后，只要刷入太极6.1.8，手机开机到SONY XPERIA Logo界面就会重复重启，卸载Magisk后恢复，不安装太极Magisk，20.4Magisk正常使用。

**Comment by aipaideer** [comment]
Magisk版本：20.4
太极Magisk模块版本：6.1.8
太极APP版本：6.1.1
手机型号：小米5X
Magisk版本更新到20.4后，只要刷入太极6.1.8，就会卡开机第二屏，卸载Magisk后恢复，不安装太极Magisk，20.4Magisk正常使用。

**Comment by tiann** [comment]
请提供手机里面的 /data/system/taichi/modules.list 以及 /data/system/taichi/apps.list  /data/local/tmp/taichi.log 文件。

**Comment by Mapaler** [comment]
[taichi-debug-file.zip](https://github.com/taichi-framework/TaiChi/files/4448918/taichi-debug-file.zip)
附上了20.3正常使用的文件和20.4异常后的文件。
Magis 20.4装了太极6.1.8后，从TWRP里看没有 /data/system/taichi 文件夹，只有  /data/local/tmp/taichi.log

手机型号：Sony XZs(G8232)，安卓8.0.0

**Comment by xiaofei290** [comment]
@tltanlintl 问题是否已找到原因？一直不敢刷模块，看着好心急

**Comment by Evlos** [comment]
Magisk版本：20.4
太极Magisk模块版本：6.1.8
太极APP版本：5.8.2
手机型号：SONY XZP G8142
手机开机到 XPERIA Logo 界面就会无限重启，刷官 rom 之后重试依然无限重启

**Comment by tanghengvip** [comment]
坚果R1 SOS7.0.1 (安卓8.1.1)
magisk+太极模块，magisk 20.3升级20.4后无限bootloop

**Comment by just-nice1** [comment]
https://shizuku.rikka.app/guide/setup.html?night=1#device-is-not-rooted for taichi

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Mapaler** [comment]
[20.3→20.4.zip](https://github.com/taichi-framework/TaiChi/files/4787879/20.3.20.4.zip)
Magisk版本：20.4
太极Magisk模块版本：6.2.1
太极APP版本：6.2
手机型号：Sony XZs(G8232)，安卓8.0.0

新版本还是无限重启

**Comment by xiaofei290** [comment]
> [20.3→20.4.zip](https://github.com/taichi-framework/TaiChi/files/4787879/20.3.20.4.zip)
> Magisk版本：20.4
> 太极Magisk模块版本：6.2.1
> 太极APP版本：6.2
> 手机型号：Sony XZs(G8232)，安卓8.0.0
> 
> 新版本还是无限重启
20.3+6.2.1+6.3是否正常？

**Comment by Mapaler** [comment]
@xiaofei290 Magisk 20.3可以，这几个月都是用的20.3。

**Comment by xiaofei290** [comment]
> @xiaofei290 Magisk 20.3可以，这几个月都是用的20.3。

20.3+6.3版本的app也没问题？

**Comment by Mapaler** [comment]
> 
> 
> > @xiaofei290 Magisk 20.3可以，这几个月都是用的20.3。
> 
> 20.3+6.3版本的app也没问题？

没试过，只测试APP有意义吗？

**Comment by nightmare30** [comment]
> 请提供手机里面的 /data/system/taichi/modules.list 以及 /data/system/taichi/apps.list /data/local/tmp/taichi.log 文件。

你好
我的设备 Xperia 1 II    XQ-AT52 Android 10
太极版本6.3.0
Magisk版本 20.4
在Magisk刷入太极后出现无限重启，太极中和Magisk中没有其他任何模块
由于没有对应的TWRP，故无法卸载Magisk或太极并提供log。
和前面几位遭遇的情况类似，不知道是否方便修复
谢谢

**Comment by nightmare30** [comment]
> 请提供手机里面的 /data/system/taichi/modules.list 以及 /data/system/taichi/apps.list /data/local/tmp/taichi.log 文件。

我卡开机后重新刷了原来的boot [找到了太极的log
[0.zip](https://github.com/taichi-framework/TaiChi/files/4989830/0.zip)
