### ISSUE TITLE
Update : Exi For Swiftkey Keyboard 

### ISSUE THREAD

**Issue by beingkha3** [taichi-framework/TaiChi#1110]
Please add support for Exi For Swiftkey Keyboard 
 v2.6.0
https://repo.xposed.info/module/com.mayulive.swiftkeyexi

**Comment by tiann** [comment]
https://taichi.cool/doc/module-white-list.html

**Comment by beingkha3** [comment]
Sir this website is in chinese after I registe for white listing the app
