### ISSUE TITLE
無法移除

### ISSUE THREAD

**Issue by sunnyluranja** [taichi-framework/TaiChi#1111]
## 什么问题

無法移除

## 详细情况

安裝完成開啟程式，閃退，進行移除，依然閃退，無法移除此APP

Magisk 版本：無
太极 Magisk 模块版本：無
太极APP版本：東皇鍾5.8.2
开启的 Xposed 模块：無
Xposed模块版本：無
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：J 9110
ROM版本：55.1.A.3.49

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
https://twitter.com/twsxtd/status/1251518007374786562
