### ISSUE TITLE
art::RuntimeCallbacks::DdmPublishChunk 空指针

### ISSUE THREAD

**Issue by aviraxp** [taichi-framework/TaiChi#1116]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
MoKee Version: 'MK100.0-violet-202003241433-EXPERIMENTAL'
Build fingerprint: 'xiaomi/violet/violet:9/PKQ1.181203.001/V10.3.9.0.PFHCNXM:user/release-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2020-03-26 22:15:25+0800
pid: 17597, tid: 17597, name: cent.mm:toolsmp  >>> com.tencent.mm:toolsmp <<<
uid: 10135
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
Cause: null pointer dereference
    r0  f785cb54  r1  00000000  r2  ffe95a24  r3  f78ae3e0
    r4  e2369574  r5  41504e4d  r6  e2369574  r7  00000001
    r8  f544b260  r9  ffe959f4  r10 f37c1028  r11 ffe95a24
    ip  00000000  sp  ffe959c8  lr  f3a95a4f  pc  f3a95b66

backtrace:
      #00 pc 00383b66  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x2e4000) (art::RuntimeCallbacks::DdmPublishChunk(unsigned int, art::ArrayRef<unsigned char const> const&)+482) (BuildId: 9a11dae454bcd615d8f1913509ab47bc)
      #01 pc 00320daf  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x2e4000) (art::DdmServer_nativeSendChunk(_JNIEnv*, _jclass*, int, _jbyteArray*, int, int)+62) (BuildId: 9a11dae454bcd615d8f1913509ab47bc)
      #02 pc 0004cf21  /system/framework/arm/boot-core-libart.oat (art_jni_trampoline+136) (BuildId: 8cd95a27096fb61eb371330d3f2bf7d32071484e)
      #03 pc 000c1349  /system/framework/arm/boot-core-libart.oat (org.apache.harmony.dalvik.ddmc.DdmServer.sendChunk+64) (BuildId: 8cd95a27096fb61eb371330d3f2bf7d32071484e)
      #04 pc 003f8c29  /system/framework/arm/boot-framework.oat (android.ddm.DdmHandleAppName.sendAPNM+232) (BuildId: 238906adec0a115fb27e6efbc18fa69f93618735)
      #05 pc 0044ad89  /system/framework/arm/boot-framework.oat (android.app.ActivityThread.handleBindApplication+1016) (BuildId: 238906adec0a115fb27e6efbc18fa69f93618735)
      #06 pc 004450c1  /system/framework/arm/boot-framework.oat (android.app.ActivityThread$H.handleMessage+6552) (BuildId: 238906adec0a115fb27e6efbc18fa69f93618735)
      #07 pc 006331e1  /system/framework/arm/boot-framework.oat (android.os.Handler.dispatchMessage+136) (BuildId: 238906adec0a115fb27e6efbc18fa69f93618735)
      #08 pc 00635c73  /system/framework/arm/boot-framework.oat (android.os.Looper.loop+1490) (BuildId: 238906adec0a115fb27e6efbc18fa69f93618735)
      #09 pc 0045188d  /system/framework/arm/boot-framework.oat (android.app.ActivityThread.main+748) (BuildId: 238906adec0a115fb27e6efbc18fa69f93618735)
      #10 pc 000d7bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 9a11dae454bcd615d8f1913509ab47bc)
      #11 pc 0042f4e3  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x2e4000) (art_quick_invoke_static_stub+246) (BuildId: 9a11dae454bcd615d8f1913509ab47bc)
      #12 pc 000dffd1  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+196) (BuildId: 9a11dae454bcd615d8f1913509ab47bc)
      #13 pc 00370a43  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x2e4000) (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+54) (BuildId: 9a11dae454bcd615d8f1913509ab47bc)
      #14 pc 00371d6b  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x2e4000) (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned int)+858) (BuildId: 9a11dae454bcd615d8f1913509ab47bc)
      #15 pc 0031ed97  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x2e4000) (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+30) (BuildId: 9a11dae454bcd615d8f1913509ab47bc)
      #16 pc 000b97ef  /system/framework/arm/boot.oat (art_jni_trampoline+110) (BuildId: 022108e22025f7366674173c47b7e7f4dd88466e)
      #17 pc 00829933  /system/framework/arm/boot-framework.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+114) (BuildId: 238906adec0a115fb27e6efbc18fa69f93618735)
      #18 pc 0082ff0b  /system/framework/arm/boot-framework.oat (com.android.internal.os.ZygoteInit.main+1762) (BuildId: 238906adec0a115fb27e6efbc18fa69f93618735)
      #19 pc 000d7bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 9a11dae454bcd615d8f1913509ab47bc)
      #20 pc 0042f4e3  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x2e4000) (art_quick_invoke_static_stub+246) (BuildId: 9a11dae454bcd615d8f1913509ab47bc)
      #21 pc 000dffd1  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+196) (BuildId: 9a11dae454bcd615d8f1913509ab47bc)
      #22 pc 00370a43  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x2e4000) (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+54) (BuildId: 9a11dae454bcd615d8f1913509ab47bc)
      #23 pc 00370873  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x2e4000) (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+290) (BuildId: 9a11dae454bcd615d8f1913509ab47bc)
      #24 pc 002bd2b3  /apex/com.android.runtime/lib/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+462) (BuildId: 9a11dae454bcd615d8f1913509ab47bc)
      #25 pc 0007d355  /system/lib/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+28) (BuildId: 19675c18b6e61731755c7587aebeeb6a)
      #26 pc 0007f755  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+492) (BuildId: 19675c18b6e61731755c7587aebeeb6a)
      #27 pc 00004307  /system/bin/app_process32 (__udivmoddi4+754) (BuildId: b64882950fd463c74612dcea05ce84bc)
      #28 pc 00059d1f  /apex/com.android.runtime/lib/bionic/libc.so (__libc_init+66) (BuildId: 89dae2170d378c5d0f862ca51b6e50d5)
      #29 pc 00004033  /system/bin/app_process32 (__udivmoddi4+30) (BuildId: b64882950fd463c74612dcea05ce84bc)
      #30 pc 00004456  <anonymous:f7e1b000>

**Comment by aviraxp** [comment]
完整tombstone https://paste.ubuntu.com/p/GHc7wYw4F5/

**Comment by tiann** [comment]
看起来不一定是太极的问题
