### ISSUE TITLE
BUG：/data/local/tmp/taichi.log

### ISSUE THREAD

**Issue by lihanchen** [taichi-framework/TaiChi#1122]
## 什么问题

之前手机提示空间不足，发现/data/local/tmp/taichi.log占用40多G

## 详细情况

我的小米9刷的xiaomi.eu的ROM，logcat里会有很多垃圾信息。
看起来太极会把logcat都存到/data/local/tmp/taichi.log
希望能加一个选项关闭这个功能或者限制log大小

Magisk 版本：20.4
太极 Magisk 模块版本：6.1.8
太极APP版本：6.0.2-2397
手机型号：小米9
ROM版本：xiaomi.eu 20.3.26

## 配置文件
这个我觉得是framework基本逻辑问题，应该不需要模块list和log
如果需要我再post

**Comment by tiann** [comment]
卧槽。。我改下

**Comment by lihanchen** [comment]
怎么样了？另外这个写入log有try catch吗？我如果建同名目录会影响t太极功能吗？

**Comment by tiann** [comment]
6.2.0 已修复。
