### ISSUE TITLE
兼容性问题：王者荣耀无法用微信登录

### ISSUE THREAD

**Issue by meetinnet** [taichi-framework/TaiChi#1124]
微信运行在太极阴中，王者荣耀运行在正常系统中，登录的时候提示微信未安装，按照惯例，添加王者荣耀到太极阴里面，再次微信登录的时候提示签名不对，无法进入，见图。

![image](https://user-images.githubusercontent.com/30096780/79065484-25186e80-7ce3-11ea-81ce-0312f5a3c896.png)

**Comment by cc9014** [comment]
手机重启下

**Comment by meetinnet** [comment]
> 手机重启下

你这个办法，我真是无语，你知道王者荣耀多大，安装文件不到2个G，但是装完还要更新一堆乱七八糟的配置，弄利索了4，5个G，没有半小时装不完。 听你一句话，我重新来了两遍!!!  (第一遍华为提示风险，手一抖点了同意卸载。)

关键是，居然特么的好用！！！非常感谢。

**Comment by CodingOX** [comment]
> 微信运行在太极阴中，王者荣耀运行在正常系统中，登录的时候提示微信未安装，按照惯例，添加王者荣耀到太极阴里面，再次微信登录的时候提示签名不对，无法进入，见图。
> 
> ![image](https://user-images.githubusercontent.com/30096780/79065484-25186e80-7ce3-11ea-81ce-0312f5a3c896.png)

我来告诉你这么解决。100%有效。
你先杀掉对应的微信的进程，然后再启动王者，这时候王者会拉起微信的进程，因为是微信第一次被拉起，所以不会出现签名问题！

**Comment by 256051** [comment]
> 

这个方法好！！
