### ISSUE TITLE
麻烦适配一下CustoMIUIzer，这都快反馈一年了

### ISSUE THREAD

**Issue by wzgrx** [taichi-framework/TaiChi#1125]
![Screenshot_2020-04-21-22-44-13-158_com miui home](https://user-images.githubusercontent.com/39661556/79880993-484dc700-8423-11ea-8c85-56205f67c950.png)
![Screenshot_2020-04-21-22-43-17-557_com miui home](https://user-images.githubusercontent.com/39661556/79881031-513e9880-8423-11ea-95ae-93d95b13e0f8.png)

## 什么问题
小米安卓9，全局模式开启CustoMIUIzer
100％卡桌面，卡系统ui，疯狂报错，麻烦修复一下行吗，
从6.0到最新6.12版本，一直这样？不晓得在更新什么
（请简要说明你遇到的问题）

## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：最新
太极 Magisk 模块版本：最新
太极APP版本：最新
开启的 Xposed 模块：CustoMIUIzer
Xposed模块版本：2.2.2
开启的其他 Magisk 模块：(无）无
其他 Magisk 模块版本：（无）无
手机型号：小米
ROM版本：安卓9

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

手机进不去，没办法提供，麻烦自己试试吧，这种小问题拖这么久？
补充：有能力请务必提供日志文件已快速解决问题。

**Comment by just-nice1** [comment]
我什么都知道

Sent from ProtonMail mobile

-------- Original Message --------
