### ISSUE TITLE
Device emulator pro 3.53

### ISSUE THREAD

**Issue by sumsamalar** [taichi-framework/TaiChi#1127]
I don't understand Chinese. But as said v3.53 device emulator pro is not supported it shows module not supported when we open app. And also make device ID masker lite supportable please

**Comment by mickychenchen** [comment]
Device emulator pro only supported in Taichi Yang. You need to root your phone to use it.

**Comment by sumsamalar** [comment]
Thnx device emulator working now.... But please make xprivacylua latest
version compatible bcz without latest xprivacylua pro not working which
adds extra features

**Comment by just-nice1** [comment]
I didn't author this there are shared user i.d. s i did not know about using my email. I apologise. Justin

Sent from ProtonMail mobile

-------- Original Message --------
