### ISSUE TITLE
Xprivacy Lua

### ISSUE THREAD

**Issue by sumsamalar** [taichi-framework/TaiChi#1132]
However Taichi supports xprivacy lua version 1.24.2 but it doesn't support latest one. I have also uploaded the module to admin.taichi.cool but not yet approved. Please approve the latest one asap because Xprivacy lua pro is addon which adds some extra features is not working because it needs latest one

**Comment by tiann** [comment]
please use the fork: https://github.com/android-hacker/XPrivacyLua

**Comment by marcussacana** [comment]
@tiann not working to me, any hints?
