### ISSUE TITLE
功能建议: 随机包名

### ISSUE THREAD

**Issue by Innerside** [taichi-framework/TaiChi#1134]
**什么问题**
希望 太极 App 能够添加类似于Magisk Manager或GameGuardian 所使用的随机包名 功能 来做到更好的隐藏自身。据我所知，目前的一些银行类App已经开始检测太极包名。
比如 中国工商银行App 在用户只安装 太极·阴 并且没有把它加入 太极 内的情况下检测 太极 包名并弹出告警。
**例子**
![0](https://user-images.githubusercontent.com/64391243/81585844-45714100-93e7-11ea-8685-1452043a5ca8.jpg)

**Comment by h3soso** [comment]
> **什么问题**
> 希望 太极 App 能够添加类似于Magisk Manager或GameGuardian 所使用的随机包名 功能 来做到更好的隐藏自身。据我所知，目前的一些银行类App已经开始检测太极包名。
> 比如 中国工商银行App 在用户只安装 太极·阴 并且没有把它加入 太极 内的情况下检测 太极 包名并弹出告警。
> **例子**
> ![0](https://user-images.githubusercontent.com/64391243/81585844-45714100-93e7-11ea-8685-1452043a5ca8.jpg)

是的，我也是这样。

**Comment by Declarcall** [comment]
同，建议随机包名，或自定义包名。

**Comment by myjsqmail** [comment]
同求

**Comment by setion** [comment]
同求+1

**Comment by fcying** [comment]
这是个好功能..

**Comment by bluef1ash** [comment]
同求+1

**Comment by tiann** [comment]
没意义，升级到 Android 11 之后，这个功能就是摆设。
