### ISSUE TITLE
太极·阴 创建的网易云音乐从太极内消失

### ISSUE THREAD

**Issue by wed0n** [taichi-framework/TaiChi#1139]
## 什么问题

太极·阴 创建的网易云音乐从太极内消失

## 详细情况

手机重启后网易云音乐从太极中消失，网易云音乐无法打开，一直卡在启动页，除此之外无任何现象。已经出现了3次这种情况。
自行摸索的缓解方法:从网易官方下载安装包在太极内创建，即可保留数据。

Magisk 版本：无
太极 Magisk 模块版本：无
太极APP版本：湛泸·6.2.0-2972
开启的 Xposed 模块：云村清洁工
Xposed模块版本：2.7.1
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：vivo x21
ROM版本：Android 9 
                    PD1728-YD-B_A_7.9.0

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

### 无root无法提供

**Comment by tiann** [comment]
#1257
