### ISSUE TITLE
BUG：太极阴无法创建B站 6.0 与 6.1 版本

### ISSUE THREAD

**Issue by miyouzi** [taichi-framework/TaiChi#1143]
## 什么问题

哔哩哔哩最新的6.1与6.0版本，太极阴无法创建应用。

PS：B站 5.58 版本可以成功创建。

## 详细情况

在添加新版哔哩哔哩过程中闪退。

Magisk 版本：N/A
太极 Magisk 模块版本：N/A
太极APP版本：6.2.0-3046
开启的 Xposed 模块：哔哩漫游
Xposed模块版本：1.2.5
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：华为平板M6 （10寸版）
ROM版本：EMUI 10.1

**Comment by nightmare30** [comment]
用最新的太极6.4可以解决

**Comment by whatqiu** [comment]
> 用最新的太极6.4可以解决

where is taichi6.4,逗我吗？

**Comment by nightmare30** [comment]
> > 用最新的太极6.4可以解决
> 
> where is taichi6.4,逗我吗？

早就有了 就是不知道官网和GitHub为什么不上
![Screenshot_20200828-232143_TaiChi](https://user-images.githubusercontent.com/65210538/91584672-8f296b80-e985-11ea-874b-e54d9a492429.jpg)

**Comment by just-nice1** [comment]
I need the old stable bug free version how do I get the bugless ?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by tiann** [comment]
fixed in version 6.4
