### ISSUE TITLE
BUG：太极阳magisk成功激活无极后未刷机失效无法重新激活

### ISSUE THREAD

**Issue by ghost** [taichi-framework/TaiChi#1146]
## 
我手机使用无极激活码激活后，过段时间或者用科学上网就会导致码失效，而且一直无法重新激活，Android ID是没有改变的，就一直是已被使用
## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：20415
太极 Magisk 模块版本：6.2.1
太极APP版本：6.3.0
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：机型伪造，WiFi增强，GPS回国，AD hosts，MM，scene
其他 Magisk 模块版本：
手机型号：乐视pro3
ROM版本：10.0

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

modules：/data/app/com.fkzhang.wechatxposed-HPMhxX5evMwdn8t1_1dVYg==/base.apk|com.fkzhang.wechatxposed,com.tencent.mm
/data/app/com.raincat.dolby_beta-v08pqp3L8i00RDofcR5Gkg==/base.apk|com.raincat.dolby_beta,com.netease.cloudmusic
/data/app/github.tornaco.android.thanos-OQ67Tt86Tsk9xZ1zSjsiaQ==/base.apk|com.android.systemui,android,github.tornaco.android.thanos
/data/app/com.rikka.qqFontBubble-d-5niyi82E1k95XPHFlijA==/base.apk|com.rikka.qqFontBubble,com.tencent.mobileqq
/data/app/cn.kwaiching.hook-fc8dAzYWM1GXbKuNkPwWeA==/base.apk|com.ss.android.ugc.aweme,cn.kwaiching.hook
/data/app/louis.baseapk-bu1JXIjhAb3HA0sGloA0TQ==/base.apk|louis.baseapk,com.tencent.mobileqq
/data/app/com.xloger.exlink.app-OoN6EVtLXI2t2TCB6CzLUQ==/base.apk|com.xloger.exlink.app,com.tencent.mm,com.tencent.mobileqq
/data/app/nil.nadph.qnotified-y9avyiAyuaWorIKzLtrLVQ==/base.apk|nil.nadph.qnotified,com.tencent.mobileqq
/data/app/com.specher.music163-vgh-YUFbV80sXs9-eu4mOA==/base.apk|com.specher.music163,com.netease.cloudmusic
/data/app/pansong291.xposed.quickenergy.qiufeng-pL-DRNolpasOVkfIep0POA==/base.apk|com.eg.android.AlipayGphone,pansong291.xposed.quickenergy.qiufeng

apps.list：com.ss.android.ugc.aweme
com.eg.android.AlipayGphone
com.tencent.mm
com.xunmeng.pinduoduo
im.hoho.alipayInstallB
com.tencent.mobileqq
com.huawei.health
com.raincat.dolby_beta
com.fkzhang.wechatxposed
com.tencent.tim
com.specher.music163
com.taobao.taobao
com.netease.cloudmusic
com.xloger.exlink.app
com.rikka.qqFontBubble
com.tencent.qqmusic
louis.baseapk
com.huawei.hwid
com.huawei.android.hsf
nil.nadph.qnotified
pansong291.xposed.quickenergy.qiufeng
cn.kwaiching.hook
com.tencent.qqlive
com.baidu.homework
github.tornaco.android.thanos
com.fenbi.android.solar

#
补充：有能力请务必提供日志文件已快速解决问题。

**Comment by 2242389481** [comment]
![Screenshot_20200613-215451](https://user-images.githubusercontent.com/66890608/84581786-878f0780-ae17-11ea-8a2c-ec98b04fe76e.jpg)
Android ID没有变，但是就是一直提示码失效，这个问题已经好多次了，我已经为同样一部手机要了三四个无极码了，现在的是4428b59f-f994-4261-95bd-cf2dac6d6891
