### ISSUE TITLE
Bug report: Cannot open Taichi

### ISSUE THREAD

**Issue by romanian9** [taichi-framework/TaiChi#1153]
**Describe the bug**
Just installed Taichi 6.3.0 on huawei y9 prime with android 10 and it gives me the following error (Engine is error, You must upgrade the engine otherwise taichi can not work properly) when i tap the (update module engine) it says (update module engine failed, please retry or upgrade Taichi error: -100) when i tap try again it just brings up the same message when i tap upgrade the software shuts down

**To Reproduce**
1. Go to 'open app'

**Expected behavior**
The app to actually work

**Smartphone (please complete the following information):**
Magisk version：none
TaiChi-Magisk module version：none
TaiChi version：6.3.0
Which Xposed modules are enabled ?：none
Xposed modules version：none
Which Magisk modules are enabled ?：none
Magisk modules version：none
Device ：huawei y9 prime
ROM：

**Additional context**
Tried using another mobile (xiaomi redmi note 9s) still got the same issue

**Comment by romanian9** [comment]
> Add any other context about the problem here.

Tried using another mobile (xiaomi redmi note 9s) still got the same issue

**Comment by midot8** [comment]
Me too :(
Android 9

**Comment by paulwongx** [comment]
Is there a fix for this issue? I'm getting the same error on Galaxy Note 4
