### ISSUE TITLE
太极阳模块在Android 11无法复制粘贴

### ISSUE THREAD

**Issue by CuCuCheung** [taichi-framework/TaiChi#1154]
太极 • 阳 在 Android 11会导致系统剪切板失效，使整个系统无法复制粘贴
Magisk 版本：Canary
太极 Magisk 模块版本：6.2.1
太极APP版本：6.3
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：Pixel3 XL
ROM版本：Android 11 beta2

**Comment by tiann** [comment]
[magisk-taichi-v6.2.2.zip](https://github.com/taichi-framework/TaiChi/files/4894539/magisk-taichi-v6.2.2.zip)

**Comment by CuCuCheung** [comment]
谢谢！
