### ISSUE TITLE
BUG：exposed edge 5.42 在太极·Magisk 6.21下未激活不生效

### ISSUE THREAD

**Issue by wanghlstar** [taichi-framework/TaiChi#1155]
## 什么问题

1. exposed edge 5.42 在太极·Magisk 6.21下未激活不生效，包括在模块下载里下载的5.5
2. flyme 自带的分身，按照公众号教程双开，无效

## 详细情况

1. exposed edge 5.42 在太极·Magisk 6.21下提示未激活且不生效，包括在模块下载里下载的5.5，【提示Xposed框架未安装】
太极·Magisk6.1.8 正常，

2. flyme自带的分身，会在/storage/emulated 下建立999的用户文件夹，里面为双开应用的信息，默认非双开应用是/storage/emulated  

Magisk 版本：20.4
太极 Magisk 模块版本：6.2.1
太极APP版本：6.3
开启的 Xposed 模块：
Xposed模块版本：exposed edge 5.42 
开启的其他 Magisk 模块：taichi6.2.1  enhanced mode for storage 黑域补丁版
其他 Magisk 模块版本：enhanced mode for storage 黑域补丁版（必须先启用黑域成功后才能刷入太极，同时或者黑域在后无限重启，不刷黑域也有
【1. exposed edge 5.42 在太极·Magisk 6.21下未激活不生效，包括在模块下载里下载的5.5
2. flyme 自带的分身，按照公众号教程双开，无效】
）
手机型号：魅族16x
ROM版本：flyme 8.1.daily。6.30

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。
/data/system/taichi/modules.list ：
/data/app/com.jozein.xedgepro-3ieqcUPIuHu2asUIU8dAmQ==/base.apk
/data/system/taichi/apps.list：
com.eg.android.AlipayGphone
com.tencent.mm
com.tencent.mobileqq
com.coderstory.toolkit
com.kelvin.wesport
com.android.systemui
com.tencent.tim
com.u.awemepartner
com.dahuo.sunflower.xp.none
com.android.packageinstaller
com.jozein.xedgepro
com.meizu.flyme.update
com.meizu.customizecenter
com.android.mms
com.meizu.mstore
com.phoneinfo.changerpro
com.meizu.flyme.launcher
com.tencent.qqlive
com.rong.xposed.fakelocation

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by wanghlstar** [comment]
[taichi.log.zip](https://github.com/taichi-framework/TaiChi/files/4894613/taichi.log.zip)
log~~

**Comment by wanghlstar** [comment]
[taichi (1).log.zip](https://github.com/taichi-framework/TaiChi/files/4894645/taichi.1.log.zip)
6.18 log

**Comment by tiann** [comment]
用 6.2.2 试一下

**Comment by wanghlstar** [comment]
![WechatIMG270](https://user-images.githubusercontent.com/12810547/87028130-bdee5580-c210-11ea-8afc-ebdc31d81917.jpeg)

flyme的分身类似 island ？那双开就得双开太极和模块了 
=========================
com.jozein.xedgepro 这个仍然无效，目前6.1.8 也够用，不犯强迫症了，月底上安卓10了，再看看是否需要用新版本吧~~
感谢抽空回复，多谢

**Comment by MYCampanula** [comment]
你是那个在杭州黑黑的柏油路上与我们校车回本部的车并行被我看见的吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wanghlstar"<notifications@github.com&gt;; 
发送时间: 2020年7月11日(星期六) 晚上7:26
收件人: "taichi-framework/TaiChi"<TaiChi@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [taichi-framework/TaiChi] BUG：exposed edge 5.42 在太极·Magisk 6.21下未激活不生效 (#1155)





 
Closed #1155.
 
&mdash;
