### ISSUE TITLE
TaichiQQBUG：打开个性签名闪退

### ISSUE THREAD

**Issue by kurisucat** [taichi-framework/TaiChi#1166]
**描述错误**

打开 QQ 的个性签名会闪退

**重现**

重现行为的步骤：

1打开“侧滑栏”

2单击“个性签名”

**预期行为**

不闪退。

**手机信息：**

Taichi 版本：湛泸·6.3.0

启用了哪些Xposed模块？：

- Undo 1.0.4
- 抖音伴侣 2.5
- 上帝模式 2.7.10
- 对话框取消 2.2.0
- CoolapkEX 4.0
- 你才长按复制访问 0.0.8
- DisableFlagSecure 1.2
- ColorQQ 1.4.1
- JustTrustMe 2
- XAotoDaily 1.8.9
- Push 0.3.6.20200315.1bd534f_framework
- 哔哩漫游 1.3.0
- 深色模式切换 2.5.7
- 太极更新宝 5
- UnblockMusic Pro 2.8.0
- QQ瘦身 0.3
- 文本自定义 2.3.1 ԅ(¯﹃¯ԅ)
- 去你大爷的内置浏览器 3.0
- QNotified 0.8.9.58.99b8b18

设备：坚果 Pro 3

ROM：Android 10

**Comment by oO0oO0oO0o0o00** [comment]
QQ 8.3.3.4515没有问题，可能是模块问题。

禁用所有模块后如果没问题，可以每次随机禁用一半模块来不断缩小范围确定来源。

**Comment by kurisucat** [comment]
> QQ 8.3.3.4515没有问题，可能是模块问题。
> 
> 禁用所有模块后如果没问题，可以每次随机禁用一半模块来不断缩小范围确定来源。

试过了，没用...

**Comment by oO0oO0oO0o0o00** [comment]
噗。。是啥版本QQ？确实不行的话窝就先不更新QQ了，谢谢踩坑dalao❤~
