### ISSUE TITLE
工商银行打不开

### ISSUE THREAD

**Issue by g90130** [taichi-framework/TaiChi#1198]
## 什么问题

工商银行APP打开提示检测到太极包名然后自动关闭

## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

太极APP版本：6.4.0.09021214-4961
![Screenshot_2020-12-17-19-12-40-395_com icbc](https://user-images.githubusercontent.com/46667747/102510982-35c78280-40c3-11eb-9302-43460256c5b6.jpg)

**Comment by batumgl** [comment]
我遇到了相同问题

**Comment by Declarcall** [comment]
银行金融类APP 和 太极只能选一个的情况下，必须作出选择

**Comment by tiann** [comment]
升级到 Android 11.
