### ISSUE TITLE
Downloaded Taichi - now having trouble downloading modules...

### ISSUE THREAD

**Issue by adzkash99** [taichi-framework/TaiChi#1207]
So I am on device : OnePlus 3T Android version 9 
OxygenOS version 9.0.6
Rooted via Magisk 
I downloaded and installed Taichi_5.8.2-release.apk 
I downloaded and installed Taichi Magisk module 15.0~16.x 
I then proceeded to download a couple modules 
Then went 
I then went to Magisk manager where I installed the module and then to file manager where I installed the Taichi apk 
After I finished with that I rebooted my device 
When I opened Taichi I was prompted to update something (forgot exact message) anyway I updated it successfully and when I went to modules it was blank and nothing was there. So I went to download modules section and it said there was a network error, but my internet is working fine so I don't get it someone please help!!

**Comment by Xnehaxixh** [comment]
I'm facing the same issue. But mine is a normal install, no root/magisk. I'm on RealmeUI 1 (Android 10).

<a href="https://ibb.co/BVLKdKD"><img src="https://i.ibb.co/kgK6k6n/Screenshot-2021-01-10-20-12-34-85-8121ef2cc23a3edfdb1c2f4b9c942689.jpg" width="300"></a>
