### ISSUE TITLE
BUG：修改为你遇到的问题的详细描述

### ISSUE THREAD

**Issue by wujuncctv** [taichi-framework/TaiChi#1210]
## 什么问题

无法打开微信

## 详细情况

红米note9 安卓10  通过太极重新安装微信后，是黑屏页面
坚果3  安卓7.1.2 通过太极重新安装微信后，是黑屏页面

没有使用其他模块版本

Magisk 版本：
太极 Magisk 模块版本：
太极APP版本：6.1.2-5095
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：红米note9 
ROM版本：安卓10

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
#1219
