### ISSUE TITLE
BUG：微信8.0.0无法打开 启动没有反应

### ISSUE THREAD

**Issue by SingleCoreSun** [taichi-framework/TaiChi#1218]
## 什么问题

从微信7.0.20更新到微信8.0.0之后
出现微信无法打开的情况，点击图标打开无任何反应

## 详细情况

最初使用的微信7.0.20版本是正常使用的
更新到微信8.0.0内测版后就无法打开了
卸载之后重新安装7.0.20仍然无法打开，出现黑屏
一直回退到7.0.18才能使用

Magisk 版本：(无）
太极 Magisk 模块版本：(无）
太极APP版本：版本号:湛泸·6.4.0.09021214-5188
开启的 Xposed 模块：(无）
Xposed模块版本：(无）
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：黑鲨3pro
ROM版本：JOYUI 12 20.11.10

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by PluginsKers** [comment]
遇到同样的情况，我7.0版本就已存在。转生后启动黑屏（无法正常启动）

**Comment by yuhong220002** [comment]
遇到同样的情况+1

**Comment by 52zsj** [comment]
同样的问题 今天刚想弄8.0 然后就一路炸 炸到现在只能用WX V7.0.18

**Comment by actor7z** [comment]
https://wwi.lanzous.com/ix3e8kpu12d  
太极6.5.0拿走不谢！暂时解决7022版黑白屏问题

**Comment by 2370177068** [comment]
加了微信8.0.0之后闪退

**Comment by cz233** [comment]
一加6微信8.0也停止运行 红米note7倒是正常
