### ISSUE TITLE
BUG:无法打开7.0.22及以上版本的微信

### ISSUE THREAD

**Issue by huifeideteji** [taichi-framework/TaiChi#1219]
## 什么问题 
微信7.0.22版本及以上黑屏

## 详细情况
微信7.0.22版本及以上黑屏
在创建微信7.0.22及以上版本微信后会出现黑屏情况，无法使用。
在正常安装不创建的情况下可以正常使用

Magisk 版本：无
太极 Magisk 模块版本：无
太极APP版本：湛沪6.3.0-5195
开启的 Xposed 模块：qn 上帝模式
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：vivo x21i

**Comment by actor7z** [comment]
我12月份就遇到这个问题，测试出来手残更新，聊天记录全没，做了份华为备份。坐等更新解决问题。

**Comment by SingleCoreSun** [comment]
跟楼上一样，做了一份8.0的备份，里面包含了我所有的聊天记录，先暂时用7.18
等修复了再恢复8.0
实在没办法了 折腾不出来

**Comment by huifeideteji** [comment]
我做了备份 结果备份数据全都是损坏的😭
以至于我现在聊天记录全没了

**Comment by SingleCoreSun** [comment]
我的8.0备份，卸载wx再恢复备份之后，显示还在太极中，所以，应该，可能，大概，还没坏
如果太极修复了 可以正常再打开的 吧

**Comment by actor7z** [comment]
> 跟楼上一样，做好一份8.0的备份，里面包含了我所有的聊天记录，先暂时用7.18
> 等修复了再恢复8.0
> 实在没办法了折腾不出来

可惜作者最近忙学业与工作去了无暇更新，现在出新版和测试版我都关注他们更新后是否黑白屏。挽救我的65g聊天记录

**Comment by actor7z** [comment]
兄弟们的已经解决聊天记录成功找回，网上有个原神版太极6.5支修复了7.022版问题，恢复后官网重新下载安装7022即可打开，记得把这几天或者一个月的聊天先备份。

**Comment by LevenYi** [comment]
> 兄弟们我的已经解决聊天记录成功找回，网上有个原神版太极6.5支修复了7.022版问题，恢复后官网重新下载安装7022即可打开，记得把这几天或者一个月的聊天先备份。

hxd指个路

**Comment by actor7z** [comment]
> > 兄弟们我的已经解决聊天记录成功找回，网上有个原神版太极6.5支修复了7.022版问题，恢复后官网重新下载安装7022即可打开，记得把这几个或者一个月的聊天先备份。
> 
> hxd指个路

https://wwi.lanzous.com/ix3e8kpu12d 拿走不谢！
