### ISSUE TITLE
BUG：微信8.0无法使用

### ISSUE THREAD

**Issue by usherzhao** [taichi-framework/TaiChi#1221]
## 什么问题

MIUI12 在太极里安装了微信8.0无法启动

## 详细情况

完整安装.
手机卸载了原有微信以后.直接通过太极安装微信8.0的apk文件

Magisk 版本：
太极 Magisk 模块版本：
太极APP版本：6.4.0.09021214.5209
开启的 Xposed 模块：
Xposed模块版本：128
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：小米8探索版
ROM版本：MIUI12 20.9.4

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。
我在data/system下没看到taichi的目录

补充：有能力请务必提供日志文件已快速解决问题。
![Screenshot_2021-01-27-16-06-03-386_com estrongs android pop](https://user-images.githubusercontent.com/3993043/105961820-ffb1f100-60b9-11eb-994d-62a83ce6ce81.jpg)

**Comment by TinQlo** [comment]
三星S10，Android 10；太极阴128有同样的问题

**Comment by zifeiyue** [comment]
三星NOTE 10，Android 10；太极阴128有同样的问题+1

**Comment by loveless6trq** [comment]
一加7p，Android 10，太极阴128也是，提示应用屡次停止运行

**Comment by ljing124** [comment]
索尼Xperia 1，Android 10，太极阴128遇到同样问题

**Comment by ljing124** [comment]
> 索尼Xperia 1，Android 10，太极阴128遇到同样问题

更换为32位版本微信后能够正常启动

**Comment by just-nice1** [comment]
Fbi here near me followed all day I just told them because the v30 got smashed to pieces and I almost shot my foot thanks

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by LiFaNF** [comment]
> 一加7p，Android 10，太极阴128也是，提示应用屡次停止运行

麻烦问下解决了吗

**Comment by LiFaNF** [comment]
大佬们 你们的问题解决了吗

**Comment by loveless6trq** [comment]
> 大佬们 你们的问题解决了吗

作者公众号上说过年更新解决，等吧

**Comment by LiFaNF** [comment]
> > 大佬们 你们的问题解决了吗
> 
> 作者公众号上说过年更新解决，等吧

好的吧  哎 手贱更新了下  过年期间用不了了啊 退回微信版本也不行

**Comment by usherzhao** [comment]
迫于无奈..我刷了太极阳

**Comment by L-Evan** [comment]
下载原神版解决了问题

**Comment by LiFaNF** [comment]
> 下载原神版解决了问题

原神版是什么呀 会不会比普通的风险多

**Comment by L-Evan** [comment]
> > 下载原神版解决了问题
> 
> 原神版是什么呀会不会比普通的风险多

我觉得不会，不太清楚0.0

**Comment by twmhx** [comment]
> > 下载原神版解决了问题
> 
> 原神版是什么呀 会不会比普通的风险多

为什么我下了原神版还是打不开，一直黑屏。

**Comment by tiann** [comment]
1. 更新到 7.0
2. 从安装包选择原版微信重新安装。
