### ISSUE TITLE
Bug report: Whenever I create WildRift app and after the cloning then install but after no app is installed and the app prompts me to install the app again and nothing is installed

### ISSUE THREAD

**Issue by Teemo15** [taichi-framework/TaiChi#1225]
**Describe the bug**

**To Reproduce**
1. Try to create WildRift app
2. After the cloning and install but no app is installed after you hit the install button
3. The app says "Click to continue: androidx.multidex.MultidexApplication

**Expected behavior**

**Smartphone (please complete the following information):**
Magisk version：
TaiChi-Magisk module version：
TaiChi version：6.4
Which Xposed modules are enabled ?：
Xposed modules version：
Which Magisk modules are enabled ?：
Magisk modules version：
Device ：
ROM：

**Additional context**

**Comment by Teemo15** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Try to create WildRift app
> 2. After the cloning and install but no app is installed after you hit the install button
> 3. The app says "Click to continue: androidx.multidex.MultidexApplication
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Smartphone (please complete the following information):**
> Magisk version：
> TaiChi-Magisk module version：
> TaiChi version：6.4
> Which Xposed modules are enabled ?：
> Xposed modules version：
> Which Magisk modules are enabled ?：
> Magisk modules version：
> Device ：
> ROM：
> 
> **Additional context**
> Add any other context about the problem here.
> 

    Sorry devs for wasting your time I fix it ty

**Comment by epistularum** [comment]
> Sorry devs for wasting your time I fix it ty
I am having the same problem, how did you fix it?
