### ISSUE TITLE
Bug report: App Env is not supported by Taichi app

### ISSUE THREAD

**Issue by meatmax** [taichi-framework/TaiChi#1229]
**Describe the bug**
It says that App Env module is not supported and cannot be check the box.

**Smartphone (please complete the following information):**
TaiChi version：6.4.09
Which Xposed modules are enabled ?：App Env
Xposed modules version：3.2.10
Device ：RMX2020
ROM：stock (realme ui 1)

**Comment by tiann** [comment]
taichi magisk is supported.
