### ISSUE TITLE
MIUI12.5无法使用太极阳

### ISSUE THREAD

**Issue by shiyanaaa** [taichi-framework/TaiChi#1230]
## 什么问题

（请简要说明你遇到的问题）

## 详细情况
维术，报一个bug，红米k20pro安装太极+magisk模块后，重启跳过锁屏直接进入系统，除了设置app，其他APP无法打开，状态栏无法显示，这时卸载了太极就会进入锁屏，然后一切正常，安卓11，MIUI12.5

Magisk 版本：21.4
太极 Magisk 模块版本：6.2.4
太极APP版本：6.1.2
开启的 Xposed 模块：无
Xposed模块版本：无
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：红米k20pro
ROM版本：MIUI12.5 21.2.3

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
你的App版本太低了，用 6.4.0 试下
