### ISSUE TITLE
BUG：华为mate30 pro 5G版安装微信8.0闪退

### ISSUE THREAD

**Issue by Loghaoming** [taichi-framework/TaiChi#1235]
## 什么问题

在太极APP中添加微信8.0的更新包时无法更新，一直闪退。有安装之前版本的微信

手机未解锁未root

Magisk 版本：无
太极 Magisk 模块版本：无

太极APP版本：
![mmexport1613913711180](https://user-images.githubusercontent.com/33663268/108626402-e7e84580-748a-11eb-9d71-a2b035eea22f.jpg)

开启的 Xposed 模块：
![mmexport1613913705886](https://user-images.githubusercontent.com/33663268/108626395-def77400-748a-11eb-9d2f-0baab1ac86fb.jpg)

Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：华为mate30 pro 5G
ROM版本：
![IMG_20210221_211402](https://user-images.githubusercontent.com/33663268/108626422-01898d00-748b-11eb-884b-0de03cec41e2.jpg)

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
升级到最新版太极。
