### ISSUE TITLE
Request you opensource localization for Taichi - 要求您开源太极拳的本地化

### ISSUE THREAD

**Issue by dantecpu** [taichi-framework/TaiChi#1237]
您好，考虑到称为taichi-framework的产品，特别是taichi manager在世界范围内得到广泛使用，我对您有两个要求：

a）至少将隐私政策翻译成英文，以使用户了解他们接受您的产品使用的条件；

b）开放您的本地化文件，以允许非英语或汉语的人满意地使用您的产品。

--------------------------------------------------------------------------------------------------------------------------------------------

Hello, considering the product called taichi-framework and particularly taichi manager are used widespread in the world, I have two requests for you:

a) Translate the privacy policy at least to English to make know users what conditions they accept using your product;

b) opensource your localization files in the optic of allowing people who aren't English nor Chinese Native to use your product with satisfaction.

**Comment by tiann** [comment]
Good advice
