### ISSUE TITLE
希望添加Flyme7助手

### ISSUE THREAD

**Issue by Dragon-klande** [taichi-framework/TaiChi#124]
## 模块名字
Flyme7助手
## 模块用途
Flyme系统屏蔽系统更新、魅族Pay等系统检测Root，Flyme主题和谐，跳过安装应用的安全检测等对Flyme系统非常友好。
## 模块版本号
3.1.6
## 模块安装包
com.coderstory.purify
https://pan.baidu.com/s/14nl-v3V3zOXxVtlqquPT-g
提取码：244j

**Comment by tiann** [comment]
测试下能否正常使用：https://github.com/taichi-framework/Daily-Build/releases
