### ISSUE TITLE
BUG：钉钉的协作页面，工作台页面打不开

### ISSUE THREAD

**Issue by mokasoul** [taichi-framework/TaiChi#1243]
## magisk 中启用太极模块，其他什么模
钉钉的协作页面，工作台页面打不开
## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：
太极 Magisk 模块版本：7
太极APP版本：7.0
开启的 Xposed 模块:无
Xposed模块
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
ROM版本：12.5
![Screenshot_2021-03-29-06-12-03-169_me weishu exp](https://user-images.githubusercontent.com/81537121/112770340-fd9ddd00-8feb-11eb-8699-5da8d2065546.jpg)
![Screenshot_2021-03-29-06-11-50-301_com alibaba android rimet](https://user-images.githubusercontent.com/81537121/112770342-ff67a080-8feb-11eb-8036-9bbf3c82036f.jpg)
![Screenshot_2021-03-29-06-10-33-027_com alibaba android rimet](https://user-images.githubusercontent.com/81537121/112770343-00003700-8fec-11eb-9ae4-a8dfb62c7e21.jpg)
![Screenshot_2021-03-29-06-11-53-025_com alibaba android rimet](https://user-images.githubusercontent.com/81537121/112770344-0098cd80-8fec-11eb-939f-4622ce0c870f.jpg)
![Screenshot_2021-03-29-06-12-36-246_me weishu exp](https://user-images.githubusercontent.com/81537121/112770345-01316400-8fec-11eb-8ae6-303f0ab19ed2.jpg)
[lstmlog.txt](https://github.com/taichi-framework/TaiChi/files/6218207/lstmlog.txt)
[magisk_log_2021-03-29T05_38_41Z.log](https://github.com/taichi-framework/TaiChi/files/6218208/magisk_log_2021-03-29T05_38_41Z.log)

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
#1216
