### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by NSTAdventure** [taichi-framework/TaiChi#1246]
do taichi and its6 non rooted module will work on 

work profile?

**Comment by tiann** [comment]
yes.

**Comment by NSTAdventure** [comment]
> yes.

xinsta and Xprivacy nope not working 

but for xprivacy dev already mention this module won't work on work profile but how about xinsta? dev also contact you if i not wrong

**Comment by tiann** [comment]
It is module specific
