### ISSUE TITLE
BUG：太极阴qq疑似被检测

### ISSUE THREAD

**Issue by huifeideteji** [taichi-framework/TaiChi#1250]
## 什么问题

太极阴qq疑似被检测

## 详细情况

在昨天晚上我更新了qq，在今天下午再次打开QQ时发现被封号。封号原因是非官方客户端

Magisk 版本：无
太极 Magisk 模块版本：无
太极APP版本：曳影7.0.0.02111627-6038
开启的 Xposed 模块：qn
Xposed模块版本：qn为最新
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：vivox21i
![Screenshot_20210429_181754](https://user-images.githubusercontent.com/47907651/116538081-961eca00-a8d6-11eb-8a83-a1483b53c376.jpg)

**Comment by huifeideteji** [comment]
![Uploading Screenshot_20210429_181754.jpg…]()

**Comment by mother-hunter-father-killer** [comment]
我从23号就开始这样了 每天6：00-6：30之间给我封了 天天解 天天这个时间封 也不知道怎么回事 可能是腾讯亲妈死了吧？才开始重视这事？（好像我在无中生妈）

**Comment by raging-flames** [comment]
原来我的是11点过冻结，一次冻一天，换了个手机，还是阴，没事了。

**Comment by 3416581379** [comment]
我也

**Comment by Wuqibor** [comment]
我前天新装的太极，之前这手机没用过
模块也装了QN和QX(都是Github的最新版本)
太极版本是:曳影7.0.0.02111627-6038
手机是:华为畅享20 SE
QXQN就用了一些本地的美化和防撤回，没用卡片之类的功能

**Comment by 19770214** [comment]
qn在其官方tg频道说明了这个问题
因为最近一段tx也开始搞净网行动了，在服务器端动了手脚，即使使用老版本qq也会导致此问题封号
详情请到qn的官方tg频道查看

**Comment by KUMAzw** [comment]
今天才第一次遇到这种情况。。。
本来想着太极Magisk不会改包也许可以解决问题
但是相关的安装教程已经不适用于最新的Magisk了（Magisk和Magisk manager合并了）
