### ISSUE TITLE
BUG：Android 6刷入太极阳模块后卡第二启动屏

### ISSUE THREAD

**Issue by 19770214** [taichi-framework/TaiChi#1251]
## 什么问题

如标题

## 详细情况

在Android 6已root（magiskSU）系统上刷入太极阳模块后卡在第二启动屏，adb抓日志每次抓到的卡循环的原因都不一样（确定是在执行某一个或一段命令时出现问题导致循环执行），但是好像有个什么invalid temperature是每次抓包都会出现的

Magisk 版本：v22.1（22100）
太极 Magisk 模块版本：7.0.0
太极APP版本：7.0.0
开启的 Xposed 模块：大圣净化，女娲石，锁定通知，深色模式切换
Xposed模块版本：未安装
开启的其他 Magisk 模块：过多，如必须请回复我进行填写（确定不是因为模块冲突导致，因为以前没安装时也存在这种问题）
其他 Magisk 模块版本：均为22100
手机型号：CAM-AL00
ROM版本：B220（大概）

## 配置文件

未刷入模块所以不存在

补充：有能力请务必提供日志文件已快速解决问题。

这个adb日志要多抓几次然后一块发吗（因为每次循环部分都不同）

**Comment by tiann** [comment]
请关闭所有模块后重试。
