### ISSUE TITLE
BUG：MIUI12.5稳定版，钉钉最新版工作台打不开

### ISSUE THREAD

**Issue by alipay404** [taichi-framework/TaiChi#1252]
## 什么问题

（请简要说明你遇到的问题）

## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：22.1
太极 Magisk 模块版本：7.0.0
太极APP版本：7.0.0
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：小米10
ROM版本：MIUI 12.5 稳定版

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

[apps.list.txt](https://github.com/taichi-framework/TaiChi/files/6456376/apps.list.txt)
[modules.list.txt](https://github.com/taichi-framework/TaiChi/files/6456377/modules.list.txt)

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
#1216
