### ISSUE TITLE
BUG：刷机升级Android后Magisk模块安装后无法开机

### ISSUE THREAD

**Issue by xtexChooser** [taichi-framework/TaiChi#1254]
参见我在Magisk的Issue ：https://github.com/topjohnwu/Magisk/issues/4354
原先Android6.0.1时可正常使用

Magisk 版本：f822ca5b(23001)
太极 Magisk 模块版本：magisk-taichi-v7.0.0.zip
太极APP版本：湛卢6.1.2-6141
开启的 Xposed 模块：无
Xposed模块版本：无
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：SM-G9008W
ROM版本：lineage

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。
MT管理器无法读取这些文件

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by xtexChooser** [comment]
C:\Users\Administrator>adb shell cat /data/system/taichi/modules.list
cat: /data/system/taichi/modules.list: Permission denied

C:\Users\Administrator>adb shell cat /data/system/taichi/apps.list
cat: /data/system/taichi/apps.list: Permission denied

**Comment by xtexChooser** [comment]
[log_taichi_enabled.txt](https://github.com/taichi-framework/TaiChi/files/6526190/log_taichi_enabled.txt)
[log_magisk_flashed.txt](https://github.com/taichi-framework/TaiChi/files/6526192/log_magisk_flashed.txt)
[log_safe_boot.txt](https://github.com/taichi-framework/TaiChi/files/6526193/log_safe_boot.txt)


看起来像是libepic崩了

**Comment by tiann** [comment]
用低版本的面具模块

**Comment by xtexChooser** [comment]
> 用低版本的面具模块

我尝试了magisk-taichi-v5.1.3.zip，然后bootloop了

**Comment by tiann** [comment]
先删掉面具模块，然后重新安装这个试下：https://taichi.lanzoui.com/ifKPtlkjd0d

**Comment by xtexChooser** [comment]
> 先删掉面具模块，然后重新安装这个试下：https://taichi.lanzoui.com/ifKPtlkjd0d

不行，这波啊，直接在开机动画等了N分钟没反应我强关了

[log_installed_magisk_disabled_taichi.txt](https://github.com/taichi-framework/TaiChi/files/6563844/log_installed_magisk_disabled_taichi.txt)
[log_enabled_taichi.txt](https://github.com/taichi-framework/TaiChi/files/6563847/log_enabled_taichi.txt)

(话说7.0.0不就是我一开始出问题的版本吗

**Comment by xtexChooser** [comment]
> 先删掉面具模块，然后重新安装这个试下：https://taichi.lanzoui.com/ifKPtlkjd0d

在？刚才又试了下你这个，用的是lineage内置的rec，sideload卡住了，手机显示Installed但是一直没退出
![image](https://user-images.githubusercontent.com/46394906/132094484-4d634ac1-3db3-4e15-b070-69cf5d42e4df.png)
