### ISSUE TITLE
Bug report: my module showing not supported

### ISSUE THREAD

**Issue by Android1500** [taichi-framework/TaiChi#1255]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
Magisk version：
TaiChi-Magisk module version：
TaiChi version：
Which Xposed modules are enabled ?：
Xposed modules version：
Which Magisk modules are enabled ?：
Magisk modules version：
Device ：
ROM：

**Additional context**

**Comment by tiann** [comment]
what is "my module" ?

**Comment by Android1500** [comment]
> what is "my module" ?

Sorry You fixed it i am talking about Android Faker but v1.2 show support but v1.3 not support can you fix it?

**Comment by tiann** [comment]
Please submit it in: http://admin.taichi.cool/

**Comment by Android1500** [comment]
> Please submit it in: http://admin.taichi.cool/

Thanks I uploaded module how much time it will take to show?

**Comment by tiann** [comment]
in 5 min

**Comment by Android1500** [comment]
> in 5 min

I already uploaded but still its not show in taichi repo and saying module not support.
