### ISSUE TITLE
安卓11，MIUI12.5，太极阳，钉钉工作台无法打开，首页待办点击后无法打开

### ISSUE THREAD

**Issue by pjkjoe2** [taichi-framework/TaiChi#1256]
## 什么问题

（请简要说明你遇到的问题）

## 详细情况

安卓11，MIUI12.5，太极阳，钉钉工作台无法打开，首页待办点击后无法打开

Magisk 版本：
太极 Magisk 模块版本：7.0
太极APP版本：7.03
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：小米9
ROM版本：MIUI12.5  21.5.27

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
#1216
