### ISSUE TITLE
BUG 重启手机后太极阴内应用(应用宝，钉钉，华住等)消失

### ISSUE THREAD

**Issue by bxtww** [taichi-framework/TaiChi#1257]
每次重启手机后，太极阴里面的应用(应用宝，钉钉等)都消失不见了。重新在添加应用，应用闪退，提示内部错误，必须卸载，然后重新安装添加到太极才能继续使用。看看软件能不能优化一下，再次添加的时候查到软件已经优化的的就不再次优化直接放进去就行，避免每次卸载在安装？微信每次重启都在。

**Comment by bxtww** [comment]
软件消失以后在点击创建应用就显示微信，qq高德五六个软件，退出再点击创建系统所有的应用就都出来了。

**Comment by bxtww** [comment]
重启前启动软件日志：
06-03 16:34:15.006 27278 28106 D Linux   : [Posix_connect Debug]Process me.weishu.exp :80 
06-03 16:34:15.007 27278 28106 D NetdClient: netdClientConnect netId:0, uid:10640, nid:0, addr:::ffff:47.240.109.107, lan:0, localhost:0, sa_family:10, sockfd:70, thread:pool-4-thread-2, threadsocketid:0
06-03 16:34:15.021 27278 28104 D Linux   : [Posix_connect Debug]Process me.weishu.exp :80 
06-03 16:34:15.022 27278 28104 D NetdClient: netdClientConnect netId:0, uid:10640, nid:0, addr:::ffff:43.245.220.89, lan:0, localhost:0, sa_family:10, sockfd:71, thread:pool-4-thread-1, threadsocketid:0
06-03 16:34:15.023 27278 27278 I InputTransport: Create ARC handle: 0xb96a2610
06-03 16:34:15.057 27278 28093 I AdrenoGLES-0: QUALCOMM build                   : e1ac91e, I2b3b5fbd00
06-03 16:34:15.057 27278 28093 I AdrenoGLES-0: Build Date                       : 11/17/20
06-03 16:34:15.057 27278 28093 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.06
06-03 16:34:15.057 27278 28093 I AdrenoGLES-0: Local Branch                     : mybrancheb28e622-fc96-f136-8e55-5cb90179c3d8
06-03 16:34:15.057 27278 28093 I AdrenoGLES-0: Remote Branch                    : quic/gfx-adreno.lnx.1.0.r99-rel
06-03 16:34:15.057 27278 28093 I AdrenoGLES-0: Remote Branch                    : NONE
06-03 16:34:15.057 27278 28093 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
06-03 16:34:15.057 27278 28093 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch32
06-03 16:34:15.057 27278 28093 I AdrenoGLES-0: Driver Path                      : /vendor/lib/egl/libGLESv2_adreno.so
06-03 16:34:15.072 27278 28093 I AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
06-03 16:34:15.119 27278 28115 I me.weishu.exp.core.ExposedStripper: do not need to strip.
06-03 16:34:15.124  1503  1720 I ActivityTaskManager: Displayed me.weishu.exp/.ui.MainActivity: +391ms
06-03 16:34:15.127 27278 27278 D ViewRootImpl[MainActivity]: msg2 update new insets InsetsState: {mDisplayFrame=Rect(0, 0 - 1080, 2340), mSources= { InsetsSource: {mType=ITYPE_STATUS_BAR, mFrame=[0,0][1080,84], mVisible=true}, InsetsSource: {mType=ITYPE_TOP_GESTURES, mFrame=[0,0][1080,84], mVisible=true}, InsetsSource: {mType=ITYPE_LEFT_GESTURES, mFrame=[0,0][0,0], mVisible=true}, InsetsSource: {mType=ITYPE_RIGHT_GESTURES, mFrame=[0,0][0,0], mVisible=true}, InsetsSource: {mType=ITYPE_TOP_TAPPABLE_ELEMENT, mFrame=[0,0][1080,84], mVisible=true}, InsetsSource: {mType=ITYPE_LEFT_DISPLAY_CUTOUT, mFrame=[0,0][-2147483648,2340], mVisible=true}, InsetsSource: {mType=ITYPE_TOP_DISPLAY_CUTOUT, mFrame=[0,0][1080,73], mVisible=true}, InsetsSource: {mType=ITYPE_RIGHT_DISPLAY_CUTOUT, mFrame=[2147483647,0][1080,2340], mVisible=true}, InsetsSource: {mType=ITYPE_BOTTOM_DISPLAY_CUTOUT, mFrame=[0,2147483647][1080,2340], mVisible=true}, InsetsSource: {mType=ITYPE_IME, mFrame=[0,0][0,0], mVisible=false} }
06-03 16:34:15.217 27278 28106 I System.out: responsecode: 200
06-03 16:34:15.422 27278 28105 W VersionUtils: Mismatched versions: core is 'VERSION__5.1__', while android is 'VERSION__5.1-SNAPSHOT__'
06-03 16:34:15.452 27278 27278 W pool-3-thread-2: type=1400 audit(0.0:5505): avc: denied { search } for name="bbkcore" dev="sda18" ino=1741 scontext=u:r:untrusted_app:s0:c128,c258,c512,c768 tcontext=u:object_r:vivo_data_file:s0 tclass=dir permissive=0 app=me.weishu.exp
06-03 16:34:15.932 27278 28107 W Settings: Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
06-03 16:34:16.482 21177 21177 I Finsky  : [2] rgm.onTrimMemory(1): Memory trim requested to level 80
06-03 16:34:16.532 14948 14948 I awcn.ComponentCallbacks2:  onTrimMemory level:5
06-03 16:34:17.868 27278 27315 D NetdClient: queryResolvNetidForUid nid:0, uid:10640, command.cmdId:15
06-03 16:34:17.881 27278 27315 D Linux   : [Posix_connect Debug]Process me.weishu.exp :443 
06-03 16:34:17.882 27278 27315 D NetdClient: netdClientConnect netId:0, uid:10640, nid:0, addr:::ffff:40.70.161.102, lan:0, localhost:0, sa_family:10, sockfd:82, thread:AsyncTask #2, threadsocketid:0
06-03 16:34:19.543 28143 28143 W wnloader:daemo: Using default instruction set features for ARM CPU variant (cortex-a9) using conservative defaults
06-03 16:34:19.546 28143 28143 E wnloader:daemo: Not starting debugger since process cannot load the jdwp agent.
06-03 16:34:19.574 28143 28143 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
06-03 16:34:19.575 28143 28143 I wnloader:daemo: The ClassLoaderContext is a special shared library.
06-03 16:34:19.595 28143 28143 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-03 16:34:19.595 28143 28143 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-03 16:34:19.673 28143 28143 I Runtime : is64Bit: false, isArt: true

06-03 16:34:23.191 28194 28194 I EpicBridge: 	at java.lang.reflect.Method.invoke(Native Method)
06-03 16:34:23.191 28194 28194 I EpicBridge: 	at me.weishu.epic.art2.EpicNative.invoke(Native Method)
06-03 16:34:23.191 28194 28194 I EpicBridge: 	at me.ann.ˏ(SourceFile:248)
06-03 16:34:23.191 28194 28194 I EpicBridge: 	at me.ane.invokeOriginalMethod(SourceFile:419)
06-03 16:34:23.191 28194 28194 I EpicBridge: 	at me.weishu.exposed.ExposedBridge.invokeOriginalMethod(SourceFile:1200)
06-03 16:34:23.191 28194 28194 I EpicBridge: 	at java.lang.reflect.Method.invoke(Native Method)
06-03 16:34:23.191 28194 28194 I EpicBridge: 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethod(SourceFile:451)
06-03 16:34:23.191 28194 28194 I EpicBridge: 	at me.weishu.exposed.ExposedBridge$3.beforeHookedMethod(SourceFile:570)
06-03 16:34:23.191 28194 28194 I EpicBridge: 	at de.robv.android.xposed.ExposedHelper.beforeHookedMethod(SourceFile:48)
06-03 16:34:23.191 28194 28194 I EpicBridge: 	at me.apr$ʻ.ˏ(SourceFile:294)
06-03 16:34:23.191 28194 28194 I EpicBridge: 	at me.ane.a(SourceFile:237)
06-03 16:34:23.191 28194 28194 I EpicBridge: 	at me.ane.a(SourceFile:202)
06-03 16:34:23.191 28194 28194 I EpicBridge: 	at android.content.res.AssetManager_1891872712.openFd(Unknown Source:18)
06-03 16:34:23.191 28194 28194 I EpicBridge: 	at android.graphics.fonts.Font$Builder.createBuffer(Font.java:227)

06-03 16:34:26.672 28194 28194 W beacon-thread-1: type=1400 audit(0.0:5995): avc: denied { read } for name="arp" dev="proc" ino=4026532170 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:proc_net:s0 tclass=file permissive=0 app=com.tencent.android.qqdownloader
06-03 16:34:26.742 27278 27278 W pool-3-thread-2: type=1400 audit(0.0:5996): avc: denied { search } for name="bbkcore" dev="sda18" ino=1741 scontext=u:r:untrusted_app:s0:c128,c258,c512,c768 tcontext=u:object_r:vivo_data_file:s0 tclass=dir permissive=0 app=me.weishu.exp
06-03 16:34:26.772 28691 28776 D NetdClient: queryResolvNetidForUid nid:0, uid:10646, command.cmdId:15
06-03 16:34:26.778 28691 28776 D Linux   : [Posix_connect Debug]Process com.tencent.android.qqdownloader:web :443 

重启后启动软件日志：
--------- beginning of main
06-03 16:39:10.323  9743  9743 D CompatibilityChangeReporter: Compat change id reported: 147600208; UID 10596; state: ENABLED
06-03 16:39:11.078  9743  9743 W [GT]ColdPool#8: type=1400 audit(0.0:1437): avc: granted { execute } for path="/data/user/0/com.tencent.mm/tinker/patch-fb57fdbb/lib/lib/arm64-v8a/libvoipCodec.so" dev="sda18" ino=2442319 scontext=u:r:untrusted_app_29:s0:c84,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c84,c258,c512,c768 tclass=file app=com.tencent.mm
06-03 16:39:11.078  9743  9743 W [GT]ColdPool#8: type=1400 audit(0.0:1438): avc: granted { execute } for path="/data/user/0/com.tencent.mm/tinker/patch-fb57fdbb/lib/lib/arm64-v8a/libvoipComm.so" dev="sda18" ino=2442357 scontext=u:r:untrusted_app_29:s0:c84,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c84,c258,c512,c768 tclass=file app=com.tencent.mm
06-03 16:39:11.138  9792  9792 W cent.mm:toolsmp: type=1400 audit(0.0:1439): avc: denied { search } for name="bbkcore" dev="sda18" ino=1741 scontext=u:r:untrusted_app_29:s0:c84,c258,c512,c768 tcontext=u:object_r:vivo_data_file:s0 tclass=dir permissive=0 app=com.tencent.mm
06-03 16:39:11.138  9792  9792 W cent.mm:toolsmp: type=1400 audit(0.0:1440): avc: denied { search } for name="bbkcore" dev="sda18" ino=1741 scontext=u:r:untrusted_app_29:s0:c84,c258,c512,c768 tcontext=u:object_r:vivo_data_file:s0 tclass=dir permissive=0 app=com.tencent.mm
06-03 16:39:11.148  9792  9792 W cent.mm:toolsmp: type=1400 audit(0.0:1441): avc: granted { execute } for path="/data/user/0/com.tencent.mm/app_xwalk_2797/apk/oat/arm64/base.odex" dev="sda18" ino=2757649 scontext=u:r:untrusted_app_29:s0:c84,c258,c512,c768 tcontext=u:object_r:app_data_file:s0:c84,c258,c512,c768 tclass=file app=com.tencent.mm
06-03 16:39:10.332  1368  1711 I ActivityTaskManager: Displayed me.weishu.exp/.ui.MainActivity: +718ms
06-03 16:39:10.335  5486  8518 I Icing   : Usage reports ok 1, Failed Usage reports 0, indexed 0, rejected 0
06-03 16:39:10.342  9935  9935 D ViewRootImpl[MainActivity]: msg2 update new insets InsetsState: {mDisplayFrame=Rect(0, 0 - 1080, 2340), mSources= { InsetsSource: {mType=ITYPE_STATUS_BAR, mFrame=[0,0][1080,84], mVisible=true}, InsetsSource: {mType=ITYPE_TOP_GESTURES, mFrame=[0,0][1080,84], mVisible=true}, InsetsSource: {mType=ITYPE_LEFT_GESTURES, mFrame=[0,0][0,0], mVisible=true}, InsetsSource: {mType=ITYPE_RIGHT_GESTURES, mFrame=[0,0][0,0], mVisible=true}, InsetsSource: {mType=ITYPE_TOP_TAPPABLE_ELEMENT, mFrame=[0,0][1080,84], mVisible=true}, InsetsSource: {mType=ITYPE_LEFT_DISPLAY_CUTOUT, mFrame=[0,0][-2147483648,2340], mVisible=true}, InsetsSource: {mType=ITYPE_TOP_DISPLAY_CUTOUT, mFrame=[0,0][1080,73], mVisible=true}, InsetsSource: {mType=ITYPE_RIGHT_DISPLAY_CUTOUT, mFrame=[2147483647,0][1080,2340], mVisible=true}, InsetsSource: {mType=ITYPE_BOTTOM_DISPLAY_CUTOUT, mFrame=[0,2147483647][1080,2340], mVisible=true}, InsetsSource: {mType=ITYPE_IME, mFrame=[0,0][0,0], mVisible=false} }
06-03 16:39:10.343  9935 10085 I me.weishu.exp.core.ExposedStripper: do not need to strip.
06-03 16:39:10.375  9445  9664 D NetdClient: netdClientConnect netId:0, uid:10596, nid:0, addr:8.8.8.8, lan:0, localhost:0, sa_family:2, sockfd:140, thread:mars::9664, threadsocketid:0
06-03 16:39:10.376  9445  9664 D NetdClient: netdClientConnect netId:0, uid:10596, nid:0, addr:2000::, lan:0, localhost:0, sa_family:10, sockfd:140, thread:mars::9664, threadsocketid:0
06-03 16:39:10.395  5486  8518 W Icing   : No valid account for uploading user actions
06-03 16:39:10.399  9935 10040 I System.out: responsecode: 200
06-03 16:39:10.411  9445  9664 I mars::stn: [longlink_connect_monitor.cc, NetworkChange, 235]:longlink_progress network change time: 52918
06-03 16:39:10.411  9445  9664 I mars::stn: [longlink_connect_monitor.cc, __IntervalConnect, 248]:longlink_progress next connect interval: 0, process active state: true, process foreground: false
06-03 16:39:10.434  9792  9792 W cent.mm:toolsm: Accessing hidden field Landroid/app/ActivityThread$H;->APPLICATION_INFO_CHANGED:I (greylist-max-o, reflection, denied)
06-03 16:39:10.435  5486  8518 I Icing   : Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0
06-03 16:39:10.447  5486  8518 W Icing   : No valid account for uploading user actions
06-03 16:39:10.450  9445 10100 D NetdClient: netdClientConnect netId:0, uid:10596, nid:0, addr:8.8.8.8, lan:0, localhost:0, sa_family:2, sockfd:137, thread:mars::10100, threadsocketid:0
06-03 16:39:10.451  9445 10100 D NetdClient: netdClientConnect netId:0, uid:10596, nid:0, addr:2000::, lan:0, localhost:0, sa_family:10, sockfd:137, thread:mars::10100, threadsocketid:0
06-03 16:39:10.468  9445 10100 D NetdClient: netdClientConnect netId:0, uid:10596, nid:0, addr:8.8.8.8, lan:0, localhost:0, sa_family:2, sockfd:137, thread:mars::10100, threadsocketid:0
06-03 16:39:10.468  9445 10100 D NetdClient: netdClientConnect netId:0, uid:10596, nid:0, addr:2000::, lan:0, localhost:0, sa_family:10, sockfd:137, thread:mars::10100, threadsocketid:0
06-03 16:39:10.491  9445 10098 D NetdClient: netdClientConnect netId:0, uid:10596, nid:0, addr:8.8.8.8, lan:0, localhost:0, sa_family:2, sockfd:137, thread:mars::10098, threadsocketid:0
06-03 16:39:10.493  9445 10098 D NetdClient: netdClientConnect netId:0, uid:10596, nid:0, addr:2000::, lan:0, localhost:0, sa_family:10, sockfd:137, thread:mars::10098, threadsocketid:0
06-03 16:39:10.495  5486  8518 I Icing   : Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0
06-03 16:39:10.499  5486  8518 W Icing   : No valid account for uploading user actions
06-03 16:39:10.500  9445 10098 E libc    : Access denied finding property "net.dns1"
06-03 16:39:10.500  9445 10098 E libc    : Access denied finding property "net.dns2"
06-03 16:39:10.503  9445 10098 D NetdClient: netdClientConnect netId:0, uid:10596, nid:0, addr:8.8.8.8, lan:0, localhost:0, sa_family:2, sockfd:137, thread:mars::10098, threadsocketid:0
06-03 16:39:10.504  9445 10098 D NetdClient: netdClientConnect netId:0, uid:10596, nid:0, addr:2000::, lan:0, localhost:0, sa_family:10, sockfd:137, thread:mars::10098, threadsocketid:0
06-03 16:39:10.527  9737 10074 W nt.mm:appbrand: Accessing hidden field Landroid/view/LayoutInflater;->mFactorySet:Z (greylist-max-p, reflection, denied)
06-03 16:39:10.539  5486  8518 I Icing   : Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0

06-03 16:39:12.705  8996  9344 E MicroMsg.MultiProcessMMKV: [, , 9344]:MMKV file is too big, name : group_solitatire, size : 2097152, please contact with leafjia
06-03 16:39:12.705  8996  9344 I MicroMsg.KVEasyReport: [, , 9344]:SmcLogic.reportIDKey class loader 153571776, 153571776 
06-03 16:39:12.707  9445 10333 D NetdClient: netdClientConnect netId:0, uid:10596, nid:0, addr:8.8.8.8, lan:0, localhost:0, sa_family:2, sockfd:190, thread:mars::10333, threadsocketid:0
06-03 16:39:12.709  9445 10333 D NetdClient: netdClientConnect netId:0, uid:10596, nid:0, addr:2000::, lan:0, localhost:0, sa_family:10, sockfd:190, thread:mars::10333, threadsocketid:0
06-03 16:39:12.715  8996  9435 I MicroMsg.RemoteResp: [, , 9435]:summerauths jType[251] jBuf[69] jSession[16], jCookieBuf[null]
06-03 16:39:12.716  8996  9435 I MicroMsg.RemoteResp: [, , 9435]:bufToResp unpack ret[true], jType[251], enType[3], noticeid[0], headExtFlags[255] pr len[[B@913f158, 24]
06-03 16:39:12.716  8996  9435 I MicroMsg.RemoteResp: [, , 9435]:bufToResp using protobuf ok jType:251, enType:3 errCode:0, len:24, headExtFlags:255
06-03 16:39:12.720  9445 10333 D NetdClient: netdClientConnect netId:0, uid:10596, nid:0, addr:::ffff:223.166.152.101, lan:0, localhost:0, sa_family:10, sockfd:184, thread:mars::10333, threadsocketid:0
06-03 16:39:12.729  8996  9435 I MicroMsg.RemoteOnGYNetEnd: [, , 9435]:onGYNetEnd netId:0, errType:0, errCode:0, isCancel:false, hash[90651204,121196557]
06-03 16:39:12.742  9743  9768 I nt.mm:appbrand: WaitForGcToComplete blocked RunEmptyCheckpoint on ProfileSaver for 123.299ms
06-03 16:39:12.802  9737  9755 I nt.mm:appbrand: WaitForGcToComplete blocked CollectorTransition on ProfileSaver for 150.399ms
06-03 16:39:12.828  8996  9011 W System  : A resource failed to call close. 
06-03 16:39:12.895  9737 10021 I MicroMsg.StartupLogcatCatcher: [, , 10021]:finish
06-03 16:39:12.899  9737 10021 I ThreadPool.Execute: [, , 10021]:<<< com.tencent.mm.wlogcat.b.c$1@106859590 state=COMPLETE cost=2897ms/52ms ColdPool
06-03 16:39:12.918  9935 10001 D NetdClient: queryResolvNetidForUid nid:0, uid:10640, command.cmdId:15
06-03 16:39:12.920  9935 10337 D NetdClient: queryResolvNetidForUid nid:0, uid:10640, command.cmdId:15
06-03 16:39:12.926  9935 10001 D Linux   : [Posix_connect Debug]Process me.weishu.exp :443 
06-03 16:39:12.927  9935 10001 D NetdClient: netdClientConnect netId:0, uid:10640, nid:0, addr:::ffff:40.70.161.102, lan:0, localhost:0, sa_family:10, sockfd:81, thread:AsyncTask #2, threadsocketid:0
06-03 16:39:12.930  9935 10337 D Linux   : [Posix_connect Debug]Process me.weishu.exp :443 
06-03 16:39:12.930  9935 10337 D NetdClient: netdClientConnect netId:0, uid:10640, nid:0, addr:::ffff:52.177.138.113, lan:0, localhost:0, sa_family:10, sockfd:92, thread:AsyncTask #3, threadsocketid:0
06-03 16:39:13.009  8996  9344 D NetdClient: queryResolvNetidForUid nid:0, uid:10596, command.cmdId:15
06-03 16:39:13.050  9792  9792 I cent.mm:toolsm: WaitForGcToComplete blocked AddRemoveAppImageSpace on AddRemoveAppImageSpace for 795.893ms
06-03 16:39:13.053  9792  9806 W System  : A resource failed to call close. 
06-03 16:39:13.075  9737  9737 I MicroMsg.AppBrandPageViewRendererWC: [, , 9737]:[+]reportBootstrapScriptEvaluateResult succeed appId[null] name[WAWebview.js] url[null] hash[111155307]
06-03 16:39:13.076  9737  9737 I MicroMsg.AppBrand.AbsReader: [, , 9737]:AbsReader version parsed wx.version[2.16.1 | 2021.4.21 17:27:25]
06-03 16:39:13.090  9792  9792 D CompatibilityChangeReporter: Compat change id reported: 147600208; UID 10596; state: ENABLED
06-03 16:39:13.143  9737 10158 I MicroMsg.JsValidationInjector: [, , 10158]:hy: file https://lib/WASubContext.js inject success! cost:550
06-03 16:39:13.143  9737 10158 I MicroMsg.AppBrandJSContextInterfaceWC: [, , 10158]:reportBootstrapScriptEvaluateResult appId[null] name[WASubContext.js] succeed[true]
06-03 16:39:13.148  9737 10158 I MicroMsg.JsValidationInjector: [, , 10158]:hy: file https://lib/WAServiceMainContext.js inject success! cost:1999
06-03 16:39:13.149  9737 10158 I MicroMsg.AppBrandServiceWCScriptReporter: [, , 10158]:reportEvaluateResult, service_lib_script[WAServiceMainContext.js], succeed[true]
06-03 16:39:13.149  9737 10158 I MicroMsg.AppBrandQualitySystemKVProtocol: [, , 10158]:Inject MainContextLibScript[WAServiceMainContext.js] Succeed wx.version = 2.16.1, appId = null
06-03 16:39:13.267  9792 10353 I AdrenoGLES-0: QUALCOMM build                   : e1ac91e, I2b3b5fbd00
06-03 16:39:13.267  9792 10353 I AdrenoGLES-0: Build Date                       : 11/17/20
06-03 16:39:13.267  9792 10353 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.06

**Comment by tiann** [comment]
加我 TG: weishu

**Comment by bxtww** [comment]
链接：https://pan.baidu.com/s/1BTvRHZhsHNKkAXby17pF_A 
提取码：8rll 
我把正常的还有重启后的日志都放百度云盘里面了，已经加你TG了，但是手机上文件没发成功

**Comment by bxtww** [comment]
截图应用包含：微信，滴滴出行，qq,百度地图，高德地图，微博
你好，大概找到原因了，每次手机重启后，立马打开应用就只能获取上面截图六七个应用，我用mt以及开发助手刚重启的时候也是一样，但是用vivo自带的的程序应用没有问题。重启手机后大概两分钟以后在打开太极或者mt等，应用列表就是系统全部的，所以以后重启手机不能立马开太极。目前的问题是一旦开机误操作太极所有的软件都会消失，看看能不能获取很少应用程序的时候软件不能启动直接退出，待获取到应用足够多的时候在允许进去程序，以确保程序不丢失。或者已安装到太极内的程序即使不显示再次添加到太极的时候直接显示在太极内部，避免重装以后出现内部错误必须卸载在进一步安装.

**Comment by tiann** [comment]
打开系统中太极的权限设置，有个安全等级，设置为低试一下。

**Comment by tiann** [comment]
http://dl.dimensionalzone.com/f/19604958-499499738-593be4
