### ISSUE TITLE
企业微信3.1.8版本, 打不开, 点击闪屏一下就退出了

### ISSUE THREAD

**Issue by zzzgd** [taichi-framework/TaiChi#1258]
## 什么问题

如题
## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：
太极 Magisk 模块版本：
太极APP版本： 曳影 7.0.3.05282148-6234
开启的 Xposed 模块：lataclysm 1.35
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：华为p40

**Comment by tiann** [comment]
插件问题。

**Comment by zhougz520** [comment]
@zzzgd 你的问题解决了吗？我也有这个问题

**Comment by zzzgd** [comment]
> @zzzgd 你的问题解决了吗？我也有这个问题

好像折腾了几次, 太极和企业微信都删除了重下好像可以了, 最简单的办法就是退版本
