### ISSUE TITLE
太极阳模块无法使用

### ISSUE THREAD

**Issue by SunFlower-CX** [taichi-framework/TaiChi#1260]
## 什么问题

太极阳模块如微x模块，qn无法在微信qq设置里显示

## 详细情况

安装模块后已重启手机还是出现视频中的问题

https://user-images.githubusercontent.com/67369886/120878492-707c9300-c5ef-11eb-892c-8e659be5e3e7.mp4

Magisk 版本：23.0(23000)
太极 Magisk 模块版本：7.0.0
太极APP版本：7.0.0
开启的 Xposed 模块：微x模块，qnotified
Xposed模块版本：微x模块2.22 qnotfied 0.8.19.2c41172
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：Redmi POCO F3
ROM版本：ArrowOS 11.0 Offical 
Android 11

## 配置文件
![微信图片_20210605111201](https://user-images.githubusercontent.com/67369886/120878424-e2081180-c5ee-11eb-8596-57ee9ca8f8f5.png)
![微信图片_20210605111205](https://user-images.githubusercontent.com/67369886/120878425-e3d1d500-c5ee-11eb-8fce-59c867454664.png)
![微信图片_20210605111708](https://user-images.githubusercontent.com/67369886/120878518-96099c80-c5ef-11eb-8e8a-c5e6e9d43555.png)

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
重新勾选

**Comment by tiann** [comment]
不支持你这个 qq 版本

**Comment by SunFlower-CX** [comment]
> 不支持你这个 qq 版本

你好，安装qq8.0.0 重新勾选模块还是不行，我需要提供别的什么文件以方便查明原因
