### ISSUE TITLE
王者荣耀 新赛季 加入后闪退

### ISSUE THREAD

**Issue by zivencn** [taichi-framework/TaiChi#1264]
王者荣耀 新赛季 加入后闪退

**Comment by tiann** [comment]
请提供详细信息。

**Comment by zivencn** [comment]
太极版本：7.0.3.05282148-6343
王者荣耀：v3.65.1.6

6月23号王者荣耀更新后，新版本拉入太极里面，打开10秒钟左右闪退

尝试过卸载，重装，不能解决。

王者荣耀未更新之前都是正常使用的，就是这次更新之后出现闪退问题的。
