### ISSUE TITLE
错误码：-100

### ISSUE THREAD

**Issue by Og371828** [taichi-framework/TaiChi#1331]
![Collage_20220505_164733](https://user-images.githubusercontent.com/98318626/166890359-0d500cb9-a409-4f33-a088-c0c7f905f04b.jpg)

鸿蒙2.0配置，最新版太极：版本承影．9.0.1.04182224。
请教什么问题（之前好的，闲着没事卸了再下最新版后前几天也可以用，今天打开就这这样了）一直重试一直不行，已经说最新版本它仍让我更新版本，点了更新又闪退。

**Comment by Og371828** [comment]
![Screenshot_20220505_162123_me weishu exp](https://user-images.githubusercontent.com/98318626/166887314-fcff00da-748c-4194-bd30-bb03ab8630f1.jpg)

**Comment by Og371828** [comment]
![Uploading Screenshot_20220505_162514_me.weishu.exp.jpg…]()

**Comment by Og371828** [comment]
![Uploading Screenshot_20220505_162225_com.android.settings.jpg…]()

**Comment by Og371828** [comment]
![Uploading Screenshot_20220505_162442.jpg…]()

**Comment by Og371828** [comment]
![Uploading Screenshot_20220505_162514_me.weishu.exp.jpg…]()

**Comment by oit63** [comment]
可能服务器挂了，我索尼刚重装了太极也是

**Comment by myillustrious** [comment]
+1我也是这个问题，一开始我还以为是修手机之前备份的太极阳恢复后用不了。。

**Comment by LChenGit** [comment]
新手机昨天上午装了太极还没问题 因为别的问题reset了一下 重装了以后太极就100错误了 搜了下说是服务器问题
