### ISSUE TITLE
Bug report: Can't Update Module Engine 

### ISSUE THREAD

**Issue by YourBoyPoy** [taichi-framework/TaiChi#1332]
**Describe the bug**
I cant Update Module engine 

**To Reproduce**
1. Go Open App
2. Click on Update Module engine
3. Says update module engine Failed (error: - 100)

**Expected behavior**
At first It says to update module engine ..I saw someone on yt They Update it.. It supposed to Say Update success..But mine says update module engine Failed.. And When i Clicked Upgrade Tachi It Crashes..
 But its the latest app idk what to do

**Smartphone (please complete the following information):**
Magisk version：none
TaiChi-Magisk module version：None
TaiChi version：9.0.1
Which Xposed modules are enabled ?：Xinstaller
Xposed modules version：5.0
Which Magisk modules are enabled ?：none
Magisk modules version：idk
Device ：Oppo A12e
ROM：

**Additional context**
My app Ver is 9.0.1 which is The latest in May 5 2022
![Screenshot_2022-05-05-17-48-54-85](https://user-images.githubusercontent.com/104979278/166900339-4e7a35c5-0deb-43f6-bfb8-8c47d5e5202c.png)
@tiann

**Comment by justyukio** [comment]
me2

**Comment by justyukio** [comment]
server offline

**Comment by YourBoyPoy** [comment]
> server offline

When Will be Fix?

**Comment by tiann** [comment]
fixed

**Comment by YourBoyPoy** [comment]
> fixed

Ty
