### ISSUE TITLE
BUG：太极阳在安卓模拟器中出现兼容性错误，无法启用taichi-zygisk模块

### ISSUE THREAD

**Issue by huayuprophet** [taichi-framework/TaiChi#1363]
## 什么问题

在pc安卓模拟器中，太极阳无法正常启用太极zygisk模块，变灰无法选择，提示存在兼容性问题。
非zygisk版本未测，并且不知道在其他安卓x86镜像如wsl中是否存在同样问题

## 详细情况

案例：pc安卓逍遥模拟器，安卓712-64镜像，安装magisk-delta和最新版本太极阳

Magisk 版本：
太极 Magisk 模块版本：迄今最新
太极APP版本：迄今最新
开启的 Xposed 模块：无
Xposed模块版本：无
开启的其他 Magisk 模块：无
其他 Magisk 模块版本：无
手机型号：逍遥安卓x86 7.1.2-64bit
ROM版本：同上

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。
（无关文件）

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
你定义一下什么叫“最新”

**Comment by huayuprophet** [comment]
app版本10.2.2
模块版本zygisk-taichi-v8.0.0
