### ISSUE TITLE
BUG：软件闪退

### ISSUE THREAD

**Issue by kasa888** [taichi-framework/TaiChi#1384]
## 什么问题

使用太极阴加载软件后 打开软件闪退

## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：太极阴
太极 Magisk 模块版本：
太极APP版本：内核129
开启的 Xposed 模块：无
Xposed模块版本：无
开启的其他 Magisk 模块：(无）无
其他 Magisk 模块版本：（无）无
手机型号：NOTE12R
ROM版本：

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by lobsterforsale** [comment]
出现了同样的问题，手机重启后所有太极内软件卡在打开页面。

**Comment by Haibara-z** [comment]
MIUI 14.0.3出现同样问题，软件卡在打开页面或者闪退

**Comment by tiann** [comment]
连个版本都不知道，你是要人算命吗？
