### ISSUE TITLE
Bug report: 昨晚睡前还好好的，早上起来打开微信发现黑屏了

### ISSUE THREAD

**Issue by mikephp2022** [taichi-framework/TaiChi#1387]
微信8.0.2，太极阴7.0，手机安卓12.0
早上起来后打开微信发现黑屏。重启了还是一样。以为是太极版本太旧。就下载了14.0.5版本覆盖安装。打开微信还是黑屏
模块全部关了打开也是一样黑屏
求助有人知道现在我该怎么做吗？

**Comment by tiann** [comment]
日志

**Comment by mikephp2022** [comment]
> 日志

唉 没有root 进不去data目录

**Comment by mikephp2022** [comment]
> 日志

![image](https://github.com/taichi-framework/TaiChi/assets/101032086/198c8c9e-3c3f-4a34-82bf-d440b8b4f8fd)

**Comment by tiann** [comment]
https://taichi.cool/zh/doc/adb.html

**Comment by mikephp2022** [comment]
> https://taichi.cool/zh/doc/adb.html
谢谢教程
[bugreport.zip](https://github.com/taichi-framework/TaiChi/files/12908656/bugreport.zip)

**Comment by tiann** [comment]
> > https://taichi.cool/zh/doc/adb.html
> > 谢谢教程
> > [bugreport.zip](https://github.com/taichi-framework/TaiChi/files/12908656/bugreport.zip)

https://taichi.lanzouq.com/i4suM1buf7oj 这个版本还有问题吗？

**Comment by mikephp2022** [comment]
> > > https://taichi.cool/zh/doc/adb.html
> > > 谢谢教程
> > > [bugreport.zip](https://github.com/taichi-framework/TaiChi/files/12908656/bugreport.zip)
> 
> https://taichi.lanzouq.com/i4suM1buf7oj 这个版本还有问题吗？

就是微信打开黑屏问题了

**Comment by tiann** [comment]
> > > > https://taichi.cool/zh/doc/adb.html
> > > > 谢谢教程
> > > > [bugreport.zip](https://github.com/taichi-framework/TaiChi/files/12908656/bugreport.zip)
> > 
> > 
> > https://taichi.lanzouq.com/i4suM1buf7oj 这个版本还有问题吗？
> 
> 就是微信打开黑屏问题了

再试试这个：https://taichi.lanzouq.com/iTA0a1buk0wf

**Comment by mikephp2022** [comment]
> > > > > https://taichi.cool/zh/doc/adb.html
> > > > > 谢谢教程
> > > > > [bugreport.zip](https://github.com/taichi-framework/TaiChi/files/12908656/bugreport.zip)
> > > 
> > > 
> > > https://taichi.lanzouq.com/i4suM1buf7oj 这个版本还有问题吗？
> > 
> > 
> > 就是微信打开黑屏问题了
> 
> 再试试这个：https://taichi.lanzouq.com/iTA0a1buk0wf

唉 还是黑屏 已经删除所有模块 也重启手机

**Comment by tiann** [comment]
<img width="140" alt="image" src="https://github.com/taichi-framework/TaiChi/assets/4233744/05bf3553-6724-4278-8a7b-03ca51000341">
如果愿意的话，可以加我微信解决。

**Comment by mikephp2022** [comment]
> <img alt="image" width="140" src="https://user-images.githubusercontent.com/4233744/275307118-05bf3553-6724-4278-8a7b-03ca51000341.png"> 如果愿意的话，可以加我微信解决。

我微信打不开。我借一下别人的

**Comment by tiann** [comment]
qq 也行，你 qq 号告诉我加你；如果这里不方便，可以邮件 twsxtd@gmail.com 告诉我。
