### ISSUE TITLE
请求支持 NekoSMS

### ISSUE THREAD

**Issue by Metaphilium** [taichi-framework/TaiChi#151]
## 模块名字
NekoSMS
## 模块用途
根据自定义的规则拦截短信
## 模块版本号
0.17.0
## 模块安装包
https://github.com/apsun/NekoSMS/releases

### 其它
~~另外请问一下假如 NekoSMS 可以使用的话应该添加哪个应用呢，是「信息服务」（com.android.mms.service）吗？~~

--------

### 更新
拦截正常
@Louissenny 的问题，**仅需**添加「**电话服务**」（**com.android.phone**）即可。

**Comment by hongsheep** [comment]
本来想单独提交一个issue，看了下已经有了。这是良心好软，必须支持。

**Comment by danche4810** [comment]
我是小白

**Comment by danche4810** [comment]
怎么提交

**Comment by hongsheep** [comment]
进了这个thread已经有人提交了…坐等研发。

**Comment by Louissenny** [comment]
+1 原生9.0表示真的找不到一个好用的短信拦截app quq

**Comment by tiann** [comment]
模块引擎更新到 13 试下是否可以用。
注意：添加 电话服务（包名 com.android.phone) 到太极。

**Comment by Metaphilium** [comment]
太极・Magisk 4.7.0 / 模块引擎 14
NekoSMS 已启用 目前暂未收到短信所以还没测试，等有相关情况我会在这儿反馈。感谢作者的辛勤工作！

**Comment by Louissenny** [comment]
只需要添加电话服务就可以了吗？短信服务是否需要
