### ISSUE TITLE
太极模块与Viperfx冲突

### ISSUE THREAD

**Issue by Jack0001** [taichi-framework/TaiChi#165]
手机型号：Redmi 5 Plus
ROM版本：Resurrection Remix 7.0(Android Pie)
Xposed模块：未启用
APP：Viperfx

问题描述：刷入太极模块后第一次启动，一切正常，重启后太极失效变回阴，Viperfx也无法挂载(app消失)，取消激活太极模块后，Viperfx重新正常挂载。

其他Magisk模块：mm管理器，Viperfx，fbind

补充：支付宝貌似也在太极模块挂载时无法正常打开，卡在启动界面。

**Comment by Jack0001** [comment]
刚刚发现，即使保留一个模块，只激活太极，也是仅第一次启动生效，重启后失效。

**Comment by 13192937589** [comment]
希望大佬加入此模块振动调节器，
https://repo.xposed.info/module/ztc1997.vibrationtuner

**Comment by tiann** [comment]
@13192937589 新问题单独开 issue，写在这可能会忘了

**Comment by kid-oh** [comment]
我也有这个问题，viper会出现清除数据进行启用

**Comment by tiann** [comment]
最新版 4.7 是否有这个问题？
