### ISSUE TITLE
求支持【一个视界】xposed模块适配

### ISSUE THREAD

**Issue by a2212997715** [taichi-framework/TaiChi#185]
## 模块名字
一个视界
## 模块用途
这是 第二空间 的Xposed版。常规的应用锁软件使用轮询或者辅助功能来检测当前的运行进程，这会耗尽电池并减慢设备的运行速度并且需要程序始终保持后台运行。在Xposed框架的帮助下，一个视界使用事件驱动的方法来检测应用程序的启动并锁定它，从而实现更好的性能和更全面的应用保护。同时当隐藏应用图标后，通过拨号启动应用将无需常驻后台。
一个视界是一个超级强大的隐私保护应用，它可以巧妙而秘密地隐藏图片、视频、文件以及应用，为您所有的秘密提供一个安全而隐秘的空间。

## 模块版本号
8.3.2
## 模块安装包
http://t.cn/EtmxJRo

**Comment by tiann** [comment]
开启此模块之后，进入应用锁可以正常设置；但是打开对应的应用没有任何表现，这个应该需要一个视界的开发者协助才能解决。

**Comment by a2212997715** [comment]
> 开启此模块之后，进入应用锁可以正常设置；但是打开对应的应用没有任何表现，这个应该需要一个视界的开发者协助才能解决。

已经给模块作者反馈了，感谢weishu
