### ISSUE TITLE
哔哩布丁1.5.6 哔哩哔哩5.37.0卡启动页

### ISSUE THREAD

**Issue by blackyau** [taichi-framework/TaiChi#192]
手机型号：华为Mate9 Pro LON-AL00
ROM版本：EMUI 8.0.0
Xposed模块：哔哩布丁1.5.6 #78 
APP：哔哩哔哩5.37.0

问题描述：
在太极中勾选激活 哔哩布丁1.5.6 启动 哔哩哔哩 时会卡首屏，并且会提示 「太极已阻止 哔哩哔哩 闪退」，其他模块均使用正常

其他Magisk模块：
ADB & Fastboot for Android NDK
App Ops System Plugin
DNS Switcher
Google Sans MOD Font
Ice Box System Plugin Module
Riru - Core
Riru - Storage Redirect

其他Xposed模块：
QQ净化 2.7.0
音量增强器 0.0.29
云村清洁工 2.6.1
蚂蚁森林梦 1.4

补充：
以下是完整的 logcat
我在 10:17 启动的哔哩哔哩
https://drive.google.com/open?id=1z8wy0bJ8gwChL5Qszyf0ERBrsRvv78Ot

**Comment by Cloudy-Kumori** [comment]
同样

**Comment by jzl2163** [comment]
同样

**Comment by 1604589485** [comment]
一样，我是mate20Pro

**Comment by kckm** [comment]
同样情况，没有其他magisk模块和xposed模块也会卡第一屏，暂时把布丁退回1.5.5使用。

**Comment by 103268** [comment]
同，但概念版正常使用

**Comment by tiann** [comment]
fixed https://www.lanzous.com/i36ytmj
