### ISSUE TITLE
请求添加进程锁-防止掉后台模块

### ISSUE THREAD

**Issue by mu3c** [taichi-framework/TaiChi#196]
## 模块名字
进程锁-防止掉后台
## 模块用途
用于锁进程，像QQ微信这种需要后台的应用，一旦划掉任务卡片，就要重新启动，而重新启动又要好几秒才能进去。。
## 模块版本号
3.1.1_Stable_20180627113000
## 模块安装包
https://www.coolapk.com/apk/top.fols.aapp.eternalprocessxposed

**Comment by 06ji** [comment]
微信和QQ划掉是不掉的，基本上进缓存了

**Comment by mu3c** [comment]
进不进缓存不懂。我的一划掉重新点就要见到启动页，卡好几秒。不划掉才能随便切。之前用这个的永恒锁才能锁住，划掉之后重新点进去就都马上进去了。而且普通的锁还锁不住，，要永恒锁才可以。。MIUI。系统里该给的什么无限制后台什么的也都统统给了。。因为游戏检测才换了太极。。

**Comment by MichaelPanPRC** [comment]
@06ji 在 Android Pie 上， API 26 的微信保留人物卡在后台的方式是缓存，划掉缓存立刻掉，一点后台不留，与 issue 描述一致。

**Comment by Travisss** [comment]
qq微信我这里设置自启动后，后台划掉也无所谓，不会关掉

**Comment by tiann** [comment]
条件：
1. 太极主版本升级到 5.1.8。低版本不要尝试，会导致无法开机等严重问题。  
2. 进程锁升级到 3.1.2
3. 模块适配引擎更新到 82.
