### ISSUE TITLE
高德闪退

### ISSUE THREAD

**Issue by 839008591** [taichi-framework/TaiChi#237]
太极Magisk模块版本：4.5

太极APP版本：4.3.2

手机型号：1+5t

ROM版本：魔趣9

Xposed模块：MDWechat

APP：高德地图，微信

APP及版本：高德8.88.0
xposed版本:3.4.0
问题描述：

①将高德地图app添加到太极magisk后，闪退
②不勾选tablayout选项，首页和尾页的tablayout就无法显示

**Comment by tiann** [comment]
#320 

已经查明，同一个原因。
