### ISSUE TITLE
适配 应用控制器 v3.0.1版！！！

### ISSUE THREAD

**Issue by abc2209198** [taichi-framework/TaiChi#272]
## 模块更新了什么？

1、服务禁用、唤醒锁禁用、定时器禁用（类似Per App Hacking）

2、强退、Standby和墓碑功能。强退类似黑域或阻止运行而墓碑和Standby类似iOS系统的后台方式。

3、IFW禁用防火墙，可以单独禁用服务、广播、活动 三种组件（类似写轮眼）并且加入了Xposed压制，如果有框架效果更强，不给毒瘤启动的机会。该功能需要ROOT。

4、最近任务控制，可以锁定最近任务、模糊最近任务预览、移除杀死进程。

5、冻结应用、阻止卸载，冻结应用，启动时自动解冻和关闭时自动冻结，并可以创建快捷方式，禁止卸载可以防止他人卸载APP。

6、应用锁、启动控制，可以控制自己启动的应用，可以锁定应用通过指纹解锁进入应用

7、内存清理，adb命令等。

8、强制打盹功能，可设置亮屏打盹、熄屏打盹、白名单等。

9、界面控制，类似PCB（perfectcolorbar）,可以让应用状态栏和导航栏变色（自动取色），可以更改toast样式，可设置屏幕圆角。

10、跳过广告功能和对话框通知屏蔽功能，提供了三种跳过方式针对不同的应用进行不同的设置，适用于大多应用。

11、后续会增加更多功能，发展方向主要为优化应用，但也会增加一些不影响性能的其他小功能。

**Comment by a2212997715** [comment]
这app作者有时候一天3更新
太极什么时候能适配完
能不能开放版本啊，

**Comment by tiann** [comment]
开放了有什么用，压根用不了现在。

**Comment by tiann** [comment]
以后会适配的，现在你可以用 2.8.9 版本

**Comment by luo1227135067** [comment]
过年前我就请求适配3.0版本了。然后他们适配不了。出了问题，回复我说年后慢慢搞，然后到现在还是2.8.9。反正就是这个太强大，他们搞不定，应该就是这样

**Comment by tiann** [comment]
随你怎么说，你这种人很恶心

**Comment by tiann** [comment]
三无小号跑过来闹事是不，丢不丢人
