### ISSUE TITLE
太极阴添加youtube中途闪退

### ISSUE THREAD

**Issue by duanxr** [taichi-framework/TaiChi#275]
太极Magisk模块版本：无
太极APP版本：4.30
手机型号：荣耀V20 PCT-AL10
ROM版本：MagicUI2.0.1（Android 9.0.1.129）
Xposed模块：无
Xposed模块版本：无
APP及版本：youtube 14.05.56

问题描述：添加youtube过程中太极阴应用直接闪退回桌面，再打开就像无事发生过一样，添加失败

其他Magisk模块：无

补充：已经试过移除所有xposed模块和太极内应用，仍无法添加youtube，卸载从google play安装的youtube，改为直接添加pureapk下载的youtube apk文件，依然闪退

**Comment by NNNNNNAAAAAA** [comment]
https://www.xda-developers.com/youtube-vanced-apk/
这里有个不需要xposed就能实现下载去广告以及后台播放的版本

**Comment by tiann** [comment]
https://github.com/taichi-framework/TaiChi/releases/tag/5.0.5
