### ISSUE TITLE
开启核心破解之后 potato_bacon_2.0 无法开机

### ISSUE THREAD

**Issue by gowfqk** [taichi-framework/TaiChi#280]
太极Magisk模块版本：4.20
太极APP版本：4.30 
手机型号：oneplus A1000
ROM版本：potato_bacon_2.0（Android9.0）
Xposed模块：无
Xposed模块版本：无
APP及版本：无

问题描述：magisk中激活taichi后重启就无法开机，用mm管理器禁用模块后可以正常重启

其他Magisk模块：mm管理器

**Comment by 839008591** [comment]
我的一加5t开机卡解锁屏幕，进不去桌面

**Comment by tiann** [comment]
使用最新的magisk 模块 4.5 或者 4.6 试下。

**Comment by aixiaoke5** [comment]
一加6T没有遇见你说的情况
h2os beta4
magisk 18.1

**Comment by 839008591** [comment]
今天试了下，把太极中所有模块☑️去掉，删去添加的app，顺利开机了

**Comment by tiann** [comment]
@839008591 能否确认下具体是哪个模块的问题？

**Comment by 839008591** [comment]
查出来了，是核心破解1.2.0，这个模块失效，且导致开机卡锁屏

**Comment by tiann** [comment]
那我 close了，核心破解的确不支持所有的 ROM。
