### ISSUE TITLE
Magisk版太极重启后变为阴的问题

### ISSUE THREAD

**Issue by kisrea** [taichi-framework/TaiChi#288]
太极Magisk模块版本：4.5.0
太极APP版本：4.3.0
手机型号：小米4c
ROM版本：魔趣MK90.0
Xposed模块：
Xposed模块版本：
APP及版本：

问题描述：刷入模块后，第一次重启完全可用，第二次及以后重启都变成了阴。

其他Magisk模块：Greenify4Magisk、魔法省电模块

补充：

**Comment by tiann** [comment]
把其他模块关了试试。

**Comment by OXERIS** [comment]
我也遇到了这个问题，再重启一次就好了，我每重启一次，阴和阳都会变呢
我是一加3t andriod 8.0 氧os

**Comment by shingz96** [comment]
同样问题 一加3 NOS 还是需要软重启

**Comment by yiyang-cn** [comment]
确实如此，目前出现这个问题后，重启系统可恢复。多次复现该问题发现，每次重启系统都会在阴阳间切换

**Comment by tiann** [comment]
https://github.com/taichi-framework/TaiChi-Magisk/releases/tag/4.7.0 装下这个看看

**Comment by tiann** [comment]
此问题是否在  4.7 上修复了？

**Comment by shingz96** [comment]
> 此问题是否在 4.7 上修复了？

感谢大佬
实测已修复 多次重启后都没有问题

太极Magisk模块版本：4.7.0
太极APP版本：4.3.5
手机型号：一加3
ROM版本：氮OS (NOS) 9.0

**Comment by tiann** [comment]
好的，谢谢反馈
