### ISSUE TITLE
太极阳，微信点击表情按钮卡死

### ISSUE THREAD

**Issue by HaleShaw** [taichi-framework/TaiChi#315]
太极Magisk模块版本：4.5.0
太极APP版本：4.3.5
手机型号：荣耀10
ROM版本：8.1
Xposed模块：微X
Xposed模块版本：1.25
APP及版本：微信7.0.3

问题描述：
聊天窗口，点击表情按钮，微信卡死
其他Magisk模块：

补充：
发送网络表情，这个功能打开或者关闭，都试了。手机重启也试了，微信重新优化也试了。

**Comment by tiann** [comment]
这种细微功能处的bug 不是太极的问题
