### ISSUE TITLE
太极阴4.3.5已可以添加应用宝和应用宝hook模块，但是模块无效，不能打开免流通道

### ISSUE THREAD

**Issue by Hades-Shaw** [taichi-framework/TaiChi#317]
## 模块名字
应用宝hook
## 模块用途
打开应用宝免流通道
## 模块版本号
1.6
## 模块安装包
链接: https://pan.baidu.com/s/1drP2rz1KCG1U-oKKa8xZbA 提取码: yq7i 

应用宝版本7.3.3

**Comment by tiann** [comment]
当时测试的时候应用宝版本为 7.0.x  换这个版本尝试下

**Comment by Hades-Shaw** [comment]
找不到7.0.x呀，酷安上只有7.0.4，试了一下，不行，能不能分享一下7.0.x

**Comment by tiann** [comment]
7.0.x 的意思是是 7.0.几的版本，估计就是 7.0.4 吧，你自己试下。

**Comment by Hades-Shaw** [comment]
试过了，7.0.4，无效，首页下拉是刷新，没有出现免流通道
免流通道是7.3.1内测才出现的，但是后来又隐藏了，7.0这么早的版本也可以吗？
手机：华为nova2s，emui8.0，android8.0

**Comment by tiann** [comment]
有群友反馈可以用 但是 9.0.
