### ISSUE TITLE
太极阳4.3.2和之后的任意版本，在三星9.0系统上一启用xposed edge pro就会导致无法开机

### ISSUE THREAD

**Issue by weisyr** [taichi-framework/TaiChi#318]
太极Magisk模块版本：4.5
太极APP版本：4.3.2/4.3.5
手机型号：三星S9+国行
ROM版本：one ui 1.0（Pie）
Xposed模块：xposed edge pro
Xposed模块版本：5.2.3/5.3
APP及版本：5.2.3/5.3

问题描述：一启用xposed edge pro5.2.3/5.3版,重启后就会导致无法开机

其他Magisk模块：无（唯一edge测试）

补充：还在三星8.0的时候，最新公测的太极阳4.3.5启用edge5.3版无效，但重启能正常开机

**Comment by tiann** [comment]
试下这个版本：https://www.lanzous.com/i36xw2b
