### ISSUE TITLE
希望支持Google App 助手 1.8.0

### ISSUE THREAD

**Issue by Dark-Existed** [taichi-framework/TaiChi#319]
## 模块名字
Google App 助手
## 模块版本号
1.8.0
## 模块更新了什么？
新增新版本的Google Search的支持

**Comment by Dark-Existed** [comment]
是 1.8.0 不是1.9.0  不小心打错了

**Comment by tiann** [comment]
https://github.com/taichi-framework/Daily-Build/releases/tag/4.3.5.3
