### ISSUE TITLE
百度网盘闪退

### ISSUE THREAD

**Issue by Marukon** [taichi-framework/TaiChi#320]
太极Magisk模块版本：4.6.0
太极APP版本：5.3.5.3
手机型号：一加5t
ROM版本：9
Xposed模块：上帝模式，核心破解，Screenshot Delay Remover - Mod
Xposed模块版本：2.7.7，1.2.0，2
APP及版本：百度网盘9.5－9.6.1

问题描述：
闪退，优化无效，其他应用如高德地图，支付宝,qq等均正常
其他Magisk模块：
riru
补充：
无

**Comment by tiann** [comment]
关掉上帝模式试试呢？我开启边缘手势之后，把百度网盘加入也会闪退

**Comment by tiann** [comment]
试下这个版本：https://www.lanzous.com/i36xw2b

**Comment by zhangxuhu** [comment]
你好，安装上述版本后，百度网盘app不在闪退，但一直卡首屏。
经过取消勾选上帝模式和大圣净化VXP1.83（新安装的）之后可以正常打开，而勾选上帝模式或者大圣净化的任何一个百度网盘app都卡首屏

**Comment by Marukon** [comment]
大佬你好 是否需要提供log或者其他信息？

**Comment by tiann** [comment]
https://taichi.ctfile.com/fs/19604958-365278317

**Comment by Marukon** [comment]
谢谢作者
