### ISSUE TITLE
请求支持WIFI模拟器模块

### ISSUE THREAD

**Issue by Cyclonekid** [taichi-framework/TaiChi#322]
## 模块名字
WIFI模拟器 

## 模块用途
对应用进行WIFI模拟
即使手机使用的数据流量
你可以设置成任意WIFI
上班族应该很需要
使用前请先安装Xposed框架或者VirtualXposed

## 模块版本号
1.0

## 模块安装包

https://www.coolapk.com/apk/com.knoyo.wifisimulator

**Comment by tiann** [comment]
https://github.com/taichi-framework/Daily-Build/releases/tag/4.3.5.3
