### ISSUE TITLE
请求支持 Gboard助手

### ISSUE THREAD

**Issue by MoonBegonia** [taichi-framework/TaiChi#324]
## 模块名字

Gboard助手

## 模块用途

Gboard功能增强：始终显示剪切板入口，Android 9.0 下开启导航栏变色

## 模块版本号

2.2.0

## 模块安装包

https://www.coolapk.com/apk/com.elderdrivers.gboard

**Comment by tiann** [comment]
试下这个是否正常 https://github.com/taichi-framework/Daily-Build/releases/tag/4.3.5.3

**Comment by MoonBegonia** [comment]
谢谢 weishu ，可以正常使用。
