### ISSUE TITLE
请求适配模块 AideHelper

### ISSUE THREAD

**Issue by Revincx** [taichi-framework/TaiChi#326]
请求适配模块 AideHelper    谢谢！

## 模块名字
AideHelper
## 模块用途
一款专门为AIDE量身打造的Xposed插件，提供个性化选择 功能: 1.版本切换 2.禁用自动旋转 3.符号栏调整 4.搜索结果界面调整 5.去除AIDE的icon 6.中文补全 7.Gradle补全拓展(new) 8.解锁专业版(new) 
## 模块版本号
1.0
## 模块安装包
https://www.coolapk.com/apk/me.tvcfish.xposed.aidehelper

**Comment by tiann** [comment]
https://github.com/taichi-framework/Daily-Build/releases/tag/4.3.5.3
