### ISSUE TITLE
刷好太极.magisk模块，第二次重启手机，卡锁屏

### ISSUE THREAD

**Issue by 839008591** [taichi-framework/TaiChi#328]
太极Magisk模块版本：4.5.0
太极APP版本：4.3.5
手机型号：oneplus 5t
ROM版本：魔趣9（Android9.0）
Xposed模块：无
Xposed模块版本：无
APP及版本：无

问题描述：刷好太极.magisk模块，第二次重启手机，卡锁屏，用终端命令删除太极模块后正常开机，可以再次刷入太极模块，然后第二次重启，再次卡锁屏

**Comment by tiann** [comment]
#280 
都是 oneplus 9.0 的问题
