### ISSUE TITLE
太极Magisk阻止了所有crash

### ISSUE THREAD

**Issue by vvb2060** [taichi-framework/TaiChi#33]
在 JNI_OnLoad 里直接返回 jni_err 后，产生 ANR。
https://github.com/brevent/genuine/commit/2c74d73032923f639d8ef8be61c3a89d447f5402

**Comment by tiann** [comment]
没有太好的办法区分异常到底是可恢复的还是不可恢复的，以后我加个开关吧。

**Comment by liudongmiao** [comment]
等你这个普及了，再尝试 anti epic。

思路大致如下：

1. 根据 epic 或者其它的 so 库，找到 classloader（Xposed 是直接 system classloader）
jvm 特性，同一个 so 不能加载多次；同时底层能知道 so 库所在 classloader。
但是，明显都是私有字段，隐藏方法，相对麻烦。

2. 在 classloader 里找 DexposedBridge ...然后再适当取消。
总不能直接遍历，查找所有的二进制代码，换成不带 hook 的吧..
（Xposed 是直接一个方法处理，所以很容易直接替换）

其实，可以给用户 app 一个选择，是否允许被 hook...
反正，都在同一个进程里，肯定是有办法知道的。
这时，就是猫鼠游戏了。
一旦知道，不能反 hook，还不能直接退出么...

但是：
> Q：为什么会出现阻止闪退？
> A：这是太极自带的特性，忽略即可。理论上，如果模块自己没有做好，会导致APP闪退；太极给了APP一个不闪退的机会。并不代表太极本身出现了问题。

而实际已经崩溃，又不会继续往下运行，在系统层面就表现为 anr 了。

**Comment by tiann** [comment]
> 而实际已经崩溃，又不会继续往下运行，在系统层面就表现为 anr 了。

如果确实有逻辑错误，这时候阻止闪退是不合理的。

但是对于Xposed来说，很多插件自己没有处理好异常，在APP版本不匹配，出现 NoSuchMethodError, ClassNotFoundException, NullPointException 等异常的情况非常多；这时候阻止闪退能让APP无痛继续运行。

另外，子线程组织闪退绝大部分情况也没什么问题，除非这个子线程与主线程有交互。

**Comment by liudongmiao** [comment]
fix in https://github.com/brevent/genuine/commit/1d01d46eaafd7aec1b9af97902b03846110546c0#diff-6baf147e44ed2b9c64cdb953d8d5014cR1561

**Comment by tiann** [comment]
现在没有一个好的方法区分到底是 hook 出问题产生的异常还是 APP 自己的问题。有一些逻辑是依赖异常来运行的，比如：

```java
try {
    // branch1
} catch (CustomException e) {
    // branch2
}
```

如果 hook branch1 这个分支中的任何函数以及这些函数调用的任何函数，假设这里面的函数出现了 CustomException 或者它的子类，只能原模原样地 throw 出去，不能包装，也不能吃掉继续运行。实际上这种场景是无处不在的，无法区分。

如果需要用异常机制来退出，直接 exit 就行了。

**Comment by liudongmiao** [comment]
问题是 exit，系统就会再来打开一遍，不断循环。

现在退出的时候，直接重置了 exception handler。

当然，由于 epic 并不开源，所以我也没公布 anti epic 的代码，公开代码直接发现加载了 dex，就崩溃.
