### ISSUE TITLE
请求更新blued模块

### ISSUE THREAD

**Issue by MillionZBW** [taichi-framework/TaiChi#330]
## 模块名字
blued模块
## 模块版本号
最新版本1.1.2
## 模块更新了什么？
适配blued_6.7.5版本

**Comment by MillionZBW** [comment]
忘了提供下载链接了https://pan.baidu.com/s/1nvZLaml#list/path=%2FBluedHook&page=1

**Comment by tiann** [comment]
你要是装了最新版的太极，你会发现已经支持了。。
