### ISSUE TITLE
请求允许在太极阴上添加漫画人

### ISSUE THREAD

**Issue by miyouzi** [taichi-framework/TaiChi#331]
## 模块名字

**漫画人**，包名：**com.ilike.cartoon**

## 模块用途

目前太极阴已支持```APP Locale 2```，漫画人的限制漫画还会检查语言，希望能使```APP Locale 2```作用于漫画人。在 VXP 中已确认可以正常运作。

## 模块版本号

3.2.2(182)

## 模块安装包

http://www.manhuaren.com/

**Comment by tiann** [comment]
https://github.com/taichi-framework/Daily-Build/releases/tag/4.3.5.9
