### ISSUE TITLE
开启VPN 就会卡死到锁屏界面

### ISSUE THREAD

**Issue by yFFyF** [taichi-framework/TaiChi#332]
太极Magisk模块版本：4.7
太极APP版本：4.3.5
手机型号：一加3T
ROM版本：phh gsi 9.0
之前版本也一直有这个问题

**Comment by HaoyeTang** [comment]
试过多种vpn吗？还是你现在用的vpn特有的问题

**Comment by yFFyF** [comment]
> 试过多种vpn吗？还是你现在用的vpn特有的问题

是v2rayng shadowsocks BifrostV这些APP 打开就会出问题

**Comment by tiann** [comment]
开启了什么 Xposed 模块？

**Comment by bafflingbug** [comment]
太极Magisk模块版本：4.5
太极APP版本：4.3.5
手机型号：一加5
ROM版本：H2OS 9.0.0 (Android9)

在使用SSRR(https://github.com/shadowsocksrr/shadowsocksr-android/releases)和v2rayNG情况下**_没有_**出现该问题。

Magisk模块：mm管理器，太极，冰箱，busybox
xp模块：应用变量，微信群消息助手，blued，大圣净化，justtrustme，云村清洁工，去你大爷的内置浏览器

**Comment by yFFyF** [comment]
> 开启了什么 Xposed 模块？

什么xposed模块也没开 其他magisk模块也关了。需要什么日志吗 我也不会呃😳😳

**Comment by tiann** [comment]
在 rec 中执行 rm -rf /data/system/taichi 再看看。

**Comment by yFFyF** [comment]
> 在 rec 中执行 rm -rf /data/system/taichi 再看看。

一个一个xposed模块试了下  对话框取消 核心破解 都会导致这个问题

**Comment by tanghengvip** [comment]
> 太极Magisk模块版本：4.5
> 太极APP版本：4.3.5
> 手机型号：一加5
> ROM版本：H2OS 9.0.0 (Android9)
> 
> 在使用[SSRR](https://github.com/shadowsocksrr/shadowsocksr-android/releases)和v2rayNG情况下**没有**出现该问题。
> 
> Magisk模块：mm管理器，太极，冰箱，busybox
> xp模块：应用变量，微信群消息助手，blued，大圣净化，justtrustme，云村清洁工，去你大爷的内置浏览器

老铁，你的justtrustme模块工作正常吗？

**Comment by bafflingbug** [comment]
> > 太极Magisk模块版本：4.5
> > 太极APP版本：4.3.5
> > 手机型号：一加5
> > ROM版本：H2OS 9.0.0 (Android9)
> > 在使用[SSRR](https://github.com/shadowsocksrr/shadowsocksr-android/releases)和v2rayNG情况下**没有**出现该问题。
> > Magisk模块：mm管理器，太极，冰箱，busybox
> > xp模块：应用变量，微信群消息助手，blued，大圣净化，justtrustme，云村清洁工，去你大爷的内置浏览器
> 
> 老铁，你的justtrustme模块工作正常吗？

暂时没用到，没测试过

**Comment by tanghengvip** [comment]
> > > 太极Magisk模块版本：4.5
> > > 太极APP版本：4.3.5
> > > 手机型号：一加5
> > > ROM版本：H2OS 9.0.0 (Android9)
> > > 在使用[SSRR](https://github.com/shadowsocksrr/shadowsocksr-android/releases)和v2rayNG情况下**没有**出现该问题。
> > > Magisk模块：mm管理器，太极，冰箱，busybox
> > > xp模块：应用变量，微信群消息助手，blued，大圣净化，justtrustme，云村清洁工，去你大爷的内置浏览器
> > 
> > 
> > 老铁，你的justtrustme模块工作正常吗？
> 
> 暂时没用到，没测试过

用电脑抓包软件(Fiddler或Charles)抓"七猫免费小说"App接口数据，抓不到就代表模块无效。
有空的话可以帮忙测一下吗~麻烦啦！

**Comment by bafflingbug** [comment]
> > > > 太极Magisk模块版本：4.5
> > > > 太极APP版本：4.3.5
> > > > 手机型号：一加5
> > > > ROM版本：H2OS 9.0.0 (Android9)
> > > > 在使用[SSRR](https://github.com/shadowsocksrr/shadowsocksr-android/releases)和v2rayNG情况下**没有**出现该问题。
> > > > Magisk模块：mm管理器，太极，冰箱，busybox
> > > > xp模块：应用变量，微信群消息助手，blued，大圣净化，justtrustme，云村清洁工，去你大爷的内置浏览器
> > > 
> > > 
> > > 老铁，你的justtrustme模块工作正常吗？
> > 
> > 
> > 暂时没用到，没测试过
> 
> 用电脑抓包软件(Fiddler或Charles)抓"七猫免费小说"App接口数据，抓不到就代表模块无效。
> 有空的话可以帮忙测一下吗~麻烦啦！

我认为这种和主题无关的是否应该使用另外的issue，还有酷安没有找到这个app

**Comment by TTTPOB** [comment]
> 一个一个xposed模块试了下 对话框取消 核心破解 都会导致这个问题
我这里有同样的情况，没有测试对话框取消但是核心破解确实会导致这个问题。

**Comment by yFFyF** [comment]
> > 一个一个xposed模块试了下 对话框取消 核心破解 都会导致这个问题
> > 我这里有同样的情况，没有测试对话框取消但是核心破解确实会导致这个问题。

估计system-wide modules都有问题。可是现在 东皇钟 一个模块都不生效了🌚🤪

**Comment by yFFyF** [comment]
> > > > 一个一个xposed模块试了下 对话框取消 核心破解 都会导致这个问题
> > > > 我这里有同样的情况，没有测试对话框取消但是核心破解确实会导致这个问题。
> > 
> > 
> > 估计system-wide modules都有问题。可是现在 东皇钟 一个模块都不生效了🤪
> 
> 你可以试试卸掉太极，删掉magisk模块，删除/data/system/taichi然后重新开始做一遍安装，反正我好了

你也是升级东皇钟以后模块都不生效？然后重装就好了？

**Comment by TTTPOB** [comment]
你是501还是502，据我所知501确实有不生效的bug。
我不生效是玄学，做了一遍就好了。
________________________________
