### ISSUE TITLE
小米 Android 8.0 点击切换输入法相关按钮直接重启

### ISSUE THREAD

**Issue by NNNNNNAAAAAA** [taichi-framework/TaiChi#333]
太极Magisk模块版本：4.7.0
太极APP版本：4.3.5.5（4.3.5.7也试过了）
手机型号：小米6
ROM版本：开发版9.2.14（安卓8.0）
Xposed模块：
Xposed模块版本：
APP及版本：

问题描述：
只要点击切换输入法相关按钮就会直接黑屏重启，包括但不仅限以下界面，和输入法无关
![screenshot_2019-02-21-03-23-46-700_com tencent mo](https://user-images.githubusercontent.com/7733207/53118643-897ce980-3588-11e9-807c-d06f22af9bc2.png)
<img width="458" alt="snipaste_2019-02-21_03-36-12" src="https://user-images.githubusercontent.com/7733207/53119199-dca36c00-3589-11e9-8386-aeb5c3a0e113.png">

其他Magisk模块：已全部卸载排查，也换过magisk版本，确认是太极的问题

补充：

**Comment by tiann** [comment]
没有开启任何  Xposed 模块？

**Comment by NNNNNNAAAAAA** [comment]
昨天试了关闭所有xposed模块也有这个问题，但是我刚刚又试了一次全部禁用然后再打开，就不重启了，奇怪

**Comment by tiann** [comment]
可能是某个插件的问题，你逐一排查下。

在 太极magisk模块禁用之后，关闭模块是无效的。

**Comment by tiann** [comment]
猜测 Edge 的可能性比较大

**Comment by NNNNNNAAAAAA** [comment]
我并没有安装edge模块，能影响系统的估计也就是核心破解以及disableflagsecure了，但是现在这两个都开着，也不会重启了

**Comment by NNNNNNAAAAAA** [comment]
今天又出现这个问题了，我禁用了disableflagsecure暂时好像没事了

**Comment by tiann** [comment]
现在还会出现这个情况吗？

**Comment by NNNNNNAAAAAA** [comment]
现在没这个问题了，但是disableflagsecure貌似失效了，刚刚试了下开启也没法截图支付二维码了
