### ISSUE TITLE
请求更新WechatLuckyMoney

### ISSUE THREAD

**Issue by zhangxuhu** [taichi-framework/TaiChi#334]
## 模块名字
WechatLuckyMoney
## 模块版本号
1.4.3
## 模块更新了什么？
适配微信7.0.3

下载：https://repo.xposed.info/module/me.veryyoung.wechat.luckymoney

**Comment by tiann** [comment]
https://github.com/taichi-framework/Daily-Build/releases/tag/4.3.6
