### ISSUE TITLE
功能申请 隐藏部分插件

### ISSUE THREAD

**Issue by lukemin** [taichi-framework/TaiChi#335]
太极Magisk模块版本：4.7
太极APP版本：4.3.5.3
手机型号：小米note3
ROM版本：MIUI10 9.2.15国内开发版
能不能在app插件管理界面加一个隐藏插件功能 因为现在和ed能共存 有些插件太极不支持全局，在ed用方便一点。

**Comment by tiann** [comment]
没什么用，太极以后也不需要这功能；浪费精力。
