### ISSUE TITLE
请求增加网易云音乐插件支持

### ISSUE THREAD

**Issue by Guoganghhu** [taichi-framework/TaiChi#336]
网易云音乐插件

网易云音乐的 Xposed 插件。来自作者 Specher，目前功能有自动签到、跳过启动广告、本地数据修改、美化功能。

2.8.2

com.specher.music163_v21_fab79b.apk (28.5 KB)

**Comment by tiann** [comment]
模块文件没有上传成功

**Comment by Guoganghhu** [comment]
模块: [com.specher.music163_v21_fab79b.zip](https://github.com/taichi-framework/TaiChi/files/2888027/com.specher.music163_v21_fab79b.zip)

MD5 :  fab79b2c910db212d1824282094bc9f3

**Comment by tiann** [comment]
https://github.com/taichi-framework/Daily-Build/releases/tag/4.3.6
