### ISSUE TITLE
请求普通版添加新模块运动修改器

### ISSUE THREAD

**Issue by zgc** [taichi-framework/TaiChi#337]
## 模块名字
运动修改器
## 模块用途
支持以一定的倍率修改微信运动、QQ健康、悦动圈、乐动力、三星健康、支付宝、华为健康等的运动步数，支持自定义倍率，自定义开关，同时不影响其他微信QQ其他功能的正常使用比如微信摇一摇。
## 模块版本号
2.1.3
## 模块安装包
http://caiyao.name/releases/sporteditor_2.1.3.apk

**Comment by tiann** [comment]
https://github.com/taichi-framework/Daily-Build/releases/tag/4.3.6
