### ISSUE TITLE
坚果 Pro2s开机卡logo

### ISSUE THREAD

**Issue by Melonlollipop** [taichi-framework/TaiChi#34]
手机型号：坚果 Pro2s
ROM版本：Android OS 8.1（Smartisan OS 6.6.5.5.4）
Xposed模块：无Xposed
APP：太极·Magisk v3.2-b

问题描述：开机卡在logo

其他 Magisk 模块：第三方字体，MM管理器

**Comment by xiang473535976** [comment]
同样   pro2s  卡开机     无任何模块   只刷入太极    ab  都试了  3.3  3.6  都卡

**Comment by tiann** [comment]
最新版模块 4.5.0 是否依然存在这个问题？

**Comment by tanghengvip** [comment]
坚果Pro2s能刷Magisk？**怎么刷的？**

**Comment by Blankeer** [comment]
手持 Pro2s 瑟瑟发抖，楼上两位大兄弟正常了吗？

**Comment by Blankeer** [comment]
> > 手持 Pro2s 瑟瑟发抖，楼上两位大兄弟正常了吗？
> 
> 这个问题一解决我立马解锁 Pro2s 刷太极 ^_^

老铁，你在哪个太极群里，加个好友交流下，我在一元群，pro2s解锁需要9008工程线。

**Comment by tanghengvip** [comment]
> > > 手持 Pro2s 瑟瑟发抖，楼上两位大兄弟正常了吗？
> > 
> > 
> > 这个问题一解决我立马解锁 Pro2s 刷太极 ^_^
> 
> 老铁，你在哪个太极群里，加个好友交流下，我在一元群，pro2s解锁需要9008工程线。

QQ群搜索"坚果Pro2s玩机交流"，资料应有尽有。但是目前人满了。
可以解锁/root/刷面具。
9008工程线你得自己搞定。

**Comment by zhuiyi220** [comment]
千万别刷  等等再说 卡logo卡的过分

**Comment by Blankeer** [comment]
> 千万别刷 等等再说 卡 logo 卡的过分

按照上面作者说的方案尝试了吗？工程线还在路上，准备尝试下

**Comment by zhuiyi220** [comment]
> > 千万别刷 等等再说 卡 logo 卡的过分
> 
> 按照上面作者说的方案尝试了吗？工程线还在路上，准备尝试下
屡试不爽 哈哈哈  一直卡  搞了一天

**Comment by zhuiyi220** [comment]
710处理器的问题。。。

**Comment by Blankeer** [comment]
> 710 处理器的问题。。。

怎么得出这个结论的。。。

**Comment by zhuiyi220** [comment]
> > 710 处理器的问题。。。
> 
> 怎么得出这个结论的。。。

酷安有大神

**Comment by zhuiyi220** [comment]
> 最新版模块 4.7.0 是否依然存在这个问题？

大佬 多久能修复这个bug

**Comment by Blankeer** [comment]
正在刷入 twrp 走上不归路。。。

**Comment by zhuiyi220** [comment]
> 正在刷入 twrp 走上不归路。。。

刷成功了 丢个爪哈

**Comment by Blankeer** [comment]
> > 正在刷入 twrp 走上不归路。。。
> 
> 刷成功了 丢个爪哈

magisk 刷入成功，刷入taichi 不出意外卡logo了，我按照 [自救办法](https://github.com/taichi-framework/TaiChi/wiki/%E5%87%86%E5%A4%87%E4%BA%8B%E9%A1%B9)，并没有 /data/taichi  和 /data/system/taichi 这两目录，还在摸索怎么正常开机中

**Comment by zhuiyi220** [comment]
> > > 正在刷入 twrp 走上不归路。。。
> > 
> > 
> > 刷成功了 丢个爪哈
> 
> magisk 刷入成功，刷入taichi 不出意外卡logo了，我按照 [自救办法](https://github.com/taichi-framework/TaiChi/wiki/%E5%87%86%E5%A4%87%E4%BA%8B%E9%A1%B9)，并没有 /data/taichi 和 /data/system/taichi 这两目录，还在摸索怎么正常

> > > 正在刷入 twrp 走上不归路。。。
> > 
> > 
> > 刷成功了 丢个爪哈
> 
> magisk 刷入成功，刷入taichi 不出意外卡logo了，我按照 [自救办法](https://github.com/taichi-framework/TaiChi/wiki/%E5%87%86%E5%A4%87%E4%BA%8B%E9%A1%B9)，并没有 /data/taichi 和 /data/system/taichi 这两目录，还在摸索怎么正常开机中

清除data重新刷一次就可以了  taichi暂时先别刷了。。。。。

**Comment by Blankeer** [comment]
> > > > 正在刷入 twrp 走上不归路。。。
> > > 
> > > 
> > > 刷成功了 丢个爪哈
> > 
> > 
> > magisk 刷入成功，刷入 taichi 不出意外卡 logo 了，我按照 [自救办法](https://github.com/taichi-framework/TaiChi/wiki/%E5%87%86%E5%A4%87%E4%BA%8B%E9%A1%B9)，并没有 /data/taichi 和 /data/system/taichi 这两目录，还在摸索怎么正常
> 
> > > > 正在刷入 twrp 走上不归路。。。
> > > 
> > > 
> > > 刷成功了 丢个爪哈
> > 
> > 
> > magisk 刷入成功，刷入 taichi 不出意外卡 logo 了，我按照 [自救办法](https://github.com/taichi-framework/TaiChi/wiki/%E5%87%86%E5%A4%87%E4%BA%8B%E9%A1%B9)，并没有 /data/taichi 和 /data/system/taichi 这两目录，还在摸索怎么正常开机中
> 
> 清除 data 重新刷一次就可以了 taichi 暂时先别刷了。。。。。

不用这么麻烦，之前没装mm管理器，直接刷一个 magisk-uninstall.zip，然后进入/data/adb/modules 删除taichi，正常开机后，再重新刷 magisk，再装mm

**Comment by tanghengvip** [comment]
> > > > > 正在刷入 twrp 走上不归路。。。
> > > > 
> > > > 
> > > > 刷成功了 丢个爪哈
> > > 
> > > 
> > > magisk 刷入成功，刷入 taichi 不出意外卡 logo 了，我按照 [自救办法](https://github.com/taichi-framework/TaiChi/wiki/%E5%87%86%E5%A4%87%E4%BA%8B%E9%A1%B9)，并没有 /data/taichi 和 /data/system/taichi 这两目录，还在摸索怎么正常
> > 
> > 
> > > > > 正在刷入 twrp 走上不归路。。。
> > > > 
> > > > 
> > > > 刷成功了 丢个爪哈
> > > 
> > > 
> > > magisk 刷入成功，刷入 taichi 不出意外卡 logo 了，我按照 [自救办法](https://github.com/taichi-framework/TaiChi/wiki/%E5%87%86%E5%A4%87%E4%BA%8B%E9%A1%B9)，并没有 /data/taichi 和 /data/system/taichi 这两目录，还在摸索怎么正常开机中
> > 
> > 
> > 清除 data 重新刷一次就可以了 taichi 暂时先别刷了。。。。。
> 
> 不用这么麻烦，之前没装mm管理器，直接刷一个 magisk-uninstall.zip，然后进入/data/adb/modules 删除taichi，正常开机后，再重新刷 magisk，再装mm

这波操作很⑥！
不知道@tiann 有没有在看这个问题？求修复哇...

**Comment by zhuiyi220** [comment]
> > > > > > 正在刷入 twrp 走上不归路。。。
> > > > > 
> > > > > 
> > > > > 刷成功了 丢个爪哈
> > > > 
> > > > 
> > > > magisk 刷入成功，刷入 taichi 不出意外卡 logo 了，我按照 [自救办法](https://github.com/taichi-framework/TaiChi/wiki/%E5%87%86%E5%A4%87%E4%BA%8B%E9%A1%B9)，并没有 /data/taichi 和 /data/system/taichi 这两目录，还在摸索怎么正常
> > > 
> > > 
> > > > > > 正在刷入 twrp 走上不归路。。。
> > > > > 
> > > > > 
> > > > > 刷成功了 丢个爪哈
> > > > 
> > > > 
> > > > magisk 刷入成功，刷入 taichi 不出意外卡 logo 了，我按照 [自救办法](https://github.com/taichi-framework/TaiChi/wiki/%E5%87%86%E5%A4%87%E4%BA%8B%E9%A1%B9)，并没有 /data/taichi 和 /data/system/taichi 这两目录，还在摸索怎么正常开机中
> > > 
> > > 
> > > 清除 data 重新刷一次就可以了 taichi 暂时先别刷了。。。。。
> > 
> > 
> > 不用这么麻烦，之前没装mm管理器，直接刷一个 magisk-uninstall.zip，然后进入/data/adb/modules 删除taichi，正常开机后，再重新刷 magisk，再装mm
> 
> 这波操作很⑥！
> 不知道@tiann 有没有在看这个问题？求修复哇...

估计用这个手机的比较少。。。所以。。。。。。。。。。。。。

**Comment by Blankeer** [comment]
我在协助 weishu 解决。。。

**Comment by zhuiyi220** [comment]
> 我在协助 weishu 解决。。。

厉害了  好了丢个爪哦

**Comment by tiann** [comment]
[magisk-taichi-v4.7.4.zip](https://github.com/taichi-framework/TaiChi/files/2918028/magisk-taichi-v4.7.4.zip)

应该已经解决了，谢谢 @Blankeer 的配合，太棒了！

**Comment by zhuiyi220** [comment]
> [magisk-taichi-v4.7.4.zip](https://github.com/taichi-framework/TaiChi/files/2918028/magisk-taichi-v4.7.4.zip)
> 
> 应该已经解决了，谢谢 @Blankeer 的配合，太棒了！

帅气 我试试 等会来回复

**Comment by zhuiyi220** [comment]
> [magisk-taichi-v4.7.4.zip](https://github.com/taichi-framework/TaiChi/files/2918028/magisk-taichi-v4.7.4.zip)
> 
> 应该已经解决了，谢谢 @Blankeer 的配合，太棒了！

刷完了 没卡logo了 但是 阳 没出来 还是阴。。。

**Comment by Blankeer** [comment]
> > [magisk-taichi-v4.7.4.zip](https://github.com/taichi-framework/TaiChi/files/2918028/magisk-taichi-v4.7.4.zip)
> > 应该已经解决了，谢谢 @Blankeer 的配合，太棒了！
> 
> 刷完了 没卡 logo 了 但是 阳 没出来 还是阴。。。

我开机都是阳了，刚刚模块有点问题没生效，需要卸载原先阴优化过的app，安装原版app，然后重新添加。。。
我这现在一切正常了。
不说了，玩耍去了。

**Comment by MelanPrince** [comment]
最新版本  4.7 magisk 安装完  taichi 重启 卡logo。  magisk 18.2 特殊版本。

**Comment by MelanPrince** [comment]
坚果Pro 2S v6.6.5.5.4_TNT   
magisk-taichi-v4.7.4.zip  未卡logo
