### ISSUE TITLE
请求支持MusicNotification插件

### ISSUE THREAD

**Issue by hzx19980513** [taichi-framework/TaiChi#341]
一个将默认音乐通知变成安卓 O样式的 xposed模块，适用于一些音乐通知被魔改的系统，比如说 Miui。
版本1.0 
github项目地址 https://github.com/Qiwu2542284182/MusicNotification
模块地址 https://pan.baidu.com/s/1AtB9hjvMYR5otp0HiYXkGw

**Comment by tiann** [comment]
https://github.com/taichi-framework/Daily-Build/releases/tag/4.3.6

**Comment by hzx19980513** [comment]
这个模块更新了 希望weishu支持一下  https://www.coolapk.com/apk/me.qiwu.MusicNotification
