### ISSUE TITLE
请求添加微信巫师插件

### ISSUE THREAD

**Issue by akkuman** [taichi-framework/TaiChi#343]
### 聊天相关

- 防止微信好友撤回聊天消息（撤回提示可自定义）。
- 转发消息时可选择任意数量好友。
- 发送消息时可发送9张以上的图片（上限可调整，默认1000张）。
- 隐藏不常用的群聊至群聊助手。（需在设置界面手动开启）
- 设定好友为密友，隐藏聊天痕迹。（需在设置界面手动开启）
- 一键标记所有聊天对话为已读。

### 朋友圈相关

- 防止微信好友删除朋友圈动态、评论。
- 屏蔽微信在朋友圈投放的广告。
- 一键转发他人朋友圈。
- 单条朋友圈一键截图。
- 按关键字屏蔽朋友圈，免除广告与秀恩爱的烦恼。（需在设置界面手动开启）

### 其他杂项

- 自动确认电脑端登录请求（开启该功能即视为用户同意自行承担可能的安全风险）。

模块地址：[https://github.com/Gh0u1L5/WechatMagician](https://github.com/Gh0u1L5/WechatMagician)

**Comment by tiann** [comment]
这插件停更了，bug很多没必要支持。
