### ISSUE TITLE
模块要你命三千更新

### ISSUE THREAD

**Issue by lukemin** [taichi-framework/TaiChi#344]
最新版5.212  https://repo.xposed.info/module/cn.kwaiching.hook

**Comment by ConjuringLee** [comment]
此模块会导致抖音无法正常打开，存在严重bug

**Comment by tiann** [comment]
测试了，貌似不会

**Comment by tiann** [comment]
https://github.com/taichi-framework/Daily-Build/releases/tag/4.3.6

**Comment by ConjuringLee** [comment]
好的感谢

**Comment by GaHoKwan** [comment]
最新版还是显示不支持
