### ISSUE TITLE
請求新增 BubbleUPnP 

### ISSUE THREAD

**Issue by rexx0520** [taichi-framework/TaiChi#346]
## 模块名字
BubbleUPnP
## 模块用途
將大多數音樂軟體播放中的音樂投放至 DLNA/UPnP 接收器上
## 模块版本号
3.2.1
## 模块安装包
https://play.google.com/store/apps/details?id=com.bubblesoft.android.bubbleupnp

**Comment by tiann** [comment]
测试下能否正常使用：https://github.com/taichi-framework/Daily-Build/releases

**Comment by rexx0520** [comment]
似乎並不能使用...
