### ISSUE TITLE
能否注入时顺便改个包名…希望原版和改版共存…

### ISSUE THREAD

**Issue by Herenxiaode** [taichi-framework/TaiChi#347]
能否注入时顺便改个包名…
希望原版和改版共存…
有的东西还是希望在原版上运行…
在安全性上即便相信太极…
但插件繁多还是会有些担心…

**Comment by Herenxiaode** [comment]
话说这个Issues有没有搜索的?
稍微翻了几页没看到类似的话题…
github用的少…不太了解怎么用…

**Comment by tiann** [comment]
改包名的话分分钟给你检测出来，没什么意义。

**Comment by Herenxiaode** [comment]
目的是共存.

**Comment by Herenxiaode** [comment]
好吧,放弃,还是用vx比较适合…
