### ISSUE TITLE
坚果pro开机卡logo

### ISSUE THREAD

**Issue by wojiu** [taichi-framework/TaiChi#348]
太极Magisk模块版本：4.7.0
太极APP版本：4.3.5
手机型号：OD103
ROM版本：锤子官方rom6.1.3(Android 7.1.1)
Xposed模块：
Xposed模块版本：
APP及版本：

问题描述：刷入taichi模块后，重启手机卡在第一屏

其他Magisk模块：无

补充：刷入edxposed，xposed framework后都卡在第一屏，其它与xposed无关的模块能正常刷入使用

**Comment by tiann** [comment]
#34
