### ISSUE TITLE
ChiMi 黑屏问题

### ISSUE THREAD

**Issue by soulmates** [taichi-framework/TaiChi#349]
红米note5(pro)，MIUI10，Android8.1.0，太极Magisk版。

因为Chimi模块，勾选了系统界面，会导致偶尔出现黑屏无法进行任何操作，仅电源键可能调出重启菜单以及微弱点亮屏幕。并且开机后必然出现此问题。如果不添加系统界面到太极则不会。

(此前刚支持chimi的时候没事)

**Comment by tiann** [comment]
那你用老版本的吃米先试试
