### ISSUE TITLE
Ad快消模块无效，和minminguard模块的情况一模一样

### ISSUE THREAD

**Issue by akang1937** [taichi-framework/TaiChi#350]
太极Magisk模块版本：4.7.0
太极APP版本：稳定版4.3.8
手机型号：redmi7
ROM版本：miui10.2.8.0稳定版（安卓9.0）
Xposed模块：Ad快消
Xposed模块版本：1.4.4
APP及版本：所有APP都无效，比如：爱奇艺、bilibili、驾考宝典、酷狗音乐等

问题描述：所有APP启动页广告都无法消除（我记得这个模块就是消除启动页广告的，以前一直都再用的）

其他Magisk模块：MM管理器

补充：

**Comment by tiann** [comment]
有效，把app加入太极。
