### ISSUE TITLE
劳驾作者添加支持隐藏root的模块Zuper

### ISSUE THREAD

**Issue by swh922** [taichi-framework/TaiChi#352]

**Comment by tiann** [comment]
这个模块可能是可以支持的，但是我还是想问下，magisk hide 不好用吗？

**Comment by swh922** [comment]
@tiann 羞死我了，我怎么把这个给忘了，不好意思了

**Comment by bmanex** [comment]
能的話還是想拜託作者支持一下，有些APP會偵測GPS HOOK可以用ZUPER給屏蔽偵測

**Comment by tiann** [comment]
@bmanex 更新到 33 看看能否正常使用。

**Comment by bmanex** [comment]
> @bmanex 更新到 33 看看能否正常使用。

感謝，真的可以用
