### ISSUE TITLE
请求支持 微信助手 模块

### ISSUE THREAD

**Issue by a666888a** [taichi-framework/TaiChi#356]
## 模块名字
微信助手
## 模块用途
Xposed 微信辅助模块，实现消息防撤回、模拟位置、运动步数修改、猜拳骰子游戏作弊、零钱余额修改、微信运动一键点赞。

优势 能够动态适配 无视微信更新 依旧适配
## 模块版本号
1.13
## 模块安装包
https://github.com/wuxiaosu/XposedWechatHelper

**Comment by tiann** [comment]
https://github.com/taichi-framework/Daily-Build/releases/tag/4.3.9.2
