### ISSUE TITLE
太极模块B和Substratum主题冲突

### ISSUE THREAD

**Issue by zodk** [taichi-framework/TaiChi#36]
手机型号：万普拉斯涡轮增压版 一加3T
ROM版本：9.0
Xposed模块： QX 微X模块 音量增强器 云村清洁工
APP：Substratum Magisk太极

问题描述：日期 1.22在没刷太极模块前，sub主题一切正常
刷了模块B重启后sub任何叠加层失效。
  1.23之前相机莫名FC 禁用卸载模块B重刷 重启后太极未能激活Magisk版并且只要模块B在面具一直是启用状态的话sub都用不了
所以现在是两个都用不了
其他 Magisk 模块：Busybox AML 杜比蝰蛇 MM管理器 Substratum模块（这个模块装了sub主题管理就自动安上的）

补充：目前已知，就是和Substratum模块冲突

**Comment by zodk** [comment]
目前我软重启N次了 magisk版太极仍是无法激活（已经刷了模块B了）

**Comment by zodk** [comment]
昨晚到中午发现还可以使用就是sub主题用不了
下午没多久，我支付宝想扫个红包发现相机FC了
然后就尝试禁用模块b试试看，没想到一禁用到现在死活用不了

**Comment by tiann** [comment]
应该已经修复了
