### ISSUE TITLE
请求支持 钉钉辅助模块

### ISSUE THREAD

**Issue by BaoJingchuan** [taichi-framework/TaiChi#360]
## 模块名字
钉钉助手
## 模块用途
钉钉辅助模块，实现模拟位置，在taichi.cool上下载的钉钉打卡测试需要收费使用，而界面和功能跟这个模块一致，暂未探清是否是此模块的翻版
## 模块版本号
v1.04
## 模块安装包
https://github.com/wuxiaosu/XposedRimetHelper

**Comment by tiann** [comment]
这二者是一个东西，麻烦搞清楚再来提问题。

**Comment by BaoJingchuan** [comment]
都说功能一致了，一个开源免费一个收费能是一个东西？

**Comment by abadm** [comment]
确定这俩不是一个东西一个是盗
