### ISSUE TITLE
请求创建应用支持share 微博客户端

### ISSUE THREAD

**Issue by hack003** [taichi-framework/TaiChi#361]
目前太极创建应用不支持添加这个share 微博客户端
请求创建应用支持share 微博客户端
share  微博客户端是一款比较优秀的微博三方客户端，用户比较多，但目前不能正常分享到微信，所以请求可以创建应用支持share 微博客户端 到太极 ，以便能正常分享。感谢作者

**Comment by VectorZhao** [comment]
我测试了一下，分享图片给微信好友是可以的啊。。。

**Comment by hack003** [comment]
分享图片是没问题 ，但分享一条微博就不行，点了微信没反应，调不出选择好友界面。麻烦再测下，


发送自 Windows 10 版邮件应用

发件人: VectorZhao
发送时间: 2019年2月25日 9:54
收件人: taichi-framework/TaiChi
抄送: hack003; Author
主题: Re: [taichi-framework/TaiChi] 请求创建应用支持share 微博客户端 (#361)

我测试了一下，分享图片给微信好友是可以的啊。。。

**Comment by tiann** [comment]
https://github.com/taichi-framework/Daily-Build/releases/tag/4.3.9.2
