### ISSUE TITLE
微X 多窗口模式（显示文章） 工作不正常

### ISSUE THREAD

**Issue by Hubedge** [taichi-framework/TaiChi#365]
太极Magisk模块版本：4.7.0
太极APP版本：4.3.9
手机型号：一加6
ROM版本：H2OS 9.0.2
Xposed模块：微X
Xposed模块版本：1.25_8.47
APP及版本：微信

问题描述：

1. 在微X中打开 其他-多窗口模式（显示文章）
2. 从订阅号中打开文章链接，文章窗口不为多窗口模式，工作不正常；
3. 从朋友圈、微信收藏中打开文章链接，文章窗口为多窗口模式，工作正常。

补充：
Android 8.x 配官方 Xposed 无此问题。

**Comment by tiann** [comment]
不知道微X的实现原理，我这短期内不会修复。

**Comment by Hubedge** [comment]
这个 issue 需要提给微x的作者吗？

**Comment by 06ji** [comment]
> 这个 issue 需要提给微x的作者吗？

要的，未来是太极

**Comment by 06ji** [comment]
> 不知道微X的实现原理，我这短期内不会修复。

我也发现了，太极APP4.3版本能正常显示多窗口模式，然后直接更新4.3.9，多窗口模式就失效了

**Comment by 06ji** [comment]
> 太极Magisk模块版本：4.7.0
> 太极APP版本：4.3.9
> 手机型号：一加6
> ROM版本：H2OS 9.0.2
> Xposed模块：微X
> Xposed模块版本：1.25_8.47
> APP及版本：微信
> 
> 问题描述：
> 
> 1. 在微X中打开 其他-多窗口模式（显示文章）
> 2. 从订阅号中打开文章链接，文章窗口不为多窗口模式，工作不正常；
> 3. 从朋友圈、微信收藏中打开文章链接，文章窗口为多窗口模式，工作正常。
> 
> 补充：
> Android 8.x 配官方 Xposed 无此问题。

确实是，4.3时候没问题。4.3.9多窗口失效了
