### ISSUE TITLE
希望支持蚂蚁森林助手

### ISSUE THREAD

**Issue by 212919220** [taichi-framework/TaiChi#366]

**Comment by tianyugo** [comment]
支持！

**Comment by lmrpx** [comment]
顶

**Comment by tiann** [comment]
自行测试：https://github.com/taichi-framework/TaiChi/releases/tag/5.0.2

**Comment by tianyugo** [comment]
这个5.0.2 
创建应用没有支付宝，，下载模块没有模块。。。怎么破

**Comment by tiann** [comment]
普通版创建不了

**Comment by 212919220** [comment]
> 自行测试：[https](https://github.com/taichi-framework/TaiChi/releases/tag/5.0.2)：[//github.com/taichi-framework/TaiChi/releases/tag/5.0.2](https://github.com/taichi-framework/TaiChi/releases/tag/5.0.2)

可以用！谢谢weishu
