### ISSUE TITLE
勾选模块后模块打不开，所有模块都是闪退

### ISSUE THREAD

**Issue by Qcheng001** [taichi-framework/TaiChi#367]
太极Magisk模块版本：4.7
太极APP版本：4.3.9
手机型号：小米8
ROM版本：miui10 9.2.21
Xposed模块：所有模块
Xposed模块版本：各个版本
APP及版本：

问题描述：在太极内勾选模块后，被勾选的模块崩溃无法打开，在更新太极4.3.9后遇到的问题，不勾选正常打开，设置好后再勾选不生效，

其他Magisk模块：无

补充：

**Comment by tiann** [comment]
“所有模块” 具体是什么模块？

**Comment by Qcheng001** [comment]
> “所有模块” 具体是什么模块？

手机上安装的所有模块都打不开😁，不好意思，表述不清，一元群里也有人碰到这个问题了，

**Comment by tiann** [comment]
.........

**Comment by tiann** [comment]
你是觉得我不理解汉语，还是觉得我能掐指一算知道你手机里都装了些什么模块？

**Comment by Qcheng001** [comment]
> 你是觉得我不理解汉语，还是觉得我能掐指一算知道你手机里都装了些什么模块？

就是手机上装了的模块，微信学英语，淘饭饭，文本自定义等，我今天想要打开设置下的，发现崩溃，取消勾选后，就能打开了，重新勾选打不开但是可用，但是新安装的模块就算设置好后再勾选，也不生效，就是这样
