### ISSUE TITLE
太极里面添加新软件的界面能不能不包含已经添加的软件

### ISSUE THREAD

**Issue by uiwjgensuali** [taichi-framework/TaiChi#369]
太极Magisk模块版本：
太极APP版本：
手机型号：
ROM版本：
Xposed模块：
Xposed模块版本：
APP及版本：

问题描述：
太极里面添加新软件能不能不包含已经添加的软件，有时候 添加了大部分的安装软件，再去添加一个新软件，软件太多很难找，能不能把已经添加的不显示，或者不显示系统软件？？？？
其他Magisk模块：

补充：

**Comment by tiann** [comment]
https://github.com/taichi-framework/TaiChi/releases/tag/5.0.2
