### ISSUE TITLE
新增模块要妳命三千5.212支持

### ISSUE THREAD

**Issue by GaHoKwan** [taichi-framework/TaiChi#371]
## 模块名字
要妳命三千
## 模块版本号
5.212
## 模块更新了什么？
各种抖音版本的新版支持

https://repo.xposed.info/module/cn.kwaiching.hook

太极·阴 4.3.9 核心123

**Comment by GaHoKwan** [comment]
![screenshot_20190226-031921_taichi](https://user-images.githubusercontent.com/7671203/53362817-fa037c00-3975-11e9-8a30-b0126799c6d7.jpg)

**Comment by tiann** [comment]
自行测试：https://github.com/taichi-framework/TaiChi/releases/tag/5.0.2
