### ISSUE TITLE
请求添加新模块 小鸡炖蘑菇

### ISSUE THREAD

**Issue by spyrsueky** [taichi-framework/TaiChi#374]
## 模块名字
小鸡炖蘑菇
## 模块用途
支付宝收取能量，和养鸡
## 模块版本号
1.1.9
## 模块安装包
小鸡炖蘑菇.apk
https://pan.baidu.com/s/1VC9Z8Lf05uVZvHVYTqMJNQ

**Comment by spyrsueky** [comment]
pursueky/Screenshot_2019-02-26-14-00-35-026_me.weishu.exp.png

**Comment by spyrsueky** [comment]
https://raw.githubusercontent.com/spyrsueky/pursueky/master/Screenshot_2019-02-26-14-00-35-026_me.weishu.exp.png

**Comment by spyrsueky** [comment]
[https://raw.githubusercontent.com/spyrsueky/pursueky/master/Screenshot_2019-02-26-14-00-35-026_me.weishu.exp.png](url)

**Comment by tiann** [comment]
使用前请先提供 zfb 加好友吱口令已激活本插件？

**Comment by tiann** [comment]
自己测试：https://github.com/taichi-framework/TaiChi/releases/tag/5.0.2
