### ISSUE TITLE
太极阳很多模块闪退

### ISSUE THREAD

**Issue by HaleShaw** [taichi-framework/TaiChi#375]
太极Magisk模块版本：4.7.0
太极APP版本：4.3.9
手机型号：荣耀10
ROM版本：8.1
Xposed模块：边缘手势
Xposed模块版本：5.3
APP及版本：

问题描述：最近太极更新这两三次，很多模块都闪退

其他Magisk模块：Google App助手 1.8.0，上帝模式 2.7.7，QQ净化 3.4.0，假装分享 -126，ChromePie 0.7.4，AideHelper 1.0，监视剪切板 1.0，运动修改器 2.1.3

补充：上述几个模块全都闪退，不知道怎么回事。

**Comment by Qcheng001** [comment]
老哥我也是，我还以为系统原因，重刷都不行，模块和太极都卸了重装也不行，只要勾选就崩溃，不勾选就能打开，

**Comment by tiann** [comment]
进 rec 执行 rm -rf /data/system/taichi 看看

**Comment by Qcheng001** [comment]
韦数按你说的那样做还是闪退，现在太极app版本是5.0.1

**Comment by AceMONKEY519** [comment]
别安装AD快消，是这个模块导致的，我百分百确定

**Comment by Qcheng001** [comment]
卧槽，楼上老哥牛逼，确实是这个原因，刚试了下真的可以了
