### ISSUE TITLE
求太极官网模块后显示版本号

### ISSUE THREAD

**Issue by HaleShaw** [taichi-framework/TaiChi#378]
## 模块名字
所有模块
## 模块更新了什么？
希望能在太极官网下载模块页面，在每个模块后面都显示版本号和更新时间。
这样能更直观，不用每天都把每一个模块点开去看一下是否有更新。
当然，如果每个模块能点开有个介绍页面就更完美了，同时罗列部分能支持的历史版本。（这个估计你实现太耗时）

**Comment by zhangxuhu** [comment]
可以有热心网友来pr，大佬负merge

**Comment by hh2333** [comment]
我晚上如果有时间就先加上一部分（咕咕咕予定:full_moon_with_face:

**Comment by tiann** [comment]
https://taichi.cool/module/module_cn
