### ISSUE TITLE
V++

### ISSUE THREAD

**Issue by AceMONKEY519** [taichi-framework/TaiChi#383]
太极Magisk模块版本：4.7.0
太极APP版本：4.3.9.3
手机型号：一加6，红米Note7
ROM版本：氢OS 9.0，MIUI10 9.0
Xposed模块：V++
Xposed模块版本：1.0.4
APP及版本：微信7.0.3

问题描述：V++设置窗口始终无法出现

其他Magisk模块：

补充：

**Comment by a2212997715** [comment]
q++和v++都有这样的问题

**Comment by tiann** [comment]
需要等一段时间才出现，非太极的问题。

**Comment by AceMONKEY519** [comment]
Q++等一会儿能出来，但是V++从来没出来过呢
