### ISSUE TITLE
网易云音乐插件

### ISSUE THREAD

**Issue by AceMONKEY519** [taichi-framework/TaiChi#384]
太极Magisk模块版本：470
太极APP版本：4393
手机型号：OP6  lavender
ROM版本：H2OS 9.0   miui10  9.0
Xposed模块：网易云音乐插件
Xposed模块版本：2.8.2
APP及版本：网易云音乐5.9.0

问题描述：能设置，显示设置已生效，打开网易云音乐实际没生效

其他Magisk模块：

补充：

**Comment by tiann** [comment]
非 magisk 版？

**Comment by AceMONKEY519** [comment]
magisk版

**Comment by tiann** [comment]
“实际没生效“ 具体指的什么？

**Comment by AceMONKEY519** [comment]
功能设置里的选项开启了均不生效。

**Comment by wuzunweiwang** [comment]
这个似乎是网易云版本的问题好像  我的网易云580 插件282 我开了签到和本地黑胶vip 但是只有黑胶生效，签到不生效

**Comment by tiann** [comment]
与网易云的版本有关，非太极的问题。测试可以正常使用。
