### ISSUE TITLE
完美指纹

### ISSUE THREAD

**Issue by AceMONKEY519** [taichi-framework/TaiChi#385]
## 模块名字
完美指纹
## 模块用途
解决系统限制不能开机首次使用指纹解锁
## 模块版本号
1.0
## 模块安装包
https://www.coolapk.com/apk/djwdj.wmzw

**Comment by tiann** [comment]
由于这么模块停止维护，并且仅支持少部分机型；我只能做到这么多了。
测试小米手机开启之后，进桌面无限loading。

如果你可能用就用，不能用就只能这样了。

https://github.com/taichi-framework/TaiChi/releases/tag/5.0.2

**Comment by AceMONKEY519** [comment]
那fingerprintenable模块呢？可以使用吗

**Comment by AceMONKEY519** [comment]
感谢维术！一加6测试可以用完美指纹。
