### ISSUE TITLE
与riru v15冲突

### ISSUE THREAD

**Issue by singleNeuron** [taichi-framework/TaiChi#387]
太极Magisk模块版本：4.7
太极APP版本：4.3.9
手机型号：Nexus6p
ROM版本：StatixOS Android9
Xposed模块：
Xposed模块版本：
APP及版本：

问题描述：
手机重启后riru无法正常工作，提示文件未被替换。执行一次软重启后正常。
如果需要的话我可以提供edxp的工具抓取的日志

其他Magisk模块：riru v15，存储重定向，edxp 2.9.9-beta2

补充：

**Comment by tiann** [comment]
不会再修复与 Riru 有关的问题，我已经做了很多了。

**Comment by zhangxuhu** [comment]
去riru的repo提 issue吧
