### ISSUE TITLE
大佬，什么时候增加mxfq模块，就等这个了

### ISSUE THREAD

**Issue by sofish0** [taichi-framework/TaiChi#389]

**Comment by zhangxuhu** [comment]
https://github.com/taichi-framework/TaiChi/blob/master/.github/ISSUE_TEMPLATE/--------.md

请使用issue模板提交问题 ，方便weishu

**Comment by sofish0** [comment]
模块名字
MXFQ

模块用途
QQ消息窗口快捷回复

模块版本号
1.2.4.1210

模块安装包
https://www.coolapk.com/apk/com.mx.qqwindow

**Comment by tiann** [comment]
这模块使用了不兼容  Android 9.0的加固，在 9.0 上什么都不干打开就闪退。不会支持。
