### ISSUE TITLE
请求支持[应用管理]

### ISSUE THREAD

**Issue by JAustinal** [taichi-framework/TaiChi#393]
play商店链接：https://play.google.com/store/apps/details?id=github.tornaco.xposedmoduletest

**Comment by zhangxuhu** [comment]
https://github.com/taichi-framework/TaiChi/blob/master/.github/ISSUE_TEMPLATE/--------.md

请使用issue模板提交问题 ，方便weishu

**Comment by tiann** [comment]
#99 
提 issue 之前麻烦先看看是不是有人已经提过了。
