### ISSUE TITLE
是否可能仅在Island工作空间中运行太极/VirtualXposed？

### ISSUE THREAD

**Issue by littlef0x** [taichi-framework/TaiChi#395]
系统：H2OS 9（基于Android 9.0）
App：太极 4.3.9.4/VirtualXposed 0.17.2
目前Island工作正常，需要Xposed模块的app都在Island里，主空间并不需要，但是Xposed和太极均无法在工作空间工作，已尝试方法如下：
太极从已安装应用添加：添加后要求卸载原应用，卸载就真的卸载了，太极版没有安装
太极从安装包添加：安装过程中闪退
VirtualXposed从安装包/已安装应用添加：安装正常，启动应用卡在Opening xxx
请问是否有方法实现仅在工作空间使用太极/VirtualXposed，或者两个空间都安装太极，但只在工作空间安装app和模块？谢谢。

**Comment by tiann** [comment]
太极 magisk 可以实现

**Comment by littlef0x** [comment]
手机并未解锁BL，无法安装magisk。所以非magisk版无法实现是么？如果使用Island+太极双开应用，然后删除主空间应用，是否可以工作？

**Comment by tiann** [comment]
删除主空间应用之后，island 中的应用如果还能存在，那么就可以工作。

如果你需要主空间中用原来的安装包，太极中用太极处理过的安装包；那么这样从原理上讲是无法实现的。

**Comment by littlef0x** [comment]
主空间不需要使用原版，只需要工作空间安装太极版即可。这样如果应用升级，可以直接通过太极覆盖安装工作空间的太极版应用么？

**Comment by tiann** [comment]
这个没有尝试过，不知道 island 有没有做处理。你需要自己试下。

**Comment by littlef0x** [comment]
好的我尝试一下，谢谢解答

**Comment by littlef0x** [comment]
经测试，双开之后再删除主空间应用，Island工作空间的太极版应用正常。
至于升级等有新版发布再反馈。

**Comment by littlef0x** [comment]
久等了，微信发新版隔太久了😂
微信7.0.3→7.0.4，太极5.2.0-253非root，内核124，按照上面的操作仅在工作空间保留app，之后手动下载新版安装包，安装时打开方式选择太极的“应用安装/升级”，经过太极优化后可以正常安装升级，模块也没有报错
