### ISSUE TITLE
新增模块支持：SkyOlin Helper（程序窗口化助手）

### ISSUE THREAD

**Issue by w805735525** [taichi-framework/TaiChi#397]
## 模块名字
SkyOlin Helper（程序窗口化助手）

## 模块用途
这是一个很强大的分屏模块可实现同屏显示多个软件比手机自带分屏软件更实用
*将程序窗口化
*自定义程序分辨率
*自定义程序DPI
*强制屏幕旋转

## 模块安装包
https://pan.baidu.com/s/1c1oRizm

**Comment by tiann** [comment]
模块本身不支持 9.0
