### ISSUE TITLE
支持 recovery直接刷入或者别的 su

### ISSUE THREAD

**Issue by kaniwow** [taichi-framework/TaiChi#403]
太极Magisk模块版本：4.7.0
太极APP版本：5.0.1
手机型号：
ROM版本：
Xposed模块：
Xposed模块版本：
APP及版本：

问题描述：这不是一个真正的bug反馈

其他Magisk模块：

补充：
对于一些仅有su文件而没有解锁bootloader的用户和坚守supersu的用户这个东西挺实用的来着，我有拆包查看过模块，大概知道替换哪些文件，不过对于一些bash脚本中的权限设置还是看不太懂，希望伟叔能写个类似的教程

**Comment by tiann** [comment]
实际上是可以支持的，不过现在没空搞。bash脚本里面最重要的是更改 selinux策略。supersu的话，可以用 supolicy 完全是可以做到的。

**Comment by tiann** [comment]
Magisk已经成为事实上的 Systemless 解决方案，去支持旧方案没多大意义了。
