### ISSUE TITLE
太极微信荣耀note10 拍三张照片后, 无权限使用相机. 4.37似乎无此问题.

### ISSUE THREAD

**Issue by Killea** [taichi-framework/TaiChi#404]
太极Magisk模块版本： None
太极APP版本：4.3.8 5.0.x
手机型号：荣耀 NOTE 10
ROM版本：EMUI 8.20
Xposed模块：NONE
Xposed模块版本：NONE
APP及版本：微信 6.x  and  7.x

问题描述：在仅仅创建微信不添加任何模块的情况下, 使用微信连拍3三张照片,相机立即无权使用.
我猜测是4.38版本修复exposed运行环境引入的问题. 4.37以及之前的版本似乎没有这个问题.

其他Magisk模块：None

补充：这个问题如果没有华为的手机似乎难以重现. 希望遇到同样问题的朋友跟帖.

**Comment by tiann** [comment]
无权使用是什么意思？

**Comment by Killea** [comment]
跟这个帖子弹出的提示信息一样,必须是连拍三张就挂.
https://club.huawei.com/thread-17821635-1-1.html
重启手机,或者关闭微信再开还可以再拍三张.
权限丢了后,手机放一会,时间不定. 还可以再拍三张.

**Comment by Killea** [comment]
另外,全新安装的微信没有任何问题. 如果用太极卸载,apk签名被改了以后重装,就出现这个问题.

**Comment by tiann** [comment]
把太极关了就不会了？
这哥们儿的帖子没说他装了太极吧，我觉得这是你系统的问题。

**Comment by tiann** [comment]
为什么 437 没问题，是因为那时候的系统没问题。

**Comment by Killea** [comment]
我再解释一下.如果我不安装太极, 就没有这个问题. 
那哥们我只是借用一下图片.

**Comment by Killea** [comment]
你说的是系统问题有可能, 这个系统不装太极的时候微信正常.
系统跟太极有冲突, 导致太极运行的微信不正常.
如果其他人也遇到这个问题, 那么就请查一下.

**Comment by PikuZheng** [comment]
相同现象，华为p20，Android9.0，排除权限设置问题

**Comment by PikuZheng** [comment]
我再说一下故障现象。使用经过太极处理的微信程序（我的是play版7.0.0），在微信内拍三张照片发送。在试图拍第四张照片时，微信拒绝拍照，提示没有相机或存储权限（相机预览画面有的，推测是存储权限）。考虑是太极问题，不是因为运行环境，而是因为太极处理过微信安装包（与是否安装了太极无关）。

**Comment by tiann** [comment]
前段时间我复现过，现在也不出现了。如果还有问题再提出。

**Comment by PikuZheng** [comment]
5.1.12-211仍有此现象。

**Comment by rainsuns** [comment]
mate8，荣耀v8在5.2太极阴都有这问题
