### ISSUE TITLE
核心破解挂了？

### ISSUE THREAD

**Issue by kaniwow** [taichi-framework/TaiChi#411]
太极Magisk模块版本：4.7.0
太极APP版本：5.0.1
手机型号：Honor10
ROM版本：emui9
Xposed模块：核心破解
Xposed模块版本：1.2.0
APP及版本：全局模块

问题描述：
核心破解出错，无法降级安装程序

其他Magisk模块：
app systemize
busybox
chinese (simplified) fongt completion
iOS12.1 Emoji
init.d injector
riru-core
riru-mipushfake
机型修改
Unlock CN GMS

补充：

**Comment by tiann** [comment]
把你其他的模块都给关了，什么都没动怎么突然就会挂呢？
