### ISSUE TITLE
请求支持 应用变量

### ISSUE THREAD

**Issue by xiaohuang2004** [taichi-framework/TaiChi#413]
## 模块名字
应用变量
## 模块用途
模拟手机型号和参数
## 模块版本号
3.2.10
## 模块安装包
https://github.com/kingsollyu/AppEnv-Kotlin/releases/tag/3.2.10

**Comment by tiann** [comment]
magisk 已经支持了，普通版需要修改模块本身的安装包，这个现在不打算这样干。
