### ISSUE TITLE
太极非magisk lataclysm

### ISSUE THREAD

**Issue by PikuZheng** [taichi-framework/TaiChi#419]
## 模块名字
lataclysm

## 模块用途
伪装位置

## 模块版本号
1.35

## 模块安装包
https://dl-xda.xposed.info/modules/com.cataclysm.i_v64_037bfa.apk

希望在太极阴中添加

**Comment by tiann** [comment]
添加了也没法用，太极阴需要把这个模块重新创建一遍，现在是不行的。
