### ISSUE TITLE
新增模块支持： MIUI 息屏显示通知图标

### ISSUE THREAD

**Issue by ztc1997** [taichi-framework/TaiChi#420]
## 模块名字
MIUI 息屏显示通知图标
## 模块用途
MIUI 只有数个应用的图标能在 AOD 显示，这个模块使所有应用程序都可以在息屏显示上显示通知图标。
## 模块版本号
0.1.1
## 模块安装包
https://github.com/ztc1997/MIUIAODNotificationIcon/releases

**Comment by tiann** [comment]
模块引擎更新到 13 看看是否可以正常使用

**Comment by ztc1997** [comment]
@tiann 无效。我开发时是在edxp测试的，edxp上没问题。

**Comment by tiann** [comment]
尝试一下把系统界面添加到太极呢？

**Comment by ztc1997** [comment]
@tiann 我删除了其他应用，禁用了其他模块，就起效了。我排查一下是哪个冲突了。

**Comment by ztc1997** [comment]
@tiann 有效的，没问题了，可能是第一次测试的时候没调好。

**Comment by tiann** [comment]
@ztc1997 如果愿意的话，可以加下开发者QQ群：529427040
