### ISSUE TITLE
新增模块支持：Serial Number Changer

### ISSUE THREAD

**Issue by byqty** [taichi-framework/TaiChi#422]
## 模块名字
Serial Number Changer
## 模块用途
伪装设备SN硬件序列号
## 模块版本号
2.1
## 模块安装包
https://repo.xposed.info/module/com.intplus.idchanger

**Comment by tiann** [comment]
这模块有缺陷，只hook了
`SystemProperties.get(String, String)` 漏掉了一些东西会导致有些场景hook不到。

**Comment by byqty** [comment]
> 这模块有缺陷，只钩了
> `SystemProperties.get(String, String)`漏掉了一些东西会导致有些场景钩不到。

可否试试1.8或者1.9版本，新版好像确实有问题，我用1.9版正常

**Comment by tiann** [comment]
1.9 一样只做了这个处理。

**Comment by byqty** [comment]
> 1.9一样只做了了这个处理。

好吧，那算了，多谢回复，打扰了😁😁
