### ISSUE TITLE
太极阳下云闪付选卡无限加载

### ISSUE THREAD

**Issue by shinelinxx** [taichi-framework/TaiChi#423]
太极Magisk模块版本：TaiChi 4.7.0
太极APP版本：东皇钟 5.0
手机型号：小米6
ROM版本：MIUI10最新稳定版 安卓8.0
Xposed模块：
Xposed模块版本：
APP及版本：云闪付6.1.8（以及历史版本）

问题描述：
开启太极阳（Taichi magisk模块）后，云闪付支付无法切换其他支付卡，点击切换进入无限加载。App其他功能暂时没有发现问题。
问题排除: 1、关闭Taichi后，重启后云闪付可以正常使用。2、返回旧版云闪付（倒退若干版本号）无法解决 3、使用了Magisk hide后，问题存在，排除root原因。4、使用了GooglePlay的云闪付问题无法解决。5、貌似某些xp用户也存在这个问题。

是否有方法隐藏被检测？还是其他原因
其他Magisk模块：

补充：

**Comment by tiann** [comment]
我尝试了云闪付 6.1.8 一切正常。

你的magisk 版本是不是太高了？高版本的 magisk hide 现在有问题，至少回退到 18.0。

**Comment by shinelinxx** [comment]
> 我尝试了云闪付 6.1.8 一切正常。
> 
> 你的magisk 版本是不是太高了？高版本的 magisk hide 现在有问题，至少回退到 18.0。

问题解决，谢谢
