### ISSUE TITLE
新增模块支持：ColorOS5.2-Android-8.1-模块

### ISSUE THREAD

**Issue by 646951596** [taichi-framework/TaiChi#424]
## 模块名字
ColorOS5.2-Android-8.1-模块
## 模块用途
OPPO手机root后状态栏有红条警告，该模块能隐藏红条等
## 模块版本号
1.3版本
## 模块安装包
https://share.weiyun.com/5ujj5Is

**Comment by tiann** [comment]
https://github.com/taichi-framework/taichi-framework.github.io/blob/master/module/changelog_cn.md
