### ISSUE TITLE
OP6_H2 新版 ROM safetynet检查均false

### ISSUE THREAD

**Issue by AceMONKEY519** [taichi-framework/TaiChi#426]
太极Magisk模块版本：4.7.0
太极APP版本：5.0.2-7
手机型号：一加6
ROM版本：OP6_H2_Beta_16
Xposed模块：
Xposed模块版本：
APP及版本：

问题描述：
勾上太极magisk模块以后，safetynet检查均FALSE，上个版本的ROM以及最新太极，勾上了magisk太极都是true。
其他Magisk模块：

补充：

**Comment by tiann** [comment]
新版的 magisk 自带的 magisk hide有问题，至少回退到 18.0 
类似问题见 #436

**Comment by AceMONKEY519** [comment]
应该不是magisk的问题，我昨晚双清开机后，刷入太极magisk，没启用任何其他模块与XP插件时，safetynet均pass。
