### ISSUE TITLE
新增模块支持：麻花助手

### ISSUE THREAD

**Issue by AceMONKEY519** [taichi-framework/TaiChi#429]
## 模块名字
麻花助手
## 模块用途
去除启动页广告；
去除启动页5s倒计时；
去除启动页历史广告显示；
去除“推荐”、“电影”、“电视剧”页面中存在的广告；
去除视频播放页面的广告；
为助手添加图标；
为助手添加设置菜单；
获取视频播放地址（测试）；
去除主界面升级提示。
## 模块版本号
0.6.2
## 模块安装包
https://github.com/1595901624/mhzs/releases/download/0.6.2Beta/mhzs_0.6.2_Beta.apk

**Comment by 06ji** [comment]
支持！

**Comment by tiann** [comment]
`com.amahua.ompimdrt` 这是个什么APP，没找到地方下载。

**Comment by 06ji** [comment]
> `com.amahua.ompimdrt` 这是个什么APP，没找到地方下载。

http://m.imahua.com/app/download

**Comment by 06ji** [comment]
> `com.amahua.ompimdrt` 这是个什么APP，没找到地方下载。

模块引擎更新到8了，是不是漏掉了麻花助手。。。

**Comment by tiann** [comment]
不是说支持就能支持的，作者已经明确说明了，理论不支持

**Comment by tiann** [comment]
这个包名不对，在官网下载的包名：`com.amahua.ywofnbfd`
模块hook的包名：`com.amahua.ompimdrt`

**Comment by tiann** [comment]
https://github.com/1595901624/mhzs/pull/2

**Comment by AceMONKEY519** [comment]
https://github.com/1595901624/mhzs/releases/download/0.6.4Beta/mhzs_0.6.4_beta.apk

**Comment by AceMONKEY519** [comment]
> [1595901624/mhzs#2](https://github.com/1595901624/mhzs/pull/2)
0.6.5作者说已经可以用了，麻花官网下的app，我再测试下。
https://github.com/1595901624/mhzs/releases/download/0.6.5Beta/mhzs_0.6.5_Beta.apk

**Comment by AceMONKEY519** [comment]
> 这个包名不对，在官网下载的包名：`com.amahua.ywofnbfd`
> 模块hook的包名：`com.amahua.ompimdrt`

测试了下XPosed环境下，0.6.5已经支持麻花影视了。麻烦大佬再试下。

**Comment by tiann** [comment]
https://taichi.cool/module/changelog_cn
