### ISSUE TITLE
新增模块支持：【No Lock Home】

### ISSUE THREAD

**Issue by CHN-beta** [taichi-framework/TaiChi#430]
## 模块名字
No Lock  Home
## 模块用途
在检测到手机连接上特定的WiFi（通过MAC或SSID判断）或者基站后，点亮手机、解锁时不需要密码、也不需要指纹。
## 模块版本号
2.2.1
## 模块安装包
（将`.zip`改为`.apk`）
[No Lock Home_2.2.1.zip](https://github.com/taichi-framework/TaiChi/files/2926420/No.Lock.Home_2.2.1.zip)

**Comment by tiann** [comment]
尝试把 模块适配引擎更新到版本 10 试一下，我MIUI貌似用不了。

**Comment by PianCat** [comment]
@tiann MIUI好像把解锁机制魔改了来着……

**Comment by tiann** [comment]
如无响应视我就关闭了。
