### ISSUE TITLE
BUG：转转APP无法用微信登陆，提示请先安装微信客服端（已经安装微信，并添加到了太极）

### ISSUE THREAD

**Issue by banzuan** [taichi-framework/TaiChi#433]
## 什么问题
转转无法用微信登陆，提示请先安装微信客服端（已经安装微信，并添加到了太极）
## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：
太极 Magisk 模块版本：
太极APP版本：东皇钟-5.0.2-8
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：魅族PRO 7
ROM版本：Flyme 7.9.3.5 beta

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
转转是否添加到了太极？

**Comment by banzuan** [comment]
> 转转是否添加到了太极？
没有，有没有终极的解决办法？能不能不添加？这样下去也不是办法

**Comment by tiann** [comment]
只有两种办法：
1. 添加转转到太极。
2. 使用太极·阳。

**Comment by banzuan** [comment]
好的，谢谢大神回复
