### ISSUE TITLE
BUG：太极·Magisk与riru冲突

### ISSUE THREAD

**Issue by Howard20181** [taichi-framework/TaiChi#435]
## 什么问题

当开启 太极·Magisk时，riru core不工作

## 详细情况

太极·Magisk 123 开启后riru所有模块都无法使用

Magisk 版本：18.1
太极 Magisk 模块版本：4.7.0
太极APP版本：5.0.1-8
开启的 Xposed 模块：*
Xposed模块版本：*
开启的其他 Magisk 模块：riru-core
其他 Magisk 模块版本：V14~16
手机型号：小米5(gemini)
ROM版本：MIUI 10.2

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。
[modules.list.txt](https://github.com/taichi-framework/TaiChi/files/2930348/modules.list.txt)
[apps.list.txt](https://github.com/taichi-framework/TaiChi/files/2930349/apps.list.txt)

补充：有能力请务必提供日志文件已快速解决问题。

[magisk_log_20190305_180646.log](https://github.com/taichi-framework/TaiChi/files/2930342/magisk_log_20190305_180646.log)

**Comment by zhangxuhu** [comment]
https://github.com/RikkaApps/Riru/issues/23

@tiann weishu大大您好，我这抓取了全套的log，包括兼容的和不兼容的（间歇性兼容），麻烦您看看，谢谢。

**Comment by tiann** [comment]
不会再再这上面花精力了，哪个既然4.6能用你就用4.6，没有什么差别。
