### ISSUE TITLE
BUG：Taichi Magisk 4.7 模組導致 Google Pay 無法使用

### ISSUE THREAD

**Issue by rexx0520** [taichi-framework/TaiChi#436]
## 什么问题

Taichi Magisk 4.7 模組導致 Google Pay 無法使用

## 详细情况

安裝 4.0 版模組時 Google Pay 可正常運作
4.7 版則被 Google Pay 檢測出裝置已 Root
兩種情況下 SafetyNet 皆為通過狀態。

Magisk 版本：
太极 Magisk 模块版本：4.0 / 4.7
太极APP版本：5.0.2-8
开启的 Xposed 模块：綠色守護、音量增強器、雲村清潔工、App Locale 2
Xposed模块版本：123
开启的其他 Magisk 模块：若需要我可再附註
其他 Magisk 模块版本：
手机型号：HTC U11+
ROM版本：8.0

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。
目前已改用太極˙陰，軟體和模組都重新配置了...

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
使用4.0版本时，magisk本身的版本是否与4.7时候一致？

**Comment by rexx0520** [comment]
一致的，都是最新版本

weishu <notifications@github.com> 於 2019年3月5日 週二 下午10:18寫道：

**Comment by tiann** [comment]
尝试退回到magisk 18.0，我觉得这不是太极的问题。检测到root，显然是因为magisk hide挂了。而最新的magisk重写了magisk hide。

**Comment by rexx0520** [comment]
已確認，Magisk 18.0 版本使用 4.7 半太極模組 Google Pay 正常使用無問題，謝謝！
