### ISSUE TITLE
新增模块支持：【微信群同步直播】

### ISSUE THREAD

**Issue by leafzz** [taichi-framework/TaiChi#439]
## 模块名字
微信群同步直播
## 模块用途
1.多群直播讲课，同步转发消息，转发语音，图片，视频，链接
2.录播功能，支持选择已经发送的消息再次进行转发到目标群
## 模块版本号
4.0
## 模块安装包
支持微信版本：最新7.0.3

（将.zip改为.apk）
[微信群同步直播-4.0-20190228-release.zip](https://github.com/taichi-framework/TaiChi/files/2934209/-4.0-20190228-release.zip)
测试卡密：7043300  8328430  5330530  6202850  7031760  3782830   2396080   1649840   2214530

**Comment by leafzz** [comment]
@tiann @zhangxuhu @zsakvo @PianCat 在吗，麻烦审核下，谢谢

**Comment by tiann** [comment]
模块引擎更新到 12

**Comment by leafzz** [comment]
@tiann 你好，模块引擎更新到12 是什么意思？ 谢谢

**Comment by zhangxuhu** [comment]
> @tiann 你好，模块引擎更新到12 是什么意思？ 要怎么做呢？ 文档没看到 谢谢

你好，太极从东皇钟5.0版本开始支持模块引擎动态更新，不再需要更新太极app版本即可更新支持的模块。您可以打开太极app，点击加号，模块管理，右上角三个点，就有更新模块引擎。这样就可以使用这个新适配的模块了。建议仔细阅读太极使用说明。

**Comment by leafzz** [comment]
> > @tiann 你好，模块引擎更新到12 是什么意思？ 要怎么做呢？ 文档没看到 谢谢
> 
> 你好，太极从东皇钟5.0版本开始支持模块引擎动态更新，不再需要更新太极app版本即可更新支持的模块。您可以打开太极app，点击加号，模块管理，右上角三个点，就有更新模块引擎。这样就可以使用这个新适配的模块了。建议仔细阅读太极使用说明。

感谢回复，我按照你的操作去做了，点击了更新适配引擎，可是我的xpose app还是显示暂不支持

**Comment by zhangxuhu** [comment]
> > > @tiann 你好，模块引擎更新到12 是什么意思？ 要怎么做呢？ 文档没看到 谢谢
> > 
> > 
> > 你好，太极从东皇钟5.0版本开始支持模块引擎动态更新，不再需要更新太极app版本即可更新支持的模块。您可以打开太极app，点击加号，模块管理，右上角三个点，就有更新模块引擎。这样就可以使用这个新适配的模块了。建议仔细阅读太极使用说明。
> 
> 感谢回复，我按照你的操作去做了，点击了更新适配引擎，可是我的xpose app还是显示暂不支持

您使用的是太极.Magisk嘛？另外请确认您目前使用的适配引擎版本号是不是12呢？

**Comment by leafzz** [comment]
> > > > @tiann 你好，模块引擎更新到12 是什么意思？ 要怎么做呢？ 文档没看到 谢谢
> > > 
> > > 
> > > 你好，太极从东皇钟5.0版本开始支持模块引擎动态更新，不再需要更新太极app版本即可更新支持的模块。您可以打开太极app，点击加号，模块管理，右上角三个点，就有更新模块引擎。这样就可以使用这个新适配的模块了。建议仔细阅读太极使用说明。
> > 
> > 
> > 感谢回复，我按照你的操作去做了，点击了更新适配引擎，可是我的xpose app还是显示暂不支持
> 
> 您使用的是太极.Magisk嘛？另外请确认您目前使用的适配引擎版本号是不是12呢？

我用的是太极阴，适配引擎版本号：12

**Comment by zhangxuhu** [comment]
> > > > > @tiann 你好，模块引擎更新到12 是什么意思？ 要怎么做呢？ 文档没看到 谢谢
> > > > 
> > > > 
> > > > 你好，太极从东皇钟5.0版本开始支持模块引擎动态更新，不再需要更新太极app版本即可更新支持的模块。您可以打开太极app，点击加号，模块管理，右上角三个点，就有更新模块引擎。这样就可以使用这个新适配的模块了。建议仔细阅读太极使用说明。
> > > 
> > > 
> > > 感谢回复，我按照你的操作去做了，点击了更新适配引擎，可是我的xpose app还是显示暂不支持
> > 
> > 
> > 您使用的是太极.Magisk嘛？另外请确认您目前使用的适配引擎版本号是不是12呢？
> 
> 我用的是太极阴，适配引擎版本号：12

估计weishu可能只给太极阳适配了，麻烦@tiann在确认下。

貌似提太极阴支持的模块需要在issue中特别注明的吧?

**Comment by leafzz** [comment]
好的, 我需要重新提交issue吗？ @tiann @zhangxuhu

**Comment by tiann** [comment]
太极·阴现在不会支持这个模块。

**Comment by leafzz** [comment]
> 太极·阴现在不会支持这个模块。

为什么呢？是有什么原因嘛？

**Comment by tiann** [comment]
太极·阴需要修改安装包，在找到更好的方法之前，我没必要去趟这个浑水。

**Comment by leafzz** [comment]
> 太极·阴需要修改安装包，在找到更好的方法之前，我没必要去趟这个浑水。

太极·阴里面不是已经有很多xpose的插件了嘛？我的也只是一个Xpose App

**Comment by tiann** [comment]
你这个是商业行为，定性不一样。
