### ISSUE TITLE
新增模块支持：【模块名】小米净化

### ISSUE THREAD

**Issue by AceMONKEY519** [taichi-framework/TaiChi#440]
## 模块名字
小米净化
## 模块用途
·解决hosts去广告导致系统提示网络异常的问题
·更新适配最新个性主题xx
·修复一些细节问题
## 模块版本号
2.1.5
## 模块安装包
https://pan.baidu.com/s/12u3iq_BgLrfMJbx6bm76uQ 提取码：1bre
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
模块适配引擎更新到 11 即可；注意把需要去广告的应用添加到太极，如下载管理。核心破解无需添加APP。
