### ISSUE TITLE
新增模块支持：【支付宝装x模块】

### ISSUE THREAD

**Issue by a2212997715** [taichi-framework/TaiChi#441]
## 模块名字
支付宝装x
## 模块用途
修改本地支付宝会员
## 模块版本号
2.28
## 模块安装包
https://www.coolapk.com/apk/im.hoho.alipayInstallB
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
模块引擎更新到 13 即可

**Comment by a2212997715** [comment]
> 模块引擎更新到 13 即可

感谢作者大大
