### ISSUE TITLE
新增模块支持：微视助手

### ISSUE THREAD

**Issue by l453562560** [taichi-framework/TaiChi#446]
## 模块名字
微视助手
## 模块用途
去水印下载，去广告，禁用更新，去除时间限制，自动点赞
## 模块版本号
1.6.6
## 模块安装包
https://pan.baidu.com/s/1haQhP58VuaHG80PIIMpPSA 提取码：yt4a
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
分享的文件已经取消，有别的下载渠道吗？

**Comment by tiann** [comment]
模块引擎更新到 12

**Comment by l453562560** [comment]
老大厉害，刚刚能用了，只是不在太极里面优化一下不会生效
