### ISSUE TITLE
BUG：更新至东皇钟后，模块失效

### ISSUE THREAD

**Issue by 15klli** [taichi-framework/TaiChi#447]
## 什么问题

从 4.3.9 更新至东皇钟 5.0.5(03-07日的推送)后 ，所有模块全部失效，含 微X模块、森林&庄园

## 详细情况

1. 3月7日打开太极APP后，有推送新版本，更新后发现模块都失效了。如当安装完毕更新版本后，马上打开微信，则微X模块仍生效，但**结束运行微信后，再打开微信**，则 无法生效。
2. 已尝试清除太极APP 缓存与数据，依然无法生效
3. 重新安装 4.3.9 版本，模块全部生效。

Magisk 版本：v18.1
太极 Magisk 模块版本：v3.2
太极APP版本：5.0.5
开启的 Xposed 模块：微X模块、森林&庄园
Xposed模块版本：微X模块（1.25）、森林&庄园（1.1.2）
开启的其他 Magisk 模块：淘饭饭
其他 Magisk 模块版本：MM（2018.8.1）MIUI10 vip下载（v2.0beta）
手机型号：小米note3
ROM版本： MIUI10

## 配置文件
* apps.list
```
 sr java.util.HashSet篋厱柛?  xpw    ?@     t com.specher.smt com.eg.android.AlipayGphonet name.caiyao.sporteditort com.jozein.xedget com.tencent.mmt com.oasisfeng.greenifyt com.sollyu.xposed.hook.modelt com.chen.firstxposedt z.houbin.em.energyt com.jy.taofanfant com.click369.controlbpt com.ext.star.wars.vxpt com.fkzhang.wechatxposedt com.qianbajin.sportacceleratort com.joe.alipaytreet com.wuxianlin.luckyhookert com.taobao.taobaot com.tencent.qqlivet chili.xposed.chimit com.sec.android.app.shealthx
```

* modules.list
```/data/app/com.fkzhang.wechatxposed-0dCDHKuOaT_dz1tRfVLaww==/base.apk
/data/app/com.jy.taofanfan-Jm0z-M62J4TvqcXrQScSsA==/base.apk
/data/app/z.houbin.em.energy-xNr1NgUGq8ixS5NM5snUgg==/base.apk
/data/app/name.caiyao.sporteditor-lp0aUnE_xe4HQgXV9utNEg==/base.apk
```

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by 15klli** [comment]
对不起，现在发现是因为我的 太极Magisk 版本太低，更新至 v4.7.0 后即可，[太极Magisk v4.7.0 下载链接](https://www.lanzous.com/i37r5vi)

**Comment by caliban511** [comment]
现在模块不在Github上更新了吗？

**Comment by tiann** [comment]
啥？

**Comment by caliban511** [comment]
Github上模块最新还停留在4.2版，上面又说要用4.7版。
以后模块都要在微信上获取下载链接吗？

**Comment by tiann** [comment]
https://github.com/taichi-framework/TaiChi-Magisk

**Comment by caliban511** [comment]
原来如此，地址已经收藏，非常感谢。。。
