### ISSUE TITLE
新增模块支持：【InstantFaceUnlock】

### ISSUE THREAD

**Issue by Buffoonss** [taichi-framework/TaiChi#448]
## 模块名字
InstantFaceUnlock
## 模块用途
人脸识别后自动上滑
## 模块版本号
2.1.0
## 模块安装包
[模块链接Xposed Info](https://dl-xda.xposed.info/modules/com.samstenner.instantunlock_v9_c2a17c.apk)

**Comment by tiann** [comment]
模块引擎更新到 17 看看是否正常

**Comment by tiann** [comment]
如无响应视我就关闭了。
