### ISSUE TITLE
Bug report: FakeLocation的反检测和太极冲突

### ISSUE THREAD

**Issue by lvzhenbo** [taichi-framework/TaiChi#450]
**Describe the bug**
当FakeLocation开启反检测功能时，太极会不停闪退，还提醒不要修改太极（没有修改）。

**To Reproduce**

**Expected behavior**
希望能和FakeLocation的开发者联系一下修复这个BUG，毕竟很多人都拥有这两个软件
**Smartphone (please complete the following information):**
Magisk version：
TaiChi-Magisk module version：
TaiChi version：东皇钟·5.0.5-14
Which Xposed modules are enabled ?：Bluded1.1.1，QQ净化3.5.0/2.7.0，QX1.21，CoolapkEx1.0，ColorQQ1.2.9，Q++1.2.5
Xposed modules version：
Which Magisk modules are enabled ?：
Magisk modules version：
Device ：小米MIX2S
ROM：MIUI10开发板9.2.28ROOT

**Additional context**
FakeLocation下载地址：https://www.coolapk.com/apk/com.lerist.fakelocation

**Comment by tiann** [comment]
这个你得联系fakelocation的作者解决；让他只针对需要 FakeLocation 的应用开启增强反检测，我这边做不了什么。
