### ISSUE TITLE
新增模块支持：【Flat Style Bar Indicators】

### ISSUE THREAD

**Issue by zyt1998hetutu** [taichi-framework/TaiChi#451]
## 模块名字
Flat Style Bar Indicators
## 模块用途
对状态栏进行美化
## 模块版本号
5.1.3
## 模块安装包
安装包：https://www.lanzous.com/i3couod
源地址：https://repo.xposed.info/module/com.bocharov.xposed.fsbi
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
1. 太极主程序升级到 5.1.8.4 ： https://taichi.ctfile.com/fs/19604958-365754974
2. 模块适配引擎更新到 89
3. 添加系统界面到太极，并勾选此模块。
4. 重启手机。

PS：仅测试过 9.0. 其他系统自行测试不保证可用且不会修复。

**Comment by Francishuai** [comment]
貌似不太可以，我尝试了很多次。应该是系统的原因，一加系统
