### ISSUE TITLE
新增模块支持：【绿色守护】

### ISSUE THREAD

**Issue by PianCat** [taichi-framework/TaiChi#452]
模块名字

绿色守护Greenify

模块用途

全局用后台管理

模块版本号

4.6.3

模块安装包

安装包：https://www.coolapk.com/apk/com.oasisfeng.greenify
源地址：None
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
模块引擎更新到 15 即可。
