### ISSUE TITLE
新增模块支持：【PerfectColorBar】

### ISSUE THREAD

**Issue by ghost** [taichi-framework/TaiChi#453]
# 模块名字
PerfectColorBar

# 模块用途
对状态栏，导航栏还有Toast进行美化

# 模块版本号
1.5.2/1.5.3

模块安装包
安装包：[PerfectColorBar V1.5.2 最后一版支持MIUI的](https://www.lanzous.com/i3cq9yj)
@weishu

**Comment by PianCat** [comment]
[PerfectColorBar V1.5.2 这个版本貌似比较稳定且支持MIUI](https://www.lanzous.com/i3cq9yj)

**Comment by tiann** [comment]
1. 太极主程序升级到 5.1.8.4 ： https://taichi.ctfile.com/fs/19604958-365754974
2. 模块适配引擎更新到 89

PS：仅测试过 9.0. 其他系统自行测试不保证可用且不会修复。
