### ISSUE TITLE
新增模块支持：【钉钉助手】

### ISSUE THREAD

**Issue by qqqm7** [taichi-framework/TaiChi#454]
## 模块名字
钉钉助手
## 模块用途
钉钉辅助模块，实现模拟位置，taichi.cool上的钉钉打卡为盗版，同一地点无法产生多个经纬度，请予以支持
## 模块版本号
v1.04
## 模块安装包
https://github.com/wuxiaosu/XposedRimetHelper/releases/download/v1.04/rimethelper-release-v1.04.apk
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
这两个安装包就是一摸一样的，文件的 sha256 都是一样的。
你之前提交过这个问题，我已经告诉你了。

**Comment by qqqm7** [comment]
大哥，这真不是一个东西啊，界面都完全不一样。。

**Comment by tiann** [comment]
不好意思我搞错了，这个模块我本地存的安装包跟你是一样的；但是实际上线上的安装包不一样，可能是我搞混了；抱歉。

适配引擎更新到 17 看一下

**Comment by qqqm7** [comment]
> 不好意思我搞错了，这个模块我本地存的安装包跟你是一样的；但是实际上线上的安装包不一样，可能是我搞混了；抱歉。
> 
> 适配引擎更新到 17 看一下

**Comment by qqqm7** [comment]
经测试，miui10 适配引擎17 安卓9.0 钉钉助手正常运行，谢老大

**Comment by qqqm7** [comment]
> 不好意思我搞错了，这个模块我本地存的安装包跟你是一样的；但是实际上线上的安装包不一样，可能是我搞混了；抱歉。
> 
> 适配引擎更新到 17 看一下

建议下架已上线版本，那个版本很坑人。。还收钱。。

**Comment by tiann** [comment]
好的，我下版本改掉，谢谢反馈！
