### ISSUE TITLE
太极阴创建部分加固应用闪退

### ISSUE THREAD

**Issue by neoblackxt** [taichi-framework/TaiChi#456]
## 什么问题

太极创建应用(有道词典)时发生闪退

## 详细情况

太极阴，创建网易有道词典 7.8.7，在提示请等待，可能需要较长时间...的几秒钟后，太极自身发生闪退

Magisk 版本：
太极 Magisk 模块版本：
太极APP版本：5.0.5
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：小米6
ROM版本：MIUI10.2.1.0

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

[logcat2.log](https://github.com/taichi-framework/TaiChi/files/2944267/logcat2.log)

大概在28183行附近

**Comment by tiann** [comment]
能否把你的这个版本的有道词典apk发上来？我从小米应用商店下载的，发现没有这个问题

**Comment by NeoBlackXT** [comment]
> 能否把你的这个版本的有道词典apk发上来？我从小米应用商店下载的，发现没有这个问题

酷安上下载的，超过10M，github不让上传。小米应用商店的，我刚刚试了也没问题。酷安的比小米应用商店的大了几兆。

**Comment by tiann** [comment]
好的，我试试

**Comment by tiann** [comment]
这个渠道的apk文件被加固了，加固的方式采用把指令与 dex 打包在一起；临时使用未加固的版本即可。

**Comment by Neboer** [comment]
我的版本是官网下载的7.8.9版本，可以正常创建但是打开后会闪退。

**Comment by wustwg** [comment]
> 这个渠道的apk文件被加固了，加固的方式采用把指令与 dex 打包在一起；临时使用未加固的版本即可。

太极不支持加固app吗？
