### ISSUE TITLE
新增模块支持：【FakeGApps】

### ISSUE THREAD

**Issue by 472714747** [taichi-framework/TaiChi#457]
## 模块名字
FakeGApps
## 模块用途
用于MicroG的签名伪装
## 模块版本号
2.0
## 模块安装包
安装包地址：https://dl-xda.xposed.info/modules/com.thermatk.android.xf.fakegapps_v3_bfc686.apk
源地址：https://repo.xposed.info/module/com.thermatk.android.xf.fakegapps

**Comment by tiann** [comment]
模块引擎更新到 17 看看是否正常

**Comment by 472714747** [comment]
激活之后无限重启。。。
