### ISSUE TITLE
新增模块支持：【TumblrAdAway】

### ISSUE THREAD

**Issue by 472714747** [taichi-framework/TaiChi#458]
## 模块名字
TumblrAdAway
## 模块用途
tumblr去广告
## 模块版本号
v1.8
## 模块安装包
https://github.com/apsun/TumblrAdAway/releases/download/v1.8/TumblrAdAway-1.8.apk

**Comment by tiann** [comment]
模块引擎更新到 17 看看是否可用

**Comment by 472714747** [comment]
没有效果，不过我并不确定是不是因为模块本身失效

**Comment by tiann** [comment]
这模块不更了，你需要装一年前的安装包。
