### ISSUE TITLE
用了太极以后网易云音乐无法设置下载目录和缓存。

### ISSUE THREAD

**Issue by caliban511** [taichi-framework/TaiChi#460]
太极5.0.5
网易云音乐PLAY3.4.1
这是很久以前就发现的老问题了，因为不影响平时听歌就没反馈。
昨天发现老版音量放大器不好用了，就换成新的，结果优化来重启去下载是还是时灵时不灵的，就把云音乐从PLAY3.4.1版升级成了国内的5.9.1版，结果还是一样。
于是又想换回干净无广告的PLAY版，发现无法覆盖降级安装，只好卸载了重装，然后之前手机TF卡上存的上万首歌全部消失，悔之晚矣。
现在只好重新下载，但是现在无法设置云音乐的下载位置，都会下载到默认的手机内部存储。这才磕磕绊绊的下了两千多首，存储就暴涨了几个G，而且以后刷机需要三清的时候也保不住的，到时候又要重新下载。
所以就想问下，能不能解决一下这个网易云音乐下载位置无法设置的问题？

**Comment by AceMONKEY519** [comment]
magiskhide加入网易云音乐就可以了
