### ISSUE TITLE
用了太极以后网易云音乐无法设置下载目录和缓存。

### ISSUE THREAD

**Issue by caliban511** [taichi-framework/TaiChi#461]
太极Magisk模块版本：所有版本
太极APP版本：所有版本
手机型号：小米Max3
ROM版本：miui10.2 安卓8.1
Xposed模块：音量放大器
Xposed模块版本：所有版本
APP及版本：网易云音乐PLAY版3.4.1 ， 国内版5.9.1

问题描述：
这是很久以前就发现的老问题了，因为不影响平时听歌就没反馈。
昨天发现老版音量放大器不好用了，就换成新的，结果优化来重启去下载是还是时灵时不灵的，就把云音乐从PLAY3.4.1版升级成了国内的5.9.1版，结果还是一样。
于是又想换回干净无广告的PLAY版，发现无法覆盖降级安装，只好卸载了重装，然后之前手机TF卡上存的上万首歌全部消失，悔之晚矣。
现在只好重新下载，但是现在无法设置云音乐的下载位置，都会下载到默认的手机内部存储。这才磕磕绊绊的下了两千多首，存储就暴涨了几个G，而且以后刷机需要三清的时候也保不住的，到时候又要重新下载。
所以就想问下，能不能解决一下这个网易云音乐下载位置无法设置的问题？

其他Magisk模块：

补充：

**Comment by tiann** [comment]
magisk hide 的问题吧？

**Comment by caliban511** [comment]
@tiann  感谢回复。magisk hide我没用，里面什么都没动，，，还是说，需要我做些什么？要怎么设置呢？

**Comment by tiann** [comment]
尝试把网易云音乐加入 magisk hide 看看

**Comment by caliban511** [comment]
@tiann 还真是，因为以前用XP时从没这个问题，印象中换上太极后才出现，所以一直以为是太极的锅。(o_ _)ﾉ
这下解决了，谢谢帮助。
