### ISSUE TITLE
新增模块支持：【应用管理】

### ISSUE THREAD

**Issue by ourforPP** [taichi-framework/TaiChi#462]
## 模块名字
应用管理
## 模块用途
限制应用自启、应用权限管理等，目前手机200多个应用全靠这个压着，不然开机后点都点不动
## 模块版本号
5.1.5
## 模块安装包
https://github.com/Tornaco/X-APM/releases/download/5.1.5/x-apm-app-release-aio.apk
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
#99

**Comment by ourforPP** [comment]
为什么直接给我关了

**Comment by ourforPP** [comment]
> #99

为啥给我关了,是不会支持么

**Comment by tiann** [comment]
重复

**Comment by ourforPP** [comment]
> 重复

OO  我去翻了一下，看到了，不好意思，之前没注意
