### ISSUE TITLE
坚果PRO2s5.0版本太极无限重启 ，老版本正常

### ISSUE THREAD

**Issue by zhuiyi220** [taichi-framework/TaiChi#463]
## 什么问题
坚果PRO2s5.0版本太极无限重启 ，老版本正常

## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：18.2
太极 Magisk 模块版本：太极阳
太极APP版本：taichi_5.0.1.apk
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：坚果PRO2s
ROM版本：8.1

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
magisk 模块版本号是多少？

**Comment by zhuiyi220** [comment]
> magisk 模块版本号是多少？

18.2

**Comment by zhuiyi220** [comment]
> magisk 模块版本号是多少？

不好意思 写错了  magisk-taichi-v4.7.4   坚果pro2s专版

**Comment by Blankeer** [comment]
咦，上次不是解决了吗？在 pro2s 交流群很多人都刷了正常的。

**Comment by zhuiyi220** [comment]
> 咦，上次不是解决了吗？在 pro2s 交流群很多人都刷了正常的。

上次的问题是刷magisk-taichi模块会卡logo ，这次的是安装最新版本的太极5.0 重启后无限重启

**Comment by Blankeer** [comment]
我升5.0试试看

**Comment by zhuiyi220** [comment]
> 我升5.0试试看

升级后 重启一下 就会出现这个问题

**Comment by PianCat** [comment]
貌似专版并不会被维护吧……

**Comment by zhuiyi220** [comment]
大佬还给解决吗。。。

**Comment by zhuiyi220** [comment]
> 我升5.0试试看

你试了吗 怎么样

**Comment by zhuiyi220** [comment]
SOS V6.6.6_TNT B3版本才会出现  非内测版不会

**Comment by tiann** [comment]
@zhuiyi220 能协助抓下日志吗？

**Comment by zhuiyi220** [comment]
> @zhuiyi220 能协助抓下日志吗？

不重启就不会出现这种情况  我直接升级的话 日志会出来这个报错信息吗

**Comment by zhuiyi220** [comment]
> @zhuiyi220 能协助抓下日志吗？

如果重启的话就进不去了。。。。

**Comment by Blankeer** [comment]
我这试了5.0.5，重启一切正常

**Comment by zhuiyi220** [comment]
> 我这试了5.0.5，重启一切正常

你是B3吗

**Comment by Blankeer** [comment]
B3是什么

**Comment by zhuiyi220** [comment]
> B3是什么

内测SOS V6.6.6_TNT B3

**Comment by Blankeer** [comment]
6.6.5.5.4 最新版

**Comment by zhuiyi220** [comment]
> 6.6.5.5.4 最新版

不是内测B3是没问题的

**Comment by Blankeer** [comment]
内测有个锤子功能？被 zjtd 收购后不敢升级系统

**Comment by DestinyHunter** [comment]
同样

**Comment by zhuiyi220** [comment]
> 同样

等新版本吧 6.6.6正式版出来再看吧‘

**Comment by DestinyHunter** [comment]
6.6.6 已推送

**Comment by zhuiyi220** [comment]
@@文件来自@DestinyHunter

apps.list:
com.eg.android.AlipayGphone
me.firesun.wechat.enhancement
com.qianbajin.sportaccelerator
com.tencent.mm
bin.xposed.Unblock163MusicClient
com.netease.cloudmusic

modules.list:
/data/app/me.firesun.wechat.enhancement-lnkhavSblU7ZruMni7TsKw==/base.apk
/data/app/bin.xposed.Unblock163MusicClient-814iHq-E0wue0iWtnDyNdA==/base.apk
/data/app/com.qianbajin.sportaccelerator-kkaZtlW5DrRxaZhLIuQ2JA==/base.apk

**Comment by zhuiyi220** [comment]
> 6.6.5.5.4 最新版

正式办你升级了吗

**Comment by Blankeer** [comment]
并没有收到 6.6.6 的系统更新推送

**Comment by DestinyHunter** [comment]
日志怎么获取

**Comment by zhuiyi220** [comment]
> 并没有收到 6.6.6 的系统更新推送

上次你是怎么给大佬提供日志的

**Comment by Blankeer** [comment]
> > 并没有收到 6.6.6 的系统更新推送
> 
> 上次你是怎么给大佬提供日志的

先刷 LogCat 面具模块，再刷 taichi ，开机，卡logo，进 adb，进 data/local/boot/ 提取日志

**Comment by DestinyHunter** [comment]
[boot-2019-03-14-15-46-03.log](https://github.com/taichi-framework/TaiChi/files/2965193/boot-2019-03-14-15-46-03.log)

**Comment by zhuiyi220** [comment]
[boot-2019-03-14-15-46-03.log](https://github.com/taichi-framework/TaiChi/files/2965199/boot-2019-03-14-15-46-03.log)

**Comment by Blankeer** [comment]
6.6.6 系统推送有公告吗？是否有分批推送？我这一直检查都没有

**Comment by zhuiyi220** [comment]
> 6.6.6 系统推送有公告吗？是否有分批推送？我这一直检查都没有

http://dl2.smartisan.com/ota/OCEAN/ocean/6.6.6_TNT/20190313/6.6.6_TNT-201903130004-user-oce-d3ab68cfa6.zip

**Comment by DestinyHunter** [comment]
抓的直链, 好像内侧的才给推.

**Comment by zhuiyi220** [comment]
没后续了吗。。。

**Comment by DestinyHunter** [comment]
TnT

**Comment by DestinyHunter** [comment]
最新的还是一样

**Comment by tanghengvip** [comment]
醉了...我现在都不敢重启

**Comment by zhuiyi220** [comment]
> 醉了...我现在都不敢重启

卸载5.0 装一个老版本就好了

**Comment by DestinyHunter** [comment]
老版本提示内核过期了..让更新..新版本不能用啊

**Comment by zhuiyi220** [comment]
大佬好像不准备管这个了😂😂

**Comment by DestinyHunter** [comment]
::😞😞😞😞😞😞😞😞

**Comment by tiann** [comment]
我没有这种机器，想管也没有办法。你们提供的日志基本看不出什么东西。

**Comment by zhuiyi220** [comment]
> 我没有这种机器，想管也没有办法。你们提供的日志基本看不出什么东西。

呃呃 那就很尴尬了  主要是我们也不知道怎么能提供给你有效的   @Blankeer   上次是他帮你的 这次要不也帮一下。。。

**Comment by tanghengvip** [comment]
> > 我没有这种机器，想管也没有办法。你们提供的日志基本看不出什么东西。
> 
> 呃呃 那就很尴尬了 主要是我们也不知道怎么能提供给你有效的 @Blankeer 上次是他帮你的 这次要不也帮一下。。。

你知不知道具体从哪个版本的太极开始出现这个问题的？开发者或许review一下那个版本相关的改动。

**Comment by zhuiyi220** [comment]
> > > 我没有这种机器，想管也没有办法。你们提供的日志基本看不出什么东西。
> > 
> > 
> > 呃呃 那就很尴尬了 主要是我们也不知道怎么能提供给你有效的 @Blankeer 上次是他帮你的 这次要不也帮一下。。。
> 
> 你知不知道具体从哪个版本的太极开始出现这个问题的？开发者或许review一下那个版本相关的改动。

就是从APK升级到太极钟开始。。。。

**Comment by zhuiyi220** [comment]
> 6.6.6 系统推送有公告吗？是否有分批推送？我这一直检查都没有

你升级6.6.6了吗   太极咋样了。。。

**Comment by Blankeer** [comment]
> > 6.6.6 系统推送有公告吗？是否有分批推送？我这一直检查都没有
> 
> 你升级 6.6.6 了吗 太极咋样了。。。

😩我并没有升级，等周末啥时候有空了升级下，抓点日志。。。

**Comment by DestinyHunter** [comment]
> > > 6.6.6 系统推送有公告吗？是否有分批推送？我这一直检查都没有
> > 
> > 
> > 你升级 6.6.6 了吗 太极咋样了。。。
> 
> 😩我并没有升级，等周末啥时候有空了升级下，抓点日志。。。
就等大老来弄好了

**Comment by DestinyHunter** [comment]
😩😩😩咩有消息了吗

**Comment by zhuiyi220** [comment]
> 😩😩😩咩有消息了吗

放弃吧。。。。

**Comment by tanghengvip** [comment]
瑟瑟发抖不敢关机...
![涂鸦_Screenshot_2019-04-02-10-30-05-336_设置.png](https://i.loli.net/2019/04/02/5ca2c99083dbe.png)

**Comment by zhuiyi220** [comment]
> 瑟瑟发抖不敢关机...
> ![涂鸦_Screenshot_2019-04-02-10-30-05-336_设置.png](https://camo.githubusercontent.com/f4e1894e6a9f3d972d3d68d1d305564484c4fe5b/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30342f30322f356361326339393038336462652e706e67)
直接@大佬啊

**Comment by DestinyHunter** [comment]
> > 瑟瑟发抖不敢关机...
> > ![涂鸦_Screenshot_2019-04-02-10-30-05-336_设置.png](https://camo.githubusercontent.com/f4e1894e6a9f3d972d3d68d1d305564484c4fe5b/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30342f30322f356361326339393038336462652e706e67)
> > 直接@大佬啊

我用钛备份备份太极..重启就先删了太极开机再还原😂

**Comment by zhuiyi220** [comment]
> > > 瑟瑟发抖不敢关机...
> > > ![涂鸦_Screenshot_2019-04-02-10-30-05-336_设置.png](https://camo.githubusercontent.com/f4e1894e6a9f3d972d3d68d1d305564484c4fe5b/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30342f30322f356361326339393038336462652e706e67)
> > > 直接@大佬啊
> 
> 我用钛备份备份太极..重启就先删了太极开机再还原😂
哎 实在不行 了解一下edxposed

**Comment by zhuiyi220** [comment]
> > > 并没有收到 6.6.6 的系统更新推送
> > 
> > 
> > 上次你是怎么给大佬提供日志的
> 
> 先刷 LogCat 面具模块，再刷 taichi ，�开机，卡logo，进 adb，进 data/local/boot/ 提取日志
哥们你现在刷了太极吗

**Comment by zhuiyi220** [comment]
继续关注 求解决 @tiann

**Comment by zhuiyi220** [comment]
凉了吗 。。。

**Comment by tanghengvip** [comment]
> 凉了吗 。。。

issue没关，还有希望。我坚持不关机！

**Comment by DestinyHunter** [comment]
> > 凉了吗 。。。
> 
> issue没关，还有希望。我坚持不关机！
然而 666.1 magisk 也凉了

**Comment by zhuiyi220** [comment]
> > > 凉了吗 。。。
> > 
> > 
> > issue没关，还有希望。我坚持不关机！
> > 然而 666.1 magisk 也凉了

上午我刚试过 是的 还是不行 所以。。。和系统版本无关  而是taichi.apk  东皇钟的问题

**Comment by DestinyHunter** [comment]
> > > > 凉了吗 。。。
> > > 
> > > 
> > > issue没关，还有希望。我坚持不关机！
> > > 然而 666.1 magisk 也凉了
> 
> 上午我刚试过 是的 还是不行 所以。。。和系统版本无关 而是taichi.apk 东皇钟的问题

你6.6.6.1 magisk 可以用????

**Comment by zhuiyi220** [comment]
> > > > > 凉了吗 。。。
> > > > 
> > > > 
> > > > issue没关，还有希望。我坚持不关机！
> > > > 然而 666.1 magisk 也凉了
> > 
> > 
> > 上午我刚试过 是的 还是不行 所以。。。和系统版本无关 而是taichi.apk 东皇钟的问题
> 
> 你6.6.6.1 magisk 可以用????

是的 可以的

**Comment by DestinyHunter** [comment]
> > > > > > 凉了吗 。。。
> > > > > 
> > > > > 
> > > > > issue没关，还有希望。我坚持不关机！
> > > > > 然而 666.1 magisk 也凉了
> > > 
> > > 
> > > 上午我刚试过 是的 还是不行 所以。。。和系统版本无关 而是taichi.apk 东皇钟的问题
> > 
> > 
> > 你6.6.6.1 magisk 可以用????
> 
> 是的 可以的
那个版本的 我刷magisk 也是卡锤子

**Comment by zhuiyi220** [comment]
彻底沉了。。。。

**Comment by zhuiyi220** [comment]
最新版还是卡logo,很奇怪 刷面具版模块没问题 ，安装了最新APK  再重启就会无限卡

**Comment by tiann** [comment]
[logcat_v13.2.zip](https://github.com/taichi-framework/TaiChi/files/3160146/logcat_v13.2.zip)
@zhuiyi220 shu刷一下这个日志模块，复现以下场景，然后把 /data/local/boot 下所有的日志文件发我看看

**Comment by zhuiyi220** [comment]
> [logcat_v13.2.zip](https://github.com/taichi-framework/TaiChi/files/3160146/logcat_v13.2.zip)
> @zhuiyi220 shu刷一下这个日志模块，复现以下场景，然后把 /data/local/boot 下所有的日志文件发我看看
[
[boot-2019-05-09-14-17-22.log](https://github.com/taichi-framework/TaiChi/files/3160659/boot-2019-05-09-14-17-22.log)
](url)

**Comment by tiann** [comment]
[5.1.13.apk.zip](https://github.com/taichi-framework/TaiChi/files/3165120/5.1.13.apk.zip)
应该已经修复了，谢谢 @zhuiyi220 这两天的配合。
