### ISSUE TITLE
新增模块支持：Mipushframework(小米系统级推送)

### ISSUE THREAD

**Issue by sjk8250** [taichi-framework/TaiChi#464]
## 模块名字
Mipushframework(小米系统级推送)
## 模块用途
用于伪装成小米手机，使应用注册小米推送。
## 模块版本号
0.3.6.20190128.b0fe719
## 模块安装包
https://github.com/MiPushFramework/MiPushFramework/releases/download/0.3.6.20190128.b0fe719/xmsf_service.apk
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by sjk8250** [comment]
这是国内技术大牛Trumeet的作品，能够使普通安卓手机上的App通过小米推送服务推送消息。但很多App会识别手机是否为小米系统，若不是就不会注册小米推送，本模块既是小米系统级推送的服务，也能通过Xposed将手机伪装成小米系统。如果太极阴能支持此模块，那创建的应用就会将手机识别为小米系统，从而注册小米推送。希望国内两位技术大佬的App能珠联璧合，为大伙创造神一样的技术体验！

**Comment by tiann** [comment]
@sjk8250 模块适配引擎更新到24试下能否正常使用？

**Comment by sjk8250** [comment]
感谢老大这么快就更新了。现在可以勾选，由于这个模块也需要创建为应用，创建后总是意外停止，。另外模块没有生效，创建的应用仍识别的是手机原来的信息。

**Comment by tiann** [comment]
https://github.com/MiPushFramework/MiPushFramework/blob/master/push/src/main/java/com/xiaomi/xposed/hook/MiPushEnhanceHook.java#L75

**Comment by tiann** [comment]
https://github.com/MiPushFramework/MiPushFramework/issues/263

**Comment by tiann** [comment]
@sjk8250 magisk 版应该已经可以正常使用了。非 magisk 版的话，目前可以用 Device Fake 修改设备为小米设备，具体修改点如下：

> ro.miui.ui.version.name=V9
ro.miui.ui.version.code=7
ro.miui.version.code_time=1527550858
ro.miui.internal.storage=/sdcard/
ro.product.manufacturer=Xiaomi
ro.product.brand=Xiaomi
ro.product.name=Xiaomi

**Comment by yanyumihuang** [comment]
但是，太极阴并不支持devices fake啊
   @@@![photo_2019-03-11_17-01-40](https://user-images.githubusercontent.com/26965886/54111655-5f984380-441f-11e9-8435-db4c95703275.jpg)
@tiann

**Comment by tiann** [comment]
我忘了这模块在 Android N以上有问题，5.0版本的时候给去了。

还是等等后续解决方案吧。

**Comment by sjk8250** [comment]
非常感谢大佬回复并专门到Mipush去发帖反应问题，后续如果Mipush 有更新我再来报告

**Comment by tiann** [comment]
[app-release.apk.zip](https://github.com/taichi-framework/TaiChi/files/3097857/app-release.apk.zip)
试下这个shi是否正常工作？

**Comment by sjk8250** [comment]
安装提示解析包错误，怎么破？

**Comment by pigxiang** [comment]
> 非常感谢大佬回复并专门到Mipush去发帖反应问题，后续如果Mipush 有更新我再来报告

熏弟，现在有新进展么？
