### ISSUE TITLE
希望支持一下Flyme助手

### ISSUE THREAD

**Issue by slmepipi** [taichi-framework/TaiChi#465]
## 模块名字
Flyme7助手

## 模块用途
Flyme系统屏蔽系统更新、魅族Pay等系统检测Root，Flyme主题和谐，跳过安装应用的安全检测等对Flyme系统非常友好。
## 模块版本号
3.2.1
## 模块安装包
com.coderstory.purify
链接：https://pan.baidu.com/s/1emYfnea-Y82x8ueLhB-WZg 提取码：efth ​​​​

**Comment by tiann** [comment]
#124

**Comment by tiann** [comment]
更新到 25

**Comment by slmepipi** [comment]
更新到什么25

**Comment by tiann** [comment]
模块管理-右上角菜单-更新适配引擎到

**Comment by slmepipi** [comment]
我现在是27更新不到25

**Comment by slmepipi** [comment]
好了我看到了，现在软件支持了

**Comment by slmepipi** [comment]
谢谢！
