### ISSUE TITLE
新增模块支持：可以钉钉模拟位置的【模拟位置 fake location】或者mock location

### ISSUE THREAD

**Issue by lbb3034** [taichi-framework/TaiChi#466]
## 模块名字
【模拟位置 fake location】或者mock location
## 模块用途
模拟位置
## 模块安装包

[com.rong.xposed.fakelocation.zip](https://github.com/taichi-framework/TaiChi/files/2948299/com.rong.xposed.fakelocation.zip)
或者
[mocklocation_v1_135e3b.zip](https://github.com/taichi-framework/TaiChi/files/2948302/mocklocation_v1_135e3b.zip)

(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
阳已经支持了，阴需要作者修改；但这模块已经不维护了，所以搞不了。
