### ISSUE TITLE
麻花助手  模块更新

### ISSUE THREAD

**Issue by Czy492** [taichi-framework/TaiChi#469]
模块名字

麻花助手

模块版本号
0.6.6   beta

模块更新了什么？
1支持com.amahua.ywofnbfd和com.amahua.ompimdrt两个包名；
2新增测试模块 ClearMarqueePlugin 清除底部滚动广告（测试功能，可能无效）；
3支持Edxposed框架Tai-Chi框架。
  
下载地址

https://github.com/1595901624/mhzs/releases

**Comment by tiann** [comment]
更新到25即可。另：请按照issue模版提交。
