### ISSUE TITLE
新增模块支持：音效增强器

### ISSUE THREAD

**Issue by TheRainight** [taichi-framework/TaiChi#470]
## 模块安装包 https://pan.baidu.com/s/1BbbJBKpYJxZM917q48UnZw

(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
无版权歌曲，是会员歌曲吗？测试了貌似没有用。QQ音乐版本 8.9.8.5

**Comment by TheRainight** [comment]
具体我也不是很清楚，在酷安太极评论区有人想提交我就帮忙提交了，这个软件的作者好像是开发edxposed的那个

**Comment by TheRainight** [comment]
@tiann 具体我也不是很清楚，在酷安太极评论区有人想提交我就帮忙提交了，这个软件的作者好像是开发edxposed的那个

**Comment by TheRainight** [comment]
@tiann 应该只有变灰的那种吧 比如unravel、逆态度这种吧

**Comment by TheRainight** [comment]
@tiann qq音乐8.9.1.4可以用

**Comment by tiann** [comment]
模块适配引擎更新到 29 即可。
已确认：无版权歌曲并非会员歌曲，本模块可以听无版权歌曲。
