### ISSUE TITLE
新增模块支持：【ROOTCLOAK】

### ISSUE THREAD

**Issue by jswxnxl** [taichi-framework/TaiChi#472]
## 模块名字 
Rootcolak
## 模块用途
防止程序root检测
## 模块版本号
3.0
## 模块安装包
链接: https://pan.baidu.com/s/1KZ5233KTSCJ_xfjzIqmgzg 提取码: krce 复制这段内容后打开百度网盘手机App，操作更方便哦
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
更新到 33 看看能否正常使用。
