### ISSUE TITLE
New module support: [Force immersive Mode]

### ISSUE THREAD

**Issue by zhidezh** [taichi-framework/TaiChi#475]
## Usage

APP强制全屏模式。

## Module version 
3.04

## APK file

http://www.mumayi.com/android-925577.html

**Comment by zhidezh** [comment]
喜欢全屏阅读模式，长期使用Force immersive Mode模块，希望能适配，谢谢！

**Comment by tiann** [comment]
请按照issue 模版提交，然后上传必要的安装包文件。你提供的这个链接已经不提供下载了。
