### ISSUE TITLE
新增模块支持：【模块名】gravitybox 重力工具箱 

### ISSUE THREAD

**Issue by AceMONKEY519** [taichi-framework/TaiChi#480]
## 模块名字
gravitybox
## 模块用途
        重力工具箱GravityBox是一款依赖Xposed框架支持的全能系统设置DIY工具。
支持：安卓4.4电池图标美化、状态栏图标美化、时间居中显示、支持数字电量、全局透明度开启、隐藏SIM卡提示和显示、增加高级电源菜单、修改快捷下拉栏、简单开启虚拟按键功能、自带按键救星功能、关机菜单加入截屏功能、旧式电视CRT关屏特效、恢复开发者选项、锁屏快速程序启动等等
        重力工具箱GravityBox是一款依赖Xposed框架支持的全能系统工具，支持修改ROM的部分系统级重要参数。
## 模块版本号
9.0.0-beta1
## 模块安装包
https://share.weiyun.com/5TNPFs4
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
模块配置引擎更新到 30 即可，可能会有部分功能不正常或者无法使用，属于正常情况；后续解决。

**Comment by AceMONKEY519** [comment]
好迅速，感谢大佬。

weishu <notifications@github.com> 于 2019年3月11日周一 20:40写道：

**Comment by AceMONKEY519** [comment]
激活不了，打开显示系统框架无反应，一直都这样。

MENKEY ASL <cjh519520@gmail.com> 于 2019年3月11日周一 20:41写道：

**Comment by tiann** [comment]
勾选-重启系统。
