### ISSUE TITLE
新增模块支持：重力工具箱Gravity Box [O]

### ISSUE THREAD

**Issue by yujincheng08** [taichi-framework/TaiChi#481]
## 模块名字
重力工具箱Gravity Box [O]
## 模块用途
重力工具箱GravityBox [O}是一款依赖Xposed框架支持的全能系统设置DIY工具。
支持：安卓4.4电池图标美化、状态栏图标美化、时间居中显示、支持数字电量、全局透明度开启、隐藏SIM卡提示和显示、增加高级电源菜单、修改快捷下拉栏、简单开启虚拟按键功能、自带按键救星功能、关机菜单加入截屏功能、旧式电视CRT关屏特效、恢复开发者选项、锁屏快速程序启动等等
重力工具箱GravityBox是一款依赖Xposed框架支持的全能系统工具，支持修改ROM的部分系统级重要参数。

## 模块版本号
8,5.2
## 模块安装包
[com.ceco.oreo.gravitybox.apk.zip](https://github.com/taichi-framework/TaiChi/files/2952905/com.ceco.oreo.gravitybox.apk.zip)

猛然发现支持Pie的重力工具箱了，因而请求支持支持Oreo的

**Comment by tiann** [comment]
更新到 33 即可，如果无法正常使用，也不会修复。
