### ISSUE TITLE
新增模块支持：Xglyph²

### ISSUE THREAD

**Issue by coolmint12** [taichi-framework/TaiChi#483]
## 模块名字
Xglyph²
## 模块用途
一款名为Ingress的现实增强游戏的辅助工具
## 模块版本号
1.8.1
## 模块安装包
https://forum.xda-developers.com/xposed/modules/mod-xglyph-ingress-glyph-game-mods-t3455025
https://repo.xposed.info/module/com.cypher.xglyph2
https://github.com/Cypher01/Xglyph2

**Comment by tiann** [comment]
更新到 33 看看能否正常使用。
