### ISSUE TITLE
新增模块支持：【Force immersive Mode】

### ISSUE THREAD

**Issue by zhidezh** [taichi-framework/TaiChi#484]
## 模块安装包
[com.hamzahrmalik.immersiveforcer-3.0.4-13.zip](https://github.com/taichi-framework/TaiChi/files/2955795/com.hamzahrmalik.immersiveforcer-3.0.4-13.zip)

(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
更新到 33 看看能否正常使用。

**Comment by zhidezh** [comment]
完美支持，万分感谢！！！！！！！！
