### ISSUE TITLE
Bug report: 我在taichi下载的模块，成功卡住小米手机！！系统彻底崩溃

### ISSUE THREAD

**Issue by hellmeangod** [taichi-framework/TaiChi#491]
**Describe the bug**
我在这里下载的https://github.com/taichi-framework/TaiChi-Guide/wiki/Modules “模拟位置”
我高度怀疑“模拟位置” 勾选模块后运行软件，他提示我要我重启手机以后再使用本软件，我照它提示重启手机，结果我的手机再次卡米，手机系统在开机界面一直加载中无法运行！第二次系统崩溃！第一次是用的太极，第二次用的edxposed。
PS：如果不是“模拟位置” 那肯定就是"device faker"惹的祸！
**To Reproduce**

**Expected behavior**
不要卡机！！！

**Smartphone (please complete the following information):**
Magisk version：16.8
TaiChi-Magisk module version：
TaiChi version：
Which Xposed modules are enabled ?：
Xposed modules version：
Which Magisk modules are enabled ?：
Magisk modules version：
Device ：
ROM：

**Additional context**

**Comment by tiann** [comment]
**please complete the following information**

你什么都不告诉我，我怎么帮你解决问题？

**Comment by hellmeangod** [comment]
那个你需要什么信息呢？我用的最新版的taichi，软件是在你的网站下的，MIUI10，手机小米6X。
还有一个卡米的原因可能是：运动模拟器、运动修改器、运动加速器3个软件同时装了。
我认为这不是taichi的问题，因为我用edxposed出现同样的现象。我现在终于知道怎么暂时从卡米回复而不要重装手机系统的方法，我现在暂时用edxposed，因为edxposed有一个uninstall edxposed卡刷包，我每次一装这个卡刷包，让edxposed失效，手机就可以暂时启动了，我再吧卡手机的软件卸载，就恢复了，但是taichi暂时没看到uninstall taichi卡刷包，可能是taichi不需要卡刷模块的原因吧

**Comment by tiann** [comment]
直接卡刷太极的 magisk 模块，模块就卸载了。
