### ISSUE TITLE
Bug report: Taichi Magisk Doesn't work

### ISSUE THREAD

**Issue by nemui3353** [taichi-framework/TaiChi#493]
**Describe the bug**

Taichi Magisk doesn't work with any Xposed modules.
Xposed modules can't detect taichi magisk as Xposed framework.
For example, Greenify keep saying that you should
install Xposed Framework though it's activated in taichi app

**To Reproduce**

**Expected behavior**

Every modulee should detect taichi magisk as xposed framework..

**Smartphone (please complete the following information):**
Magisk version：18.2-51110866(canary build)
TaiChi-Magisk module version：4.7.6
TaiChi version：5.0.5-33
Which Xposed modules are enabled ?：Greenify
Xposed modules version：4.6.3
Which Magisk modules are enabled ?：
Magisk modules version：
Device ：Galaxy S9+
ROM：Stock

**Additional context**

**Comment by tiann** [comment]
@nemui3353 Could you please test this version of Greenify? https://www.lanzous.com/i3et9wh

And follow these steps:
1. install the specific version.
2. re-check Greenify in Module Manage of TaiChi.
3. reboot the system.

**Comment by nemui3353** [comment]
@tiann Oh It's working!!
