### ISSUE TITLE
新增模块支持：【GetVideo_1.3】

### ISSUE THREAD

**Issue by jueerye** [taichi-framework/TaiChi#496]
## 模块名字 
GetVideo_1.3

## 模块用途 
用于抓取M3U8链接也可以抓取优酷 爱奇艺 腾讯的COOKIE

## 模块版本号 
1.3 好像这个不更新了·但是我也不知道这个是从哪出的

## 模块安装包

http://t.cn/EMj0UP1

**Comment by Cowboy-Shuai** [comment]
希望能支持这个模块😊
