### ISSUE TITLE
新增模块支持：Xposed edge Pro v5.3

### ISSUE THREAD

**Issue by nekoprpr** [taichi-framework/TaiChi#498]
## 模块安装包 https://github.com/taichi-framework/TaiChi/issues/309 我看之前好像已经适配过了 我安装后可以选中该模块 但是打开后提示没有激活 重启也没有效果
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by caliban511** [comment]
我这里升级到MIUI10，安卓9之后，也出现了同样的问题，无论怎样清数据、重装、重启，都没用。同样是PRO版5.3。

**Comment by ousui** [comment]
用了 @caliban511  的方法还是不行， 一加5 安卓9 ……

**Comment by thisismuffin** [comment]
我也是使用付費5.3版，taichi中可以勾選，可是進入xposed edge pro會顯示沒有激活。從tai chi裡下載5.2.3的免費版本可以使用，但升級成5.3免費版後又無法使用。
@caliban511不知道可不可以提供詳細的解決方法呢？ 我把taichi magisk模塊刪除重裝後還是沒有用

**Comment by caliban511** [comment]
@thisismuffin 上面不是说了吗，卸载太极APP，删掉太极的面具模块，重启手机后一切重来。我是这样弄好的，纯属瞎猫碰到死耗子，原理什么的完全不懂。

**Comment by thisismuffin** [comment]
@caliban511 謝謝分享，不過還是不行，等作者修復囉

**Comment by tiann** [comment]
**请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！**

**Comment by thisismuffin** [comment]
@tiann 
https://nofile.io/f/yoBt9h9Hoa1/base.apk
補個xposed edge 5.3免費版
我測試跟付費版5.3一樣的情況
taichi內可勾選，重開後進入app還是會顯示沒有安裝xposed

**Comment by nekoprpr** [comment]
@tiann 
链接: https://pan.baidu.com/s/1FHI0fQiqlpnm6-cpoUL_QA 提取码: 312p 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by tiann** [comment]
模块没问题。
开启magisk 模式后 - 勾选模块 - 重启手机 即可。

**Comment by ousui** [comment]
@tiann  应用添加哪些？ 我这里添加了： 系统界面、一加桌面、Android 系统。
重启无数次了，还是不行。
是否有地方可以查日志？

**Comment by nekoprpr** [comment]
@tiann 
可以勾选模块 但是打开模块后无法开启功能
看起来也并不是我个人出现这问题...
需要添加某些系统应用在里面吗?

**Comment by zc1248856165** [comment]
> 模块没问题。
> 开启magisk 模式后 - 勾选模块 - 重启手机 即可。

太极阴无法支持xposed edge么

**Comment by zc1248856165** [comment]
> @tiann
> 可以勾选模块 但是打开模块后无法开启功能
> 看起来也并不是我个人出现这问题...
> 需要添加某些系统应用在里面吗?

你们都是太极magisk的么

**Comment by ousui** [comment]
> > @tiann
> > 可以勾选模块 但是打开模块后无法开启功能
> > 看起来也并不是我个人出现这问题...
> > 需要添加某些系统应用在里面吗?
> 
> 你们都是太极magisk的么

我是。，
