### ISSUE TITLE
新增模块支持：【小米净化】

### ISSUE THREAD

**Issue by YazawaNiko7** [taichi-framework/TaiChi#499]
## 模块名字
小米净化
## 模块用途
修复核心破解兼容android pie
修复隐藏应用名称支持隐藏文件夹名称
## 模块版本号
2.1.6
## 模块安装包
链接：https://pan.baidu.com/s/1J-8Fa-fQ51_OZlESWYtIFQ 提取码：2lhv
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
fixed in 40
