### ISSUE TITLE
BUG：太极阳添加应用界面不显示已经添加的程序（对应的程序没有打勾）

### ISSUE THREAD

**Issue by Cyclonekid** [taichi-framework/TaiChi#502]
## 什么问题
太极阳添加应用界面不显示已经添加的程序（对应的程序没有打勾）

（请简要说明你遇到的问题）

## 详细情况
       不知道从哪个版本开始  太极阳添加程序界面所有程序都没有选中了，（添加过的应用后面也没有对勾，但在太极的主界面显示正常）

![image](https://user-images.githubusercontent.com/17697818/54338394-bf375e80-466c-11e9-8351-d4d87aced50e.png)

![image](https://user-images.githubusercontent.com/17697818/54338403-c3fc1280-466c-11e9-85db-7bbb5e309e09.png)

安装的插件
![image](https://user-images.githubusercontent.com/17697818/54338410-c9595d00-466c-11e9-945f-1cbf66bfc7db.png)

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：18.1
太极 Magisk 模块版本：4.7.6
太极APP版本：东皇钟5.05-35
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：MI6
ROM版本：MIUI 10 9.3.7

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。
modules.lst

/data/app/ma.wanam.youtubeadaway-CQM02Ur0BOQcrVehiA-w1A==/base.apk
/data/app/com.ext.star.wars.vxp-fpRqkKvml76-Ze1SMYZtXQ==/base.apk
/data/app/com.chen.firstxposed-H9ezPyCwUyzGXXWiWIsjUw==/base.apk
/data/app/com.pyler.youtubebackgroundplayback-uFLDSuJ2Av-EdItvw9A6dg==/base.apk
/data/app/com.blanke.awemexposed-1P5Zt-Zs4vHzC4i4K5aHnA==/base.apk
/data/app/lantian.nolitter-f5Oj7vX2T8-FLNF9lL9ufA==/base.apk
/data/app/com.fkzhang.wechatxposed-fsYUb1td9ZBC70sQzf3aJw==/base.apk
/data/app/com.jy.taofanfan-KJ0eWZLsgYqMkHX47sfaaw==/base.apk
/data/app/com.click369.controlbp-xxbDwN2gtwJ18dSURrgRAA==/base.apk
/data/app/com.github.tianma8023.xposed.smscode-44RouTHmF6Kpavzjj_D8sg==/base.apk
/data/app/chili.xposed.chimi-JrrmBlpZyhFjE6odKOU2JA==/base.apk
/data/app/com.devadvance.rootcloak2-TTQez4E9-usPyrt-5gcAUg==/base.apk
/data/app/me.zjns.lovecloudmusic-wOw0FuCszc5XHIOnDBTUAg==/base.apk
/data/app/com.qianbajin.sportaccelerator-0s2h9iL10cJhiaeycd_SdA==/base.apk
/data/app/me.weishu.corepatch-a9YEEFMd19-FoZKVeShzfg==/base.apk

apps.list

com.pyler.youtubebackgroundplayback
com.eg.android.AlipayGphone
com.tencent.mm
com.netease.newsreader.activity
com.click369.controlbp
com.miui.packageinstaller
com.miui.home
com.fkzhang.wechatxposed
com.android.systemui
com.taobao.taobao
chili.xposed.chimi
com.netease.cloudmusic
com.blanke.awemexposed
com.github.tianma8023.xposed.smscode
com.miui.securitycenter
me.zjns.lovecloudmusic
lantian.nolitter
com.chen.firstxposed
com.devadvance.rootcloak2
com.cib.cibmb
com.jy.taofanfan
me.weishu.corepatch
com.android.providers.downloads.ui
com.android.thememanager
com.ext.star.wars.vxp
com.qianbajin.sportaccelerator
com.icbc.im
com.android.settings
com.google.android.youtube
com.jingdong.app.mall
ma.wanam.youtubeadaway

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
这是 bug 吗？
