### ISSUE TITLE
一加3 太极Magisk4.7.6 卡在锁屏页面,无限重启系统界面,且无法解锁

### ISSUE THREAD

**Issue by ml863606** [taichi-framework/TaiChi#503]
## 什么问题

一加3 太极Magisk4.7.6 卡在锁屏页面,无限重启系统界面,且无法解锁

## 详细情况

安装太极Magisk4.7.6版本后,重启手机卡在锁屏界面,无法解锁,且手机会过个10s左右,自动重启系统界面

Magisk 版本：
太极 Magisk 模块版本：4.7.6
太极APP版本：5.0.5
开启的 Xposed 模块：YouTube AdAway,假装分享Xposed,LuckyHooker,音量增强器,音效增强器,要你命3000,云村清洁工,AD快消,网易云音乐插件
Xposed模块版本：
开启的其他 Magisk 模块：Enable Doze for GMS Magisk Module(v6),  VIPER4Android FX(v2.7.0.0) ,Wifi Bondding(1.9)
其他 Magisk 模块版本：（无）
手机型号：OnePlus3
ROM版本：RR 9.0(20180309)

## 配置文件

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by ml863606** [comment]
[Modules-apps.zip](https://github.com/taichi-framework/TaiChi/files/2966052/Modules-apps.zip)

**Comment by tiann** [comment]
在 recovery 里面执行 `rm -rf /data/system/taichi` 或者直接删除 `/data/system/taichi` 目录

**Comment by ml863606** [comment]
可以了,谢谢!
