### ISSUE TITLE
新增模块支持：【设备ID更改器】

### ISSUE THREAD

**Issue by luoliwa** [taichi-framework/TaiChi#508]
## 模块名字
设备ID更改器
## 模块用途
模拟设备ID
## 模块版本号
1.5.3
## 模块安装包
https://www.coolapk.com/apk/com.phoneinfo.changerpro
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by pharmavan** [comment]
帮顶起来，我也需要这个模块，求伟叔支持

**Comment by 06ji** [comment]
这个 和 应用变量哪个强

**Comment by pharmavan** [comment]
> 这个 和 应用变量哪个强

各有优劣，虽然应用变量功能更多些，但这个更简洁稳定些，个别时候只需要这个简单功能就可以了，主要是稳定。

**Comment by pharmavan** [comment]
@tiann 求支持【设备ID更改器】

**Comment by tiann** [comment]
84

**Comment by tiann** [comment]
magisk only

**Comment by pharmavan** [comment]
> magisk only

大佬好，就是太极不能支持吗？

**Comment by tiann** [comment]
只有 magisk 版可以用。

**Comment by pharmavan** [comment]
> 只有 magisk 版可以用。

@tiann 是用的面具版本太极，但是模块管理里边显示“暂不支持”，不能勾选。面具模块是4.8，太极版本是5.1.1-83

**Comment by tiann** [comment]
更新到 84

**Comment by pharmavan** [comment]
> 更新到 84

@tiann 可以勾选了，感谢大佬。
