### ISSUE TITLE
Bug report: Can't create system apps

### ISSUE THREAD

**Issue by exodius48** [taichi-framework/TaiChi#509]
**Describe the bug**
System apps does not show on TaiChi

**To Reproduce**
1. Go to 'Taichi'
2. Click on 'Create app'
3. Scroll down to ' all apps '
4. See error , no system apps shown.

**Expected behavior**
Youtube is pre installed app on my device, taichi can't detect it

**Smartphone (please complete the following information):**
Magisk version：Non root/Don't use magisk
TaiChi-Magisk module version：Non root/Don't use magisk
TaiChi version：5.0.5-39
Which Xposed modules are enabled ?：Xinsta & Youtube AdAway 
Xposed modules version：Xinsta 2.1.0 & Youtube Adaway 4.3.3
Which Magisk modules are enabled ?：Non root/Don't use magisk
Magisk modules version：Non root/Don't use magisk
Device ：Xiaomi Poco F1
ROM：Global ROM 10.2.3.0 (MIUI 10 Android 9)

**Additional context**
Only user app that detect on taichi

**Comment by tiann** [comment]
Can YouTube  be uninstalled ? If so, i will make it possible.

**Comment by Droidiat** [comment]
you can remove any system app using this adb command 
pm uninstall -k --user 0 [ package name ]

**Comment by tiann** [comment]
@Droidiat Many Roms in China has many build-in APPs, this apps can not be installed :(  So i just don't show System Apps in `Select App List`.

I will find a better way to deal with it.

**Comment by exodius48** [comment]
@tiann YouTube in global rom can't be uninstalled completely, i can only uninstall update of it. Most of preinstalled apps installed as system apps not user apps, especially apps from google, like chrome, youtube, google photos, google drive, etc.
I already tried to uninstall update of youtube, reboot device, then still not shown on TaiChi.

@Droidiat If i uninstall system app, i can't install update (OTA), because system app has been tempered or modified.

**Comment by tiann** [comment]
@exodius48 non-root mode of TaiChi must uninstall the original app first becuase it changes the signature of APK, if the app cann't be uninstalled, it means that the APP can not run in non-root mode if TaiChi :(

**Comment by Droidiat** [comment]
> 

> 
> @Droidiat If i uninstall system app, i can't install update (OTA), because system app has been tempered or modified.

Who told you that ? I already used that way several times with 2 phones to remove bloatware & still receive/install OTA updates without any issue.

**Comment by exodius48** [comment]
@tiann Nah..that is the issue, taichi non root mode will replace original app with modified app, if i can create Youtube, then install over pre-installed youtube, it won't be installed because different signature,, hmm.. i confused now.. :(

@Droidiat Are you using xiaomi phones? If so, read here http://en.miui.com/thread-121168-1-1.html
i'm using xiaomi phone since 2014 (from MIUI 5), and can't install ota if i uninstalled app, if i uninstall app, system will download full rom (size amount ~ 1.5 GB - 2.0 GB, depend on your phone), and after install full rom, system app that i've removed will installed back. And who want download full rom almost 2 GB size? I have limited internet quota, so i prefer OTA instead full rom. Size of OTA usually smaller than full rom, about 500 MB.

**Comment by Droidiat** [comment]
> @Droidiat Are you using xiaomi phones? If so, read here http://en.miui.com/thread-121168-1-1.html
> i'm using xiaomi phone since 2014 (from MIUI 5), and can't install ota if i uninstalled app, if i uninstall app, system will download full rom (size amount ~ 1.5 GB - 2.0 GB, depend on your phone), and after install full rom, system app that i've removed will installed back. And who want download full rom almost 2 GB size? I have limited internet quota, so i prefer OTA instead full rom. Size of OTA usually smaller than full rom, about 500 MB or less.

Yes , currently I'm using Xiaomi Mi mix 2 , I removed bloatware & still receive small OTA update ( Dev 
 versions ) , last one was yesterday.

I'm new to Xiaomi world but I'm using this device since it available in the market & I never had update issues with this method I'm sure , I also tested it on google devices without any problem.

**Comment by exodius48** [comment]
@Droidiat Dev rom is once per week receive update, as i write above, i don't use it. I prefer stable rom to save my internet quota. 
Ok, i've uninstalled youtube using adb, see it still receive small OTA or Full rom. 
![2019-03-17_133730](https://user-images.githubusercontent.com/9832875/54486356-da4ade00-48b9-11e9-8e22-a3a0003a8cb9.png)

**Comment by exodius48** [comment]
@Droidiat Nah... i've uninstalled youtube using that command, but tai chi still can't detect youtube, coz youtube still present on /system/app
![Screenshot_2019-03-17-13-40-32-793_com mixplorer](https://user-images.githubusercontent.com/9832875/54486415-74ab2180-48ba-11e9-8123-a00056a6fe27.png)

**Comment by exodius48** [comment]
@tiann If this issue can't be resolved, you can close this issue. No problem for me, i just need to use module that modified user app, not system app since my phone non-root. 

Cheers

**Comment by tanghengvip** [comment]
@exodius48 I think TaiChi magisk mode can solve all ur puzzles. just forget about the OTA and flash the magisk in.
