### ISSUE TITLE
新增模块支持：【XPrivacyLua Pro】

### ISSUE THREAD

**Issue by hkfires** [taichi-framework/TaiChi#512]
## 模块名字
XPrivacyLua Pro
## 模块用途
可以在XPrivacyLua的基础上进行选项或hook自定义
## 模块版本号
0.73
## 模块安装包
https://play.google.com/store/apps/details?id=eu.faircode.xlua.pro

**Comment by tiann** [comment]
Could you upload the module apk to github? it is inconveniently, discommodiously for me to access Google Play.y

**Comment by hkfires** [comment]
> Could you upload the module apk to github? it is inconveniently, discommodiously for me to access Google Play.y

不用google play的话，在作者的官网也能够下载到，链接如下：https://lua.xprivacy.eu/latest/
如果要看模块更多信息的话，可以在xda看，链接如下：https://forum.xda-developers.com/general/paid-software/xprivacylua-pro-companion-app-t3743040

**Comment by tiann** [comment]
太极里面可运行的 XPrivacyLua实际上是我修改过的，原作者的版本只检测 Xposed 环境。他似乎也不愿意针对其他环境作修改，所以针对 PRO 版本我这边干不了什么。

**Comment by guorenxi** [comment]
> 太极里面可运行的 XPrivacyLua实际上是我修改过的，原作者的版本只检测 Xposed 环境。他似乎也不愿意针对其他环境作修改，所以针对 PRO 版本我这边干不了什么。

XPrivacyLua Pro+1，请问能否分享mod的方法？

**Comment by tofuliang** [comment]
> 太极里面可运行的 XPrivacyLua实际上是我修改过的，原作者的版本只检测 Xposed 环境。他似乎也不愿意针对其他环境作修改，所以针对 PRO 版本我这边干不了什么。

求更新一下能在太极内使用的XprivacyLua
