### ISSUE TITLE
New module support: [X Messenger Privacy]

### ISSUE THREAD

**Issue by Cecil107** [taichi-framework/TaiChi#514]
Module name
X Messenger Privacy

Usage
Block "typing" (3 dots) indication
Hide like (thumbs up) button in conversations to prevent accidental presses
Hide like (thumbs up) button in expanded notifications
Hide "Invite to Messenger" banner & button in conversations with people not using Messenger
Hide "Wave" button in "Active" tab to prevent accidental presses
Block message "seen" indication from appearing to others (premium version)
Click twice on a message in a thread, to manually mark it seen (premium version)
Hide your chat status completely (also hide online minutes) (premium version)
Facebook app stealth mode: Hide online status when using Facebook app (for Android prior to 5.0, use a Facebook app version <100 or >=103) (premium version)
See who's online, while appearing offline by using the two above features (premium version)
Hide audio & video call buttons in conversations, to prevent accidental presses (premium version)
Hide call status, by completely disabling VoIP (premium version)
Features video: https://www.youtube.com/watch?v=OcCIG6O6_Tc

Module version
2.7.8

APK file
hhttps://repo.xposed.info/module/com.john.xmessengerprivacy

**Comment by tomissmart86520** [comment]
update to 2.9.0 final
download link: https://dl-xda.xposed.info/modules/com.john.xmessengerprivacy_v110_8ff3ea.apk
@tiann
