### ISSUE TITLE
模块更新支持：【应用控制器】-【3.1.5】

### ISSUE THREAD

**Issue by luoliwa** [taichi-framework/TaiChi#515]
## 模块名字
应用控制器
## 模块版本号
3.1.5
## 模块更新了什么？
3.1.5
1.修复还原应用锁波纹颜色无效问题。
2.修复部分机型应用锁验证后无法自动打开应用的bug。
3.修复部分机型定时器无法显示的bug。
4.修改进入暂停状态的应用颜色为红色。
5.界面控制中新增自定义应用锁波纹动画颜色功能。
## 模块安装包
https://www.coolapk.com/apk/com.click369.controlbp

**Comment by tiann** [comment]
#272
