### ISSUE TITLE
新增模块支持：【小熊跑步】

### ISSUE THREAD

**Issue by dfr3500** [taichi-framework/TaiChi#518]
模块名字
小熊跑步

模块用途
跑步手机模拟软件，悦动圈等跑步软件皆可模拟里程，也可模拟步数，修改支付宝步数。

模块版本号
1.5.0

模块安装包
https://www.coolapk.com/apk/com.anjoyo.xyl.run

**Comment by dfr3500** [comment]
模块用途
跑步手机模拟软件，悦动圈等跑步软件皆可模拟里程，也可模拟步数，修改支付宝步数。

**Comment by tiann** [comment]
82
