### ISSUE TITLE
新增模块支持：【Line Hack】

### ISSUE THREAD

**Issue by tomissmart86520** [taichi-framework/TaiChi#521]
## 模块安装包 https://my.pcloud.com/publink/show?code=XZTmYq7ZXY9bXknf3ERVgXPuAdxysBC085fV

(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by vmpvup** [comment]
希望能支持这个模组，LINE用户搭配这个很方便

**Comment by mingoyo** [comment]
貌似無法成功執行
