### ISSUE TITLE
新增模块支持：Undo - 撤消

### ISSUE THREAD

**Issue by 06ji** [taichi-framework/TaiChi#522]
## 模块名字
Undo - 撤消
## 模块用途
利用Xposed框架，为你的输入框增加撤销（Ctrl-Z）选项。
## 模块版本号
1.0.4
## 模块安装包
https://www.coolapk.com/apk/top.imlk.undo
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by caliban511** [comment]
EDGE有撤销和重做功能

**Comment by 06ji** [comment]
> EDGE有撤销和重做功能

这个怎么找不到下载

**Comment by caliban511** [comment]
就是边缘手势拓展模块

**Comment by tiann** [comment]
87
