### ISSUE TITLE
faccessat 劫持得不好

### ISSUE THREAD

**Issue by liudongmiao** [taichi-framework/TaiChi#523]
android 6 起，faccessat 和直接系统调用不太相同，加了些判断。

当然，也不会有用户去检测这个。再说，用户也可以直接 syscall __NR_openat 来读文件是吧...

如果把 syscall 也给劫持了...目前鄙人项目，可以检测简单的 inline hook，支持 hookzz, whale 以及 cydia substrate (太极可能使用这个？)

**Comment by addhaloka** [comment]
kernel hook你检测个毛线
