### ISSUE TITLE
新增模块支持：【Mock Mock Locations】

### ISSUE THREAD

**Issue by mickychenchen** [taichi-framework/TaiChi#526]
## 模块名字
Mock Mock Locations
## 模块用途
Some apps won't let you use them if "Allow mock locations" is turned on, even if you aren't mocking your location.
This helps prevent apps from detecting that "Allow mock locations" is turned on.
## 模块版本号
1.4
## 模块安装包
https://repo.xposed.info/module/com.brandonnalls.mockmocklocations
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
Does it works well now?

**Comment by mickychenchen** [comment]
> Does it works well now?

測試成功 非常感謝!
