### ISSUE TITLE
BUG：绿色守护无法开启XP特性

### ISSUE THREAD

**Issue by caliban511** [taichi-framework/TaiChi#528]
## 什么问题

绿色守护无法开启XP特性。。。
我用的是PLAY收费版，从来都没有开启成功过，太极是不是只支持免费版的？
换了太极里面提供的模块下载安装，也无法开启。
加入列表、优化、取消优化、取消再勾选、清数据、卸载、重启、重装，，，都试过了……
之前一直没有试过三清重刷系统，前两天升级安卓P，三清了一次，再装还是这样，就上来反馈一下。

## 详细情况

绿色守护无法开启XP特性

Magisk 版本：1.8.1
太极 Magisk 模块版本：4.7
太极APP版本：5.10
开启的 Xposed 模块：绿色守护
Xposed模块版本：4.5.1 收费版
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：小米MAX3
ROM版本：MIUI10.2.1 安卓P

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
建议使用 4.6.3

**Comment by caliban511** [comment]
感谢回复 绿色守护升级到4.6.3，太极升级到5.1.1， 在模块管理中点掉再选中，重启后问题依旧。

**Comment by tiann** [comment]
安装包上传下？

**Comment by caliban511** [comment]
@tiann
这个是收费版的解锁应用，主程序现在用的就是模块下载里的版本，就不重复上传了。
链接:https://pan.baidu.com/s/19sIpJrDsnYRoXZnHKFrANg 提取码:0u09

**Comment by caliban511** [comment]
更新到5.1.3和4.8.0，问题依旧。

**Comment by penuser** [comment]
这边报相同bug
机型红米4，系统MIUI10正式版
Magisk+太极阳，绿色守护是太极ctfile下载的4.6.3

尝试打开绿色守护的XP功能时提示请安装XP框架。

**Comment by tiann** [comment]
@penuser 是否使用了 deodex 之类的功能？是否尝试过卸载绿色守护，禁用magisk绿色守护之后重新安装？

**Comment by penuser** [comment]
> @penuser 是否使用了 deodex 之类的功能？是否尝试过卸载绿色守护，禁用magisk绿色守护之后重新安装？

感谢回复
1 很抱歉我不知道deodex是什么东西……
2 先前有绿色守护4.5.1，尝试卸载绿色守护重装，重装过两次，第二次确认卸载干净（卸载apk，确认模块从列表中消失）后重启再重装，但是没有效果。
3 在此期间，Magisk的绿色守护模块一直处于禁用状态。（事实上如果保持模块开启，无法通过常规方法卸载绿色守护）
4 也尝试过先安装绿色守护后第一次也不打开，先确认模块激活，重启后再进入，依然提示xposed未安装。

**Comment by penuser** [comment]
@tiann 
同样一台设备在更新太极阳5.32之后问题解决。
1. 更新Xposed插件4.96后未解决
2. 更新太极5.30后未解决（回滚至5.20）
3. 解决方案简述如下：
卸载面具中的绿色守护模块，卸载后绿色守护APK消失。随后将太极阳从5.20升级至5.32。重启。
重启后先打开太极并打开所有的“保持存活”相关功能，miui同时打开自启动和锁后台。
接下来安装绿色守护apk（太极提供版），安装好后在太极阳模块中勾选apk模块。
最后再重启一次，重启后检查Xposed模式是否可以工作。

推测和自启动/锁后台相关。但是懒得做加减法了。赞美太极阳。
