### ISSUE TITLE
新增模块支持：【钉钉助手(自动抢红包版)】

### ISSUE THREAD

**Issue by sky-wei** [taichi-framework/TaiChi#531]
## 模块名字
钉钉助手(自动抢红包版)

## 模块用途
钉钉自动抢红包与消息防撤回功能

## 模块版本号
v1.1.0版本

## 模块安装包
https://dl-xda.xposed.info/modules/com.sky.xposed.rimet_v2_486e1b.apk

## 项目源地址
https://github.com/sky-wei/xposed-rimet

**Comment by laihu** [comment]
请支持

**Comment by tiann** [comment]
55
