### ISSUE TITLE
新增模块支持：【XP快译】

### ISSUE THREAD

**Issue by whyope333** [taichi-framework/TaiChi#533]
## 模块名字
 XP快译

## 模块用途 
翻译软件，无需后台自动翻译剪切板内容并以悬浮窗的形式显示出来，长按可复制

## 模块版本号
3.0.6

## 模块安装包
https://www.lanzous.com/i3i9g4f

(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
#308
