### ISSUE TITLE
JustTrustMe不生效

### ISSUE THREAD

**Issue by Alvinnfly** [taichi-framework/TaiChi#538]
## 什么问题

JustTrustMe不生效

## 详细情况

Magisk 版本：18.2
太极 Magisk 模块版本：4.7.6
太极APP版本：5.0.5-43
开启的 Xposed 模块：JustTrustMe
Xposed模块版本：.2
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：mi9
ROM版本：10.2.15.0

在太极中启用了JustTrustMe，并将微信添加到太极app中，然而抓包失败，还是之前的只有No data的ssl握手记录。
尝试过使用packetcapture，并将packetcapture添加到太极app中；或者fiddler，Wlan使用fiddler的代理，都失败。

隐隐约约感觉是需要将某个系统组件添加到太极app中？

**Comment by tiann** [comment]
> 或者fiddler，Wlan使用fiddler的代理

这个表明不是太极的问题吧？试试别的应用，微信可能做了处理。

**Comment by lly2016** [comment]
> > 或者fiddler，Wlan使用fiddler的代理
> 
> 这个表明不是太极的问题吧？试试别的应用，微信可能做了处理。

谢大佬回复
其他APP都不生效（只添加目标APP和抓包APP）
APP用了ssl pinning，justtruseme跳过ssl pinning 
我感觉是我的什么姿势不对？导致没有生效，可能是ssl pinning用的是系统的一个功能，然后太极里面要加入一个系统的APP？
网上搜的教程也都是用xp+justtrustme，xp是全局的，所以没问题，然而没有用太极的...

**Comment by Alvinnfly** [comment]
> > 或者fiddler，Wlan使用fiddler的代理
> 
> 这个表明不是太极的问题吧？试试别的应用，微信可能做了处理。

谢大佬回复
其他APP都不生效（只添加目标APP和抓包APP）
APP用了ssl pinning，justtruseme跳过ssl pinning 
我感觉是我的什么姿势不对？导致没有生效，可能是ssl pinning用的是系统的一个功能，然后太极里面要加入一个系统的APP？
网上搜的教程也都是用xp+justtrustme，xp是全局的，所以没问题，然而没有用太极的...

**Comment by tanghengvip** [comment]
我也是在magisk模式下使用这个模块，一个target sdk version=26的App，本来是抓不到的，使用后可以。

**Comment by Alvinnfly** [comment]
> 我也是在magisk模式下使用这个模块，一个target sdk version=26的App，本来是抓不到的，使用后可以。

微信也是26...
只用添加目标APP到太极名单吗？我咋怎么都不行...
现在是用备用机抓...实在不行就放弃了

**Comment by tanghengvip** [comment]
> > 我也是在magisk模式下使用这个模块，一个target sdk version=26的App，本来是抓不到的，使用后可以。
> 
> 微信也是26...
> 只用添加目标APP到太极名单吗？我咋怎么都不行...
> 现在是用备用机抓...实在不行就放弃了

我只是添加目标App，然后启用模块就好了。
你是抓微信webview吗？要不你尝试一下开启/关闭微信的x5内核，可能与此有关。
[debugx5.qq.com](url)

**Comment by Alvinnfly** [comment]
![Uploading Screenshot_2019-03-25-14-20-36-762_me.weishu.exp.png…]()

![IMG_20190325_142105](https://user-images.githubusercontent.com/46491442/54899062-8ec3b000-4f09-11e9-8ae9-32a995395a1b.jpg)


上两张图，用的是justtrustme的.2版本，已经启用且重启过

**Comment by Alvinnfly** [comment]
> > > 我也是在magisk模式下使用这个模块，一个target sdk version=26的App，本来是抓不到的，使用后可以。
> > 
> > 
> > 微信也是26...
> > 只用添加目标APP到太极名单吗？我咋怎么都不行...
> > 现在是用备用机抓...实在不行就放弃了
> 
> 我只是添加目标App，然后启用模块就好了。
> 你是抓微信webview吗？要不你尝试一下开启/关闭微信的x5内核，可能与此有关。
> [debugx5.qq.com](url)

是小程序，需要什么特别的姿势吗
谢谢...

**Comment by tanghengvip** [comment]
> > > > 我也是在magisk模式下使用这个模块，一个target sdk version=26的App，本来是抓不到的，使用后可以。
> > > 
> > > 
> > > 微信也是26...
> > > 只用添加目标APP到太极名单吗？我咋怎么都不行...
> > > 现在是用备用机抓...实在不行就放弃了
> > 
> > 
> > 我只是添加目标App，然后启用模块就好了。
> > 你是抓微信webview吗？要不你尝试一下开启/关闭微信的x5内核，可能与此有关。
> > [debugx5.qq.com](url)
> 
> 是小程序，需要什么特别的姿势吗
> 谢谢...

我这边即使不用JustTrustMe，直接连Fiddler就可以抓小程序接口数据。
那个Packge Capture我也可以抓到小程序，你会不会是没装证书？
![WeChat_data_in_package_capture.png](https://i.loli.net/2019/03/25/5c98cd7b63a72.png)

**Comment by Alvinnfly** [comment]
> > > > > 我也是在magisk模式下使用这个模块，一个target sdk version=26的App，本来是抓不到的，使用后可以。
> > > > 
> > > > 
> > > > 微信也是26...
> > > > 只用添加目标APP到太极名单吗？我咋怎么都不行...
> > > > 现在是用备用机抓...实在不行就放弃了
> > > 
> > > 
> > > 我只是添加目标App，然后启用模块就好了。
> > > 你是抓微信webview吗？要不你尝试一下开启/关闭微信的x5内核，可能与此有关。
> > > [debugx5.qq.com](url)
> > 
> > 
> > 是小程序，需要什么特别的姿势吗
> > 谢谢...
> 
> 我这边即使不用JustTrustMe，直接连Fiddler就可以抓小程序接口数据。
> 那个Packge Capture我也可以抓到小程序，你会不会是没装证书？
> ![WeChat_data_in_package_capture.png](https://camo.githubusercontent.com/66cb0f8fa689d66ba52665b457ffa375d17c5d80/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30332f32352f356339386364376236336137322e706e67)

都装了证书，fiddler和packetcapture....只不过没有装到system文件夹下
我咋就抓不上啊...
算了以后用备用机吧，谢谢了

**Comment by aaronclub** [comment]
我也遇到了这个问题，justtrustme.2版本不生效，但是我换成了.4版本，就好了，你可以试一下：https://github.com/pengwei1024/JustTrustMe/releases/download/V0.4/app-release.apk

**Comment by hslzyd** [comment]
> 我也遇到了这个问题，justtrustme 0.2版本不生效，但是我换成了0.4版本，就好了，你可以试一下：https://github.com/pengwei1024/JustTrustMe/releases/download/V0.4/app-release.apk

原来还有0.4版本！试了下在荣耀V10（Android 9）可以了，感谢

**Comment by leafney** [comment]
感谢，v0.4可以

**Comment by WangJi** [comment]
我靠，还有一个 `0.4` 版本，我差点都放弃了。       
因为在`ios`上装了证书可以直接抓，没这么麻烦。

**Comment by Suchbear** [comment]
> 我也遇到了这个问题，justtrustme 0.2版本不生效，但是我换成了0.4版本，就好了，你可以试一下：https://github.com/pengwei1024/JustTrustMe/releases/download/V0.4/app-release.apk

实测android10.0有效 感谢 十分有趣

**Comment by Licsber** [comment]
实测安卓10有效 感谢

**Comment by zidekuls** [comment]
> 我也遇到了这个问题，justtrustme 0.2版本不生效，但是我换成了0.4版本，就好了，你可以试一下：https://github.com/pengwei1024/JustTrustMe/releases/download/V0.4/app-release.apk

谢谢，我的安卓10也生效了。可以问下你是从哪儿找到这个仓库的吗？因为我直接搜索搜到的仓库只有02版本。
