### ISSUE TITLE
Bug report: Exi for SwiftKey mod v2.0.4 (latest supported by TaiChi) and TaiChi v5.0.5

### ISSUE THREAD

**Issue by K0media** [taichi-framework/TaiChi#539]
**Describe the bug**
Please refer to this album:
https://photos.app.goo.gl/idqaWqB1VS8vFbubA

Details: aftere setting everything up, a preventive toast shows up on the app (when popping up SwiftKey keyboard) and prevents the module from working.

**To Reproduce**
1. Have latest TaiChi installed (of course);
2. Have the last supported version for Exi for SwiftKey installed (currently v2.0.4 is the supported one);
3. Have a SwiftKey supported app version installed (I tested as the Exi's developer suggested within the module, 7.2.3.20 which was the latest one for the module support. If you want to know more about this module, please check the [XDA Thread](https://forum.xda-developers.com/xposed/modules/mod-exi-swiftkey-t3650598) or [Xposed Repo](http://repo.xposed.info/module/com.mayulive.swiftkeyexi));
4. Set up the Xposed mod and TaiChi to get it to work properly;
5. Sit and wait until TaiChi prepares the app to work;
6. The you get this unexpected error as a toast warning:
![image](https://user-images.githubusercontent.com/22375465/54791454-b4566e00-4c18-11e9-89ab-b26e2efccc0a.png)

**Expected behavior**
Well, I guess that after all that work it was supposed to work right away, right?

**Smartphone (please complete the following information):**
Magisk version：None (not rooted)
TaiChi-Magisk module version：None (not rooted)
TaiChi version：5.0.5
Which Xposed modules are enabled ?：Exi for SwiftKey (via TaiChi)
Xposed modules version：2.0.4 (latest supported on TaiChi, the newest version available is 2.1.3, as the time I'm writing)
Which Magisk modules are enabled ?：None (not rooted)
Magisk modules version：None (not rooted)
Device ：Xiaomi Redmi Note 4X (mido, Snapdragon 625)
ROM：Stock MIUI 10 (I can provide more details if needed later. Latest rolled out version available for this device.)

**Additional context**
Also, if possible, I'd like to you support the latest version available, which is 2.1.3 (see XDA thread or Xposed repo). Just tell me if anything goes wrong.
Also, don't forget to check the Google Photos album I've done. Everything is clear there.

I almost forgot to mention: Google Account's OAuth doesn't work (with the first set-up) to sync my personal dictionary with the official SwiftKey keyboard app. Please check it to work also if possible. Otherwise I'll have to use a Microsoft account instead. But Google's OAuth would be much better than other way around.

**Comment by tiann** [comment]
@K0media Thanks for your hard work, i will look into it.

**Comment by tiann** [comment]
It seems that there are serious bug in kernel of TaiChi, it may take a while to fix :(

**Comment by K0media** [comment]
@tiann, no worries. It's not a priority for me right now. I can wait calmly until it gets fixed. Thanks for the support. 🙂

**Comment by tiann** [comment]
It has been fixed, please wait for next release.

**Comment by tiann** [comment]
please try: https://taichi.ctfile.com/fs/19604958-365278317

**Comment by K0media** [comment]
Okay, just tested with the version you provided (v5.1.8) it and it didn't work, unfortunately. Idk if it's because I'm on MIUI 10.2 or something, but it didn't work out. I'll try to attach a screenshot so you can see the error, but it's similar to what happened in the past.

Please check here:
https://photos.app.goo.gl/WPmycwqAYsZPjkAT9

Please make sure to support the latest version of the module (v2.2.0 at this moment um typing) and make Google OAuth available, because it's broken right now.

Obs.: I've downloaded the latest version supported by the module. It is compatible with the TaiChi build you provided me (Exi for SwiftKey v2.0.4) along with official SwiftKey v7.2.3.24 from APK Mirror.

If I'm doing something wrong, please tell me, so I can make further tests to see if it's really working or not.

Again, thanks for the hard work. 🙂

**Comment by tiann** [comment]
@K0media I am sorry, I only test it on Android Pie, I will check it soon.

**Comment by tiann** [comment]
should be fixed in latest version.
