### ISSUE TITLE
坚果PRO2s5.0版本太极无限重启，不安装任何模块  Bug report: 

### ISSUE THREAD

**Issue by zhuiyi220** [taichi-framework/TaiChi#541]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
Magisk version：
TaiChi-Magisk module version：
TaiChi version：
Which Xposed modules are enabled ?：
Xposed modules version：
Which Magisk modules are enabled ?：
Magisk modules version：
Device ：
ROM：

**Additional context**

**Comment by tiann** [comment]
#463
