### ISSUE TITLE
Feature Request: add official Xposed repository to TaiChi

### ISSUE THREAD

**Issue by K0media** [taichi-framework/TaiChi#542]
Currently I have to browse the official Xposed repository via a web browser. But it would be much better if the official Xposed modules of their repository were listed on TaiChi (as an option) instead of just a few modules.

Maybe that's just for compatibility purposes, but I'd like to list the full Xposed repo right via TaiChi anyway. It's much more convenient to download/update/add modules that way.

Please consider adding this feature, as an option on TaiChi's settings, if you prefer.

**Comment by tiann** [comment]
This feature is working-in-progress, thanks for your advice.
