### ISSUE TITLE
新增模块支持：【模块名】

### ISSUE THREAD

**Issue by scarecrow3333** [taichi-framework/TaiChi#547]
## 模块名字
WeChat Magician（微信巫师）
## 模块用途
WeChat Magician（微信巫师）是一款能够实现防止微信好友撤回聊天消息和微信好友删除朋友圈动态、评论的Xposed框架模块。
## 模块版本号
v2.8.0
## 模块安装包
https://dl-xda.xposed.info/modules/com.gh0u1l5.wechatmagician_v50_87af1c_0.apk

该模块内的微信密友功能较为实用，模块于微信7.0版本后已失效，7.0之前版本仍能使用，如需测试可使用6.7.3版本，谢谢！

**Comment by tiann** [comment]
这模块已经不维护了，要用密友功能，有个单独的插件叫微信密友，用那个就行了。

**Comment by scarecrow3333** [comment]
老大，能否告知哪里能下载这个插件，谢谢。
