### ISSUE TITLE
希望能够添加模块在线仓库

### ISSUE THREAD

**Issue by cjjdaq** [taichi-framework/TaiChi#549]
## 什么问题
希望能够添加模块在线仓库，像magisk仓库那样，用于直接下载与直接更新，而非跳转到第三方。这样模块作者也能提交版本，后台也可以自动更新引擎用于app自动更新。

## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：
太极 Magisk 模块版本：
太极APP版本：
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：
ROM版本：

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by a2212997715** [comment]
顶一下

**Comment by elvisw** [comment]
这个就需要云服务器资源了，是需要用钱来解决的问题😁

**Comment by tiann** [comment]
除非有人提供 CDN

**Comment by a2212997715** [comment]
> 除非有人提供 CDN

大佬不考虑一下xp模块商店吗，edxp就是在xp管理器基础上实现模块更新和下载的，不知道太极可以不
