### ISSUE TITLE
BUG：安卓7.1.2安装太极5各版本无法使用微信增强插件

### ISSUE THREAD

**Issue by chinese-tea** [taichi-framework/TaiChi#551]
## 什么问题

安卓7.1.2安装太极5各版本无法使用微信增强插件

## 详细情况

各种尝试都不行，重新创建应用重启手机重新安装模块都试了

Magisk 版本：
太极 Magisk 模块版本：
太极APP版本：5.1.1
开启的 Xposed 模块：WechatEnhancement微信增强插件 1.9.1
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：国美2017x82a 
ROM版本：安卓7.1.2

## 配置文件

这两个文件我找不到，搜索不到
请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
更新到最新版太极再试试
