### ISSUE TITLE
模块更新支持：【哔哩布丁】-【1.5.7】

### ISSUE THREAD

**Issue by BoringCat** [taichi-framework/TaiChi#556]
## 模块名字
哔哩布丁

## 模块版本号
1.5.7

## 模块更新了什么？
大概更新支持哔哩哔哩客户端5.39.0（作者没写更新日志）

## 模块安装包
https://drive.google.com/file/d/1Djq2kS4cYowzEJadJs7IETCcacJ9YPpx/view?usp=sharing

**Comment by PianCat** [comment]
支持5.39.0了

**Comment by PianCat** [comment]
https://pan.baidu.com/s/10v3zJUnEy8Z1UKqSPmg3mg  u35j

**Comment by tiann** [comment]
55
