### ISSUE TITLE
新增模块支持：【你才长按复制访问】

### ISSUE THREAD

**Issue by Marukon** [taichi-framework/TaiChi#558]
## 模块名字
你才长按复制访问
## 模块用途
在QQ/WX内直接打开淘宝、抖音等链接
## 模块版本号
0.02
## 模块安装包
https://repo.xposed.info/module/com.jy.xposed.web
https://dl-xda.xposed.info/modules/com.jy.xposed.web_v2_ac063e.apk
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
56
