### ISSUE TITLE
模块更新支持：【欅坂メッセージ助手】-【3.3】

### ISSUE THREAD

**Issue by yuiiga** [taichi-framework/TaiChi#560]
## 模块名字
欅坂メッセージ助手
## 模块版本号
3.3
## 模块更新了什么？
适配更新
## 模块安装包
https://github.com/nondanee/KeyakiMsgAssistant-Xposed

**Comment by yuiiga** [comment]
https://www.coolapk.com/apk/com.nondanee.keyakimsgassistant

**Comment by tiann** [comment]
55
