### ISSUE TITLE
新增模块支持：MyHanXiuCao

### ISSUE THREAD

**Issue by zc8** [taichi-framework/TaiChi#561]
## 模块名字
MyHanXiuCao
## 模块用途
破解开车软件含羞草研究所vip权限，仅做测试，勿做他用！By 酷安Larson。
## 模块版本号
1.4
## 模块安装包
https://dl-xda.xposed.info/modules/cn.ainixiang.myhanxiucao_v4_aedffa.apk
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by jjjyyyllll** [comment]
同求支持

**Comment by tanghengvip** [comment]
@tiann 有女朋友，他对这个模块可能没兴趣，哈哈~

**Comment by tiann** [comment]
70

**Comment by ZXCASD854** [comment]
[>>>>点击进入含羞草实验室研究所](http://www.618sss.com)


[>>>>点击进入含羞草实验室研究所](http://www.618sss.com)


[>>>>点击进入含羞草实验室研究所](http://www.618sss.com)


[>>>>点击进入含羞草实验室研究所](http://www.618sss.com)


[>>>>点击进入含羞草实验室研究所](http://www.618sss.com)
