### ISSUE TITLE
新增模块支持：hideapp

### ISSUE THREAD

**Issue by dhbowen** [taichi-framework/TaiChi#566]
模块名字

hideapp

模块用途

利用Xposed框架，隐藏APP，可指定对任意APP隐藏或者全局隐藏。默认打开软件为是一个伪装的计算器，输入设定密码后进入真实程序。

模块版本号

5.4

模块安装包

https://pan.baidu.com/s/1T16XiE_k7uRNzJnyetKISw 提取码:1522 
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by 06ji** [comment]
去哪设定密码？？？安装打开就计算器，如何进

**Comment by dhbowen** [comment]
这个密码是xposed生效的时候进入就会让设置密码。不生效打开就是一个计算器，输入数字是红色就是没生效。

**Comment by tiann** [comment]
没搞懂怎么用

**Comment by woshihume** [comment]
太极阳 面具的模块 4.8  还是不支持该模块吗？

**Comment by woshihume** [comment]
> 没搞懂怎么用

你用太极可以安装吗？可以使用吗?

**Comment by woshihume** [comment]
> 没搞懂怎么用

- [ ] 可以用xp示范看
![Screenshot_2019-04-02-22-37-07-775_de robv androi](https://user-images.githubusercontent.com/49150175/55412098-60914080-5599-11e9-8692-88ea3e472897.png)


1. 

伪装成一个计算器，如果支持后， 打开软件，是一计算器，会输入一个密码 才能打开里面软件， 然后可选软件不被其他软件所检测到是否安装。
步骤：例如支付宝不想被root 所检测到已经获取权限。
  打开软件
![Screenshot_2019-04-02-22-35-37-671_my mongyi hide](https://user-images.githubusercontent.com/49150175/55411699-b44f5a00-5598-11e9-8b19-8dd43dbd6775.png)

设置一个密码
![Screenshot_2019-04-02-22-35-30-378_my mongyi hide](https://user-images.githubusercontent.com/49150175/55411503-54f14a00-5598-11e9-8b4a-a15af9759322.png)
然后找到支付宝，点击去，看到限制模式， 可以设置禁止访问指定程序， 或者仅允许，
![Screenshot_2019-04-02-22-35-46-262_my mongyi hide](https://user-images.githubusercontent.com/49150175/55411677-a8fc2e80-5598-11e9-83b8-9ffe94a1f444.png)
我们设置仅允许 访问某个程序，（如果别的应用用支付宝支付是默认为   未安装支付宝此软件） ，然后打上小勾既可以了
![Screenshot_2019-04-02-22-36-13-550_my mongyi hide](https://user-images.githubusercontent.com/49150175/55411823-e95bac80-5598-11e9-8aa2-ff48e80d1f99.png)


最后设置好后， 关掉既可以。
![Screenshot_2019-04-02-22-36-29-443_my mongyi hide](https://user-images.githubusercontent.com/49150175/55412054-4f483400-5599-11e9-871e-6d11d0acb73f.png)

**Comment by woshihume** [comment]
> 没搞懂怎么用

希望大佬能尽快适配 ，太极能支持。方便大家使用，软件隐藏效果非常好，可以使别的应用检测不到您的安装这个软件！

**Comment by neoblackxt** [comment]
复杂😲

**Comment by woshihume** [comment]
您好，，这个用起来，效果很好的，其实很简单，可否支持一下？
 
---原始邮件---
发件人: "Neo"<notifications@github.com>
发送时间: 2019年5月30日(星期四) 中午1:33
收件人: "taichi-framework/TaiChi"<TaiChi@noreply.github.com>;
抄送: "Comment"<comment@noreply.github.com>;"woshihume"<1132943616@qq.com>;
主题: Re: [taichi-framework/TaiChi] 新增模块支持：hideapp (#566)



复杂😲

**Comment by o02** [comment]
老铁，你忘了写清楚怎么进设置，这APP在没设置密码的时候，直接点计算器的=号，就进入真正的APP界面了。
