### ISSUE TITLE
支持weiboadblocker

### ISSUE THREAD

**Issue by a2212997715** [taichi-framework/TaiChi#569]
## 模块名字
weiboadblocker
## 模块用途
(去除新浪微博客户端时间线中的所有广告，包括热门和Banner)

新安装的用户建议重新登录下，或者直接清除weibo app的数据，以面刷出之前app缓存的广告。
## 模块版本号
1.3
## 模块安装包
http://t.cn/EJgPi2T
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
66
