### ISSUE TITLE
新增模块支持：【lataclysm】

### ISSUE THREAD

**Issue by iaston** [taichi-framework/TaiChi#574]
## 模块名字
lataclysm

## 模块用途
伪装位置,GPS定位,基站定位,WIFI定位.伪装运营商
介绍：https://repo.xposed.info/module/com.cataclysm.i

## 模块版本号
1.35

## 模块安装包
https://dl-xda.xposed.info/modules/com.cataclysm.i_v64_037bfa.apk

**Comment by MoonBegonia** [comment]
@iaston #87

**Comment by iaston** [comment]
看见了，但貌似到现在为止还是没有支持啊

**Comment by MoonBegonia** [comment]
@iaston 

![Screenshot_20190331-212850.png](https://i.loli.net/2019/03/31/5ca0c1b153863.png)

**Comment by iaston** [comment]
收到，已经在magisk版本测试成功，谢谢
