### ISSUE TITLE
New module support: hushsms

### ISSUE THREAD

**Issue by theoneandonly-vector** [taichi-framework/TaiChi#578]
## Module name
hushsms

## Usage
send different sms-types like pdu type 0
 
## Module version
2.7.7

## APK file
https://androidfilehost.com/?fid=11410932744536992759

**Comment by tiann** [comment]
66

**Comment by theoneandonly-vector** [comment]
why?

**Comment by theoneandonly-vector** [comment]
only "normal sms" seems to work now. when I try on a different phone with normal xposed the following also work with same sim-card:
mms notification
class 0
MWI message

**Comment by tiann** [comment]
what is `mms notification` and `class 0`, `MWI message` ?

Maybe you need to add these package to TaiChi?

**Comment by theoneandonly-vector** [comment]
these aren't packages. the APP itself allows a more "direct" access to the
smartphone-modem through "xposed" or " TaiChi", which allows one to send
different types of sms/mms.

Am Mi., 3. Apr. 2019 um 04:32 Uhr schrieb weishu <notifications@github.com>:

**Comment by theoneandonly-vector** [comment]
but I have no deep understanding of the underlying work.

Am Fr., 5. Apr. 2019 um 10:47 Uhr schrieb Marius von Gunten <
lolxdner@gmail.com>:
