### ISSUE TITLE
New module support: IMEI Masker [ Xposed ]

### ISSUE THREAD

**Issue by pyshivam** [taichi-framework/TaiChi#582]
## Module name

IMEI Masker [ Xposed ]

## Usage

Utility To Mask IMEI Of Device.

The Main Aim Is To Spoof The Values From Third Party Apps Which Tracks Users And Their Personal Data.

## Module version 

 2.0.1

## APK file

https://dl-xda.xposed.info/modules/ml.pyshivam.imeimasker_v3_562ef3.apk

Please provide the apk file, otherwise this issue will be ignored!

**Comment by tiann** [comment]
67

**Comment by AndreiBabich** [comment]
Hi, thanks for the software, could you please make it work with two SIM cards?
like "Hijack Suite"
