### ISSUE TITLE
BUG：有时候卡首屏 无法打开

### ISSUE THREAD

**Issue by yuiiga** [taichi-framework/TaiChi#583]
## 什么问题
有时候无法打开 ， 部分功能无法使用

## 详细情况

双击文字无法弹窗复制,有时候卡首屏 无法打开

Magisk 版本：18.1
太极 Magisk 模块版本：4.8.0
太极APP版本：5.1.3-66
开启的 Xposed 模块：欅坂メッセージz助手
Xposed模块版本：3.3
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：红米note4x 
ROM版本：7.1.2

## 配置文件

[list.zip](https://github.com/taichi-framework/TaiChi/files/3028220/list.zip)

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
Android 7.1.2 ?

https://github.com/taichi-framework/TaiChi/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8#%E8%AF%B4%E6%98%8E

**Comment by yuiiga** [comment]
还有一个9的 但是没有生效 也没有日志
