### ISSUE TITLE
多开分身软件分身的微信添加到太极阳后无法启动分身的微信

### ISSUE THREAD

**Issue by FeNg360** [taichi-framework/TaiChi#584]
## 什么问题

（请简要说明你遇到的问题）

## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：7.1.1
太极 Magisk 模块版本：4.8.0
太极APP版本：5.1.1
开启的 Xposed 模块：微x
Xposed模块版本：1.25
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：一加6
ROM版本：android P 9.0.3

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
不清楚多开分身干了什么。
