### ISSUE TITLE
新增模块支持：【Droidsword】

### ISSUE THREAD

**Issue by KyuubiRan** [taichi-framework/TaiChi#585]
## 模块名字
DroidSword
## 模块用途
逆向神器，快速定位UI信息。
## 模块版本号
1.0.4
## 模块安装包
https://github.com/githubwing/DroidSword/raw/master/app/release/app-release.apk

**Comment by KyuubiRan** [comment]
还有老大之前提的两个magisk版重启和强停的功能有意向嘛 听嫂子说写代码写的走火入魔了 要注意身体啊😂

**Comment by wf521gyx** [comment]
支持，强烈推荐大大适配

**Comment by tiann** [comment]
@KyuubiRan 近期加上
