### ISSUE TITLE
模块更新支持：【release】-【0.1-δ】

### ISSUE THREAD

**Issue by zh-ao** [taichi-framework/TaiChi#586]
## 模块名字
release
## 模块版本号
0.1-δ
## 模块更新了什么？
固定搜索框位置，修复搜索框消失bug
更改漫画源，做到秒刷新。
退出APP后自动隐藏图标
## 模块安装包
https://dl-xda.xposed.info/modules/com.app.legend.dms_v4_2accd7.apk

**Comment by tiann** [comment]
70
