### ISSUE TITLE
模块更新支持：【模块名】-【版本号】

### ISSUE THREAD

**Issue by caliban511** [taichi-framework/TaiChi#591]
## 模块更新了什么？New action: stop all, stop looping(multi-action and repeat), playing sound and speech, injecting gesture, and gesture recording.
Bug fixes.

## 模块安装包：
链接:https://pan.baidu.com/s/1S-i9Hl7hogRR1l90ia2x_Q 提取码:gki1

**Comment by caliban511** [comment]
我在google play里关掉自动更新，关了三次，结果play在后台给我自动更新了三次，，，
实在是没办法了，求大佬早日适配一下。

**Comment by tiann** [comment]
70
