### ISSUE TITLE
BUG：magisk4.8.0不正常重启时会卡在锁屏界面

### ISSUE THREAD

**Issue by xiaoding721** [taichi-framework/TaiChi#592]
## 什么问题
太极magisk4.8.0不正常重启时会卡在锁屏界面

## 详细情况
不使用电源键执行重启时就会一直重复屏幕卡住然后变亮然后跳到锁屏界面

Magisk 版本：18.1
太极 Magisk 模块版本：4.8.0
太极APP版本：东皇钟 5.1.1-69
开启的 Xposed 模块：QX1.21 ;上帝模式2.77; WX1.25; 验证码提取器2.0.1; 音量增强器0.0.30; 云村清洁工2.5.2; 指纹支付3.9.2; 网易云音乐插件2.8.2;核心破解1.2.0 
Xposed模块版本：1.21 2.77 1.25 2.0.1 0.0.30 2.5.2 3.9.2 .12.0 2.8.2
开启的其他 Magisk 模块：mm管理器2018.8.1;
其他 Magisk 模块版本：（无）
手机型号：小米5s
ROM版本：MK90.0-capricorn-201904020251-nightly

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

[apps.zip](https://github.com/taichi-framework/TaiChi/files/3036366/apps.zip)

**Comment by tiann** [comment]
删除 `/data/system/taichi` 目录再试下

**Comment by neoblackxt** [comment]
我也遭遇了这个问题，删除/data/system/taichi后终于恢复了
