### ISSUE TITLE
模块更新支持：【应用控制器】-【3.2.3】

### ISSUE THREAD

**Issue by iaston** [taichi-framework/TaiChi#594]
## 模块名字
应用控制器
## 模块版本号
3.2.3
## 模块更新了什么？
底层代码修改，请务必重启手机，否则可能会有未知问题(耗电/卡顿)！

1.修复部分系统重启后未运行的应用卡片没有清除问题。
2.修复个别系统微信登录被拦截问题。
3.修复存储重定向导致部分文件管理器的一些异常（如果出现异常，请把你的文件管理器包名提供给我）。
4.修复android p网络防火墙无效问题。
5.修复部分android p系统卡开机（有两个测试正常,不代表所有正常，老司机可以安装后反馈在评论区）。
提示：无论使用任何模块，首先要会备份系统/使用TWRP删除安装包，这是开车最基本常识，一旦出现无法开机请删除data/app/com.click369.controlbp即可，如果卡开机并且你是老司机，可以联系我QQ，我给发测试包进行测试，因为ed或太极并不是官方xp，所以有一定的概率是框架的bug，框架有bug只能通过不断测试绕过框架的bug。
## 模块安装包
https://www.coolapk.com/apk/com.click369.controlbp

**Comment by AceMONKEY519** [comment]
这模块申请过适配了。但会导致卡屏，不建议更新

**Comment by tiann** [comment]
81 -> 3.2.6
