### ISSUE TITLE
新增模块支持：【模块名】阻止运行

### ISSUE THREAD

**Issue by 1010739073** [taichi-framework/TaiChi#603]
## 模块安装包：
下载地址：https://dl-xda.xposed.info/modules/me.piebridge.forcestopgb_v872_69fb0e.apk
模块介绍：https://repo.xposed.info/module/me.piebridge.forcestopgb

(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
不清楚这个模块是怎么检测 Xposed 的，在太极里面它死也认为没有Xposed；这个我这边解决不了。
