### ISSUE TITLE
模块更新支持：【森林庄园】-【116d v2】

### ISSUE THREAD

**Issue by 1099248243** [taichi-framework/TaiChi#604]
## 模块安装包
https://www.lanzous.com/i3ns4gj

**Comment by vivtoum** [comment]
支付宝最新版支持吗

**Comment by cocowobo** [comment]
我也好奇，还是用的1.1.2，感觉稳定点，可以本地锁死配置文件，1.1.6无法锁定配置文件，就不能打开主app查看收取记录，

**Comment by cocowobo** [comment]
1.1.6 V2 是scanf print 破解的。需要改.data文件，需要自己写入 USER_ID 和KEY_DO，和1.1.6 test倒是无需改什么直接用，两者那个好我就不知道了。

**Comment by vivtoum** [comment]
意思是我拿1.1.5能用的.data文件覆盖的话，1.1.6v2也就生效对吧。
还有一个问题就是，生效之后能打开app看吗，还能修改设置吗？

**Comment by cocowobo** [comment]
1.1.5和1.1.6的.data应该是通用的，1.1.6V2.和1.1.6 test 都是破解版，v2.破解后还需要自己设置id
和KEYDO，test。我看群里发布说明是无需授权验证激活，无需修改即可使用，
我现在也在实验，实践知道1.1.5 是最慢的且不能锁定.data文件，否则庄园会罢工，我晚上想试试1.1.6Test。等我实验完了，看看结果，记得使用谷歌市场的 支付宝且只能用 10.1.60之前的支付宝，60的支付宝网络借口改了，

**Comment by vivtoum** [comment]
我1.1.5的.data文件我看了下，里面包含有id 和 keydo 值，所以应该可以理解为这个.data文件算是通用了吧。（滑稽）
