### ISSUE TITLE
magisk 18.0，模块4.8.0，卡米了

### ISSUE THREAD

**Issue by caoliang313** [taichi-framework/TaiChi#606]
## 什么问题

米4 magisk 18.0，模块4.8.0，卡米了

## 详细情况

Magisk 版本：18.0
太极 Magisk 模块版本：4.8.0
太极APP版本：5.1.3
开启的 Xposed 模块：-
Xposed模块版本：-
开启的其他 Magisk 模块：MM管理器
其他 Magisk 模块版本：（无）
手机型号：MI 4W
ROM版本：10.1.1.0(MXDCNFI)
Android版本：6.0.1 MMB29M

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
magisk 版不支持 7.0及以下的系统。

**Comment by caoliang313** [comment]
。。。。
好吧，
如果在能在装magsik模块的时候能报个错，表示Android版本太低，我也就不会来来回回刷几十遍了。。。
