### ISSUE TITLE
新增模块支持：【能不能在应用里面增加一个支持插件列表和版本号】

### ISSUE THREAD

**Issue by panyuhang93** [taichi-framework/TaiChi#608]
## 模块用途
这样就不用更新[引擎更新日志]了（也很久没更新了）
## 模块安装包

(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
https://taichi.cool/module/module_cn
