### ISSUE TITLE
新增模块支持：【模块名】禁止调节音量

### ISSUE THREAD

**Issue by l453562560** [taichi-framework/TaiChi#610]
## 模块安装包
http://t.cn/EisQYM7
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by l453562560** [comment]
http://t.cn/EisQYM7

**Comment by l453562560** [comment]
使手机不再每次连接蓝牙，手机自动降低音量

**Comment by tiann** [comment]
82

**Comment by l453562560** [comment]
该模块在xp和各大网站都下架了，原作者似乎也没有更新过了，这个是我从去年的手机上提取出来的，望太极大大加到（太极模块下载）列表中去，不要让这么好用的一个模块就这么消失了。

**Comment by tiann** [comment]
好的
