### ISSUE TITLE
模块更新支持：【哔哩漫游】-【1.0.5】

### ISSUE THREAD

**Issue by iAcn** [taichi-framework/TaiChi#611]
## 模块名字
哔哩漫游

## 模块版本号
1.0.5

## 模块更新了什么？
优化运行效率
修复东京食尸鬼之类的番剧无法观看

## 模块安装包
https://github.com/iAcn/BiliRoaming/releases/tag/v1.0.5

**Comment by iAcn** [comment]
直接支持 1.0.6 吧 ☺️

**Comment by AceMONKEY519** [comment]
https://github.com/iAcn/BiliRoaming/releases/download/v1.0.6/BiliRoaming_1.0.6.apk

**Comment by AceMONKEY519** [comment]
> 直接支持 1.0.6 吧 ☺️

大佬哔哩净化啥时候填坑

**Comment by iAcn** [comment]
@AceMONKEY519 有继任者了我就不做了 :)

**Comment by jjjyyyllll** [comment]
哔哩净化继任者是谁？在哪里？有链接吗？

**Comment by jjjyyyllll** [comment]
求告知，谢谢

**Comment by Mathonix** [comment]
能让海外用户看动漫吗

**Comment by Mathonix** [comment]
可以做一个让海外用户在b站上看番剧的功能吗emm
