### ISSUE TITLE
新增模块支持：【模块名】AppContext

### ISSUE THREAD

**Issue by bN-o** [taichi-framework/TaiChi#615]
## 模块名字
AppContext

## 模块用途
Have Tasker react on running applications, without the downsides of the default implementation!

It hooks directly into the Activity-class, letting Tasker react immediately when an app starts. This means no more periodic checking which app is running, so no more battery drain and no more slow reactions. It's also perfectly accurate and doesn't need an accessibility service, so your device's screen lock can be used for enhanced data protection again.
(Experimental support for reacting on Services is also present.)

## 模块版本号
Version name: 0.4.7.2

## 模块安装包
https://dl-xda.xposed.info/modules/io.shortway.appcontext_v16_a8fecb.apk

(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by bN-o** [comment]
@tiann 煩請看看能否支持一下這個模块
謝謝

**Comment by tiann** [comment]
Please update the module compatibility engine to 82, and it should work now.

**Comment by bN-o** [comment]
Thank you. It works now.
