### ISSUE TITLE
新增模块支持：【网速监测xp版】

### ISSUE THREAD

**Issue by drowtram** [taichi-framework/TaiChi#629]
## 模块名字
网速监测xp版
## 模块用途
锤子SmartisanOS状态栏网速显示，我是此模块的开发者，普通版已经上架锤子应用市场，在群里面有人提议我申请支持下太极-Magisk版，所以前来申请下。
## 模块版本号
1.3
## 模块安装包
https://share.weiyun.com/53yR5Da

**Comment by tiann** [comment]
我手头没有锤子手机，更新到模块适配引擎到 79 帮忙看看能否正常使用

**Comment by drowtram** [comment]
> 我手头没有锤子手机，更新到模块适配引擎到 79 帮忙看看能否正常使用

不行，现在不提示“暂不支持”了，但是勾选后重启手机，状态栏网速没生效。

**Comment by drowtram** [comment]
> 我手头没有锤子手机，更新到模块适配引擎到 79 帮忙看看能否正常使用

这个生效的应用是勾选 系统界面 吧

**Comment by tiann** [comment]
@drowtram 
1. 添加 “系统界面”
2. 勾选模块

**Comment by wojiu** [comment]
成功上车，感谢😭
