### ISSUE TITLE
BUG：模拟位置这个模块开启悬浮窗后切到别的APP或桌面5秒后悬浮窗消失

### ISSUE THREAD

**Issue by RouRouX** [taichi-framework/TaiChi#632]
## 什么问题

模拟位置这个模块开启悬浮窗后切到别的APP或桌面5秒后悬浮窗消失

## 详细情况

模拟位置这个APP模拟位置正常，开启悬浮窗后，进去别的APP或者桌面，大约5秒中后悬浮窗消失，如果重新在模拟位置app中打开或者关闭悬浮窗开关，切到别的APP还是只能5秒

Magisk 版本：18.1
太极 Magisk 模块版本：4.8.0
太极APP版本：5.1.3-80
开启的 Xposed 模块：模拟位置
Xposed模块版本：1.2.681.1701
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：小米MIX2
ROM版本：MIUI10 9.3.28

**Comment by iaston** [comment]
同样情况

**Comment by jerryliang122** [comment]
我想问问你们啊，你们开了模拟位置的悬浮窗权限了么

**Comment by RouRouX** [comment]
> 我想问问你们啊，你们开了模拟位置的悬浮窗权限了么

当然开了。

**Comment by tiann** [comment]
这貌似是模拟位置这个APP自己的设置选项，跟太极无关。
