### ISSUE TITLE
新增模块支持：悟空加速

### ISSUE THREAD

**Issue by VwEl** [taichi-framework/TaiChi#633]
## 模块名字
  悟空加速
## 模块用途
「悟空加速」，加速启动 ，跳过不要的启动页。
## 模块版本号
1.8.4
## 模块安装包
https://raw.githubusercontent.com/VwEl/-/master/wu-kong-v1.8.4-167314-o_1d65h521a1p571c46198namq1fpsq-uid-1131019.apk
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
82

**Comment by drcege** [comment]
这个在普通版下怎么用，是要把所有有广告的应用都加到太极里吗？
