### ISSUE TITLE
BUG：华为P30无法安装QQ

### ISSUE THREAD

**Issue by np5cm1s** [taichi-framework/TaiChi#636]
## 什么问题

华为P30中太极无法安装QQ应用

## 详细情况

太极安装其他程序正常
创建QQ应用后安装 安装到一半会跳出 QQ7.9.8 7.9.9都是如此
软件界面显示"null 状态异常，点击处理"

Magisk 版本：无
太极 Magisk 模块版本：无
太极APP版本：5.1.3
开启的 Xposed 模块：无
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：华为P30
ROM版本：EMUI 9.1.0 Android 9

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

未找到文件

**Comment by tiann** [comment]
有办法拿到 日志吗？或者把华为安全中心啥的关掉看看？

**Comment by np5cm1s** [comment]
把 "外部来源应用检查" 关闭
允许太极 "安装外部来源应用"
激活太极 "设备管理器"
太极 "允许自启动" "允许关联启动" "允许后台活动" 也都设置了
试了还是一样

日志应该从哪里找 手机没有root 只在/Android/data/me.weishu.exp/找到太极相关目录 但里面只有个cache文件夹

**Comment by np5cm1s** [comment]
不知是否有用的系统错误报告
https://mega.nz/#!U5cwFIYa!1k4o1cKK-Xaxvuv_A_6PLhri2moIjhm8KIxYXVbW5Ks

**Comment by np5cm1s** [comment]
看到的一些讨论
https://bbs.pediy.com/thread-250773.htm

**Comment by tiann** [comment]
最新版 5.5.1 是否有此问题？

**Comment by 4DAA** [comment]
> 看到的一些讨论
> https://bbs.pediy.com/thread-250773.htm



> 把“外部来源应用检查”关闭
> 允许太极“安装外部来源应用” 
> 激活太极“设备管理器” 
> 太极“允许自启动”“允许关联启动”“允许后台活动”也都设置了
> 试了还是一样
> 
> 日志应该从哪里找手机没有根只在/Android/data/me.weishu.exp/找到太极相关目录但里面只有个缓存文件夹

你这个问题我遇到过，我之前用的华为mate20x，也是emui9，后面发现是我在自带的隐私空间里安装了一个QQ，卸载隐私空间的QQ就解决了。
