### ISSUE TITLE
新增模块支持：【全民辅助】

### ISSUE THREAD

**Issue by jiumoshou** [taichi-framework/TaiChi#638]
## 模块名字
全民辅助
## 模块用途
全民k歌启动页广告关闭，歌房语音长按改点击开关
## 模块版本号
1.0
## 模块安装包
https://github.com/jiumoshou/karorkefz/blob/master/karorkefz.apk
已更新界面

**Comment by tiann** [comment]
86

**Comment by njdhzisnbsua** [comment]
老哥，下載不了！！！
