### ISSUE TITLE
新增模块支持：【QNotified】

### ISSUE THREAD

**Issue by cinit** [taichi-framework/TaiChi#639]
## 模块名字
QNotified
## 模块用途
QNotified(QQ删好友通知)通过定期刷新QQ好友列表判断是否有好友删除用户，并在检测到被好友删除后向用户发出通知提醒。
## 模块版本号
0.1.2 (5)
## 模块安装包
https://github.com/cinit/QNotified/releases/download/v0.1.2/qnotified_012.apk

**Comment by tiann** [comment]
86

**Comment by tiann** [comment]
已经支持了，老铁

**Comment by tiann** [comment]
已经支持了，老铁
