### ISSUE TITLE
模块更新支持：【哔哩漫游】-【1.0.7】

### ISSUE THREAD

**Issue by YazawaNiko7** [taichi-framework/TaiChi#641]
## 模块名字
哔哩漫游
## 模块版本号
1.0.7
## 模块更新了什么？
更新
## 模块安装包
https://github.com/iAcn/BiliRoaming

**Comment by AceMONKEY519** [comment]
https://github.com/iAcn/BiliRoaming/releases/download/v1.0.7/BiliRoaming_1.0.7.apk

**Comment by tiann** [comment]
86
