### ISSUE TITLE
模块介绍及下载

### ISSUE THREAD

**Issue by lmrpx** [taichi-framework/TaiChi#644]
## 什么问题

模块的介绍与下载

## 详细情况

太极支持的模块应该详细介绍一下每个模块的作用，有时候光看名字不知道模块的作用。
同时在手机上的太极APP中下载模块最好支持可以下载所有的模块，而不是部分。

Magisk 版本：18.1
太极 Magisk 模块版本：4.8
太极APP版本：5.1.1-85
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：
ROM版本：

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by neoblackxt** [comment]
如果模块作者能入驻组织仓库，然后自行维护介绍，版本控制...会好一点

**Comment by a2212997715** [comment]
作者应该考虑一下xp仓库

**Comment by tiann** [comment]
有一些模块是灰色的，不可能有我来分发。

https://taichi.cool/module/module_cn
