### ISSUE TITLE
BUG：哔哩哔哩无法分享视频到微信

### ISSUE THREAD

**Issue by Githubbili** [taichi-framework/TaiChi#645]
## 什么问题
哔哩哔哩无法分享视频到微信

## 详细情况

通过太极优化哔哩哔哩之后，无法正常分享视频到微信上，显示签名不正确。

Magisk 版本：
太极 Magisk 模块版本：
太极APP版本：东皇钟5.1.3-85
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：小米8
ROM版本：MIUI10 9.3.28|开发版

## 配置文件

暂时没办法提供配置文件，后续需要，我再想想办法。

**Comment by liaolia333** [comment]
太极阴的话,确实没办法,因为一个在内一个在外.他会以为你并没有安装微信

**Comment by Githubbili** [comment]
> 太极阴的话,确实没办法,因为一个在内一个在外.他会以为你并没有安装微信

但是能正常打开微信，就是无法转发。显示签名不对，我在想是不是因为太极阴优化了哔哩哔哩的缘故，把签名改变了。

**Comment by tiann** [comment]
原理所限，没法解决。你可以把微信也加入太极。
