### ISSUE TITLE
新增模块支持：知乎助手

### ISSUE THREAD

**Issue by jsfaint** [taichi-framework/TaiChi#649]
## 模块名字
知乎助手

## 模块用途
1. 去除首页"推荐"内的广告、Live和书店等卡
2. 去除答案页面底部广告
3. 屏蔽底部"方法"或"大学"选项卡
4. 去除答案列表内的广告

## 模块版本号
1.0.1
## 模块安装包
https://github.com/picone/ZhihuXposed/releases/download/1.0.1/app-release.apk

(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
90

**Comment by jsfaint** [comment]
好高效！感谢！
