### ISSUE TITLE
BUG：无法进入magisk版的太极

### ISSUE THREAD

**Issue by xiuluowangyiping** [taichi-framework/TaiChi#651]
## 什么问题

android 7.1.1 已经刷了 magisk17.1 和 taichi 4.7.0 使用太极5.1.8.5 依旧无法进入magisk版，创建应用很慢

## 详细情况

降级了面具到17.1， magisk没有其他模块，然后安装了taichi模块， 然后再安装太极app，，创建应用依然很慢，要卸载重新安装，所以是免root版，请问该如何触发进入magisk版

Magisk 版本：17.1
太极 Magisk 模块版本：4.7.0
太极APP版本：5.1.85-90
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：
ROM版本：

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
太极没有，也不打算兼容 8.0 以下的系统：

[使用说明](https://github.com/taichi-framework/TaiChi/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8#%E8%AF%B4%E6%98%8E)
