### ISSUE TITLE
BUG：太极magisk+太极5.1.8.x+Chimi模块 bootloop

### ISSUE THREAD

**Issue by neoblackxt** [taichi-framework/TaiChi#656]
## 什么问题

太极magisk开机卡在第二屏

## 详细情况

1. 对于太极5.1.8.x版本，只开太极不开任何 Xposed 模块，无论是否SElinux 可以正常开机。
2. 对于太极5.1.8.x版本，开太极并且开模块，开启SElinxu无法开机；关闭SELinux可以开机。
3. 对于太极5.1.3版本，开太极并且开模块，开启SElinxu可以开机

Magisk 版本：v18.1
太极 Magisk 模块版本：4.8.0
太极APP版本：5.1.8-93 5.1.8.3-93 5.1.8.5-93
开启的 Xposed 模块：ChiMi
Xposed模块版本：   2.3.07
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：Xiaomi MI 6
ROM版本：MIUI 10.9.4.11开发版 Android O 8.0

## 配置文件
应用模块列表：
[list.zip](https://github.com/taichi-framework/TaiChi/files/3089693/list.zip)

5.1.8.x版本无法开机的日志
[logcat_sysPid1311_bootloop_seEnforcing_taichiV5.1.8.x-93_mmV4.8.0.log](https://github.com/taichi-framework/TaiChi/files/3089778/logcat_sysPid1311_bootloop_seEnforcing_taichiV5.1.8.x-93_mmV4.8.0.log)

5.1.3版本正常开机的日志
[logcat_sysPid1359_bootsucceed_seEnforcing_taichiV5.1.3-93_mmV4.8.0.log](https://github.com/taichi-framework/TaiChi/files/3089782/logcat_sysPid1359_bootsucceed_seEnforcing_taichiV5.1.3-93_mmV4.8.0.log)

补充说明：
1. ~~目前仅发现ChiMi模块可以稳定的重现这个问题。~~ ChiMi v2.3.07，绿色守护 v4.6.3，应用控制器 v3.2.6，模拟位置 v1.2.681.1701 都可以重现这个问题。相关issue  [BUG：在更新内核或者是更新太极内核之后magisk太极会卡m 二屏](https://github.com/taichi-framework/TaiChi/issues/653)
2. 在5.1.8.x的日志中6041行
`04-17 20:13:00.603  1311  1311 I ExposedBridge:   Loading class chili.xposed.chimi.hooks.Hook`
加载中这个类，然后就一直重复出现以下的selinux拒绝execute的提示
`04-17 20:13:00.617  1311  1311 W system_server: type=1400 audit(0.0:310): avc: denied { execute } for path="/dev/ashmem" dev="tmpfs" ino=22582 scontext=u:r:system_server:s0 tcontext=u:object_r:ashmem_device:s0 tclass=chr_file permissive=0`
似乎system_server进程陷入了一个死循环，直到关闭selinux，在7218行，才有
`04-17 20:15:40.539  1311  1311 I EpicNative: use unsafe ? false nativeOffset: 32`
3. 在5.1.3的日志中5959行
`04-17 20:23:46.646  1359  1359 I ExposedBridge:   Loading class chili.xposed.chimi.hooks.Hook`
之后很快就有5961行
`04-17 20:23:46.662  1359  1359 I EpicNative: use unsafe ? false nativeOffset: 32`
4. 使用setenforce 0关闭selinux后，等系统启动完，再次启用selinux会导致系统软重启，并一直维持在开机第二屏的状态。
5. 最近用一个定制的[TWRP](http://www.miui.com/thread-10735327-1-1.html)取消了/data分区的强制加密。
6. 在magisk中同时启用Riro-core  Riru-Edxposed taichi这三个模块，不关闭selinux居然也可以正常开机。太神奇了，这难道是缘分？getenforce 还是Enforcing的状态。

**Comment by tiann** [comment]
SELinux 的日志中没有看到有太极相关的问题，我下面的理解是否正确？

1. 只开太极不开任何 Xposed 模块，无论是否SElinux 可以正常开机。
2. 开太极并且开模块，开启SElinxu无法开机；关闭SELinux可以开机。

那么，是开启任意一个模块之后都无法开机，还是某个特定的模块？

**Comment by tiann** [comment]
第六点，因为 edxposed 开放了足够多多的 SELinux限制。具体内容我回去再看看日志。谢谢提供如此详细的信息。

**Comment by tiann** [comment]
[taichi_5.1.9.1.apk.zip](https://github.com/taichi-framework/TaiChi/files/3090322/taichi_5.1.9.1.apk.zip)

@neoblackxt 虽然可以简单粗暴地直接设置SELinux规则规避此问题，但是我想搞清楚具体原因。因此还请装一下上面那个安装包，复现一下 bootlooop 的状况然后把日志发我看一下，非常感谢

**Comment by neoblackxt** [comment]
[logcat_sysPid1387_bootloop_seEnforcing_taichiV5.1.9.1-94_mmV4.8.0_ChiMiV2.3.07.log](https://github.com/taichi-framework/TaiChi/files/3090385/logcat_sysPid1387_bootloop_seEnforcing_taichiV5.1.9.1-94_mmV4.8.0_ChiMiV2.3.07.log)
约在6000行后我关闭了SELinux

**Comment by tiann** [comment]
应该找到问题了，非常感谢。

试试这个安装包：

[taichi_5.1.9.2.apk.zip](https://github.com/taichi-framework/TaiChi/files/3090501/taichi_5.1.9.2.apk.zip)

**Comment by neoblackxt** [comment]
已解决ChiMi模块的问题！谢谢！你很有极客精神！我支持你
