### ISSUE TITLE
BUG：magisk 19.0 应用变量3.2.10不起作用

### ISSUE THREAD

**Issue by trivita** [taichi-framework/TaiChi#664]
## 什么问题

一加6 android 9.0 magisk 19.0 太极最新版本 应用变量3.2.10不起作用
## 详细情况

Magisk 版本：19.0
太极 Magisk 模块版本：4.8.2
太极APP版本：
开启的 Xposed 模块：应用变量
Xposed模块版本：3.2.10
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：一加6
ROM版本：最新beta版本9.0

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by MoonBegonia** [comment]
应用变量升级到最新版再试试，这个版本的应用变量似乎不行
https://www.coolapk.com/apk/com.sollyu.xposed.hook.model

**Comment by tiann** [comment]
说明详细情况，什么叫 “不能用”？
