### ISSUE TITLE
BUG：上帝模式微信黑屏

### ISSUE THREAD

**Issue by VictorChow** [taichi-framework/TaiChi#665]
## 什么问题

更新5.1.9.6太极·Magisk124后微信卡首页黑屏

## 详细情况

太极阳
微信7.0.4
在应用里添加微信
启动微信 微信卡首页黑屏
未更新太极5.1.9.6前 上个版本的太极微信7.0.4是不卡黑屏的

Magisk 版本：19004
太极 Magisk 模块版本：4.8.2
太极APP版本：5.1.9.6-94
开启的 Xposed 模块：未开任何微信相关模块
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：小米9
ROM版本：MIUI 10 9.4.1

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by VictorChow** [comment]
cepheus:/ # cat /data/system/taichi/modules.list
/data/app/com.fkzhang.qqxposed-PB7Ku5GjLeHfi6By4fRfiw==/base.apk
/data/app/com.ext.star.wars.vxp-n73jXzQBL8I92M8Gt-4D5w==/base.apk
/data/app/me.zjns.lovecloudmusic-nADgHS7o6gWG11Z7tMuELg==/base.apk
/data/app/com.flo354.xposed.applocale-2nb6Y2xWMYl_ZkR4EcjufA==/base.apk
/data/app/com.viewblocker.jrsen-grAH-WUoXR6rxbQUnvEkTg==/base.apk
/data/app/cc.c0ldcat.fxxkmimarket-3laNP0ufoqWWCM26M_pr9A==/base.apk

**Comment by VictorChow** [comment]
130|cepheus:/ # cat /data/system/taichi/apps.list
x.hook.emojihook
com.zzz.pudding
com.tencent.mm
com.miui.player
com.xunlei.downloadprovider
chili.xposed.chimi
com.mhook.dialog
com.lerist.xposed.apptranslator
com.daimajia.gold
com.zhihu.daily.android
com.twitter.android
com.ygkj.chelaile.standard
me.zjns.lovecloudmusic
com.umpay.qingdaonfc
com.jy.xposed.skip
com.sollyu.xposed.hook.model
cc.c0ldcat.fxxkmimarket
com.device.emulator.pro
com.jy.taofanfan
nico.styTool
tv.danmaku.bili
com.rong.xposed.fakelocation
com.smzdm.client.android
com.flo354.xposed.applocale
com.fkzhang.qqxposed
com.sankuai.meituan
com.zhihu.android
com.devicefaker.free
com.fkzhang.wechatxposed
com.tencent.tim
com.specher.music163
com.lucky.luckyclient
com.taobao.taobao
com.sky.xposed.rmad
cn.qssq666.wechat.plus
me.firesun.wechat.enhancement
x.hook.qqemoji
com.viewblocker.jrsen
com.jozein.xedge
com.miui.video
com.ss.android.article.news
com.apkpure.aegon
com.cataclysm.i
cn.wps.moffice_eng
com.wuxiaosu.wechathelper
formatfa.reflectmaster
com.ext.star.wars.vxp
com.ceco.pie.gravitybox
com.sdu.didi.psnger
com.pleasure.trace_wechat
com.wuxianlin.luckyhooker
com.blanke.mdwechat

**Comment by tiann** [comment]
先把上帝模式关掉看看能不能打开？

**Comment by VictorChow** [comment]
@tiann 关掉了上帝模式 目前微信能进来了

**Comment by tiann** [comment]
https://taichi.ctfile.com/fs/19604958-366642931

试试这个呢？

**Comment by VictorChow** [comment]
@tiann 这个5.1.9.7开了上帝模式微信依旧卡黑屏😳

**Comment by tiann** [comment]
上帝模式自身的 bug
