### ISSUE TITLE
magisk下载里面没有taichi magisk 4.9版本

### ISSUE THREAD

**Issue by iaston** [taichi-framework/TaiChi#669]
## 什么问题

124中开启全部应用功能提示要升级magisk插件到4.9.0以上，但magisk仓库里只有4.8.2的版本。

## 详细情况

124中开启全部应用功能提示要升级magisk插件到4.9.0以上，但magisk仓库里只有4.8.2的版本。在微信公众号里也找不到4.9

Magisk 版本：4.8.2
太极 Magisk 模块版本：
太极APP版本：
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：
ROM版本：

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
还有bug，等一等
