### ISSUE TITLE
BUG：5.1.9.6 应用锁模块 开机卡第二屏 （5.1.9.3正常）

### ISSUE THREAD

**Issue by Marukon** [taichi-framework/TaiChi#670]
## 什么问题

卡第二屏

## 详细情况

使用太极Magisk 4.8.2 + 太极 5.1.9.6, 勾选应用锁模块后重启，开机卡第二屏，使用5.1.9.3版本正常

Magisk 版本：19
太极 Magisk 模块版本：4.8.2
太极APP版本：5.1.9.6
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：Nexus 6P
ROM版本：Android P

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。
[apps.zip](https://github.com/taichi-framework/TaiChi/files/3096952/apps.zip)
[modules.zip](https://github.com/taichi-framework/TaiChi/files/3096953/modules.zip)

补充：有能力请务必提供日志文件已快速解决问题。
正在抓取

**Comment by tiann** [comment]
[taichi_5.1.9.7.apk.zip](https://github.com/taichi-framework/TaiChi/files/3096968/taichi_5.1.9.7.apk.zip)

有空的话试试这个

**Comment by Marukon** [comment]
[log.zip](https://github.com/taichi-framework/TaiChi/files/3096969/log.zip)
weishu大大，这是抓取的log，谢谢

**Comment by Marukon** [comment]
> [taichi_5.1.9.7.apk.zip](https://github.com/taichi-framework/TaiChi/files/3096968/taichi_5.1.9.7.apk.zip)
> 
> 有空的话试试这个

5.1.9.7测试可以，多谢
