### ISSUE TITLE
新增模块支持：【ButteredToast】

### ISSUE THREAD

**Issue by 2727682785** [taichi-framework/TaiChi#671]
## 模块用途向 Toast消息头部添加 Toast弹出者的应用名
就是在toast通知上显示是来自哪个应用的

## 模块安装包https://www.coolapk.com/apk/me.zjns.butteredtoast

(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
131
