### ISSUE TITLE
新增模块支持：【亮度保镖】

### ISSUE THREAD

**Issue by 2727682785** [taichi-framework/TaiChi#672]
## 模块名字
亮度保镖
## 模块用途
防止一些应用（如支付宝、微信的付款码）修改亮度。具体做的事情：界面亮度被设置为大于30%时，还原为系统亮度
这样子打开收付款界面就不会突然亮瞎眼了
## 模块版本号
1.4
## 模块安装包
https://www.coolapk.com/apk/cuily.xp1
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
99已经支持了，但是我不得不吐槽这个界面。。。

**Comment by 2727682785** [comment]
谢谢大佬
