### ISSUE TITLE
新增模块支持：【JDHistoryPrice(JD历史价格)】

### ISSUE THREAD

**Issue by jzw3131** [taichi-framework/TaiChi#673]
## 模块名字
JDHistoryPrice(JD历史价格)
## 模块用途
查看京东当前商品的历史价格
在京东商品详情页点击
分享按钮-其他-选择【JD历史价格】
## 模块版本号
0.13
## 模块安装包
链接: https://pan.baidu.com/s/13FJFBirWq70OujDseluJ2A 提取码: tazg 
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
99
