### ISSUE TITLE
太极阳强停的时候可以通过root权限

### ISSUE THREAD

**Issue by kaniwow** [taichi-framework/TaiChi#675]
## 什么问题

希望太极在强停的时候可以通过root权限一键强停大概这种（

## 详细情况

`null`

Magisk 版本：19.0
太极 Magisk 模块版本：4.8.2
太极APP版本：5.1.9.7
开启的 Xposed 模块：`null`
Xposed模块版本：`null`
开启的其他 Magisk 模块：`null`
其他 Magisk 模块版本：`null`
手机型号：Honor10高配版
ROM版本：EMUI9

## 配置文件

`null`

**Comment by tiann** [comment]
随随便便申请 root 权限可不是什么好事。太极本体压根就不需要 root，为了这个功能去拿 root 有点小题大做。
