### ISSUE TITLE
BUG：太极·阴下，腾讯文件、微信读书使用微信登录时提示“签名不对，请检查签名是否与开发平台签名一致。”

### ISSUE THREAD

**Issue by libingtong** [taichi-framework/TaiChi#677]
## 什么问题

太极·阴下，腾讯文件、微信读书使用微信登录时提示“签名不对，请检查签名是否与开发平台签名一致。”
腾讯文件和微信读书已经太极化了。

## 详细情况

在将腾讯文件、微信读书和微信都太极化之后，在腾讯文件、微信读书使用微信登录时还是会提示“签名不对，请检查签名是否与开发平台签名一致。”
![腾讯文件](http://wechat.dgweidao.com/attachment/images/11/2019/04/RWHYBoCISIESccdgVdfwDDwc6GEHSE.jpg)
![太极](http://wechat.dgweidao.com/attachment/images/11/2019/04/nR95gd5VxAhv9Mf492r9J9Y2RarAm2.jpg)
Magisk 版本：
太极 Magisk 模块版本：无
太极APP版本：5.1.3-99
开启的 Xposed 模块：微X模块
Xposed模块版本：2.0
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：华为Mate 20 Pro
ROM版本：9.0.0
## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

**Comment by madaono** [comment]
同样的问题，拼多多调用微信登录，QQ音乐分享到微信等都会报，均已加太极。小米mix2s

**Comment by tiann** [comment]
安装 5.2.1 版本，强制停止微信即可。
