### ISSUE TITLE
BUG:  升级太极magisk4.9.0后,无法开机

### ISSUE THREAD

**Issue by ml863606** [taichi-framework/TaiChi#680]
## 什么问题

升级太极magisk4.9.0后,无法开机

## 详细情况

从太极magisk4.8.2直接升级4.9.0后无法开机

Magisk 版本：19.0
太极 Magisk 模块版本：4.9.0
太极APP版本：5.1.9.7
开启的 Xposed 模块：都开了
Xposed模块版本：
开启的其他 Magisk 模块：mm，音效类，谷歌休doze，unclock gms，viper，voenabler，oxy-ify，shizuku boot
其他 Magisk 模块版本：（无）
手机型号：一加3
ROM版本：RR 7.0.2 PIE

相应的模块文件xml及log日志如下: 
[模块文件xml以及log.zip](https://github.com/taichi-framework/TaiChi/files/3100934/xml.log.zip)
感谢!

**Comment by tiann** [comment]
把 /data/system/taichi 目录删掉先看看，然后能否提供一下日志？

**Comment by ml863606** [comment]
请问是data/local/boot下面的日志吗?如果是的话,已经在上面的"模块文件xml以及log.zip"里面了,我试试删除taichi的目录试试看,谢谢!

**Comment by tiann** [comment]
@ml863606 能否把你的边缘手势拓展模块传上来给我看看？你可以尝试先禁用这个模块，看看能否开机。

**Comment by ml863606** [comment]
[Xposed edge pro-com.jozein.xedgepro-5.3.zip](https://github.com/taichi-framework/TaiChi/files/3105502/Xposed.edge.pro-com.jozein.xedgepro-5.3.zip)

**Comment by tiann** [comment]
请尝试新版。
