### ISSUE TITLE
也不算BUG，是一个小建议：太极阴创建app过程中，建议增加删除太极列表内app选项

### ISSUE THREAD

**Issue by wahowe** [taichi-framework/TaiChi#683]
## 什么问题

建议太极阴创建app过程中，增加删除太极列表内app选项

## 详细情况

太极阴创建app过程中，若取消卸载原app或取消安装新创建的app，
由于原APP未备份等原因中断创建，但太极列表中已经显示app行，
且有橙色警告提示，无法删除。
目前只能继续卸载原APP再安装，然后卸载去除。
 
建议太极阴创建APP过程中增加删除太极列表内app选项，这样更方便些。

Magisk 版本：(无）
太极 Magisk 模块版本：(无）
太极APP版本：5.1.9.7
开启的 Xposed 模块：微X
Xposed模块版本：1.25-8.47
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：OPPO R9splus
ROM版本：7.1.1

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by wahowe** [comment]
![微信图片_20190420094236](https://user-images.githubusercontent.com/36805247/56450252-1c52be00-6357-11e9-98f6-3e44e6bef90a.jpg)

![微信图片_20190420094243](https://user-images.githubusercontent.com/36805247/56450255-1fe64500-6357-11e9-85f4-1f657a1f1e54.jpg)

**Comment by wahowe** [comment]
![微信图片_20190420094236](https://user-images.githubusercontent.com/36805247/56450385-56708f80-6358-11e9-9c30-94dc48b4af06.jpg)

![微信图片_20190420094243](https://user-images.githubusercontent.com/36805247/56450386-596b8000-6358-11e9-8538-b27d10c5de8f.jpg)

**Comment by tiann** [comment]
好建议，下次加上

**Comment by tiann** [comment]
https://github.com/taichi-framework/TaiChi/releases/tag/5.1.10
