### ISSUE TITLE
BUG： 更新新版太极5.1.9.7后QQ和网易云音乐打不开

### ISSUE THREAD

**Issue by bovins** [taichi-framework/TaiChi#685]
## 什么问题

 更新新版太极5.1.9.7后QQ和网易云音乐打不开

详细情况

 更新新版太极5.1.9.7后QQ和网易云音乐打不开，降级到5.0.3版本后正常

Magisk 版本：17.0
太极 Magisk 模块版本：4.9.0
太极APP版本：5.1.9.7
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：小米6
ROM版本：miui10

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by bovins** [comment]
[taiji.zip](https://github.com/taichi-framework/TaiChi/files/3099732/taiji.zip)

**Comment by tiann** [comment]
把 /data/system/taichi  目录删掉再看看呢？

**Comment by bovins** [comment]
删除后网易云音乐正常，QQ依旧打不开
QQ7.9.9 和8.0.0都打不开

**Comment by KylinZhangQAQ** [comment]
我的QQ也炸了

**Comment by tiann** [comment]
其他问题请重新提交
