### ISSUE TITLE
New module support: 公众号不返回内测码，返回软件下载链接

### ISSUE THREAD

**Issue by fightergg2** [taichi-framework/TaiChi#687]
**Describe the bug**
和太极模块无关
我把设备码发到太极的微信公众号“虚拟框架”中，返回给我的是软件的下载链接，不是内测码。
我的设备码是
70abc13f122005d5bd2693012f232829

**To Reproduce**
和太极模块无关
我把设备码发到太极的微信公众号“虚拟框架”中，返回给我的是软件的下载链接，不是内测码。
我的设备码是
70abc13f122005d5bd2693012f232829

**Expected behavior**

**Smartphone (please complete the following information):**
Magisk version：
TaiChi-Magisk module version：
TaiChi version：
Which Xposed modules are enabled ?：
Xposed modules version：
Which Magisk modules are enabled ?：
Magisk modules version：
Device ：
ROM：

**Additional context**

**Comment by tiann** [comment]
太极已经不需要什么内侧码了，直接就可以使用。
