### ISSUE TITLE
BUG：用应用管理xposed压不住微信的定时器和唤醒锁

### ISSUE THREAD

**Issue by mafamily2496** [taichi-framework/TaiChi#690]
## 什么问题

打开应用管理xposed的绿色化，关闭唤醒锁和定时器，用wakelock查看微信依旧有很频繁的唤醒锁和定时器，其中唤醒锁一直是platformcomm在唤醒

## 详细情况

Magisk 版本：19.0
太极 Magisk 模块版本：4.9.0
太极APP版本：5.1.9.6-101
开启的 Xposed 模块：应用管理xposed
Xposed模块版本：5.1.7
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：小米9
ROM版本：miui10 9.4.1

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by mafamily2496** [comment]
com.chaozh.iReader
com.speedsoftware.rootexplorer
com.ray.hlwbinfo
com.linroid.zlive
com.merxury.blocker
com.tencent.mm
com.xunmeng.pinduoduo
com.tencent.mobileqq
com.mimoprint.xiaomi
com.handsgo.jiakao.android
com.click369.controlbp
com.grarak.kerneladiutor
com.sankuai.movie
com.tmri.app.main
com.futuremark.dmandroid.application
com.rarlab.rar
com.coolapk.market
com.netease.cloudmusic
github.tornaco.xposedmoduletest
com.baidu.input
com.miui.calculator
com.baidu.tieba
com.mi.liveassistant
com.microsoft.office.onenote
com.keramidas.TitaniumBackup
com.minhui.networkcapture
me.gfuil.bmap
net.dinglisch.android.taskerm
com.glbenchmark.glbenchmark27
com.microsoft.office.excel
io.telecom.gonghui.gwcx
com.microsoft.office.powerpoint
tv.danmaku.bili
com.duokan.phone.remotecontroller
flar2.devcheck
com.weico.international
com.android.email
com.eg.android.AlipayGphone
com.miui.userguide
com.xiaomi.mibrain.speech
com.zhihu.android
com.waterdaaan.cpufloat
com.websharp.mixmic.activity
org.codeaurora.snapcam
com.microsoft.office.word
com.primatelabs.geekbench
com.xiaomi.mimobile.noti
com.digibites.accubattery
com.google.android.gsf.login
com.taobao.taobao
org.telegram.messenger
com.ioncannon.cpuburn.gpugflops
com.standardar.service
eu.chainfire.perfmon
com.hexin.plat.android
com.tencent.karaoke
com.n0n3m4.gltools
com.xiaomi.jr.security
com.downloading.main.baiduyundownload
com.miui.weather2
cn.gov.tax.its
com.xiaomi.lens
com.ludashi.aibench
com.taobao.idlefish
com.chinatelecom.myctu.tca
com.github.shadowsocks
jackpal.androidterm
eu.tsoml.graphicssettings
me.piebridge.brevent
com.google.android.syncadapters.contacts
com.topjohnwu.magisk
me.weishu.corepatch
com.chinatelecom.bestpayclient
com.tencent.tmgp.pubgmhd
com.baidu.input_mi
com.iflytek.inputmethod.miui
__all__
com.mxtech.videoplayer.pro
com.jingdong.app.mall

**Comment by mafamily2496** [comment]
/data/app/github.tornaco.xposedmoduletest-C8lLGPCY93iI94XXhDKXbg==/base.apk
/data/app/me.weishu.corepatch-XwK9msMZbiXXGkyutqA_Vw==/base.apk
/data/app/com.click369.controlbp-WXlss-_GdfqlzzAp0vRchQ==/base.apk

**Comment by mafamily2496** [comment]
还想问一下如何提供日志？有教程吗

**Comment by Marukon** [comment]
https://github.com/taichi-framework/TaiChi/issues/653 请参考里面的回复 有抓取日志的教程

**Comment by mafamily2496** [comment]
[boot-1970-01-30-17-00-32.log](https://github.com/taichi-framework/TaiChi/files/3112916/boot-1970-01-30-17-00-32.log)

**Comment by tiann** [comment]
能把查看 wakelock 的软件也上传上来吗？

**Comment by mafamily2496** [comment]
![3cf549aae798617a53f8e5e981f995d](https://user-images.githubusercontent.com/13900361/56713899-b2c31d00-6765-11e9-88a4-8d5ce353cab5.png)
![92cc7990514f97e1e7f39850211d362](https://user-images.githubusercontent.com/13900361/56713900-b2c31d00-6765-11e9-8bcc-14690f6e3125.png)

**Comment by tiann** [comment]
WakeLock Detector？这个软件我用不了

**Comment by mafamily2496** [comment]
是WakeLock Detector，你报啥错

**Comment by mafamily2496** [comment]
执行当前任务失败？
