### ISSUE TITLE
模块更新支持：抖音助手 - 4.4.0

### ISSUE THREAD

**Issue by JasonKhew96** [taichi-framework/TaiChi#692]
## 模块名字
抖音助手
## 模块版本号
4.4.0
## 模块更新了什么？
适配抖音5.7.0
## 模块安装包
[com.sky.xposed.aweme_4.4.0_57.zip](https://github.com/taichi-framework/TaiChi/files/3100945/com.sky.xposed.aweme_4.4.0_57.zip)

**Comment by tiann** [comment]
109
