### ISSUE TITLE
BUG：太极Magisk模块在Q DP2上会导致蓝牙无限FC

### ISSUE THREAD

**Issue by CuCuCheung** [taichi-framework/TaiChi#694]
## 什么问题

蓝牙闪退

## 详细情况

第一次用Github，不懂如何添加图片和文件，请开发者见谅

Magisk 版本：19.0
太极 Magisk 模块版本：4.9.0
太极APP版本：5.1.9.7
开启的 Xposed 模块：无
Xposed模块版本：无
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：Pixel 2 XL
ROM版本：Android Q DP2

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by CuCuCheung** [comment]
Hello？

**Comment by lekia** [comment]
已经证实在DP3上问题依旧害得我来了一次恢复工厂……现在看来可能不用Magisk的模块是唯一的方式（哭）

**Comment by CuCuCheung** [comment]
存储重定向的作者我当天提交当天修复。
