### ISSUE TITLE
请求支持Google App 助手1.9.0版本

### ISSUE THREAD

**Issue by ABCxiaoxu** [taichi-framework/TaiChi#699]
- "模块名字"：Google App 助手

- "模块用途"：可以使用Google语音中文助理

- "模块版本号"：1.9.0

- "模块安装包"：com.elderdrivers.googlesearchbox

- content:

- "模块名字"：Google App 助手

- "模块版本号"：1.9.0

- "模块更新"：1.9.0

- "模块安装包"：com.elderdrivers.googlesearchbox

- content:

- "什么问题"：请求支持Google App 助手1.9.0版本

- "详细情况"：请求支持Google App 助手1.9.0版本

- "太极APP版本"：东皇钟·5.1.9.7-104

- "Magisk 版本"：v18.1

- "开启的 Xposed 模块"(无)

- "开启的其他 Magisk 模块"（无）

- "手机型号"Pixel 2 XL

- "ROM版本"：Android9.0.0

**Comment by tiann** [comment]
#709
