### ISSUE TITLE
BUG：希望在全局模式开启后能加入黑名单功能

### ISSUE THREAD

**Issue by pediyzhi** [taichi-framework/TaiChi#700]
## 什么问题

希望在全局模式开启后能加入黑名单功能

## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：18.1
太极 Magisk 模块版本：4.9.0
太极APP版本：5.1.9.7
开启的 Xposed 模块：(无）
Xposed模块版本：(无）
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：小米 mix2
ROM版本：Android 8.1

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
本来就不推荐开启全局模式，有这个需求请手动添加你需要的所有应用。
