### ISSUE TITLE
新增模块支持：Hide USB Debugging Mode

### ISSUE THREAD

**Issue by rexx0520** [taichi-framework/TaiChi#701]
## 模块名字
Hide USB Debugging Mode
## 模块用途
針對應用程式隱藏 USB Debugging 狀態，對某些遊戲特別有用。
## 模块版本号
1.0
## 模块安装包
https://dl-xda.xposed.info/modules/com.redlee90.hideusbdebugging_v1_8f956a.apk
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
107
