### ISSUE TITLE
Bug report: 安卓手表中的微信无法登录

### ISSUE THREAD

**Issue by ausmount** [taichi-framework/TaiChi#703]
**Describe the bug**
使用太极阴，添加微信后，安卓手表无法登录。
**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
Magisk version：
TaiChi-Magisk module version：
TaiChi version：
Which Xposed modules are enabled ?：
Xposed modules version：
Which Magisk modules are enabled ?：
Magisk modules version：
Device ：
ROM：

**Additional context**

**Comment by tiann** [comment]
无法修复
