### ISSUE TITLE
BUG：微信斗图神器和淘饭饭无法正常使用

### ISSUE THREAD

**Issue by js2854** [taichi-framework/TaiChi#704]
## 什么问题

更新模块到4.9.0，太极5.1.9.6之后，微信斗图神器不能用了，淘饭饭淘宝返利不能用了，京东正常

听从作者建议升级太极到5.1.9.7后问题依旧

## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：18.1
太极 Magisk 模块版本：4.9.0
太极APP版本：5.1.9.7
开启的 Xposed 模块：微信增强，微信斗图神器，淘饭饭
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：红米Note5
ROM版本：MIUI10.2.2.0稳定版

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

modules.list

```
/data/app/me.firesun.wechat.enhancement-M9dgiW515AQrjT3e79gGHA==/base.apk
/data/app/x.hook.emojihook-rwpx-eKckJmBS880qTD6jQ==/base.apk
/data/app/com.jy.taofanfan-b5e-CxIMJAvelpmOonbG4g==/base.apk
```

apps.list

```
x.hook.emojihook
com.specher.sm
com.tencent.mm
com.taobao.taobao
com.hiwechart.translate
com.jy.xposed.skip
chili.xposed.chimi
com.jingdong.app.mall
com.jy.taofanfan

```

![image](https://user-images.githubusercontent.com/1471787/56556208-ecf7b780-65c9-11e9-9ca7-a4d936a19668.png)
![image](https://user-images.githubusercontent.com/1471787/56556220-f84ae300-65c9-11e9-92e6-e6f5305d418c.png)
![image](https://user-images.githubusercontent.com/1471787/56556225-00a31e00-65ca-11e9-93dc-41400e9faf28.png)

**Comment by tiann** [comment]
请给我描述一下，什么叫做“不能用”？

**Comment by js2854** [comment]
> 请给我描述一下，什么叫做“不能用”？

1.微信斗图神器，长按+号旁边的笑脸图标，不弹出搜索框
2.淘饭饭，淘宝自动跟单返利不生效，如上截图，APP内只生效了京东；进入淘宝APP，生效状态时，购物页面显示返多少钱，现在不再显示

**Comment by tiann** [comment]
1. 你是不是升级了微信，如果是的话，把微信斗图神器升级到 7.0.4.
2. 这个你得去问淘饭饭，与框架无关。

**Comment by js2854** [comment]
> 1. 你是不是升级了微信，如果是的话，把微信斗图神器升级到 7.0.4.
> 2. 这个你得去问淘饭饭，与框架无关。

好的，感谢回复
