### ISSUE TITLE
模块更新支持：【微信学英语】-【v1.7.91 (54)】

### ISSUE THREAD

**Issue by L-zee** [taichi-framework/TaiChi#707]
## 模块名字
微信学英语
## 模块版本号
v1.7.91 (54)
## 模块更新了什么？
支持微信7.0.4版本
## 模块安装包
包名：com.hiwechart.translate
蓝奏云：https://www.lanzous.com/i3vwxaj?t

**Comment by L-zee** [comment]
酷安都上架了好多天了，适配一下吧..

**Comment by tiann** [comment]
107
