### ISSUE TITLE
Bug report: 坚果pro2s无限重启

### ISSUE THREAD

**Issue by zhuiyi220** [taichi-framework/TaiChi#712]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
Magisk version：
TaiChi-Magisk module version：
TaiChi version：
Which Xposed modules are enabled ?：
Xposed modules version：
Which Magisk modules are enabled ?：
Magisk modules version：
Device ：
ROM：

**Additional context**

**Comment by tiann** [comment]
$463
