### ISSUE TITLE
New module support: MinMinGuard

### ISSUE THREAD

**Issue by killer7Mod** [taichi-framework/TaiChi#714]
## Module name
MinMinGuard
## Usage
Block ads views e url in apps

## Module version 
2.0.5
## APK file
https://dl-xda.xposed.info/modules/tw.fatminmin.xposed.minminguard_v63_c1ee0b.apk

**Comment by iaston** [comment]
@tiann 大佬，这个好像很多人想要哦

**Comment by tiann** [comment]
#28
