### ISSUE TITLE
新增模块支持：【GetVideo】

### ISSUE THREAD

**Issue by 52iptv** [taichi-framework/TaiChi#716]
## 模块名字
GetVideo
## 模块用途
登录自己的视频网站会员账号后，可以解析出视频文件的下载链接，将视频文件保存到本地欣赏
## 模块版本号
V1.3.0
## 模块安装包
链接：https://pan.baidu.com/s/1ASm8NlTDUoA9YRVYAFIjxQ    提取码：ufmv

**Comment by Cowboy-Shuai** [comment]
希望支持太极阴

**Comment by Cowboy-Shuai** [comment]
希望支持太极阴

**Comment by tiann** [comment]
#496
