### ISSUE TITLE
BUG：华为荣耀9太极阳无法清除后台任务

### ISSUE THREAD

**Issue by kukume** [taichi-framework/TaiChi#717]
## 什么问题
华为emui刷太极阳bug
（请简要说明你遇到的问题）

## 详细情况
刷入太极模块之后，从华为任务栏向上滑清除后台任务，无法清除，刷入太极模块之前正常
（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：
太极 Magisk 模块版本：4.91
太极APP版本：最新版
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：华为荣耀9
ROM版本：emui9.1

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by kaniwow** [comment]
附议，荣耀10，EMUI9完美复现
