### ISSUE TITLE
新增模块支持：1ceboxTurner

### ISSUE THREAD

**Issue by rexx0520** [taichi-framework/TaiChi#721]
## 模块名字
1ceboxTurner

## 模块用途
將被冰箱凍結的應用保留在 Launcher 上

## 模块版本号
1.0.3
## 模块安装包

https://ufile.io/k6m9jf2r

**Comment by bycooso** [comment]
> ## 模块名字
> 1ceboxTurner
> 
> ## 模块用途
> 將被冰箱凍結的應用保留在 Launcher 上
> 
> ## 模块版本号
> 1.0.3
> 
> ## 模块安装包
> https://ufile.io/k6m9jf2r
