### ISSUE TITLE
BUG：Magisk模块直接更新后一直处于开机界面

### ISSUE THREAD

**Issue by ChromeHu** [taichi-framework/TaiChi#724]
## 什么问题

在更新Magisk模块后出现了重启一直处于开机加载界面

## 详细情况

1. 在Magisk Manager中更新模块后重启，之后一直处于开机加载。
2. 进入Rec使用MM禁用后可以快速进入系统。
3. 系统中重新勾选模块重启依旧出现问题
4. 重新MM禁用进入系统后，卸载太极app，重新勾选模块重启。***可以进入系统***
5. 系统中重装太极可用。

Magisk 版本：V18.1
太极 Magisk 模块版本：V4.9.1
太极APP版本：东皇钟-5.1.3
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：小米5X
ROM版本：PE（pie）

>手机发布的问题不好补充，主要是想知道一下是不是能直接更新Magisk，还是有什么步骤

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
太极升级到最新版，或者降级magisk模块即可。

**Comment by ChromeHu** [comment]
两个最新版都可以用，问题关键点是Magisk模块升级后会出现开机卡加载的问题。如果要避免就需要升级完模块后先将太极的app卸载重启，这样开机就正常。我不知道正确的升级是怎样操作的，也没有看到关于Magisk模块升级的说明，不过每次升级都要卸载重新安装配置太极步骤还是有点麻烦的。

**Comment by tiann** [comment]
magisk 版本和太极版本要匹配的。如果你不放心，可以把太极/magisk模块都卸载，然后重装最新版就行。

如果你每次都追随太极的最新版，而不是从 5.1.3 跨多版本升级，一般就不会有这个问题。

**Comment by Lucaallin77** [comment]
请问卡住了怎么开机设置啊
