### ISSUE TITLE
模块更新支持：【小米机型伪装模块】-【0.3.6.20190429.af38eb3】

### ISSUE THREAD

**Issue by mokapsing** [taichi-framework/TaiChi#731]
## 模块名字
小米机型伪装模块
## 模块版本号
0.3.6.20190429.af38eb3
## 模块更新了什么？
性能优化，减少耗电
## 模块安装包
https://github.com/MiPushFramework/MiPushFramework/releases/download/0.3.6.20190429.af38eb3/xmsf_service.apk

**Comment by tiann** [comment]
#464 新版并没有解决这个问题。
