### ISSUE TITLE
新增模块支持：【BiliRoaming】

### ISSUE THREAD

**Issue by memphise** [taichi-framework/TaiChi#737]
## 模块名字
BiliRoaming（哔哩漫游）
## 模块用途
绕过地区限制，观看港澳台番剧
## 模块版本号
1.0.8
## 模块安装包
https://github.com/iAcn/BiliRoaming/releases/download/v1.0.8/BiliRoaming_1.0.8.apk

(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

太极只支持到1.0.7，作者已经更新到1.0.8版本了，希望可以添加相关的支持。
已经和作者沟通过，作者同意到太极这里提交支持。
具体见： https://github.com/iAcn/BiliRoaming/issues/6

**Comment by tiann** [comment]
128
