### ISSUE TITLE
New module support: [Lucky Patcher] 

### ISSUE THREAD

**Issue by RebelLion420** [taichi-framework/TaiChi#744]
## Module name
Lucky patcher

## Usage
Patches to Android for IAP and Billing emulation

## Module version 
8.3.1

## APK file

https://mega.nz/#!1rh02CSC!k8pTFO9sjHGvKQiiEXt3wcathHMUprBuL4yShnJcd3A

**Comment by trinaldi** [comment]
The file you are trying to download is no longer available.

**Comment by Tuxiis** [comment]
You will have a more current lucky patcher apk.
