### ISSUE TITLE
New module support: [Statusbar Download Progress]

### ISSUE THREAD

**Issue by RebelLion420** [taichi-framework/TaiChi#745]
## Module name
Statusbar Download Progress

## Usage
Shows download progress bar in statusbar for downloads carried out via Androids standard download manager

## Module version 
4.0.0

## APK file
https://mega.nz/#!N3giRIwB!lOWrykYa01hqCUDyvW2eicrByJeS7ttw0-QJzJ8b_vA

**Comment by tiann** [comment]
136
