### ISSUE TITLE
BUG：修改为你遇到的问题的详细描述

### ISSUE THREAD

**Issue by chenhaonan520** [taichi-framework/TaiChi#747]
## 什么问题

渡劫的应用闪退

## 详细情况

在更新了太极框架之后，原先渡劫过的APP闪退，然后把太极和APP删除之后重新安装，APP渡劫后依然闪退，卸载重装几次仍然无解

Magisk 版本：
太极 Magisk 模块版本：
太极APP版本：东皇钟5.1.10
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：魅蓝3
ROM版本：flyme 6.3.0.3A

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

(手机没有root权限)
补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
信息不足，请升级到最新版 5.1.12，如果问题依然出现，补充后重新提交。
