### ISSUE TITLE
BUG 华为EMUI9.1使用太极时的问题

### ISSUE THREAD

**Issue by 1604589485** [taichi-framework/TaiChi#749]
## 什么问题
华为emui9.1想要使用太极必须先刷入太极面具模块 再装太极APP 并且不能重启 如果重启会开华为的logo

## 详细情况
华为emui9.1想要使用太极必须先刷入太极面具模块 再装太极APP 并且不能重启 如果重启会开华为的logo
我想是太极APP的问题 
Magisk 版本：
太极 Magisk 模块版本：4.9.1
太极APP版本：5.1.12
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：华为mate20 Pro
ROM版本：9.1.0.119

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by 1604589485** [comment]
我使用的是官改的ROM

**Comment by xiaomoqi520** [comment]
一样的，我华为9.1系统，刷面具，刷模块后，装太极APP，重启也是卡LOGO图标。

**Comment by digitbear** [comment]
从app开发者角度说一下。EMUI是所有ROM里最不规范、系统bug最多、最难适配的，没有之一，有些问题甚至完全无解。一旦QA团队报了单一机型的bug，十之八九是华为手机上出现的问题。相比之下，MIUI极其稳定，框架实现极其规范，除了个别老机型有些莫名其妙的小问题以外，基本是除了原生系统以外标杆一样的存在。从适配难度来说，如果以原生系统为10分给常见系统打分的话，MIUI新机型9.5分，老机型8分，flyme 9分，ov两家新机型9分，老机型4分，EMUI老机型5分，新机型3分不能更多了（就是越改越糟糕）。

作者：kingofne
链接：https://www.zhihu.com/question/47320215/answer/548123522
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

**Comment by tiann** [comment]
[logcat_v13.2.zip](https://github.com/taichi-framework/TaiChi/files/3160152/logcat_v13.2.zip)
刷一下这个日志模块，然后复现场景，把 /data/local/boot 下所有的日志文件发我看看

**Comment by 1604589485** [comment]
日志链接接:https://pan.baidu.com/s/1zSPsECnsRI50TISYPHzw6g 提取码:22nt 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by tiann** [comment]
[app-release.apk.zip](https://github.com/taichi-framework/TaiChi/files/3165245/app-release.apk.zip)
@1604589485 测试下这个是否正常

**Comment by 1604589485** [comment]
重启还是卡logo 日志的话在我的那个分享的百度网盘里面 5月10日的那个

**Comment by 1604589485** [comment]
面具版本的话是基于emui9.1编译的 是ROM作者kangvip 弄的 并不是面具作者的v19.1

**Comment by 1604589485** [comment]
他的微信号是Kangvip0811 你可以尝试联系一下他

**Comment by 1604589485** [comment]
希望这能对你有所帮助

**Comment by evol5201314** [comment]
wei叔。求修复。离不开太极。呜呜呜

**Comment by xiaomoqi520** [comment]
求修复。。手机不敢重启

**Comment by tiann** [comment]
[app-release.apk.zip](https://github.com/taichi-framework/TaiChi/files/3166192/app-release.apk.zip)
试一下这个

**Comment by evol5201314** [comment]
这是卡刷包还是apk啊。改后辍apk不能安装。解析包失败

**Comment by 1604589485** [comment]
还是会卡logo，相关日志我已经发到百度网盘了 是5月10日 晚7点23分的那个文件夹

**Comment by evol5201314** [comment]
依然卡关机

**Comment by evol5201314** [comment]
我也帮你发日志

**Comment by evol5201314** [comment]
链接:https://pan.baidu.com/s/132dO9MyrJXgySec0gk6riQ 提取码:8oj8 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by xiaomoqi520** [comment]
求修复。。手机不敢重启

**Comment by evol5201314** [comment]
有什么别的好办法可以帮助wei叔你修复吗，我愿意当试验机😊

**Comment by tiann** [comment]
[app-release.apk.zip](https://github.com/taichi-framework/TaiChi/files/3166384/app-release.apk.zip)

你刷的这个 magisk 功能是不完整的，它的 magiskpolicy 压根就工作。magiskpolicy 是太极·阳能工作的前提。如果我发的这个依然卡开机，那我也没什么办法，只有用太极·阴了。

**Comment by evol5201314** [comment]
链接:https://pan.baidu.com/s/1uFaE4M4xxz0sv2w793hsUg 提取码:9sh5 复制这段内容后打开百度网盘手机App，操作更方便哦
看看我的日志

**Comment by 1604589485** [comment]
这次没有卡开机 厉害了
