### ISSUE TITLE
BUG：nagisk版导致主题冲突

### ISSUE THREAD

**Issue by vonf** [taichi-framework/TaiChi#751]
## 什么问题
BUG：magisk版用久了不论是不是全局都会感染android系统进程，使导致主题冲突
（请简要说明你遇到的问题）

## 详细情况

（禁用magisk太极模块会变正常）

Magisk 版本：
太极 Magisk 模块版本：4.91
太极APP版本：5.11
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(有）
其他 Magisk 模块版本：（）
手机型号：索尼xzp
ROM版本：10.45

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
什么是主题冲突？
