### ISSUE TITLE
新增模块支持：【MyHXC1.4】

### ISSUE THREAD

**Issue by zbr878458173** [taichi-framework/TaiChi#753]
## 模块名字
MyHXC1.4
## 模块用途
实现 含羞草 免账号登陆看视频
## 模块版本号
1.4
## 模块安装包
https://pan.baidu.com/s/16gKfz_zW78GNvFl7TeldkQ 提取码: 2jrr

**Comment by zbr878458173** [comment]
大佬，我是你的忠实粉丝了，从以前的vaexposed就一直在用。也捐过款，只求大佬帮我适配一下这个插件啊。我现在太极和virtualXposed都有装，求大佬帮我减轻负担啊，留太极就够了。。不行我就再捐点儿。

**Comment by tiann** [comment]
更新到 164 试试看能否正常使用
