### ISSUE TITLE
新增模块支持：【抹机王】

### ISSUE THREAD

**Issue by ik518** [taichi-framework/TaiChi#756]
## 模块名字
抹机王
## 模块用途
抹机
## 模块版本号
4.2.7.1
## 模块安装包
http://down.xiaoanapp.com/soft/app/wipingking.apk
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
MIX 2S Android 9.0 不加入太极不进行任何操作，打开此APP无限白屏。
