### ISSUE TITLE
新增模块支持：【ShortcutsX】

### ISSUE THREAD

**Issue by a857112551** [taichi-framework/TaiChi#757]
## 模块名字
ShortcutsX
## 模块用途
为不支持Shortcuts的功能的app添加支持
## 模块版本号
1.7.0
## 模块安装包
http://zhuye.ml/share/ShortcutsX-1.7.0.apk

**Comment by a857112551** [comment]
小米6
miui10 9.5.14
安卓9
无法打开，白屏

**Comment by tiann** [comment]
这模块本身就不支持 9.0 吧
