### ISSUE TITLE
太极阴 5.1.11 Android 5.x 不兼容

### ISSUE THREAD

**Issue by chenhaonan520** [taichi-framework/TaiChi#758]
## 什么问题

在升级了改版本的太极之后，很多插件无法使用

## 详细情况
升级之后，q++模块提示“账号信息无法获取。。。。”，无法使用，
以及文本替换插件也无法使用
(其他插件的我没试过)

卸载之后安装回5.1.1老版本之后可正常使用，没有任何问题

Magisk 版本：无
太极 Magisk 模块版本：无
太极APP版本：5.1.11
开启的 Xposed 模块：q++，文本替换
Xposed模块版本：1.3.1
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：魅族m3
ROM版本：flyme 6.3.0.3a

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
Android 系统是什么版本？

**Comment by chenhaonan520** [comment]
上面软件名称表述有误，“文本替换”应为“文本自定义”

**Comment by chenhaonan520** [comment]
安卓系统的版本是5.1的

**Comment by tiann** [comment]
5.2.0 fixed
