### ISSUE TITLE
BUG：安装magisk模块后无法开机

### ISSUE THREAD

**Issue by sadDarkHorse** [taichi-framework/TaiChi#760]
## 什么问题
在magisk里安装太极模块后无法开机，卡在开机界面一段时间后重启跳到recovery

## 详细情况
在magisk里安装太极模块后无法开机，卡在开机界面一段时间后重启跳到recovery
用magisk manager 在recovery下将模块卸载后可以开机
Magisk 版本：v19.1
太极 Magisk 模块版本：v4.9.1
太极APP版本：5.1.11-125
开启的 Xposed 模块：(无）
Xposed模块版本：（无）
开启的其他 Magisk 模块：youtube vanced;magisk manager
其他 Magisk 模块版本：v14.10.53;2019.4.4
手机型号：小米5s
ROM版本：MIUI 10 Global 9.5.9

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
Android 系统版本多少？

**Comment by sadDarkHorse** [comment]
8.0.0
OPR1.170623.032

**Comment by sadDarkHorse** [comment]
请问如何把配置文件发上来
我已经找到了，可是我不会发

**Comment by tiann** [comment]
先把 `/data/system/taichi` 这个目录删了看看能不能开机

**Comment by sadDarkHorse** [comment]
可以了，谢谢

**Comment by jojolfy** [comment]
太极是个什么鬼，我安装了magisk后也开不了机，recovery模式下没有taichi目录

**Comment by ztpxxzt** [comment]
删了能进系统  可是怎么把太极magisk刷进去呢
