### ISSUE TITLE
新增模块支持：【小鬼微信】

### ISSUE THREAD

**Issue by payshin** [taichi-framework/TaiChi#763]
## 模块名字
小鬼微信
## 模块用途
微信防撤回，微信群发，微信批量添加好友，微信自动加群，微信批量拉群，微信模拟位置
## 模块版本号
1.6.0
## 模块安装包
https://github.com/payshin/wechatime/releases
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
打开黑屏，无法使用。

**Comment by payshin** [comment]
> 打开黑屏，无法使用。

你好，请问要如何测试呢？这边自己安装上太极阴，但没法勾上，也就没法测试。
因为这边测试XPOSED，virtualxposed,分身X版都是正常的。但是太极阴无法测试。
