### ISSUE TITLE
BUG：修改为你遇到的问题的详细描述

### ISSUE THREAD

**Issue by danyuhao** [taichi-framework/TaiChi#765]
## 什么问题

太极阴无法变成太极阳

## 详细情况

按照官网操作
1. 刷入magisk（+manager）
2. magisk 菜单download中搜索tai chi，下载tai chi 4.9.1模块安装，然后重启
3. 手机从浏览器搜索稳定版网址链接，然后下载太极5.1.11
4.下载完成直接安装后，显示还是太极阴
5. 重启系统后，进入太极应用依然显示太极阴
6. 进入magisk菜单modules，发现 Tai chi v4.9.1模块已经被check，并且无其他模块

Magisk 版本：v.19.1
太极 Magisk 模块版本：4.9.1
太极APP版本：东皇钟-5.1.11-210
开启的 Xposed 模块：无
Xposed模块版本：无
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：三星s6 edge+ （9280G)
ROM版本：Android 7.0

## 配置文件

C:\Users\msi>adb pull /data/system/taichi/modules.list
adb: error: remote object '/data/system/taichi/modules.list' does not exist

C:\Users\msi>adb pull /data/system/taichi/apps.list
adb: error: remote object '/data/system/taichi/apps.list' does not exist

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by danyuhao** [comment]
尝试回退到Magisk 版本：v.17.1失败，无法回退
尝试刷入太极 Magisk 模块版本：4.7.0问题依旧
重启后，启动太极log如下：
[log.txt](https://github.com/taichi-framework/TaiChi/files/3170906/log.txt)

**Comment by tiann** [comment]
太极·阳 不对 Android 8.0 以下的系统做任何可以运行的保证。https://github.com/taichi-framework/TaiChi/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8

**Comment by danyuhao** [comment]
ok，知道了
