### ISSUE TITLE
新增模块支持：【模块名】AllrotationEnable

### ISSUE THREAD

**Issue by cs10108** [taichi-framework/TaiChi#770]
## 模块名字
AllrotationEnable
# 模块用途
Miui沒辦法垂直倒轉180度屏幕
可解鎖無法旋轉180度問題
https://forum.xda-developers.com/xposed/modules/xposed-allrotationsenable-t3729490/post75061311#post75061311
# 模块版本号
1.0
## 模块安装包
鏈接:https://pan.baidu.com/s/1syDZ0gFAPFFdsBXQRSmxJg 密码:03h8
请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by cs10108** [comment]
有消息嗎

**Comment by tiann** [comment]
#828
