### ISSUE TITLE
新增模块支持：【模块名】XX抹机助手

### ISSUE THREAD

**Issue by 2149624900** [taichi-framework/TaiChi#775]
## 模块名字
XX抹机助手
## 模块用途
研究 学习 改机
## 模块版本号
6.3.9
## 模块安装包

(请务必给出模块的
[320叉叉抹机_破解版_6.3.9.zip](https://github.com/taichi-framework/TaiChi/files/3177821/320._._6.3.9.zip)

安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
破解？？

**Comment by 2149624900** [comment]
上传错了。。我重新上传一个。。




------------------ 原始邮件 ------------------
发件人: "weishu"<notifications@github.com>;
发送时间: 2019年5月14日(星期二) 晚上9:19
收件人: "taichi-framework/TaiChi"<TaiChi@noreply.github.com>;
抄送: "bkhd敢径"<2149624900@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [taichi-framework/TaiChi] 新增模块支持：【模块名】XX抹机助手 (#775)




破解？？

**Comment by 2149624900** [comment]
老铁辛苦了   我提交的这几个模块  大概需要多久能适配出来呢




------------------ 原始邮件 ------------------
发件人: "weishu"<notifications@github.com>;
发送时间: 2019年5月14日(星期二) 晚上9:19
收件人: "taichi-framework/TaiChi"<TaiChi@noreply.github.com>;
抄送: "bkhd敢径"<2149624900@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [taichi-framework/TaiChi] 新增模块支持：【模块名】XX抹机助手 (#775)




破解？？

**Comment by meikongwenni** [comment]
这个是破解版吗？
正版关闭服务器的话这个还能用吗？
