### ISSUE TITLE
新增模块支持：【模块名】XX抹机助手

### ISSUE THREAD

**Issue by 2149624900** [taichi-framework/TaiChi#776]
## 模块名字
XX抹机助手
## 模块用途
研究 学习  交流 改机
## 模块版本号
6.3.9
## 模块安装包
[xx抹机神器_6.3.9.zip](https://github.com/taichi-framework/TaiChi/files/3178017/xx._6.3.9.zip)

(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by online298** [comment]
请问什么时间可以适配这个模块，急需啊！

**Comment by tiann** [comment]
#828

**Comment by 2149624900** [comment]
老铁。。看不懂英文。。是支持了吗




------------------ 原始邮件 ------------------
发件人: "weishu"<notifications@github.com>;
发送时间: 2019年6月2日(星期天) 上午10:55
收件人: "taichi-framework/TaiChi"<TaiChi@noreply.github.com>;
抄送: "bkhd敢径"<2149624900@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [taichi-framework/TaiChi] 新增模块支持：【模块名】XX抹机助手 (#776)




#828
