### ISSUE TITLE
新增模块支持：【模块名】私信插件

### ISSUE THREAD

**Issue by 2149624900** [taichi-framework/TaiChi#777]
## 模块名字
私信插件
## 模块用途
研究 学习
## 模块版本号
1.0
## 模块安装包
[111.zip](https://github.com/taichi-framework/TaiChi/files/3178073/111.zip)

(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
#828

**Comment by 2149624900** [comment]
我打开了太极  还是没有见可以支持啊




------------------ 原始邮件 ------------------
发件人: "weishu"<notifications@github.com>;
发送时间: 2019年6月2日(星期天) 中午11:05
收件人: "taichi-framework/TaiChi"<TaiChi@noreply.github.com>;
抄送: "bkhd敢径"<2149624900@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [taichi-framework/TaiChi] 新增模块支持：【模块名】私信插件 (#777)




Closed #777.
