### ISSUE TITLE
新增模块支持：【Czero】

### ISSUE THREAD

**Issue by 1536455187** [taichi-framework/TaiChi#781]
## 模块用途 Czero是一款用于手机信息伪装的工具类APP，简单来说Czero就是，修改手机及模拟器的硬件信息、MAC、无线网、串码等信息，用户可以一键清空应用数据，拦截应用root检测，全方位伪装手机信息。
Czero有哪些功能
随意修改手机imei串号信息
随意修改手机品牌、型号等参数信息
随意修改手机MAC信息
随意修改手机号码、运行商等信息
拦截手机root信息
清除勾选应用数据

## 模块安装包https://share.weiyun.com/5bgwoWw

(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
#828

**Comment by yeming959** [comment]
我想知道模拟器如何使用？或者说手机模拟器如何开启太极阳
