### ISSUE TITLE
模块更新支持：【LineHack】-【0.8.2】

### ISSUE THREAD

**Issue by tomissmart86520** [taichi-framework/TaiChi#783]
## 模块名字
LineHack
## 模块版本号
0.8.2
## 模块更新了什么？
還是只支援line 9.6.1，只是更改了幾個小bug, 並把那個大廣告給拿掉了
這次終於把版本移至AS, Eclipse真的要淘汰了
## 模块安装包
https://my.pcloud.com/publink/show?code=XZV2xU7ZIOaBIIkKJ1SQXtPQhezfD4izv3p7

**Comment by tiann** [comment]
你可以在太极的模块后台 http://admin.taichi.cool/ 注册一个账号，这样以后你就可以自行更新这个模块了。

**Comment by inalam** [comment]
hello @tomissmart86520 are you the developer of linehack? i really use that module, but i'm using normal xposed. i have tried that 0.8.2 version but no luck. please help
