### ISSUE TITLE
模块更新支持：【GrindrMod】 - 【5.8.1】

### ISSUE THREAD

**Issue by MatrixLau** [taichi-framework/TaiChi#784]
## 模块名字 
GrindrMod

## 模块版本号
5.8.1

## 模块更新了什么？
更新了对新版Grindr的支持

## 模块安装包 
链接:https://pan.baidu.com/s/1hBKif4lNdlofSuAXZ72gxA 提取码:9yko

**Comment by tiann** [comment]
#828
