### ISSUE TITLE
emui使用太极的问题

### ISSUE THREAD

**Issue by 1604589485** [taichi-framework/TaiChi#785]
## 什么问题
（请简要说明你遇到的问题）
在我以前反馈了之后  您给了我一个不卡开机的太极版本，我今天在太极里 看到了更新的提醒
然后去更新了 结果还是和以前一样卡logo 希望修复这个bug  但这次面具版本是19.1
日志文件我也也会发百度网盘 我会把链接放在下面的 请尽快修复

Magisk 版本：19.1
太极 Magisk 模块版本：4.9.1
太极APP版本：5.2.0-232
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：mate20pro
ROM版本：Kangvip

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

日志链接: https://pan.baidu.com/s/1zcQTsYOK-XupFl8eKxTWow 提取码: kj7x 
是5月17日太极更新5.2.0卡logo的那个文件夹

**Comment by tiann** [comment]
那是为你们华为特别打的包，别升级就行了
