### ISSUE TITLE
Bug report: Xinternal SD 在小米平板4上没有生效

### ISSUE THREAD

**Issue by nmaccount** [taichi-framework/TaiChi#787]
**Describe the bug**

Xinternal SD 在小米平板4上没有生效。已经在太极APP里勾选了模块和安装了APP，但是设置的SD路径下没有生成APP的文件夹，而在内部存储里却看到了对应的APP文件夹，似乎Xinternal SD没有生效

**To Reproduce**
1. 安装Xinternal SD模块
2. 模块管理里勾选Xinternal SD模块
3. 安装kindle APP到太极APP

**Expected behavior**
Xinternal SD勾选生效后，APP的文件夹应该生成在Xinternal SD里设置的存储路径，而不是在内部存储里生成

**Smartphone (please complete the following information):**
Magisk version：NA
TaiChi-Magisk module version：NA
TaiChi version：5.2.0-232
Which Xposed modules are enabled ?：Xinternal SD 
Xposed modules version：4.8
Which Magisk modules are enabled ?：NA
Magisk modules version：NA
Device ：小米平板4
ROM：MIUI9.6.3.0

**Comment by tiann** [comment]
不支持 x86
