### ISSUE TITLE
BUG：每次安装字体模块或者其他模块都报Error:22

### ISSUE THREAD

**Issue by sd19836311** [taichi-framework/TaiChi#788]
## 什么问题

（每次安装新magisk模块后重启，报错显示Error:22）

## 详细情况

（每次安装新magisk模块后重启，报错显示Error:22）

Magisk 版本：19.2
太极 Magisk 模块版本：4.9.1
太极APP版本：东皇钟 5.2.0-232
开启的 Xposed 模块：绿色守护4.6.3，大圣净化1.8.6，钉钉助手1.1.5，QX模块1.21，微X模块2.2，MDwechat3.5.0 ,酷狗音乐1.1，Screenshot Delay Remover -mod 1.1
Xposed模块版本：
开启的其他 Magisk 模块：蝰蛇音效4.2 思源柔黑字体1.0
其他 Magisk 模块版本：（无）
手机型号：小米8 
ROM版本：MIUI 10.2.3.0

## 配置文件

apps.list文件内容
com.fkzhang.qqxposed
me.firesun.wechat.enhancement
bin.xposed.screenshotdelayremover.mod
com.jozein.xedgepro
com.zdy.project.wechat_chatroom_helper
com.tencent.mm
com.oasisfeng.greenify
com.tencent.mobileqq
me.veryyoung.dingding.luckymoney
com.example.wx_plug_in3
kg.crack
com.ext.star.wars.vxp
com.fkzhang.wechatxposed
com.sky.xposed.rimet
__all__
com.conch.bluedhook
com.kugou.android
com.alibaba.android.rimet
com.blanke.mdwechat

modules.list内容
/data/app/com.oasisfeng.greenify-Mkj6rUz6Brcz_MUc4NHMDg==/base.apk
/data/app/com.sky.xposed.rimet-tu9g2KNhGU3x3Tci_o479Q==/base.apk
/data/app/com.conch.bluedhook-A_6SEUiTTu8hPRLXnDv4ug==/base.apk
/data/app/com.ext.star.wars.vxp-Qiv5ZzPm9GiY52uqAWArAA==/base.apk
/data/app/com.fkzhang.qqxposed-MhZJN9ZQp4RQz46xegHzng==/base.apk
/data/app/com.blanke.mdwechat-hWu5VpBfFUSbCHqYYmAeIw==/base.apk
/data/app/com.fkzhang.wechatxposed-r7B-uDcq4YkDEM_-tkNRYA==/base.apk
/data/app/bin.xposed.screenshotdelayremover.mod-8lDh7gRfd1mxWJHfv9krTQ==/base.apk
/data/app/com.jozein.xedgepro-h_0fCiupJINR_Vgf614Mgg==/base.apk
/data/app/kg.crack-o2iYylNHPPQapzJg4IDpcw==/base.apk

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by VictorChow** [comment]
更新适配引擎试试？

**Comment by tiann** [comment]
不影响使用
