### ISSUE TITLE
如何开发太极模块？

### ISSUE THREAD

**Issue by encoderlee** [taichi-framework/TaiChi#789]
开发太极模块有什么要求？
我在android studio中使用
provided 'de.robv.android.xposed:api:82'
开发xposed模块，在xposed和virtualxposed里均能正常运行
但是在太极的“模块管理”中，显示我开发的模块为“暂不支持”
如何才能开发出被太极支持的模块？

**Comment by uweii** [comment]
这个怎么处理的，自己写的xp模块，导入太极显示不支持

**Comment by wufeng0927** [comment]
> 这个怎么处理的，自己写的xp模块，导入太极显示不支持

请问这个问题你后来怎么处理的？

**Comment by ShengliangD** [comment]
我也遇到了这个问题，请问应该怎么解决？

**Comment by wufeng0927** [comment]
@ShengliangD 应该是需要联系作者，然后加白名单。
