### ISSUE TITLE
如何开发太极模块？

### ISSUE THREAD

**Issue by encoderlee** [taichi-framework/TaiChi#790]
## 什么问题

自己开发的xposed模块，在太极的“模块管理”中显示为“暂不支持”

## 详细情况

开发太极模块有什么要求？
我在android studio中使用
provided 'de.robv.android.xposed:api:82'
开发xposed模块，在xposed和virtualxposed里均能正常运行
但是在太极的“模块管理”中，显示我开发的模块为“暂不支持”
如何才能开发出被太极支持的模块？

Magisk 版本：
太极 Magisk 模块版本：
太极APP版本：
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：
ROM版本：

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

**Comment by payshin** [comment]
显示不支持并不是真的不支持，只是你的APP没在白名单中。

**Comment by canyie** [comment]
联系作者添加白名单。

**Comment by encoderlee** [comment]
原来如此

**Comment by XhstormR** [comment]
哇，好坑爹，我说怎么一直显示暂不支持，调了好久的配置和代码，原来是因为不在白名单里面。。。。

**Comment by answer1874** [comment]
作者帮你开通了吗  我联系不上 发邮件都没回-.-!

**Comment by encoderlee** [comment]
@answer1874  我放弃了，封闭式产品不考虑

**Comment by answer1874** [comment]
> @answer1874 我放弃了，封闭式产品不考虑

-。=！ 好吧 我也是大半个月了 联系不上作者
