### ISSUE TITLE
新增模块支持：【微大师】

### ISSUE THREAD

**Issue by iori8421** [taichi-framework/TaiChi#795]
## 模块名字
微大师
## 模块用途
汇聚微信朋友圈热门转发趣图，朋友圈搞笑群视频，10秒小视频，朋友圈文字配图，早安、晚安问候语、微商文案素材等精选资源，让你的朋友圈不再单调无趣。
## 模块版本号
1.0.6
## 模块安装包
https://dl-xda.xposed.info/modules/com.wxapp.moment_v7_ed3dfe.apk
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
#828
