### ISSUE TITLE
新增模块支持：【bgoUnlockFPS】

### ISSUE THREAD

**Issue by destinybond** [taichi-framework/TaiChi#796]
## 模块名字
bgoUnlockFPS
## 模块用途
为BGO（Fate / GO_bili_version）v1.45.2版本提供在手机上解锁60FPS的模块
## 模块版本号
暂无
## 模块安装包
https://github.com/nishuoshenme/bgoUnlockFPS
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
#828
