### ISSUE TITLE
新增模块支持：【小鬼微信】

### ISSUE THREAD

**Issue by payshin** [taichi-framework/TaiChi#797]
## 模块名字
小鬼微信
## 模块用途
微信防撤回，微信群发，微信批量添加好友，微信自动加群，微信批量拉群，微信模拟位置
版本更新，修复在某种特殊情况下导致的黑屏卡顿问题。
## 模块版本号
1.6.1
## 模块安装包
https://github.com/payshin/wechatime/releases/download/releases/1.6.1.3.apk
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
#828
