### ISSUE TITLE
BUG：软重启

### ISSUE THREAD

**Issue by bugtouch** [taichi-framework/TaiChi#799]
## 什么问题

经常软重启

## 详细情况

就是突然屏幕一黑，这样卡着卡半分钟到一两分钟，然后屏幕上就显示一行英文"Find Device closed unexpectedly."，大概使用几十分钟到一小时就会这样一次

Magisk 版本：19.2(19102)
太极 Magisk 模块版本：4.9.1
太极APP版本：5.2.0
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：Mix2s
ROM版本：9.5.20

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。
[taichi.zip](https://github.com/taichi-framework/TaiChi/files/3200183/taichi.zip)

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
为什么不升级到 MIUI 10呢？我也是  MIX 2S 没有任何问题。

**Comment by bugtouch** [comment]
我的就是MIUI10。。。。。
---原始邮件---
发件人:"weishu"<notifications@github.com>
发送时间:2019年5月21日 星期二 上午10:6
收件人:"taichi-framework/TaiChi"<TaiChi@noreply.github.com>
抄送:"bugtouch"<2270924234@qq.com>;"Manual"<manual@noreply.github.com>
主题:Re: [taichi-framework/TaiChi] BUG：软重启 (#799)

为什么不升级到 MIUI 10呢？我也是  MIX 2S 没有任何问题。

&mdash;

**Comment by bugtouch** [comment]
不只是mix2s，我在酷安搜相关关键词，其他机型也有这样的。。也是用了太极

**Comment by tiann** [comment]
所以你想表达什么？每个人的问题都不一样，怎么能一概而论呢？
