### ISSUE TITLE
BUG：华为EMUI9.1使用5.2.0太极依然卡LOGO

### ISSUE THREAD

**Issue by xiaomoqi520** [taichi-framework/TaiChi#801]
## 什么问题

华为EMUI9.1使用5.2.0太极依然卡LOGO

## 详细情况

跟这个问题一样
https://github.com/taichi-framework/TaiChi/issues/749
升级了面具19.2，同时升级了太极5.2.0，依然卡LOGO，
如果用之前这个问题里面的版本，正常的。
可否新版本把这个版本修改的增加到新版本呢？
![111](https://user-images.githubusercontent.com/48594873/58066147-b60dc500-7bba-11e9-8bbe-4f53744b48f2.png)

Magisk 版本：19.2
太极 Magisk 模块版本：v4.9.1
太极APP版本：5.2.0
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：HUAWEI mate20 
ROM版本：

**Comment by tiann** [comment]
你用那个 issue 里面的 apk就行了，这个暂时不会放在主干版本里面，因为别的用户无法使用。
