### ISSUE TITLE
模块更新支持：【chimi】-【2.5.26】

### ISSUE THREAD

**Issue by xiuluo** [taichi-framework/TaiChi#809]
## 模块名字
chimi
## 模块版本号
2.5.26
## 模块更新了什么？
1.修复9.0系统部分功能失效问题（高级电源菜单，网速频率等）
2.增加Android9.0核心破解功能
3.增加实验室开启全面屏手势可使用实体按键功能
4.增加时钟常显功能（桌面上有时钟小部件时状态栏时钟也显示）
5.时钟大小自定义功能，电量数字大小自定义功能
6.电量数字百分比隐藏
7.增加锁屏界面双击息屏功能
## 模块安装包
https://github.com/yonghen/chimi-/releases/download/v2.5.26/ChiMi-v2.5.26-release.apk

**Comment by tiann** [comment]
#828
