### ISSUE TITLE
Bug report: 已经删除access，为什么还提示java.lang.IllegalStateException: Not allowed to set the device owner... already some account ...

### ISSUE THREAD

**Issue by Liyoh** [taichi-framework/TaiChi#811]
**Describe the bug**
1. 设备：三星note8 N9500 未Root
2. adb开启太极阳的时候， 出现异常
3. 异常是说明access账户未删除，可我已经在设置中删除账户，竟然还报错误

**To Reproduce**
1. 设置-> '云和账户' ->逐个删除
2. 拔出SIM卡（尝试是否为这个问题，但是已经尝试确认不是这个问题）
3. adb命令开启太极阳
4. java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device

**Expected behavior**

**Smartphone (please complete the following information):**
Magisk version：
没有安装Magisk
TaiChi version：
Which Xposed modules are enabled ?：钉钉助手
Xposed modules version：
Which Magisk modules are enabled ?：v1.1.6
Magisk modules version：null
Device ：三星Note8 N9500
ROM：null
Android version: 8.0

**Additional context**
我希望大佬能给予解决方案，谢谢

**Comment by Ten-Night** [comment]
Mate10  未Root 未解锁也是  
解决方案:
重新刷机什么都不干可以开启

**Comment by tiann** [comment]
1. adb 无法开启太极阳。
2. 有这个提示说明就是账户没有删除干净。你可以把可疑的软件先卸载掉，或者用第三方工具开启设备管理员。
