### ISSUE TITLE
模块更新支持：【MiPushFramework】-【0.3.6.20190429.af38eb3】

### ISSUE THREAD

**Issue by Tr0nger** [taichi-framework/TaiChi#812]
## 模块名字
MiPushFramework
## 模块版本号
0.3.6.20190429.af38eb3
## 模块更新了什么？
性能优化
减少耗电
## 模块安装包
https://github.com/MiPushFramework/MiPushFramework/releases/download/0.3.6.20190429.af38eb3/xmsf_service.apk

**Comment by MoonBegonia** [comment]
@Tr0nger 
Duplicate of #750 #464

**Comment by tiann** [comment]
#828
