### ISSUE TITLE
安装南方航空app闪退

### ISSUE THREAD

**Issue by wuche2012** [taichi-framework/TaiChi#814]
## 什么问题
使用太极阴安装南方航空公司APP，安装到一半的时候太极直接闪退；

（请简要说明你遇到的问题）

## 详细情况
打开太极，添加应用，选择本机安装好的南航app，然后添加，安装过程中闪退；

直接用APK文件安装，也是安装过程中闪退；

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：
太极 Magisk 模块版本：
太极APP版本：东皇钟`5.2.0-248
开启的 Xposed 模块：微信群消息助手，微X模块
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：华为荣耀8
ROM版本：EMUI8.0.0

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
526 已修复
