### ISSUE TITLE
新增模块支持：XposedBase【模块名】

### ISSUE THREAD

**Issue by XhstormR** [taichi-framework/TaiChi#817]
## 模块名字
XposedBase

## 模块用途
自己使用

## 模块版本号
1

## 模块安装包
代码仓库： https://github.com/XhstormR/XposedBase
APK：[app-release.zip](https://github.com/taichi-framework/TaiChi/files/3222282/app-release.zip)

安装模块后，状态显示暂不支持。请问 TaiChi 能否加载自己测试开发的 Xposed 模块，还是说必须得在 TaiChi 的模块白名单里面才能开启？如果是这样的话，感觉适用性小了很多。

**Comment by tiann** [comment]
#828
