### ISSUE TITLE
新增模块支持：【NoAds For YouTube / YouTube去广告】

### ISSUE THREAD

**Issue by lllinusss** [taichi-framework/TaiChi#819]
## 模块名字
NoAds For YouTube / YouTube去广告
## 模块用途
 删除YouTube中几乎所有的广告
## 模块版本号
1.0.0
## 模块安装包
https://dl-xda.xposed.info/modules/com.wovow.noads_v100_e49d8c.apk
[com.wovow.noads_v100_e49d8c.zip](https://github.com/taichi-framework/TaiChi/files/3228978/com.wovow.noads_v100_e49d8c.zip)

(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
#828
