### ISSUE TITLE
新增模块支持：【MinMinGuard】

### ISSUE THREAD

**Issue by vmpvup** [taichi-framework/TaiChi#821]
模块名字:  MinMinGuard 

模块用途:  去除广告工具

模块版本号: v2.0.6

模块安装包:  https://dl-xda.xposed.info/modules/tw.fatminmin.xposed.minminguard_v65_313415.apk

(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
#28
