### ISSUE TITLE
新增模块支持：【抖音大师】

### ISSUE THREAD

**Issue by laihu** [taichi-framework/TaiChi#824]
## 模块名字
抖音大师
## 模块用途
1. 自动切换下一个视频播放
2.自动下载无水印视频到本地

## 模块版本号
1.0.1
## 模块安装包
https://dl-xda.xposed.info/modules/com.helper.douyin_v42_86dcae.apk

(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
#828
