### ISSUE TITLE
新增模块支持：【bgoUnlockFPS】

### ISSUE THREAD

**Issue by Kaleidoblood** [taichi-framework/TaiChi#827]
## 模块名字
bgoUnlockFPS
## 模块用途
用于解锁FGO国服的帧数限制，解锁之后支持60帧
## 模块版本号
1.0
## 模块安装包
https://github.com/nishuoshenme/bgoUnlockFPS/releases/tag/1.0
(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
#828
