### ISSUE TITLE
模块更新请访问 http://admin.taichi.cool/

### ISSUE THREAD

**Issue by tiann** [taichi-framework/TaiChi#828]
本 issue 停止接受新增模块以及模块更新支持，请访问 http://admin.taichi.cool/ 自行提交！

**Comment by akealmuhairi** [comment]
<img width="360" alt="splash_img" src="https://user-images.githubusercontent.com/51520437/59157917-3fcaf700-8ac4-11e9-9e9d-4e6cd1dd3da0.png">

**Comment by akealmuhairi** [comment]
![ic_launcher](https://user-images.githubusercontent.com/51520437/59157919-4e191300-8ac4-11e9-8c2e-ad7abe22fca3.png)
<img width="360" alt="splash_img" src="https://user-images.githubusercontent.com/51520437/59157920-4e191300-8ac4-11e9-89a3-ffb4ea9cb66d.png">
![ic_launcher](https://user-images.githubusercontent.com/51520437/59157921-4e191300-8ac4-11e9-9add-ef0d3cdf7e6b.png)
![Screenshot_20190604-070025745](https://user-images.githubusercontent.com/51520437/59157922-4eb1a980-8ac4-11e9-8a25-98af127e3abb.jpg)
![ic_launcher](https://user-images.githubusercontent.com/51520437/59157923-4eb1a980-8ac4-11e9-883d-928dc77d27f0.png)
![Screenshot_20190518-074506407](https://user-images.githubusercontent.com/51520437/59157925-4eb1a980-8ac4-11e9-902e-251c913cc3f4.jpg)
[Untitled spreadsheet.pdf](https://github.com/taichi-framework/TaiChi/files/3269435/Untitled.spreadsheet.pdf)
[User Agreement.pdf](https://github.com/taichi-framework/TaiChi/files/3269436/User.Agreement.pdf)
![1557876221615](https://user-images.githubusercontent.com/51520437/59157926-4fe2d680-8ac4-11e9-966b-92e7752ed161.jpg)
![Screenshot_20190514-231514813](https://user-images.githubusercontent.com/51520437/59157927-4fe2d680-8ac4-11e9-92f3-9d6919e57a2b.jpg)
[Privacy Policy.pdf](https://github.com/taichi-framework/TaiChi/files/3269437/Privacy.Policy.pdf)

[Untitled document.pdf](https://github.com/taichi-framework/TaiChi/files/3269438/Untitled.document.pdf)
![Screenshot_20190604-070035373](https://user-images.githubusercontent.com/51520437/59157929-507b6d00-8ac4-11e9-9b36-aa88a93f7503.jpg)
![Screenshot_20190517-185342532](https://user-images.githubusercontent.com/51520437/59157930-51140380-8ac4-11e9-9fd3-8949c9190b57.jpg)
![ic_launcher](https://user-images.githubusercontent.com/51520437/59157931-51140380-8ac4-11e9-8f7b-2a5960c422f2.png)

![splash_img](https://user-images.githubusercontent.com/51520437/59157932-51140380-8ac4-11e9-807d-e14aed7cca35.png)

![ic_launcher](https://user-images.githubusercontent.com/51520437/59157933-51ac9a00-8ac4-11e9-8183-a0c7399dd4f0.png)

<img width="38" alt="ios_thumb" src="https://user-images.githubusercontent.com/51520437/59157935-51ac9a00-8ac4-11e9-8066-98e6586e0802.png">
![ic_launcher](https://user-images.githubusercontent.com/51520437/59157936-52453080-8ac4-11e9-9634-2bc5c7430b17.png)
<img width="38" alt="ios_thumb_disable" src="https://user-images.githubusercontent.com/51520437/59157937-52453080-8ac4-11e9-9974-5458a07cce21.png">

**Comment by qq31582839** [comment]
http://admin.taichi.cool/，已在这里提交多日，还请大大有空帮忙审核一下，谢谢

**Comment by zhengnanGit** [comment]
太极双开应用无法添加微信撤回模块

**Comment by stevegeiz** [comment]
![3419128305](https://user-images.githubusercontent.com/59562563/71816406-70f0c180-30bd-11ea-87fb-815aec7989e7.jpg)
![S300](https://user-images.githubusercontent.com/59562563/71816408-73531b80-30bd-11ea-8208-665a135301bb.jpeg)


請求新增加模塊支持：luckymoney(1.4.3正式版：链接: http://pan.baidu.com/s/1hrGIgMK 密码: jp9w


透视加强版:   http://pan.baidu.com/s/1kVguOp5 密码: ztyf

延时版： http://pan.baidu.com/s/1hs0dvnu 密码: yjpa)
sudohide(手机乐园或xposed下载模块里搜索)
HideX v1.0(https://wap.shouji.com.cn/down/31709.html)
畅玩微信(https://wap.shouji.com.cn/down/1551792.html)
![Screenshot_2020-01-06-19-28-31](https://user-images.githubusercontent.com/59562563/71816383-5f0f1e80-30bd-11ea-9d25-7c34e9d6b979.png)
![Screenshot_2020-01-06-19-23-12](https://user-images.githubusercontent.com/59562563/71816384-5f0f1e80-30bd-11ea-9b99-86827d05a009.png)
![Screenshot_2020-01-06-19-28-38](https://user-images.githubusercontent.com/59562563/71816385-5f0f1e80-30bd-11ea-8af0-1b09eb4bb431.png)

**Comment by iggijfhgtt6** [comment]
Hgy
