### ISSUE TITLE
新增模块支持：WechatUI

### ISSUE THREAD

**Issue by wwdboy** [taichi-framework/TaiChi#831]
## 模块安装包：

[WechatUI1.8.9.1（支持微信6.6.6国内版）.zip](https://github.com/taichi-framework/TaiChi/files/3248339/WechatUI1.8.9.1.6.6.6.zip)
虽然此模块不再更新，还是希望大神能加入支持，支持微信版本最高6.6.6

(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
#828
