### ISSUE TITLE
新增模块支持：【微咖模块】

### ISSUE THREAD

**Issue by wkxposed** [taichi-framework/TaiChi#832]
## 模块用途：一款免费的微信增强插件（当前适配的是703）
当前功能有：
一键转发朋友圈
转发语音
一键已读
一键清理僵尸粉
群发消息
调用群发接口一键群发5000人
按标签好友群发
群发所有群
群发标签群
群聊管理
入群欢迎
自动踢人
群标签管理
快捷发布公告

## 模块安装包   http://img.akawok.com/weika2.0.apk

(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
#828

**Comment by wkxposed** [comment]
你好，需要我这边如果配合修改？

**Comment by wkxposed** [comment]
你好，需要我这边如何配合修改？我在github没有看到相关提示，请告知谢谢
  

 

 ------------------ 原始邮件 ------------------
  发件人: "weishu"<notifications@github.com>;
 发送时间: 2019年6月10日(星期一) 上午10:50
 收件人: "taichi-framework/TaiChi"<TaiChi@noreply.github.com>;
 抄送: "四姑爷"<1991031768@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [taichi-framework/TaiChi] 新增模块支持：【微咖模块】 (#832)

 

 
Closed #832.

**Comment by aa668086** [comment]
想请你做一个微信模块，可以吗？

**Comment by wkxposed** [comment]
可以啊，什么需求你说



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: WWW <notifications@github.com&gt;
发送时间: 2019年10月15日 15:50
收件人: taichi-framework/TaiChi <TaiChi@noreply.github.com&gt;
抄送: 小姑爷 <1991031768@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[taichi-framework/TaiChi] 新增模块支持：【微咖模块】 (#832)




想请你做一个微信模块，可以吗？
