### ISSUE TITLE
太极提示更新引擎,然后提示更新失败,错误码-100

### ISSUE THREAD

**Issue by wlp7662973** [taichi-framework/TaiChi#838]
## 什么问题

太极提示更新引擎,然后提示更新失败,错误码-100. 点击右下角的"更新太极"会崩溃

## 详细情况
打开太极软件
太极提示模块引擎出错, 需要更新引擎才能运行: -100
点击右下角的"更新模块引擎"后,显示"更新中...",稍后报错:
引擎更新错误, 请重试或者升级到最新版本的太极! 错误码: -100
点击右下角的"更新太极"按钮, 应用会直接崩溃退出

Magisk 版本：(无）
太极 Magisk 模块版本：(无）
太极APP版本：5.2.0
开启的 Xposed 模块：(无）
Xposed模块版本：(无）
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：小米8
ROM版本：miui10 9.5.17开发版

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by wlp7662973** [comment]
我卸载并重装了太极5.2.0, 问题仍未能解决.
同时该问题会引起被太极处理过的大量app在打开的时候全都闪退, 目前手机1/4以上的app都无法使用了. 
还不敢重装app, 重新安装app会提示签名不同是否继续安装,点"是"继续安装, app的数据全部会被抹掉

**Comment by tiann** [comment]
更新引擎失败，是服务器的问题；这时候不要卸载太极，正常用就行了。卸载太极一切都没了。

**Comment by badtoken** [comment]
我也有同样的问题，一模一样

**Comment by badtoken** [comment]
> 我也有同样的问题，一模一样

已解决，更新最新版本的太极即可。https://taichi.cool/zh/download.html
