### ISSUE TITLE
新增模块支持：【YouTube去广告，锁屏播放\NoAdsBackgroundPlaybackYT】

### ISSUE THREAD

**Issue by ohyeah521** [taichi-framework/TaiChi#841]
## 模块名字
YouTube去广告，锁屏播放\NoAdsBackgroundPlaybackYT
## 模块用途
- 删除YouTube中几乎所有的广告，包括视频播放过程中的广告，实现全程无广告观看视频
- 基于特征码定位广告信息，实现自动适配新版本的YouTube，无需担心升级后功能失效
- 实现后台播放，关闭屏幕播放，极致省电
## 模块版本号
2.0.2
## 模块安装包
[YouTube去广告，锁屏播放_v2.0.2.zip](https://github.com/taichi-framework/TaiChi/files/3269003/YouTube._v2.0.2.zip)

(请务必给出模块的安装包文件，无论是通过网盘还是直接上传；否则此 issue 将被直接忽略！)

**Comment by tiann** [comment]
#828
