### ISSUE TITLE
BUG：一加7pro应用闪退且无法开机

### ISSUE THREAD

**Issue by wengzuyang** [taichi-framework/TaiChi#849]
## 什么问题
安装最新taichi后打开app一秒后闪退，重启手机后卡在“手机正在启动...”上，在线等，急。。。
安装最新

## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：Magisk-v19.3.zip
太极 Magisk 模块版本：4.9.1
太极APP版本：5.2.0
开启的 Xposed 模块：
Xposed模块版本：不懂
开启的其他 Magisk 模块：
Riru-Core V19;
Riru-EdXposed V0.4.1.2_beta;
Riru-Location Report Enabler V9.1 ;
Systemless Hosts V1.0;

手机型号：一加7pro
ROM版本：氢os

## 配置文件
手机起不来了提供不了

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by wengzuyang** [comment]
进的了twrp，有办法恢复吗

**Comment by wengzuyang** [comment]
在twrp里面切换到slot A居然可以启动了，吓得我赶紧卸载太极

**Comment by tiann** [comment]
这几个模块功能很可能互相之间是有冲突的，你把另外几个模块关掉看看会不会出现这个情况，或者你先装太极再装别的模块看看会不会出这个情况。

我也手持1+7p 不存在这个问题。

**Comment by VictorChow** [comment]
我出现了一样的问题 先装模块后装太极卡开机 先装太极在装模块就好了
