### ISSUE TITLE
BUG：安装太极APP

### ISSUE THREAD

**Issue by itispip** [taichi-framework/TaiChi#851]
## 安装太极APP以后，无法安装本地APK文件

（请简要说明你遇到的问题）

## 安装太极APP以后，试图安装本地apk文件时，没有任何反应。卸载太极APP，本地安装APK恢复正常

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：19.2
太极 Magisk 模块版本：4.91
太极APP版本：5.20
开启的 Xposed 模块：无
Xposed模块版本：无
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：nubia X
ROM版本：Android P

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
重置系统设置的默认应用程序即可
