### ISSUE TITLE
BUG：[xposed edge pro边缘任务] play市场原版无法支持

### ISSUE THREAD

**Issue by simymo** [taichi-framework/TaiChi#855]
## 什么问题

[xposed edge pro边缘任务] play市场原版无法支持

## 详细情况

从太极仓库下载的可以使用，但是play市场付费原版无法使用，显示xposed框架未安装。

Magisk 版本：19.3
太极 Magisk 模块版本：4.91
太极APP版本：5.20
开启的 Xposed 模块：124
Xposed模块版本：xposed edge pro版本：5.4.2
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：G1917
ROM版本：P

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
找人提交到 admin.taichi.cool 即可
