### ISSUE TITLE
安装模块后重启状态栏导航栏消失

### ISSUE THREAD

**Issue by DubheBroken** [taichi-framework/TaiChi#856]
## 什么问题
安装模块后，重启手机，跳过了锁屏密码直接进入桌面。导航栏和状态栏消失了，从底部上滑，从顶部下拉都无法呼出。此时太极本体里还没有添加应用。

## 详细情况

在Magisk中安装太极模块，重启手机，100%触发。

Magisk 版本：19.3
太极 Magisk 模块版本：4.9.1（4.9.0和4.7.0都试过，一样的现象）
太极APP版本：东皇钟5.2.0
开启的 Xposed 模块：未勾选任何模块
Xposed模块版本：无
开启的其他 Magisk 模块：无
其他 Magisk 模块版本：无
手机型号：荣耀V8 KNT-AL20（麒麟955）
ROM版本：EMUI 8.0.0.528（C00）

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by DubheBroken** [comment]
[配置文件.zip](https://github.com/taichi-framework/TaiChi/files/3316492/default.zip)

**Comment by tiann** [comment]
不对 9.0 以下的系统做任何何以正常运行的承诺，请尽快升级到 9.0

https://github.com/taichi-framework/TaiChi/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8#%E8%AF%B4%E6%98%8E
