### ISSUE TITLE
Bug report: Exi for swiftkey

### ISSUE THREAD

**Issue by Kyle2142** [taichi-framework/TaiChi#859]
This isn't a bug report but you've forced me to use the template because of that bot.
see https://github.com/taichi-framework/TaiChi/issues/858 for the actual issue

**Comment by Kyle2142** [comment]
Thank you @tiann for adding 2.3.1 support!

**Comment by tiann** [comment]
@Kyle2142 Register an account in http://admin.taichi.cool and give me your account name, then you can upload module by yourself.
