### ISSUE TITLE
太极阴开启阴阳之门，adb操作-卡在删除账户这个一步了，手机恢复出厂设置了，没有账户，手机型号iqoo（v1824A）

### ISSUE THREAD

**Issue by skyltl** [taichi-framework/TaiChi#860]
手机未root
![QQ截图20190622224920](https://user-images.githubusercontent.com/52105990/59965356-5f8c0180-953f-11e9-9006-8f7997e231be.png)

太极 Magisk 模块版本：无
太极APP版本：东皇钟5.20-300
开启的 Xposed 模块：假装分享、coolapkex、微信斗图神器、ad快消、畅玩微信。
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：vivoIQOO
ROM版本：Funtouch os 9
![Screenshot_2019_0622_223253](https://user-images.githubusercontent.com/52105990/59965303-b513de80-953e-11e9-9631-f4e82f0a0721.jpg)
![Screenshot_2019_0622_223314](https://user-images.githubusercontent.com/52105990/59965305-b513de80-953e-11e9-9834-9b820801a49d.jpg)

## 配置文件

请提供手机里面的 `adb shell dpm set-device-owner me.weishu.exp/.DeviceAdmin` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by zhouchengang** [comment]
卸载支付宝，，因为支付宝会有隐藏的账号（同样问题已解决）
