### ISSUE TITLE
BUG：太极magisk配合5.2.1或者5.2.0.9会导致无法开机

### ISSUE THREAD

**Issue by i-sususu** [taichi-framework/TaiChi#864]
## 什么问题

太极magisk配合5.2.1或者5.2.0.9会导致无法开机

## 详细情况

单独安装app可以开机，单独安装面具模块不装app也能开机，安装旧版本比如5.2.0.3也没问题

Magisk 版本：19.3（19300）
太极 Magisk 模块版本：4.9.2和4.9.1都试了
太极APP版本：5.2.0.9 5.2.1有问题
开启的 Xposed 模块：未开启任何模块情况下试的
Xposed模块版本：同上
开启的其他 Magisk 模块：busybox/miui主题/volume steps plus
其他 Magisk 模块版本：1.30.1/无/1.3
手机型号：小米9
ROM版本：9.6.27开发版

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。
文件1
/data/app/com.fkzhang.qqxposed-QdOrMCo85Bz4r0W6ZZE4Mw==/base.apk
/data/app/com.fkzhang.wechatxposed-yDjRs-nlTLJ1W5nHf64dhQ==/base.apk
/data/app/com.jy.xposed.web-3x02vYOe8soy9dvYWad50Q==/base.apk
/data/app/fi.veetipaananen.android.disableflagsecure-egTqRZ5F4hnSrF6hr9mLWA==/base.apk
/data/app/bin.xposed.Unblock163MusicClient-9q94A479aLyCj5JTs2W0Zw==/base.apk
/data/app/bin.xposed.screenshotdelayremover.mod-sYNDz5Jkb0KdB7plRBpo3g==/base.apk
/data/app/me.zjns.lovecloudmusic-WBznoOEVUmy1IGekxzeprg==/base.apk
/data/app/me.qiwu.MusicNotification-JESkdlpQUbDtowud7RIMQA==/base.apk
/data/app/me.weishu.corepatch-89NB4Y37agIo_kje-C3eZg==/base.apk
/data/app/name.caiyao.sporteditor-R2xeM0A8mlM1qx-26L78MA==/base.apk

文件2
me.weishu.corepatch
com.fkzhang.qqxposed
bin.xposed.screenshotdelayremover.mod
com.fkzhang.wechatxposed
name.caiyao.sporteditor
me.zjns.lovecloudmusic
__all__
com.jy.xposed.web
me.qiwu.MusicNotification
bin.xposed.Unblock163MusicClient
fi.veetipaananen.android.disableflagsecure

两个文件均在5.2.0.3能开机启用模块的情况下获取的

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by 17560648330** [comment]
我也遇到了这种情况，小米9的6.20版本，更新5.2.1跟面具4.9.2和4.9.1重启都无法开机，，切换到旧版本5.2.0就可以了

**Comment by tiann** [comment]
参见 #865
