### ISSUE TITLE
BUG：magisk-taichi v4.9.2刷入后卡第二屏，无法进入系统

### ISSUE THREAD

**Issue by wahowe** [taichi-framework/TaiChi#865]
## 什么问题
magisk-taichi v4.9.2刷入后卡第二屏，无法进入系统
（请简要说明你遇到的问题）

## 详细情况
magisk19.3刷入magisk-taichi v4.9.2后开机卡第二屏，无法进入系统
（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：19.3
太极 Magisk 模块版本：4.9.2
太极APP版本：5.2.1
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：红米
ROM版本：安卓8.1.0

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。
启动日志：
[boot.zip](https://github.com/taichi-framework/TaiChi/files/3337198/boot.zip)

**Comment by tiann** [comment]
[app-release.apk.zip](https://github.com/taichi-framework/TaiChi/files/3337310/app-release.apk.zip)
试一下这个版本是否有此问题

**Comment by 17560648330** [comment]
> [app-release.apk.zip](https://github.com/taichi-framework/TaiChi/files/3337310/app-release.apk.zip)
> 试一下这个版本是否有此问题

这个版本我试过了，也不行，重启会很长时间然后进入到rec

**Comment by i-sususu** [comment]
> [app-release.apk.zip](https://github.com/taichi-framework/TaiChi/files/3337310/app-release.apk.zip)
> 试一下这个版本是否有此问题

不行，还是无法开机，这是我的log
[backup.tar.gz](https://github.com/taichi-framework/TaiChi/files/3337730/backup.tar.gz)

**Comment by tiann** [comment]
[taichi_5.2.1.2.apk.zip](https://github.com/taichi-framework/TaiChi/files/3338485/taichi_5.2.1.2.apk.zip)

再试一下这个呢？

**Comment by i-sususu** [comment]
> [taichi_5.2.1.2.apk.zip](https://github.com/taichi-framework/TaiChi/files/3338485/taichi_5.2.1.2.apk.zip)
> 
> 再试一下这个呢？

不行，老样子，从5.2.0.9开始就不行了，5.2.0.3或者更老的就没事

**Comment by tiann** [comment]
[taichi_5.2.1.3.apk.zip](https://github.com/taichi-framework/TaiChi/files/3338777/taichi_5.2.1.3.apk.zip)

辛苦再试一下这个，或者加我 qq 一起调试一下

**Comment by i-sususu** [comment]
> [taichi_5.2.1.3.apk.zip](https://github.com/taichi-framework/TaiChi/files/3338777/taichi_5.2.1.3.apk.zip)
> 
> 辛苦再试一下这个，或者加我 qq 一起调试一下

还是不行，大神qq多少

**Comment by tiann** [comment]
@i-sususu 923551233

**Comment by i-sususu** [comment]
> @i-sususu 923551233

加了

**Comment by tiann** [comment]
5.2.2 版本已修复
