### ISSUE TITLE
太极5.2.1 微信小程序，微信自带浏览器闪退

### ISSUE THREAD

**Issue by newcastlecy** [taichi-framework/TaiChi#869]
## 什么问题
闪退
（请简要说明你遇到的问题）

## 详细情况
打开部分小程序，浏览公用号 微信自带浏览器，闪退
（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：
太极 Magisk 模块版本：4.9.2
太极APP版本：5.2.1
开启的 Xposed 模块：微X
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：MIX2s
ROM版本：6.28开发版

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
5.2.2 版本是否有此问题？

**Comment by newcastlecy** [comment]
5.2.2 正常了
