### ISSUE TITLE
BUG：双开微信无法加载到模块 

### ISSUE THREAD

**Issue by ViolentBanana** [taichi-framework/TaiChi#877]
## 什么问题

双开微信无法加载到模块,主微信可以加载到模块

## 详细情况

双开的操作视频已经看过了,因为锤子的应用双开只有个别的应用(微信,QQ,微博,,淘宝等),并没有太极以及,所以没办反参考视频操作

在手机没root的时候 使用过太极阴,添加一个微信应用,系统的分身应用是可以同时加载到模块儿
最近root以后出现了这个问题

使用的手机是坚果R1 昨天用6.6.5.2系统,今天刷了低版本的6.1.0都出现问题

Magisk 版本：7.3.2
太极 Magisk 模块版本：4.9.1
太极APP版本：5.2.0-370
开启的 Xposed 模块：微X
Xposed模块版本：2.3_2.3(b3)
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：坚果R1
ROM版本：6.1.0

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

modules:
/data/app/com.fkzhang.wechatxposed-w39ETY8i2HXoMhSar9fl4g==/base.apk
/data/app/com.example.wx_plug_in3-bGojqfGmnUzajvpapHLmsQ==/base.apk
/data/app/com.oasisfeng.greenify-BbvSDW2d3PwEVRhneUGD0w==/base.apk

apps:
com.fkzhang.wechatxposed
com.tencent.mm
com.oasisfeng.greenify
com.example.wx_plug_in3

[MobileFile.zip](https://github.com/taichi-framework/TaiChi/files/3357504/MobileFile.zip)

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
如果插件不支持双开，框架也没办法。

很多情况下，插件写死了路径，在多开环境下路径不同，导致模块加载失败。
