### ISSUE TITLE
BUG：AllTrans 翻译密钥保存异常

### ISSUE THREAD

**Issue by miyouzi** [taichi-framework/TaiChi#880]
## 什么问题

使用太极提供的 AllTrans 安装包，存在翻译密钥会被重置问题。

## 详细情况

在```全局设置```分页设置完翻译密钥后，切换到```翻译的应用程序```分页再切换回来，或者重新打开AllTrans，都会导致翻译密钥被重置。
![VEditor_20190707142459](https://user-images.githubusercontent.com/24269465/60764838-654b2080-a0c3-11e9-9bfc-84f7a2d406ae.gif)

Magisk 版本：(无）
太极 Magisk 模块版本：(无）
太极APP版本：5.2.2-393
开启的 Xposed 模块：AllTrans（太极提供版本）
Xposed模块版本：1.4.0
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：魅族 16th
ROM版本：Flyme 7.3.0.0A

## 配置文件

未ROOT无法取得

**Comment by tiann** [comment]
这不是太极的问题
