### ISSUE TITLE
请求适配模块：BHP

### ISSUE THREAD

**Issue by linlincor** [taichi-framework/TaiChi#887]
模块名字
BHP

模块用途
用于配合“面板顶栏美化”软件实现下拉菜单顶栏背景替换。

模块版本号
2.8.9

模块安装包
BHP：https://www.coolapk.com/apk/com.tinybad.beautyheaderplugin
面板顶栏美化：https://www.coolapk.com/apk/com.tinybad.headerbeauty

**Comment by hh2333** [comment]
请自行打开[太极模块适配页面](http://admin.taichi.cool)进行申请。
