### ISSUE TITLE
BUG：加入到太极的软件全部退闪

### ISSUE THREAD

**Issue by weargle** [taichi-framework/TaiChi#888]
## 什么问题
从太极5.2.1之后的太极阳版本加入到太极的软件全部退闪

## 详细情况
最近更新的几个太极阳版本都出现加入到太极中的软件一打开退闪，以为插件引起，取消全部插件勾选，还是出现退闪，在没有更改最新的太极magisk的情况下，回退之前的太极APP版本，一直回退到5.2.0版本太极APP，加入到太极的软件不再退闪，测试了一个插件没有出现退闪情况

Magisk 版本：18
太极 Magisk 模块版本：4.9.4
太极APP版本：5.2.5~5.2.0
开启的 Xposed 模块：无
Xposed模块版本：无
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：小米4c
ROM版本：10.1.1.0

## 配置文件
链接:https://pan.baidu.com/s/1KTyAP9LVmOI7_ZzkJ080dQ 提取码:0hv7

**Comment by tiann** [comment]
把 `/data/system/taichi` 目录删了看看

**Comment by tiann** [comment]
你这貌似是 Android 7.x 太极阳不会保证 Android 9.0 以下的可用性，如果你 5.2.0 能用那就用 5.2.0吧
