### ISSUE TITLE
Bug report: No project license

### ISSUE THREAD

**Issue by oxr463** [taichi-framework/TaiChi#892]
**Describe the bug**
This project doesn't contain a license.

> When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

Source: https://choosealicense.com/no-permission

I'd recommend either Apache-2.0, since that is the license for Android itself; or GPL-3.0-or-later, as that is the license for Magisk, (I personally prefer the GPL, but that's just me).

**Comment by oxr463** [comment]
@tiann, not sure if you saw this since the bot closed it immediately.

**Comment by tiann** [comment]
TaiChi is not open-source, it is an independent app and didn't use any code of Magisk.

AOSP is open-source, that doesn't means any software under Android must be open-sourced. Magisk is open-source and under GPL, but taichi has no relation with Magisk except providing a magisk module.

I appreciate the open-source community and i also open sourced many projects, such as VirtualXposed / epic / FreeReflection, etc. But that doesn't means that i must open source all my work.

**Comment by tiann** [comment]
TaiChi would be open-sourced someday maybe, but i won't do it in short terms.

**Comment by oxr463** [comment]
It would be good if you had a notice stating this in the project.
