### ISSUE TITLE
太极阴无法添加从Google play下载的支付宝

### ISSUE THREAD

**Issue by llx547305571** [taichi-framework/TaiChi#893]
太极阴无法添加从Google play下载的支付宝

在创建应用的列表中没有支付宝app可供创建
用Apk提取器提取apk后，本地apk安装创建提示：“暂不支持创建此应用”。
希望后续能支持

**Smartphone (please complete the following information):**
Magisk version：none
TaiChi-Magisk module version：none
TaiChi version：东皇钟5.2.5-427
Device ：Xperia 1
ROM：Android 9.0

**Additional context**

**Comment by tenhow** [comment]
@llx547305571 老哥，介绍里有说，支付宝是故意不支持的，你可以去看一下。 另外你的xperia 1太极有效果吗？我的怎么模块不生效呢？

**Comment by llx547305571** [comment]
> @llx547305571 老哥，介绍里有说，支付宝是故意不支持的，你可以去看一下。 另外你的xperia 1太极有效果吗？我的怎么模块不生效呢？

呃...之前没注意   我的Xperia 1是有效的啊，目前用的就微信助手、指纹识别、还有锤锤（钉钉打卡），都正常使用的
