### ISSUE TITLE
BUG：代码一直不触发 handleLoadPackage

### ISSUE THREAD

**Issue by answer1874** [taichi-framework/TaiChi#900]
## 什么问题

代码一直不触发 handleLoadPackage

## 详细情况

最近正在移植我们的插件到taichi
我下载了Xposed-Fake-Device-master
编译好后在taichi.阳里面勾选之后，并没有触发handleLoadPackage的方法
但是我下载其他的模块,是生效的。不知道为什么我的代码不生效

Magisk 版本：19.3
太极 Magisk 模块版本： 最新
太极APP版本：   5.1
开启的 Xposed 模块： Xposed-Fake-Device-master
Xposed模块版本： 1.0
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号： 小米4
ROM版本： cm12

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by answer1874** [comment]
应该是没有白名单 管理人员能帮我开通白名单吗

**Comment by tiann** [comment]
admin.taichi.cool

**Comment by iponkan** [comment]
> admin.taichi.cool
@tiann 
自己运行模块源码发现一直提示Xpoased没有load，handleLoadPackage也没有运行。
我没有区改动包名这些配置代码，关于admin.taichi.cool应该不适用我这种情况，因为我就是在别人的模块上二次开发.
我的环境：Pixel Android 10.0 手机已root，运行太极阳
模块源码：[WifiSimulator](https://github.com/xuelongqy/WifiSimulator)

_我是在使用WIFI模拟器这个模块的时候发现在手机上很不稳定，经常出现模拟失败。所以找到了这个模块的源码[WifiSimulator](https://github.com/xuelongqy/WifiSimulator)，发现这个模块的WiFi获取没有适配Android 9.0，10.0，而且想排查一下稳定性和易用性的问题（比如应用列表没有筛选功能，不能排除系统应用）。希望能帮助推动太极生态_

**Comment by iponkan** [comment]
#1055
