### ISSUE TITLE
BUG：Magisk (736729f5) (19307)上安装Tai_Chi-v4.9.6无法进入系统

### ISSUE THREAD

**Issue by Joxon** [taichi-framework/TaiChi#904]
## 什么问题

Magisk (736729f5) (19307)上安装Tai_Chi-v4.9.6无法进入系统

## 详细情况

一加7Pro GM1910，按照以下步骤进行刷机：
1. 进入TWRP
2. 刷入AOSiP-9.0-Official-guacamole-20190722
3. 刷入twrp-3.3.1-50-guacamole-unified-installer
4. 重启TWRP
5. 刷入open_gapps-arm64-9.0-nano-20190720
6. 刷入[Magisk (736729f5) (19307)](https://github.com/topjohnwu/magisk_files/commit/5c745812fe544baf4799f5cab5fd1125056c3b3b)
7. 重启，成功启动系统
8. 进入Magisk Manager (f1112fdf) (228)
9. 在Downloads页面搜索Tai Chi，安装Tai_Chi-v4.9.6.zip
10. 重启，无法进入系统
11. 进入TWRP，刷入[MagiskModulesRemoverV19+@Edzamber](https://forum.xda-developers.com/apps/magisk/magisk-v16-3-magisk-modules-remover-t3776718)，卸载所有Magisk模块
12. 重启，成功启动系统

Magisk 版本：19.4-736729f5
太极 Magisk 模块版本：4.9.6
太极APP版本：5.3.0
开启的 Xposed 模块：无
Xposed模块版本：无
开启的其他 Magisk 模块：无
其他 Magisk 模块版本：无
手机型号：一加7Pro GM1910
ROM版本：AOSiP-9.0-Official-guacamole-20190722

## 配置文件

> 请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

对应目录下无上述文件。

> 补充：有能力请务必提供日志文件已快速解决问题。

[logcat-190723.txt](https://github.com/taichi-framework/TaiChi/files/3420100/logcat-190723.txt)

**Comment by tiann** [comment]
试一下这版本是否解决问题？https://www.lanzous.com/i54h0ub

**Comment by Joxon** [comment]
安装5.3.1版本的apk后刷入4.9.6的zip包，重启成功进入系统。感谢。
