### ISSUE TITLE
升级新版Emui 带有 Erosf 文件系统后刷入补丁卡死

### ISSUE THREAD

**Issue by hais1992** [taichi-framework/TaiChi#905]
## 什么问题

升级新版Emui 带有 Erosf 文件系统后刷入补丁卡死

## 详细情况

升级至带有新文件系统的版本后，刷入magisk 然后  刷入TaiChi 4.9.6 补丁，重启手机后桌面黑屏，所有软件打不开，整个系统属于残废状态。

Magisk 版本：19.4
太极 Magisk 模块版本：4.9.6
太极APP版本：5.3.0
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：荣耀10
ROM版本：9.1.0.321

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
把太极升级到这版本再试试：https://www.lanzous.com/i54h0ub

**Comment by hais1992** [comment]
> 把太极升级到这版本再试试：https://www.lanzous.com/i54h0ub

首页添加应用无效、模块勾选不了、手动更新引擎失败
 /data/system/taichi 目录找不到 

![首页](https://i.loli.net/2019/07/24/5d37e5addb78899360.jpg)

![模块](https://i.loli.net/2019/07/24/5d37e5ae07f8670387.jpg)

![模块](https://i.loli.net/2019/07/24/5d37e750d5a0399221.png)

**Comment by hais1992** [comment]
> 把太极升级到这版本再试试：https://www.lanzous.com/i54h0ub

重启后 打开太极->模块->更新引擎 的日记  https://www.lanzous.com/i54ze9c

**Comment by answer1874** [comment]
> 把太极升级到这版本再试试：https://www.lanzous.com/i54h0ub

大佬 能不能帮我处理下开发者白名单的事情

**Comment by tiann** [comment]
@hais1992 能否把你系统的 `/system/app/FeatureFramework/FeatureFramework.apk` 这个文件发给我看看？

**Comment by maliangjie** [comment]
华为的那个超级文件系统是让系统只读不可写，估计以后都不能用修改系统的东西了

**Comment by tiann** [comment]
跟 EROFS 无关，是方舟编译器的问题。

**Comment by hais1992** [comment]
新版本 已解决
