### ISSUE TITLE
qqxposed希望提供支持

### ISSUE THREAD

**Issue by mannialanck** [taichi-framework/TaiChi#911]
## 什么问题

qqxposed1.0无法在太极中运行

## 详细情况

qqxposed1.0无法在太极中运行，因为第三方游戏希望通过qq登录，然而腾讯关闭了一部分游戏的授权登录

Magisk 版本：
太极 Magisk 模块版本：5.3.1
太极APP版本：
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：mix3
ROM版本：miui 10 

## 配置文件

无

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by hh2333** [comment]
请查看置顶的Issue。
