### ISSUE TITLE
Bug report: Module support request 

### ISSUE THREAD

**Issue by Senliast** [taichi-framework/TaiChi#913]
**Describe the bug**
I would like to use following modules with TaiChi

- GravityBox [O] v.8.5.4, filename
  com.ceco.oreo.gravitybox_v8541_d3c4af.apk
- Jasi Patcher. Please note, I am not gonna use it
  for piracy necessary, i need it either for device
  spoofing .
- PBMC Key Chains

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
Magisk version：19.4 Canary
TaiChi-Magisk module version：v.4.9.6
TaiChi version：versions kernel 124
Which Xposed modules are enabled ?：
Xposed modules version：
Which Magisk modules are enabled ?：Busybox, SQLite, Systemless Hosts, YouTube Vanced, TaiChi
Magisk modules version：
Device ：G930F
ROM：ALEXNDR ROM Oreo

**Additional context**

**Comment by hh2333** [comment]
Please read pinned issue.
