### ISSUE TITLE
一加3T 更新了Android9.0按照太极的说明使用没有任何效果

### ISSUE THREAD

**Issue by huanhuanhome** [taichi-framework/TaiChi#917]
## 什么问题
按照太极的说明使用没有任何效果

## 详细情况

一加3T 更新了Android9.0按照太极的说明使用没有任何效果

Magisk 版本：19.3
太极 Magisk 模块版本：4.9.6
太极APP版本：5.3.1-526
开启的 Xposed 模块：太极·Magisk 125 已开启
Xposed模块版本：
开启的其他 Magisk 模块：(无）使用了微信红包，运动修改器和微信学英语
其他 Magisk 模块版本：（无）
手机型号：一加3T
ROM版本：H2OS 版本  9.0.2

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
这些模块都不支持最新的微信吧

**Comment by huanhuanhome** [comment]
因为第一个安装了微信红包，后来卸载了微信红包之后，这个微信学英语和运动修改器都起作用了，接着我安装了微X模块，也是可以使用的，很有可能是微信红包这个模块影响的
