### ISSUE TITLE
help support Bug report: Module support request

### ISSUE THREAD

**Issue by ram10775** [taichi-framework/TaiChi#918]
**Describe the bug**
I would like to use following modules with TaiChi
getpaid 1.0.6 
`https://u3173425.ctfile.com/fs/3173425-390340138`
**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
Magisk version：19.4
TaiChi-Magisk module version：4.9.6
TaiChi version：5.3.2
Which Xposed modules are enabled ?：N/A
Xposed modules version：N/A
Which Magisk modules are enabled ?：Gpay SQlite fix ,tai chi
Magisk modules version：19.4
Device ：pixel2
ROM： 家 BootleggersROM 4.2

**Additional context**

**Comment by tiann** [comment]
Seems like this module is suspiciously
