### ISSUE TITLE
MIUI10版本太极阳的module.list存在会导致卡米

### ISSUE THREAD

**Issue by 1254249903** [taichi-framework/TaiChi#921]
## 什么问题

MIUI10版本太极阳的qx模块存在会导致卡米

## 详细情况

小米6手机，从老一点的开发版ota更新到了9.4.11（依旧还是安卓8），然后直装了magisk19.3，再装太极模块4.9.6，就会卡启动。（试过降低版本但是没有用）
我在recovery删除了/data/system/taichi，然后就可以开机。
开机后我在有太极模块的基础上，下载太极app，可以正常打开显示太极阳。
接下来我没有在太极里添加app，以前太极里下载的模块还在但是我没有修改选中状态（保持全部未选中），重启，成功开机。（这个时候data/system/taichi/modules.list还没有生成，因为没有检测到改动）
开机后我向太极里添加app和启用模块，此时启用的模块已经可以即时生效。但是我再一次重启，卡米，recovery，我到/system/taichi里发现了apps.list和module.list，只要删除掉module.list，就可以正常开机。
现在问题锁定在module.list上，难道我每次开机要删一遍这玩意吗😂
我更新了问题，昨天晚上我一个一个模块试过，添加到qx模块时候就卡米，和其他的没有关系。望解决。

Magisk 版本：19.3
太极 Magisk 模块版本：4.9.6
太极APP版本：5.3.1
开启的 Xposed 模块：

Xposed模块版本：
开启的其他 Magisk 模块：

其他 Magisk 模块版本：
手机型号：MI6 (sagit)
ROM版本：官方开发版9.4.11

## 配置文件

[boot-1971-11-05-16-22-43.log](https://github.com/taichi-framework/TaiChi/files/3447684/boot-1971-11-05-16-22-43.log)
[apps.txt](https://github.com/taichi-framework/TaiChi/files/3447685/apps.txt)
[modules.txt](https://github.com/taichi-framework/TaiChi/files/3447687/modules.txt)

**Comment by tiann** [comment]
把上帝模式关掉再看看会不会出问题

**Comment by 1254249903** [comment]
我的上帝模式在模块里启动了，在上帝模式app内实际没有开启。
而且昨天我挨个添加模块试了试，发现就是到qx才不能启动。

**Comment by pdone** [comment]
我也是这个情况   刷了太极Magisk模块后卡MI   在recovery删除了/data/system/taichi就可以开机   急需解决

**Comment by tiann** [comment]
Magisk 和 太极均使用最新版再试
