### ISSUE TITLE
BUG：希望能增加对以下这个模块的支持

### ISSUE THREAD

**Issue by alpsept21** [taichi-framework/TaiChi#924]
## 什么问题

这是一个让微信支持Chrome Custom Tabs的模块，希望太极能支持。
https://github.com/fei-ke/CCT/releases

## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：
太极 Magisk 模块版本：
太极APP版本：
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：
ROM版本：

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by hh2333** [comment]
请自行打开[太极模块适配页面](http://admin.taichi.cool)进行申请。
