### ISSUE TITLE
Bug report: 求支持spotify插件spotifysikp

### ISSUE THREAD

**Issue by 37xu** [taichi-framework/TaiChi#930]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
Magisk version：
TaiChi-Magisk module version：
TaiChi version：
Which Xposed modules are enabled ?：
Xposed modules version：
Which Magisk modules are enabled ?：
Magisk modules version：
Device ：
ROM：

**Additional context**

**Comment by hh2333** [comment]
请看置顶。
