### ISSUE TITLE
BUG：太极可能破坏了 system_server 的 ServiceManager 代理

### ISSUE THREAD

**Issue by Kr328** [taichi-framework/TaiChi#931]
## 什么问题

我在尝试 利用 Riru 注入 system_server 时 发现 当 太极 Magisk 启用时 模块无论如何都不会生效

## 详细情况

我的 Riru 模块 会在注入后 代理 ServiceManager 以 拦截 ActivityManagerService

ServiceManager 代理 实现 [链接](https://github.com/Kr328/Riru-InternalBrowserRedirect/blob/master/module/src/main/java/com/github/kr328/ibr/remote/proxy/ServiceManagerProxy.java)

之后 添加了 记录 ServiceManager.addService 的 日志 [链接](https://github.com/Kr328/Riru-InternalBrowserRedirect/blob/a5c2d9586906dcc4916080b75415d0dafaae3967/module/src/main/java/com/github/kr328/ibr/remote/Injector.java#L22)

发现 日志 在 PackageManagerService 之后 就再出现过了
同时发现 多个 Xposed 模块 初始化的 日志
推测 可能是 太极的 初始化 导致 ServiceManager 的 代理 被 覆盖

Magisk 版本：19.3
太极 Magisk 模块版本：4.9.6
太极APP版本：5.3.2
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块： Riru - Core, Riru - InternalBrowserRedirect
其他 Magisk 模块版本：19.4, 10
手机型号：Oneplus 6
ROM版本：PixelExperience / Android Pie

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by ITJesse** [comment]
https://github.com/taichi-framework/TaiChi/issues/948

**Comment by ITJesse** [comment]
https://github.com/taichi-framework/TaiChi/issues/933

**Comment by Rakau** [comment]
5.51浏览器依旧闪退

**Comment by tiann** [comment]
@Rakau 浏览器闪退与本 issue 无关，升级面具模块到 5.1.1，app 升级不是解决这个问题的。

**Comment by Rakau** [comment]
> @Rakau 浏览器闪退与本 issue 无关，升级面具模块到 5.1.1，app 升级不是解决这个问题的。

面具模块和APP都是最新的5.1.1

**Comment by Marukon** [comment]
好像已经修复了
