### ISSUE TITLE
BUG：在面具里激活太极阳会导致浏览器闪退

### ISSUE THREAD

**Issue by seraph758** [taichi-framework/TaiChi#933]
## 什么问题

在面具里勾选太极会导致浏览器闪退

## 详细情况

重置了手机，只安装面具激活太极阳，然后打开chrome就闪退。在面具里把太极取消掉，chrome就正常了

Magisk 版本：19。4
太极 Magisk 模块版本：4.9.6
太极APP版本：5.3.2
开启的 Xposed 模块：什么模块都没装
Xposed模块版本：
开启的其他 Magisk 模块：只有一个面具
其他 Magisk 模块版本：无
手机型号：1+7pro
ROM版本：android q dp4

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。
没有模块，所以没有这两个文件

补充：有能力请务必提供日志文件已快速解决问题。
![Screenshot_20190808-034157](https://user-images.githubusercontent.com/10000026/62654522-8a68d280-b992-11e9-97f7-e05f9aa60327.jpg)

**Comment by ITJesse** [comment]
将 Chrome 的更新卸载后恢复正常。此时 Chrome 版本如下图
![Screenshot_20190815-040133](https://user-images.githubusercontent.com/3601376/63048406-73396000-bf11-11e9-985c-a6be2698d659.png)

**Comment by ITJesse** [comment]
日志：https://pastebin.com/DpqkExFz

**Comment by Rakau** [comment]
一样闪退,卸载重装无效,版本76.0

**Comment by tiann** [comment]
Pixel Q beta6 并无此问题，其他系统的q等正式发布再修吧。

**Comment by tiann** [comment]
我刷过 1+7p  dp4 的q，也没有复现此问题，我看你的日志疑似有其他面具模块在运行。

关掉所有的面具模块，并且关掉 magiskhide 再试试

**Comment by Rakau** [comment]
MIUI的也闪退
![Screenshot_2019-08-17-13-40-36-932_com taobao tao_看图王](https://user-images.githubusercontent.com/33389179/63207247-3e85fe00-c0f5-11e9-88fa-6af0b9521657.jpg)
![Screenshot_2019-08-17-13-40-34-859_com miui home_看图王](https://user-images.githubusercontent.com/33389179/63207248-3f1e9480-c0f5-11e9-803d-bef8b253b2b8.jpg)

**Comment by tiann** [comment]
试下这个 https://www.lanzous.com/i5moomh

**Comment by Rakau** [comment]
依旧如此...

**Comment by sekaiacg** [comment]
同样闪退，P没问题，Q就闪退(MIUI )，还有加个QQ吧！

**Comment by seraph758** [comment]
> 我刷过 1+7p dp4 的q，也没有复现此问题，我看你的日志疑似有其他面具模块在运行。
> 
> 关掉所有的面具模块，并且关掉 magiskhide 再试试

我是双清完直接刷面具，然后只安装了太极一个模块，然后安装太极app。面具里激活太极模块，重启，chrome就闪退。取消激活面具模块，重启，chrome就正常

**Comment by seraph758** [comment]
> 试下这个 https://www.lanzous.com/i5moomh

试了这个还是闪退

**Comment by GKPMC** [comment]
我把Chrome从稳定版一直试到了金丝雀 这几个版本都闪退

**Comment by tiann** [comment]
#948

**Comment by xxiaofeng132** [comment]
在magisk中安装5.1.1版本后依旧会导致chrome浏览器闪退

**Comment by GKPMC** [comment]
511仍然闪退的话建议使用ku an的69beta版本 虽然版本有点老 但是不闪退

**Comment by seraph758** [comment]
> 511仍然闪退的话建议使用ku an的69beta版本 虽然版本有点老 但是不闪退

不用69，Q上默认的74就不闪退。 

我前两天在市场上更新5.1.1已经不闪退了。

**Comment by tiann** [comment]
小米系列的 Q 如果 Chrome 还闪退，面具模块升级到  5.1.2 即可。

**Comment by xxiaofeng132** [comment]
虽然我使用的不是小米系列（pixel 3）,但是使用5.1.2版本完美的解决了该问题，感谢开发者！

**Comment by Rakau** [comment]
感谢作者的付出，5.1.2解决了
