### ISSUE TITLE
Bug report: WaTweaker 1.3.8 doesn't work

### ISSUE THREAD

**Issue by fairyfeller** [taichi-framework/TaiChi#940]
**Describe the bug**
WaTweaker 1.3.8 which should work as Xposed module - doesn't work. Just does nothing

**To Reproduce**
1. Install WaTweaker 1.3.8, enable it in TaiChi
2. Add Whatsapp to TaiChi app section
3. Open WaTweaker, install patch for Whatsapp
4. Change any option in WaTweaker Xposed section
5. Nothing happens

**Expected behavior**
Working WaTweaker

**Smartphone (please complete the following information):**
Magisk version：19.4.736729f5 (latest Canary)
TaiChi-Magisk module version：5.1.0
TaiChi version：5.4.9-603
Which Xposed modules are enabled ?：WaTweaker and App Locale 2
Xposed modules version：WaTweaker 1.3.8
Which Magisk modules are enabled ?: Busybox, Magisk SELinux Manager, Simple init.d enabler, TaiChi
Magisk modules version：
Device ：Sony X Compact
ROM：ExistenZ for XC

**Additional context**
App Locale 2 is working fine with TaiChi. But not WaTweaker (even 1.3.8 version which should be supported. Any chance to make it work ?

**Comment by mxts** [comment]
Hi,

Able to support the latest version of WaTweaker? They are already at 1.4.6.
Thank you.

**Comment by bilogic** [comment]
Hi,

Able to support the latest WaTweaker 1.4.6? Thank you.

**Comment by tiann** [comment]
#925
