### ISSUE TITLE
BUG：系统语言设置繁体中文打开太极崩溃报错

### ISSUE THREAD

**Issue by LiuYiLin-CA** [taichi-framework/TaiChi#941]
## 什么问题

我将系统语言设置为繁体中文以后，再打开太极会报错。

## 详细情况

您好，尊敬的太极作者。我是您的一位粉丝，目前使用太极中。太极真的是一个特别好的软件，它能帮助我们这些搞机人士完成许许多多的事情。但是就在今天使用的过程中我发现一个问题。我将系统语言设置为繁体中文以后，再打开太极会报错。我推测是太极没有补全语言库，导致无法调出系统语言。希望您能修复一下这个bug。
我目前想到两种解决办法，一是无论系统语言是什么，都只调用简中语言（目前腾讯QQ是这种方案，效率最高，但是无法开辟更多市场）二是完善语言库（这样的效率较前者会低一点，但是更多机友能使用您的软件）。再一次感谢您开发太极这个优秀的软件。最后，我再不要脸地要一个无极的体验码

Magisk 版本：19.3
太极 Magisk 模块版本：v5.0.0
太极APP版本：东皇钟·5.4.4-614
开启的 Xposed 模块：通用
Xposed模块版本：通用
开启的其他 Magisk 模块：（无）
其他 Magisk 模块版本：（无）
手机型号：红米5Plus （Vince）
ROM版本：MIUI10 9.8.10 开发版

## 配置文件
[BUG：系统语言设置繁体中文打开太极崩溃报错.zip](https://github.com/taichi-framework/TaiChi/files/3501284/BUG.zip)

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by LiuYiLin-CA** [comment]
版主为什么不回复我的反馈啊？

**Comment by tiann** [comment]
5.5.0 fixed
