### ISSUE TITLE
BUG：全局模式下邮储银行app无法正常使用

### ISSUE THREAD

**Issue by dilexis** [taichi-framework/TaiChi#944]
## 什么问题
太极阳开启全局模式后，打开邮储银行app 点击信用卡选项会出现“太极已阻止 邮储银行 闪退xxxxxxxx” 的提示，别的功能也用不了，无法正常使用。
全局模式下打开银联官方app“云闪付”时会卡启动页，这两个app在关闭全局时都可以正常打卡和使用，最新版排除这两个app后也没有用。
麻烦大佬有空时看看是哪里出现了问题

Magisk 版本：19.3
太极 Magisk 模块版本：5.0
太极APP版本：5.4.9
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：一加7 Pro
ROM版本：secret_MEA_78

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 /data/system/taichi/apps.list 文件。
apps.list: https://u19742423.ctfile.com/fs/19742423-393095075
modules.list: https://u19742423.ctfile.com/fs/19742423-393095068

补充：有能力请务必提供日志文件已快速解决问题。

谢谢大佬的辛苦付出！

**Comment by tiann** [comment]
面具模块升级到 5.1.0，开启排除名单即可。
