### ISSUE TITLE
BUG：首页应用列表排列方式和搜索方式需要优化

### ISSUE THREAD

**Issue by AthonAlex** [taichi-framework/TaiChi#945]
## 什么问题

有2个关于首页应用列表排列方式和搜索方式需要优化

## 详细情况
1.
使用太极需要经常在太极app内强制停止应用并重新打开，有的时候也需要重新添加。
所以如果把频繁操作的应用(模块)排列在太极app内应用(模块)列表的顶端，就不用每次进入太极app都要把列表拉到底或者动用搜索功能了。
2.
首页已添加的应用也可以加上搜索功能，这样在应用较多的情况下，可以方便的找到。

以上两条如果被优化，能够大幅提高操作和测试应用和模块的效率，也能大幅优化太极app的日常使用体验！

Magisk 版本：v19.4
太极 Magisk 模块版本：v5.1.0
太极APP版本：5.5.0
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：
ROM版本：

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
长按箭头，拖动。

**Comment by tiann** [comment]
强制停止根本不需要在太极里面强制停止，打开app也不需要在太极内部打开，搜索功能没什么必要。

其次，顺序问题，你可以长按列表旁边的箭头拖动排序。

**Comment by AthonAlex** [comment]
关于强制停止，我个人还是比较喜欢把太极当做强制停止的入口，因为在设置里找更麻烦，不过确实纯粹只是个人喜好。

关于在首页增加搜索已添加（创建）应用这个功能的想法，是收集了我周围一些太极用户的实际体验得到的，既然有需求，我觉得还是值得稍微考量一下的，不过只是个建议。
（ps：其实从你这了解到能拖动顺序后，我觉得这个功能很鸡肋了，假如不能拖动顺序的话，倒还是有用）
另外拖动顺序简直就是隐藏功能啊，我之前认真阅读了你公众号的每一篇文章，还有github上面所有的说明，确实没有注意到这个功能的描述。这个表示感谢，我接触到的app很少有能这样操作的，久而久之就忘了，是我的问题。





---原始邮件---
发件人: "weishu"<notifications@github.com>
发送时间: 2019年8月17日(星期六) 晚上8:12
收件人: "taichi-framework/TaiChi"<TaiChi@noreply.github.com>;
抄送: "AthonAlex"<2606547077@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [taichi-framework/TaiChi] BUG：首页应用列表排列方式和搜索方式需要优化 (#945)



强制停止根本不需要在太极里面强制停止，打开app也不需要在太极内部打开，搜索功能没什么必要。
 
其次，顺序问题，你可以长按列表旁边的箭头拖动排序。

**Comment by tiann** [comment]
这个是我的锅，做的太隐蔽了；下次我改成长按整个条目拖动吧。

然后强制停止，其实很多系统的多任务界面长按图标之类的可以直接进去，比太极要快捷的多。

**Comment by AthonAlex** [comment]
这个……听上去长按整个条目拖动似乎会和长按条目弹出小窗相互冲突（见附件）
关于强制停止这个，长按确实也挺方便。

---原始邮件---
发件人: "weishu"<notifications@github.com>
发送时间: 2019年8月18日(星期日) 中午12:11
收件人: "taichi-framework/TaiChi"<TaiChi@noreply.github.com>;
抄送: "AthonAlex"<2606547077@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [taichi-framework/TaiChi] BUG：首页应用列表排列方式和搜索方式需要优化 (#945)



这个是我的锅，做的太隐蔽了；下次我改成长按整个条目拖动吧。
 
然后强制停止，其实很多系统的多任务界面长按图标之类的可以直接进去，比太极要快捷的多。
