### ISSUE TITLE
希望添加 HiddenCore Module 模块 

### ISSUE THREAD

**Issue by loneyclown** [taichi-framework/TaiChi#947]
## 什么问题

希望添加 HiddenCore Module 模块 

## 详细情况

建行APP采用了新的root监测机制，`rootclock`取消检测后会直接导致APP卡死，参考了52pojie的一个帖子，但是太极缺少`HiddenCore Module`模块，无法完成帖子上的操作。

52原帖：<https://www.52pojie.cn/thread-971818-1-1.html>

Magisk 版本：
太极 Magisk 模块版本：
太极APP版本：
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：
ROM版本：

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
已添加，自行测试是否有效。
