### ISSUE TITLE
BUG：Chrome和Android System WebView闪退

### ISSUE THREAD

**Issue by CrazyDoge666** [taichi-framework/TaiChi#948]
## 什么问题
浏览器闪退

## 详细情况
chrome和Android system webView闪退。在加载完网页的前一秒闪退。。多次重复闪退也不会提醒应用FC，安装太极后使用chrome显示主页面后1s左右闪退
（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：19.4-736729f5 (19307)
太极 Magisk 模块版本：5.1.1
太极APP版本：5.5.0
开启的 Xposed 模块：QX，云村清洁工，音量增强器
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：一加7Pro
ROM版本：AndroidQ第四版

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。
/data/system/taichi/modules.list日志：
/data/app/com.fkzhang.qqxposed-1xsJt2-mPO51un74TmSCvw==/base.apk
/data/app/bin.xposed.Unblock163MusicClient-_aIURGhjU5MgMi9siQ_VGw==/base.apk
/data/app/me.zjns.lovecloudmusic-D29HbCECGifzHT2qgN4xmA==/base.apk

/data/system/taichi/apps.list日志：com.fkzhang.qqxposed
com.chrome.canary
me.zjns.lovecloudmusic
com.tencent.mobileqq
bin.xposed.Unblock163MusicClient
com.netease.cloudmusic
com.google.android.webview
com.android.chrome

**Comment by tiann** [comment]
太极模块 5.1.1 已修复。
