### ISSUE TITLE
BUG：我该怎么适配太极 

### ISSUE THREAD

**Issue by coderstory** [taichi-framework/TaiChi#950]
## 什么问题

（请简要说明你遇到的问题）

## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：
太极 Magisk 模块版本：
太极APP版本：
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：
ROM版本：

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

1.这是一个已经在xposed上维护好几年的插件
2.太极显示支持几个老版本
3.不支持最新的版本号
4.把版本号改成支持的老版本号
5.启用后重启不生效
6.但其他的插件是生效的

问题
我该怎么应用刚开发的新版本？太极不通过任何日志
我改怎么调试？

或者太极只能使用插件 而无法在太极上开发 ？

**Comment by neoblackxt** [comment]
是的，只能在其他平台开发、测试、然后在其他平台以及太极上线。
不能一站式开发，这一点对开发者是有些不友好的。

**Comment by wlpiaoyi** [comment]
我开发的模块在太极里面提示暂不支持是为啥？ 太极内核 127 Xposed 模块Version 87

**Comment by tiann** [comment]
https://taichi.cool/zh/doc/how-to-debug.html
