### ISSUE TITLE
求适配Firefox Tablet Mode模块

### ISSUE THREAD

**Issue by RemRemRemRe** [taichi-framework/TaiChi#952]
## 什么问题

**Firefox Tablet Mode模块在TaiChi-Magisk中无法正常工作**
模块XDA链接:
https://forum.xda-developers.com/xposed/modules/xposed-firefox-tablet-mode-t3905868

## 详细情况

1.添加**Firefox**浏览器到太极
2.在模块列表中勾选**Firefox Tablet Mode**模块
3.模块未生效
(这个模块可以让安卓版火狐浏览器默认打开桌面版网页, 由于火狐浏览器手机端也能安装桌面端的插件,于是再加上默认请求桌面版网页,就能在手机端达到与桌面端一样的浏览体验.所以这是一个很棒的模块)

Magisk 版本：19.3
太极 Magisk 模块版本：5.1.0
太极APP版本：5.5.0
开启的 Xposed 模块：Firefox Tablet Mode
Xposed模块版本：0.4.1
开启的其他 Magisk 模块：QX,WX,剪贴板监控,网易云音乐插件(均正常工作)
其他 Magisk 模块版本：（无）
手机型号：ONEPLUSE-A5010
ROM版本：H2OS 9.0.5

## 配置文件

`/data/system/taichi/modules.list` 
[apps.list.txt](https://github.com/taichi-framework/TaiChi/files/3536919/apps.list.txt)

`/data/system/taichi/apps.list` 
[modules.list.txt](https://github.com/taichi-framework/TaiChi/files/3536920/modules.list.txt)

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
fixed in 5.5.1

preview: https://www.lanzous.com/i5szn5g

**Comment by RemRemRemRe** [comment]
66666谢大佬
