### ISSUE TITLE
BUG：XprivacyLua无法生效

### ISSUE THREAD

**Issue by cs-usst** [taichi-framework/TaiChi#954]
## 什么问题

（请简要说明你遇到的问题）
在太极·阴内，使用XprivacyLua设置隐私限制却不生效

## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

在太极·阴内安装了XprivacyLua和IMEI应用，然后打开XprivacyLua对IMEI设置禁止读取IMEI，但打开IMEI还是能够读取IMEI。

没有使用magisk和xposed

Magisk 版本：无
太极 Magisk 模块版本：无
太极APP版本：东皇钟5.2.0-673 内核124
开启的 Xposed 模块：无
Xposed模块版本：无
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：pixel
ROM版本：Android 9

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
XprivacyLua 版本？

**Comment by cs-usst** [comment]
@tiann 
XprivacyLua:1.24.2 官方版本
IMEI: https://play.google.com/store/apps/details?id=com.bobgearstudio.imei 1.2.5

**Comment by cs-usst** [comment]
@tiann 如果xprivacylua是1.25的官方版，安装并启用之后打开就会出现模块未安装或未更新的提示。这个提示通常是没有启用的时候出现，但我已经启用了

**Comment by tiann** [comment]
使用这个XPrivacyLua：https://www.lanzous.com/i2zk25e
并且，**不要把 XPrivacyLua 加入太极**

**Comment by cs-usst** [comment]
@tiann 不是特别明白，不加入太极，是指使用系统自带包安装器安装吗？这样的话（我是太极阴），太极里没有办法去管理启用太极外的模块吧？
