### ISSUE TITLE
BUG：安装模块失败,提示`libprocessgroup.so not found`

### ISSUE THREAD

**Issue by ZhangSongyi** [taichi-framework/TaiChi#956]
## 什么问题

用magisk manager安装模块过程中,日志提示`libprocessgroup.so not found`后提示安装失败

## 详细情况

- 在前一个MIUI版本(Android P)中安装过Magisk和太极Magisk模块,并在未卸载模块的情况下升级了系统
- 直接卡刷Magisk会卡启动画面,遂删除`/data/adb`目录后卡刷Magisk,成功
- 在Magisk Manager`下载`页面中选择`Tai Chi`进行安装后提示失败,错误原因为未找到`libprocessgroup.so`文件
- 直接重启会在启动画面卡住,在recovery中删除`/data/adb/modules/taichi`目录,卸载太极模块后可正常启动
- 从文件管理器中可看到,`/system/lib/libprocessgroup.so`和`/system/lib64/libprocessgroup.so`两个文件均存在
- 克隆模块仓库,手动将手机中的`libprocessgroup.so`替换仓库原有文件,删除sh脚本中对`libprocessgroup.so`的检测语句并重新打包后,可以正常刷入模块,重启后系统运行也正常.但此时太极APP无法检测到模块(无法自动变更为太极阳)

Magisk 版本： 19.4-736729f5(19307)
太极 Magisk 模块版本： v5.1.0
太极APP版本： 东皇钟 5.5.0-692
开启的 Xposed 模块：(无）
Xposed模块版本：(无）
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：小米 Mi9 透明尊享版
ROM版本：MIUI10 9.8.22 开发板, android 10

## 配置文件

(未安装模块,无配置文件)

**Comment by tiann** [comment]
建议双清之后全新安装，手动安装容易出错。
