### ISSUE TITLE
BUG：MinMinGuard支持版本有误，需修改

### ISSUE THREAD

**Issue by msdx321** [taichi-framework/TaiChi#960]
## 什么问题

之前有朋友在 admin.taichi.cool 上传过MinMinGuard的最新版（2.1.1）
但此版本把RemotePreferences替换为了XSharedPreferences，因此在太极上并不能正常工作。
同时 admin.taichi.cool 并没有提供上传统一应用不同版本的功能。所以需要手动将太极支持的版本修改为2.0.9 （稳定版，使用RemotePreferences）

## 详细情况

Magisk 版本：19.4
太极 Magisk 模块版本：5.1.2
太极APP版本：5.5.0-719
开启的 Xposed 模块：MinMinGuard
Xposed模块版本：2.0.9
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：
ROM版本：

## 配置文件

null

**Comment by tiann** [comment]
2.1.1 应该是可以正常工作的，我做过测试，是不是哪里不对？

**Comment by msdx321** [comment]
Fixed in 5.5.2 for whatever the reason.
