### ISSUE TITLE
Android 10 启用模块后不能开机

### ISSUE THREAD

**Issue by lekia** [taichi-framework/TaiChi#961]
## 什么问题

如题。

## 详细情况

电信卡，Pixel 1，从9不清除数据（update -w）通过工厂镜像（而不是OTA更新）升级到9月3日正式版的安卓10，一切系统功能正常只是Magisk没了。
重新刷入Maigsk后卡LOGO屏，用mm禁用太极模块后正常开机，于是删除模块重启再进入TWRP刷太极模块，这次LOGO后直接进入Bootloader，禁用太极后正常开机。
之前同样不清除数据升级到Android 10 pre3的时候可以开机和正常使用，但是蓝牙打开会立刻FC以至于不能愉快地使用网易云。

Magisk 版本：19.3
太极 Magisk 模块版本：4.7
太极APP版本：5.5
开启的 Xposed 模块：无
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：Pixel
ROM版本：10 (QP1A.190711.020)

**Comment by tiann** [comment]
面具模块版本太低

**Comment by lekia** [comment]
我是之前看到TaiChi-Magisk这个项目里面release只有4.7，然后TaiChi有个4.8.1……介绍页面也说是去release找，甚至在magisk仓库也说去TaiChi-Magisk的release找……
现在终于在Maigsk的下载里找到了。建议修改一下介绍？
