### ISSUE TITLE
Module request: EXI for SwiftKey

### ISSUE THREAD

**Issue by Muscarv2** [taichi-framework/TaiChi#963]
One of the few modules I can't live without.

Link: https://repo.xposed.info/module/com.mayulive.swiftkeyexi

If there is a template or something for requesting modules, please link it, I didn't not see it anywhere so I'm just trying this.

Thank you

**Comment by tiann** [comment]
should be fixed now.

**Comment by Muscarv2** [comment]
@close-issue-app[bot] well, there is no template for module request, so.... Everything around the TaiChi github and app is badly written and confusing.
