### ISSUE TITLE
模块适配UnblockMusic Pro

### ISSUE THREAD

**Issue by nining377** [taichi-framework/TaiChi#970]
解锁网易云灰色歌曲
地址：https://www.lanzous.com/i632kcd

**Comment by nekoprpr** [comment]
https://github.com/nining377/UnblockMusicPro_Xposed/releases

**Comment by lekia** [comment]
Pixel 安卓10 9月3日正式版

目前只有2.3.0适配，会提示完整性校验失败（沙盒机制？）而且不知道为什么启用模块后进网易云会无网络
2.3.1直接用不了因为没有适配

**Comment by tiann** [comment]
@lekia 给网易云音乐存储权限即可。我的 Android 10测试可以正常运行。
