### ISSUE TITLE
vpn软件，多任务后台界面滑掉，或者多任务全部清理，都一直连着，要手动进入软件界面停掉vpn才可以。

### ISSUE THREAD

**Issue by nibeishiwo** [taichi-framework/TaiChi#972]
vpn软件，多任务后台界面滑掉，或者多任务全部清理，都一直连着，要手动进入软件界面停掉vpn才可以。

## 详细情况
vpn软件，多任务后台界面滑掉，或者多任务全部清理，显示已经杀掉了，🔑图标一直都在，都一直连着，要手动进入软件界面停掉vpn才可以。测试vpn软件为纳豆和brook
所有太极版本都出现这问题。
Magisk 版本：19.3
太极 Magisk 模块版本：v5.1.2
太极APP版本：5.5.2
开启的 Xposed 模块：核心破解，xposed edge
Xposed模块版本：
开启的其他 Magisk 模块：mm管理器
其他 Magisk 模块版本：（无）
手机型号：华为mate9
 `#ROM版本：9.0和9.1

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by nibeishiwo** [comment]
音乐软件有驻通知栏，有的可以杀有的也杀不掉

**Comment by 2810676203** [comment]
这个bug跟太极有什么关系🤔
