### ISSUE TITLE
太极·阴模块适配UnblockMusic Pro

### ISSUE THREAD

**Issue by nining377** [taichi-framework/TaiChi#973]
阴和阳的审核是分开的吗？之前申请一次只有阳的能用，我的模块VXP可用，应该太极阴也是能用的，我再提交一次审核，希望阴能通过，项目地址：https://github.com/nining377/UnblockMusicPro_Xposed/releases

**Comment by tiann** [comment]
太极阴由于高版本 Android 的 SELinux 等限制，可能需要做额外的工作，所以与太极阳是分开的。早上测试过了，应该是可以用的。

**Comment by nining377** [comment]
原来如此，我把编译版本降到23了，所以应该没事
