### ISSUE TITLE
太极又不能下载了，大哥为毛我想下载一下这么难

### ISSUE THREAD

**Issue by weimingjue** [taichi-framework/TaiChi#974]
## 什么问题

上一次是诚通，这次又不知道啥了，感觉蓝奏云什么的挺稳定的为毛不用

## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：
太极 Magisk 模块版本：
太极APP版本：
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：
ROM版本：

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
lanzou 一直有在用，你是用哪里的链接下载不了？

**Comment by weimingjue** [comment]
> lanzou一直有在用，你是用哪里的链接下载不了？

太极官网啊
https://taichi.cool/download/download_cn.html
稳定版下载地址点进去直接404

**Comment by weimingjue** [comment]
> lanzou一直有在用，你是用哪里的链接下载不了？

作者呢？我哪里有点错吗？打开就跳到https://tc5.us/file/19604958-392229810
提示不存在，图片地址：
https://attach.52pojie.cn//forum/201909/26/164556v3242vyy4np4z42p.png?l

**Comment by weimingjue** [comment]
犯二了，去毛网站下，github本身就有...
还是建议赶紧把网站修复吧
