### ISSUE TITLE
nubiaz17安装magisk太极5.1.2后开机卡logo

### ISSUE THREAD

**Issue by yuxia5454** [taichi-framework/TaiChi#975]
Magisk 版本：最新版，今天刚装的
太极 Magisk 模块版本：5.1.2
太极APP版本：还没装，看教程不是先装magisk模块吗
开启的 Xposed 模块：无
Xposed模块版本：无
开启的其他 Magisk 模块：杜比音效
其他 Magisk 模块版本：6.4
手机型号：z17
ROM版本：最新版9.0

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。
没有taichi这个目录

**Comment by wl970064531** [comment]
麻烦问下这个事情有进展了么，我也是这个问题/data/system/下面没有taichi这个文件夹

**Comment by yuxia5454** [comment]
> 麻烦问下这个事情有进展了么，我也是这个问题/data/system/下面没有taichi这个文件夹

1.进入recovery模式（关机状态下按住音量键-和电源键）
2.找到文件管理，找到/data/adb文件夹
3.删除/data/adb文件夹下的taichi.img，删除
这样重启后就可以正常进入系统

**Comment by tiann** [comment]
用最新的 6.1.0 试试
