### ISSUE TITLE
建议开放对旧版本模块的支持

### ISSUE THREAD

**Issue by SakuraKoi** [taichi-framework/TaiChi#976]
## 什么问题

好好的模块，用着用着突然就失效了，进太极一看之前还能用的模块突然就版本不适配了
升级完模块发现适配的模块已经不支持我使用的应用版本了

好用的模块我会自己升级，我不升级必然是有不升级的原因，那么为什么原本正常使用的模块突然就不受支持要么升级要么不能使用？为什么要取消对旧版本模块的支持？为什么要强制用户升级模块？

## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：
太极 Magisk 模块版本：
太极APP版本：
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：
ROM版本：

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
所有的语句都是责问。既然是 issue，那就是来提问题、解决问题的。

你只需要说明你用的是什么模块，什么版本，我加上去就可以了。

**Comment by SakuraKoi** [comment]
> 所有的语句都是责问。既然是 issue，那就是来提问题、解决问题的。
> 
> 你只需要说明你用的是什么模块，什么版本，我加上去就可以了。

首先向您表示歉意
我个人对强制更新之类的行为是比较反感的，发issue的时候心情比较激动，我为我issue中用词不当和攻击性的内容致歉

但对您的提议，我认为不是一个长久的解决之道，这不仅仅是少数几个模块的问题
太极移除对旧版本模块的支持在我看来并不是一个必要的功能，使用旧版本模块也不会影响其正常运行，还会加大用户使用软件的成本(指隔一段时间就需要更新模块)那么它就是一个没有价值甚至是负价值的功能(欢迎提出反驳)，这样的功能应当被移除

**Comment by tiann** [comment]
这个问题之所以出现，是因为太极的模块管理现在有众多的管理员。可能有部分管理员把某些低版本的模块直接下线了导致这种结果；并不是我个人有意为之的。对于已经下线的模块恢复起来比较麻烦（虽然配置有历史版本，但是这不是某一次变更带来的）不过我可以保证现在已经支持的模块不会在若干个月之后被管理员下线。

作为一个临时的解决办法，可以把需要支持的旧版本模块传上来，单独添加进去。

**Comment by SakuraKoi** [comment]
好的，那就不再麻烦您再添加旧版本了，感谢您为我们提供了太极这么一个方便易用的平台，我关闭issue了
