### ISSUE TITLE
Bug report: MIUI11 太极5.5.6  QQ疯狂闪退

### ISSUE THREAD

**Issue by g1thub-h** [taichi-framework/TaiChi#977]
在更新完MIUI11以后
不管是重新创建还是优化
QQ8.1.0 8.1.3都会闪退
并且打不开图片
点击消息中的图片时
QQ直接退出报错
麻烦作者尽快修复这个bug

**Comment by LouisFan1998** [comment]
同样问题，QQ7.9.9，MIUI10开发版9.9.3。发现只要加入太极里的app都会有同样问题出现。

**Comment by g1thub-h** [comment]
发现问题根源  出现在qx2.1.14版本上  回退到2.0.1.4后正常使用
但在MIUI10时候  qx2.1.1.4+太极5.5.6+qq8.1.3正常使用
升级至MIUI11后  qx2.0.1.4+太极5.5.6+qq8.1.3才能使用

**Comment by tiann** [comment]
5.5.8 应该会有所缓解
