### ISSUE TITLE
XInternalSD无法使用

### ISSUE THREAD

**Issue by simzxu** [taichi-framework/TaiChi#978]
## 如标题
太极内模块管理已经勾选
XInternalSD全局无效，单选太极内app无效，建立了自定义目录无效，重启无效，太极已经给予储存权限和电话权限（只有这两个）
【今日头条和XInternalSD已经安装太极内部并且模块已经开启】
![image](https://user-images.githubusercontent.com/8198814/65716685-35178a80-e0d2-11e9-9f5f-765124b5dd21.png)
![image](https://user-images.githubusercontent.com/8198814/65716737-54aeb300-e0d2-11e9-8e2a-3e0e64c16ba1.png)

【XInternalSD设置如图：】
![image](https://user-images.githubusercontent.com/8198814/65716493-d2be8a00-e0d1-11e9-83f3-fbd92f69043e.png)
【今日头条已勾选】
![image](https://user-images.githubusercontent.com/8198814/65716602-11544480-e0d2-11e9-8267-d2c72ba31c6a.png)

Magisk 版本：无Magisk
太极 Magisk 模块版本：无Magisk
太极APP版本：5.5.6-846
开启的 Xposed 模块：XInternalSD
Xposed模块版本：846
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：SM-G9730（港行S10）
ROM版本：G9730ZCU2ASH2（目前最新）
安卓版本：9.0

## 配置文件
无root ，无法提供
请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

**Comment by tiann** [comment]
不要把插件在太极里面创建。
