### ISSUE TITLE
BUG：Android 10 核心破解失效

### ISSUE THREAD

**Issue by ddgweb** [taichi-framework/TaiChi#979]
## 什么问题

Android 10 核心破解失效，MIUI11

## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：19.4
太极 Magisk 模块版本：5.1.2
太极APP版本：5.5.6-847
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：
ROM版本：

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
插件的问题不是太极的问题。

**Comment by ddgweb** [comment]
> 插件的问题不是太极的问题。

插件的github主页也是你。。。。

**Comment by tiann** [comment]
Android 9.0 上的这个核心破解插件是我提供的没错，但是我现在没有机子去验证 MIUI 11上的问题。太极是太极，核心破解是核心破解。
