### ISSUE TITLE
BUG：小米8 Pixel Experience 10 开机卡第一屏

### ISSUE THREAD

**Issue by wxx9248** [taichi-framework/TaiChi#982]
## 什么问题

小米8全新刷入Pixel Experience 10，并启用太极Magisk模块（太极内未使用任何Xposed模块），开机卡第一屏，1分钟以后重启，如此循环。

## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：19.5-578a50b4
太极 Magisk 模块版本：5.1.2
太极APP版本：5.5.6-851
开启的 Xposed 模块：（无）
Xposed模块版本：（无）
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：小米8
ROM版本：PixelExperience_dipper-10.0-20190918-1239-BETA-OFFICIAL
ROM链接：https://download.pixelexperience.org/dipper/
--

补充&强调：
系统为Android 10，强制使用system-as-root，强制使用dm-verity
附件为可能出现问题的文件替换项，来自/system/lib/libprocessgroup.so
和/system/lib64/libprocessgroup.so
[libprocessgroup.zip](https://github.com/taichi-framework/TaiChi/files/3666335/libprocessgroup.zip)

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。
**不存在列表，因为未安装任何Xposed插件，未添加任何App**

补充：有能力请务必提供日志文件以快速解决问题。
**在故障发生前，adbd未启动，未能收集日志。**

**Comment by tiann** [comment]
只启用模块，不安装太极app能否开机？

**Comment by wxx9248** [comment]
不能开机。



---原始邮件---
发件人: "weishu"<notifications@github.com&gt;
发送时间: 2019年9月29日(星期日) 晚上9:16
收件人: "taichi-framework/TaiChi"<TaiChi@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Jake Wang"<wxx9248@qq.com&gt;;
主题: Re: [taichi-framework/TaiChi] BUG：小米8 Pixel Experience 10 开机卡第一屏 (#982)



只启用模块，不安装太极app能否开机？

**Comment by tiann** [comment]
https://github.com/taichi-framework/TaiChi/releases/tag/v5.1.3 是否已修复此问题？

**Comment by wxx9248** [comment]
问题已解决，非常感谢！



---原始邮件---
发件人: "weishu"<notifications@github.com&gt;
发送时间: 2019年10月11日(星期五) 凌晨2:30
收件人: "taichi-framework/TaiChi"<TaiChi@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Jake Wang"<wxx9248@qq.com&gt;;
主题: Re: [taichi-framework/TaiChi] BUG：小米8 Pixel Experience 10 开机卡第一屏 (#982)



https://github.com/taichi-framework/TaiChi/releases/tag/v5.1.3 是否已修复此问题？
