### ISSUE TITLE
TaiChi not detecting Magisk Module

### ISSUE THREAD

**Issue by RumbleRamy** [taichi-framework/TaiChi#983]
I have a Galaxy J5 Prime running Android 7.0 Nougat. I used TaiChi before and it used to work smoothly. But after I flashed my phone again and installed TWRP and rooted using magisk everything works perfectly and I installed some magisk modules they work too. The problem is
I installed Tai Chi module and installed the app but it does not detect the magisk module at all. I tried installing older versions of both the module and the app but it does not work.

![Screenshot_20190929-005930](https://user-images.githubusercontent.com/17043904/65842423-b28a0780-e32b-11e9-98a6-0be33863153e.png)
![Screenshot_20190929-005916](https://user-images.githubusercontent.com/17043904/65842424-b28a0780-e32b-11e9-9fc3-f40b5d577476.png)

**Comment by tiann** [comment]
What is the taichi app version? and maybe you can try to disable all other module in Magisk

**Comment by RumbleRamy** [comment]
I removed all other modules and cleared cache and yet still not detecting it and my TaiChi app version is 5.5.6.
I even tried older versions but still not working.

**Comment by tiann** [comment]
should be fixed in magisk module v5.1.3
