### ISSUE TITLE
你好，在太极创建程序过程中，按照提示删除原程序后，无法继续安装。显示“应用包安装程序，已停止”。

### ISSUE THREAD

**Issue by aita6760** [taichi-framework/TaiChi#985]
## 什么问题

你好，在太极中无法创建程序

## 详细情况

你好，在太极创建程序过程中，按照提示删除原程序后，无法继续安装。显示“应用包安装程序，已停止”。

Magisk 版本：
太极 Magisk 模块版本：
太极APP版本：东皇钟5.5.6-887
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：
ROM版本：

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
具体创建的什么程序？

**Comment by aita6760** [comment]
钉钉4.6.21-4.7.0，都试了一下，都不能正常创建。

**Comment by huijiaxin** [comment]
...
