### ISSUE TITLE
启用太极阳后chrome无法登录谷歌账号，只有使用太极阴才能恢复

### ISSUE THREAD

**Issue by kid-oh** [taichi-framework/TaiChi#986]
## 什么问题

启用太极阳后原本登录的谷歌账号会强制退出，无法添加账号进行同步，取消太极阳即可恢复

## 详细情况

Magisk 版本：20
太极 Magisk 模块版本：5.1.3
太极APP版本：5.5.6
开启的 Xposed 模块：无
Xposed模块版本：无
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：一加7pro
ROM版本：氧os公测第三版

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。
[modules.log](https://github.com/taichi-framework/TaiChi/files/3721400/modules.log)
[apps.log](https://github.com/taichi-framework/TaiChi/files/3721401/apps.log)

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by kid-oh** [comment]
把chrome的权限全部允许貌似可以解决

**Comment by MelanPrince** [comment]
同样问题 手动去打开 Chrome 所有全新 恢复了。
