### ISSUE TITLE
Module support

### ISSUE THREAD

**Issue by ChanceGPM** [taichi-framework/TaiChi#987]
It would be great if you could add support for the modules "Firefds Kit [Pie]", "Statusbar download progress" and "SudoHide".They work with EdXposed. 
Thanks.

**Comment by tiann** [comment]
What's wrong with `SudoHide` and `Firefds Kit [Pie]`, it works well in taichi.

**Comment by ChanceGPM** [comment]
I didn't see them in the supported module list on the thaichi homepage, so I didn't try them out. But that is great if they work! Any chance to add "Viafree Adaway" too as a supported module? Ty.

**Comment by ChanceGPM** [comment]
Can't use ThaiChi it says "Update module engine failed, please retry or upgrade ThaiChi. Error: -100" I have galaxy s8+ Samsung experience Pie, latest ThaiChi apk and magisk module.

**Comment by tiann** [comment]
@ChanceGPM try it again, the four module should work now

**Comment by ChanceGPM** [comment]
Thank you so much, I could update the module engine and the modules work now 😃
