### ISSUE TITLE
支持应用管理

### ISSUE THREAD

**Issue by 3acherMAN** [taichi-framework/TaiChi#99]
## 模块名字 
应用管理xposed
## 模块用途 
类似于应用控制器，但更美观易上手
## 模块版本号
5.1.5
## 模块安装包
[x-apm-app-release-aio.zip](https://github.com/tiann/EXposed/files/2805799/x-apm-app-release-aio.zip)

**Comment by MoonBegonia** [comment]
@tiann 应用管理Xposed 已更新  [酷安](https://www.coolapk.com/apk/github.tornaco.xposedmoduletest)

**Comment by texsd123** [comment]
什么时候能支持，开始测试了吗？
issue已经是两个月前的了

**Comment by texsd123** [comment]
@tiann 难不成是功能太多了，还没适配全？

**Comment by Fonshare** [comment]
这个是真的好用

**Comment by rizi800** [comment]
真心希望能支持这个

**Comment by tiann** [comment]
1. 太极主版本更新到 https://taichi.ctfile.com/fs/19604958-365368040
2. 应用管理Xposed使用 5.1.7 版本。
3. 模块适配引擎更新到 85

模块提示“有兼容性问题” 目前不知道什么情况；慢慢再看。
