### ISSUE TITLE
魅族16x，解锁后，解密状态，magisk 太极，必死~~ 必进入fastboot，循环~

### ISSUE THREAD

**Issue by clownstar** [taichi-framework/TaiChi#990]
## 什么问题

魅族16x，解锁后，解密状态，magisk 太极，必死~~ 必进入fastboot，循环~

## 详细情况

魅族16x，解锁后，解密状态，magisk 太极，必死~~ 必进入fastboot，循环~

Magisk 版本：
太极 Magisk 模块版本：
太极APP版本：
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：
ROM版本：

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
请详细说明你的问题以及操作步骤。

**Comment by clownstar** [comment]
魅族16x （包括16th,16p） ，android 8.1  ， flyme7 & flyme8 
安装magisk ，安装riro， 安装 magisk 太极， 重启， 转气球，过会儿自动重启进入 fastboot，重启继续进入fstboot ，需要卸载模块

根据群友反馈，16s即以上，安卓9的通过手工替换文件，可以正常太极阳和无极
16系列 安卓8.1 目前就是 重启， 转气球，过会儿自动重启进入 fastboot，重启继续进入fstboot ，需要卸载模块或者平刷

**Comment by clownstar** [comment]
magisk 20.0 
magisk taichi 5.1.3 
太极APP版本：5.58
开启的 Xposed 模块：无
Xposed模块版本：无
开启的其他 Magisk 模块：(无）riru-core
其他 Magisk 模块版本：（无）
手机型号：魅族16x
ROM版本：flyme7 / flyme8(android 8.1)
/data/system/taichi/modules.list 以及 /data/system/taichi/apps.list  开启不成功，无文件

**Comment by tiann** [comment]
1. 把其他所有模块都关掉，卸载太极app，只刷太极面具模块看看是否能依然bootloop。
2. 如果问题依旧，刷入 logcat 模块，然后复现情况，进 recovery 把 /data/local/boot 下面的所有文件都发给我。

[logcat_v13.2.zip](https://github.com/taichi-framework/TaiChi/files/3742164/logcat_v13.2.zip)

**Comment by clownstar** [comment]
[](url)
[boot.zip](https://github.com/taichi-framework/TaiChi/files/3742224/boot.zip)

**Comment by clownstar** [comment]
boot-1970-01-03-05-00-19  第一次开机  
boot-1970-01-03-05-01-15 第二次开机
boot-1970-01-03-05-03-36 去掉模块开机

**Comment by tiann** [comment]
三种情况都 bootloop 了？

**Comment by tiann** [comment]
[magisk-taichi-v5.1.3-m.zip](https://github.com/taichi-framework/TaiChi/files/3742287/magisk-taichi-v5.1.3-m.zip)

刷一下这个，然后把日志发给我看下

**Comment by clownstar** [comment]
删除模块，正常开机

这个是新的日志 
[boot-1970-01-03-05-50-09.log.zip](https://github.com/taichi-framework/TaiChi/files/3742316/boot-1970-01-03-05-50-09.log.zip)

**Comment by tiann** [comment]
开机之后太极应该是没有生效吧？

**Comment by clownstar** [comment]
删除模块，太极就没了，删除的太极模块， 

boot-1970-01-03-05-50-09.log.zip  是  magisk-taichi-v5.1.3-m.zip 开机卡bootloop 的日志

**Comment by tiann** [comment]
找到原因了，不刷任何模块，把你系统的 /system/lib/libprocessgroup.so 发给我看下

**Comment by clownstar** [comment]
嗯，是这个地方过不去，之前替换方法时，替换了这个就挂了 
[libprocessgroup.zip](https://github.com/taichi-framework/TaiChi/files/3742452/libprocessgroup.zip)

**Comment by clownstar** [comment]
[libprocessgroup.zip](https://github.com/taichi-framework/TaiChi/files/3742458/libprocessgroup.zip)

**Comment by clownstar** [comment]
f7 的
https://github.com/TadiT7/meizu_16_dump/blob/meizu_16-user-8.1.0-OPM1.171019.026-1537501340-release-keys/system/lib/libprocessgroup.so
https://github.com/TadiT7/meizu_16_dump/blob/meizu_16-user-8.1.0-OPM1.171019.026-1537501340-release-keys/system/lib64/libprocessgroup.so

**Comment by tiann** [comment]
[magisk-taichi-v5.1.3-m2.zip](https://github.com/taichi-framework/TaiChi/files/3743443/magisk-taichi-v5.1.3-m2.zip)
试下这个版本

**Comment by clownstar** [comment]
这个版本可以开机进系统了，安装了APP，太极阳模式，开全局模式，简单试了flyme助手3.2.8，重启后功能正常，其他功能没试，
感谢您百忙之中解决个别机型问题，感谢
[boot-1970-01-03-12-15-00.log.zip](https://github.com/taichi-framework/TaiChi/files/3743562/boot-1970-01-03-12-15-00.log.zip)

**Comment by tiann** [comment]
好的，稍等下我会发个正式版；感谢配合测试

**Comment by tiann** [comment]
https://github.com/Magisk-Modules-Repo/taichi/commit/f0abc6bc44fbd15048546fca55f8769bb64431aa
