### ISSUE TITLE
BUG：太极阳127(51) 应用无法识别微信

### ISSUE THREAD

**Issue by zhaoxilingcheng** [taichi-framework/TaiChi#992]
## 什么问题

刷了太极阳后，王者等程序还是无法识别微信，显示未安装微信。

## 详细情况

（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：20.0
太极 Magisk 模块版本：最新
太极APP版本：最新
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：1+7pro
ROM版本：最新

**Comment by tiann** [comment]
把微信和王者荣耀卸载了重来。
