### ISSUE TITLE
Bug report: X Messenger Privacy 顯示未啟用模塊

### ISSUE THREAD

**Issue by tomissmart86520** [taichi-framework/TaiChi#993]
**Describe the bug**
X Messenger Privacy 顯示未啟用模塊
https://imgur.com/gj3Vevc
**To Reproduce**
開啟程式就會顯示

**Expected behavior**

**Smartphone (please complete the following information):**
Magisk version：20.0(20000)
TaiChi-Magisk module version：5.1.3
TaiChi version：5.5.6-938
Which Xposed modules are enabled ?：
Xposed modules version：
Which Magisk modules are enabled ?：
Magisk modules version：
Device ：Redmi note5
ROM：10.3.2.0 PEIMIXM

**Additional context**

**Comment by tiann** [comment]
please upgrade taichi to version 5.5.8 and try again

**Comment by tomissmart86520** [comment]
更新到 5.5.8-946 版本 測試
一樣跳出未啟用模塊

**Comment by vannessqn** [comment]
I have the same problem with Virtualxposed (sorry i know this is taichi support thread)
Lastest messenger app and x messenger module, Mi 8 china rom 10.3.4 rootless and have not unblock bootloader thank you
