### ISSUE TITLE
BUG：滴滴出行在下方会弹出通知类似报错

### ISSUE THREAD

**Issue by kid-oh** [taichi-framework/TaiChi#995]
## 什么问题

使用太极阳后滴滴出行在下方会弹出通知类似报错

## 详细情况

只要开启太极阳就会出现

Magisk 版本：
太极 Magisk 模块版本：5.1.4
太极APP版本：5.5.8
开启的 Xposed 模块：无
Xposed模块版本：无
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：一加7pro
ROM版本：氧os安卓Q公测第三版

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
不知所云
