### ISSUE TITLE
Feature Request: make the source code available

### ISSUE THREAD

**Issue by francwalter** [taichi-framework/TaiChi#998]
Hello

this is not a bug, but a missing feature: please provide the source code for this TaiChi Framework.
At the moment, TaiChi framework is here on GitHub without any source-code, GitHub is serving just as a Filehoster for it. I doubt this complies with the Github rules by the way.

Without the source many users won't install this framework with root permissions, me neither.
Maybe TaiChi is a wonderful peace of software but it is far to dangerous to use it unchecked as closed source on a rooted device.

So please make the source open here on Github so we could look into it.

Thanks
frank

**Comment by tiann** [comment]
open source != safe

**Comment by francwalter** [comment]
... and:
closed source == unsafe

**Comment by tiann** [comment]
emm, please stop using gms, twitter, facebook

**Comment by francwalter** [comment]
Could you at least explain, why you don't go open source?

**Comment by tiann** [comment]
I've open-sourced a lot of code, but i don't think open source is more safe than closed source from a higher perspective.

I create VirtualXposed, but it is abused finally. Many apps integrates the code, using the magic power provided by me and making malicious actions. They can obfuscate the source code and inject target apps, hook the functions, but you don't know it at all. As far as i know, some famous apps in China already do this. 

Open-source, especially for apps like taichi, may cause more harm.

In addition, I open sourced VirtualXposed, but there are still many guys criticize it is malicious. No matter what you do, there are always people saying you are malicious, selfish and so on.

I am writing code to please myself, not satisfying someone else.

**Comment by HuskyDG** [comment]
I'm using ***LSPosed Framework***
It doesn't have WhiteList like ***Exposed aka Taichi***
